import type { Arc } from '@/types'

export const ALABASTA_ARCS: Arc[] = [
  {
    name: 'Reverse Mountain',
    slug: 'reverse-mountain',
    saga: 'alabasta',
    cover: '/arcs/reverse-mountain.jpg',
    episodeCount: 2,
    summary: 'Hasır Şapka korsanları Grand Line\'a giriş yapan Reverse Mountain\'ı aşar ve burada dev balina Laboon ile karşılaşır.',
    detailedSummary: 'Grand Line\'a girmenin tek yolu, Calm Belt\'i geçmek veya Reverse Mountain\'ı aşmaktır. Hasır Şapkalar, akıntıları yukarı doğru çıkan bu devasa dağı geçerler. Diğer tarafta, 50 yıldır mürettebatının dönüşünü bekleyen dev balina Laboon ile karşılaşırlar. Laboon, Batı Deniz\'den gelen Rumbar Korsanlarının evcil balinasıydı. Mürettebat Grand Line\'a girdiğinde Laboon\'u Reverse Mountain\'da bırakmış ama asla dönememişlerdir. Luffy, Laboon ile kavga ederek "berabere" kalır ve tekrar dövüşmek için geri döneceğine söz verir. Laboon\'un alnına Hasır Şapkaların simgesini çizer. Gizemli organizasyon Baroque Works hakkında ilk ipuçları ortaya çıkar.',
    keyEvents: [
      'Reverse Mountain geçişi',
      'Laboon ile karşılaşma',
      'Rumbar Korsanlarının hikayesi (Brook\'un eski mürettebatı)',
      'Baroque Works ilk kez anılır',
      'Mr. 9 ve Miss Wednesday ile tanışma',
    ],
    themes: ['Söz ve Sadakat', 'Bekleme ve Umut'],
    location: 'Reverse Mountain, Twin Cape',
    characters: ['luffy', 'zoro', 'nami', 'sanji', 'usopp'],
    episodes: [
      {
        number: 1,
        title: 'Grand Line\'ın Kapısı',
        slug: 'reverse-mountain-01',
        duration: '24:00',
        summary: 'Going Merry, Reverse Mountain\'ın akıntısına kapılarak dağın tepesine çıkar. Zirvedeki manzara nefes kesicidir. İniş sırasında devasa bir engelle karşılaşırlar: dev balina Laboon, dağa kafa atarak Red Line\'ı kırmaya çalışmaktadır.',
      },
      {
        number: 2,
        title: 'Laboon',
        slug: 'reverse-mountain-02',
        duration: '24:30',
        summary: 'Laboon\'un hikayesi: 50 yıl önce Rumbar Korsanları onu burada bırakmıştır. Luffy, Laboon ile savaşır ve "berabere" ilan eder. Alnına Hasır Şapka simgesini çizerek geri döneceğine söz verir. Mr. 9 ve Miss Wednesday (Vivi) gemiye biner.',
      },
    ],
  },
  {
    name: 'Whiskey Peak',
    slug: 'whiskey-peak',
    saga: 'alabasta',
    cover: '/arcs/whiskey-peak.jpg',
    episodeCount: 3,
    summary: 'Mürettebat, misafirperver görünen Whiskey Peak\'e gelir. Ancak kasaba sakinleri aslında ödül avcılarıdır. Burada prenses Vivi ile tanışırlar.',
    detailedSummary: 'Log Pose\'un işaret ettiği ilk ada Whiskey Peak\'te mürettebat coşkuyla karşılanır. Yeme-içme partisi düzenlenir. Ancak tüm kasaba sakinleri aslında Baroque Works ödül avcılarıdır ve korsanları sarhoş edip yakalamayı planlarlar. Zoro, tek başına 100 ödül avcısını yener. Bu sırada Miss Wednesday\'in gerçek kimliği ortaya çıkar: O aslında Arabasta Krallığı\'nın Prensesi Nefertari Vivi\'dir. Vivi, Baroque Works\'ün arkasındaki kişiyi araştırmak için örgüte sızmıştır. Örgütün lideri, bir Shichibukai olan Crocodile\'dır. Mr. 5 ve Miss Valentine, Vivi\'yi öldürmek için gelir. Luffy ve mürettebat, Vivi\'yi korumaya ve Arabasta\'ya götürmeye karar verir.',
    keyEvents: [
      'Zoro tek başına 100 kişiyi yener',
      'Vivi\'nin gerçek kimliği ortaya çıkar',
      'Baroque Works\'ün lideri Crocodile',
      'Mürettebat Vivi\'yi korumayı kabul eder',
    ],
    themes: ['Görünüşlerin Aldatıcılığı', 'Prensesin Fedakarlığı', 'Gizli Kimlikler'],
    location: 'Whiskey Peak',
    villain: 'Mr. 5, Miss Valentine',
    characters: ['luffy', 'zoro', 'nami', 'vivi'],
    episodes: [
      {
        number: 1,
        title: 'Misafirperverlik Tuzağı',
        slug: 'whiskey-peak-01',
        duration: '24:00',
        summary: 'Mürettebat Whiskey Peak\'te büyük bir partiyle karşılanır. Luffy, Usopp ve Sanji yiyip içerken Zoro şüphelenir. Gece olunca kasaba sakinleri gerçek yüzlerini gösterir: hepsi Baroque Works ajanıdır.',
      },
      {
        number: 2,
        title: 'Zoro\'nun 100 Kişilik Savaşı',
        slug: 'whiskey-peak-02',
        duration: '24:30',
        summary: 'Zoro, tek başına 100 Baroque Works ajanını yener. Mr. 9 ve Miss Wednesday (Vivi) kaçmaya çalışır. Luffy, durumu yanlış anlar ve Zoro ile kavga eder. Nami ikisini de durdurur.',
      },
      {
        number: 3,
        title: 'Prenses Vivi',
        slug: 'whiskey-peak-03',
        duration: '24:00',
        summary: 'Vivi\'nin Arabasta prensesi olduğu ve Baroque Works\'e casusluk için sızdığı ortaya çıkar. Örgütün lideri Shichibukai Crocodile\'dır. Mr. 5 ve Miss Valentine, Vivi\'yi öldürmeye gelir. Luffy onları yener ve mürettebat Vivi\'yi Arabasta\'ya götürmeye karar verir.',
      },
    ],
  },
  {
    name: 'Little Garden',
    slug: 'little-garden',
    saga: 'alabasta',
    cover: '/arcs/little-garden.jpg',
    episodeCount: 4,
    summary: 'Dinozorların yaşadığı prehistorik bir adada, 100 yıldır düello eden iki dev savaşçı Dorry ve Brogy ile karşılaşırlar.',
    detailedSummary: 'Log Pose, mürettebatı prehistorik ada Little Garden\'a yönlendirir. Dinozorların ve dev böceklerin yaşadığı bu adada, Elbaf\'lı iki dev savaşçı Dorry ve Brogy 100 yıldır düello etmektedir. Hangisinin daha büyük avı yakaladığı tartışmasıyla başlayan bu düello, artık sebebi bile unutulmuştur ama onurları gereği devam etmektedir. Baroque Works ajanları Mr. 3 ve Miss Goldenweek de adadır. Mr. 3\'ün Doru Doru meyvesiyle ürettiği mumdan tuzaklar mürettebatı tehlikeye atar. Zoro, kendini kesmek pahasına mumdan kurtulmaya çalışır. Devlerin savaşçı onuru ve Elbaf\'ın savaşçı kültürü Usopp\'u derinden etkiler. Mürettebat, devlerin yardımıyla adadan ayrılır.',
    keyEvents: [
      'Dorry ve Brogy\'nin 100 yıllık düellosu',
      'Mr. 3\'ün mum tuzağı',
      'Zoro\'nun kendini kesme cesareti',
      'Usopp\'un Elbaf savaşçılarına hayranlığı',
      'Devlerin yardımıyla adadan ayrılış',
    ],
    themes: ['Savaşçı Onuru', 'Dostlar Arası Rekabet', 'Cesareti Test Eden Anlar'],
    location: 'Little Garden',
    villain: 'Mr. 3, Miss Goldenweek',
    characters: ['luffy', 'zoro', 'nami', 'sanji', 'usopp', 'vivi'],
    episodes: [
      {
        number: 1,
        title: 'Devler Adası',
        slug: 'little-garden-01',
        duration: '24:00',
        summary: 'Mürettebat, dinozorların yaşadığı prehistorik ada Little Garden\'a ulaşır. Luffy ve Vivi adayı keşfederken dev savaşçı Dorry ile karşılaşırlar. Usopp da diğer dev Brogy ile tanışır.',
      },
      {
        number: 2,
        title: '100 Yıllık Düello',
        slug: 'little-garden-02',
        duration: '24:30',
        summary: 'Dorry ve Brogy\'nin 100 yıllık düellosunun hikayesi anlatılır. Elbaf\'ın en güçlü iki savaşçısı, artık sebebini bile hatırlamadıkları bir tartışma yüzünden savaşmaktadır. Savaşçı onuru her şeyin üstündedir.',
      },
      {
        number: 3,
        title: 'Mr. 3\'ün Tuzağı',
        slug: 'little-garden-03',
        duration: '24:00',
        summary: 'Baroque Works ajanı Mr. 3, Doru Doru meyvesiyle dev bir mum seti oluşturur. Zoro, Nami ve Vivi mumdan heykele dönüştürülmek üzere tuzağa düşer. Zoro, ayaklarını kesmeyi bile göze alır.',
      },
      {
        number: 4,
        title: 'Mum Mum Meyvesi',
        slug: 'little-garden-04',
        duration: '24:30',
        summary: 'Luffy ve Usopp, Mr. 3\'ü yenmek için savaşır. Usopp\'un taktikleri ve Luffy\'nin gücü birleşerek mum tuzağını kırar. Mürettebat kurtulur. Sanji, Mr. 0 (Crocodile) ile telefonda konuşarak onu kandırır. Devlerin yardımıyla adadan ayrılırlar.',
      },
    ],
  },
  {
    name: 'Drum Island',
    slug: 'drum-island',
    saga: 'alabasta',
    cover: '/arcs/drum-island.jpg',
    episodeCount: 6,
    summary: 'Nami ağır hastalanır ve mürettebat doktor aramak için Drum Adası\'na gider. Burada küçük ren geyiği doktor Tony Tony Chopper ile tanışırlar.',
    detailedSummary: 'Little Garden\'dan ayrıldıktan sonra Nami, gizemli bir böcek ısırığından dolayı 40 derece ateşle yatağa düşer. Mürettebat, acil doktor arayışıyla kararlı Drum Adası\'na yönelir. Ada, tiran kral Wapol tarafından tüm doktorların sürgün edildiği bir yerdir. Tek kalan doktor, dağın tepesinde yaşayan cadı lakaplı Dr. Kureha ve yanındaki küçük ren geyiği Tony Tony Chopper\'dır. Chopper, Hito Hito meyvesini yiyerek insan zekası kazanmış bir ren geyiğidir. Geçmişi son derece trajiktir: Sürüsü tarafından mavi burnu yüzünden dışlanan Chopper, kendisini kabul eden tek kişi olan Dr. Hiluluk tarafından büyütülmüştür. Hiluluk, tüm hastalıkları iyileştiren kiraz çiçekleri rüyasıyla yaşayan çılgın bir doktordur. Ölümcül hasta olan Hiluluk, Chopper\'ın ona getirdiği zehirli mantarı bile içer — çünkü Chopper\'ın sevgisini reddedemez. Hiluluk\'un ölümü serinin en dokunaklı sahnelerinden biridir. Luffy, Nami\'yi sırtında taşıyarak çıplak elle karla kaplı dik yamacı tırmanır. Wapol geri döner ama Luffy onu yener. Chopper, gözyaşları içinde mürettebata katılır. Hiluluk\'un pembe kiraz çiçekleri karla kaplı gökyüzünü boyar.',
    keyEvents: [
      'Nami\'nin hastalığı',
      'Dr. Hiluluk ve Chopper\'ın hikayesi',
      'Hiluluk\'un ölümü ve kiraz çiçekleri',
      'Luffy\'nin dağ tırmanışı',
      'Wapol\'ın yenilgisi',
      'Chopper mürettebata katılır',
    ],
    themes: ['Doktorluk ve Şifa', 'Kabullenme', 'Mucize ve İnanç', 'Ebeveyn-Çocuk Bağı'],
    location: 'Drum Adası',
    villain: 'Wapol',
    characters: ['luffy', 'nami', 'sanji', 'chopper'],
    episodes: [
      {
        number: 1,
        title: 'Kar Krallığı',
        slug: 'drum-island-01',
        duration: '24:00',
        summary: 'Nami ateşler içinde yatarken mürettebat Drum Adası\'na ulaşır. Karlarla kaplı ada, eski kral Wapol tarafından tüm doktorların sürgün edildiği bir yerdir. Tek doktor, dağın tepesindeki cadı Dr. Kureha\'dır.',
      },
      {
        number: 2,
        title: 'Dr. Kureha',
        slug: 'drum-island-02',
        duration: '24:30',
        summary: 'Luffy, hasta Nami\'yi sırtına alır ve Sanji ile birlikte karla kaplı dik yamacı tırmanmaya başlar. İnanılmaz bir dayanıklılık göstererek çıplak ellerle zirveye ulaşır. Dr. Kureha\'nın yanında küçük ren geyiği Chopper ile tanışırlar.',
      },
      {
        number: 3,
        title: 'Chopper\'ın Hikayesi',
        slug: 'drum-island-03',
        duration: '25:00',
        summary: 'Tony Tony Chopper\'ın trajik geçmişi anlatılır. Mavi burnu yüzünden sürüsü tarafından dışlanan Chopper, Hito Hito meyvesini yiyerek insan formuna dönüşür. Ancak insanlar da onu kabul etmez. Tek dostu çılgın doktor Hiluluk olur.',
      },
      {
        number: 4,
        title: 'Hiluluk\'un Kirazları',
        slug: 'drum-island-04',
        duration: '24:30',
        summary: 'Dr. Hiluluk ölümcül hastadır. Chopper, onu kurtarmak için bir mantar bulur ama bu mantarın zehirli olduğunu bilmez. Hiluluk, Chopper\'ın sevgisini bildiği için mantarı içer. Ölmeden önce Wapol\'ın tuzağına düşer ve kendini feda eder: "İnsanlar ne zaman ölür? Unutulduklarında!"',
      },
      {
        number: 5,
        title: 'Wapol\'a Karşı',
        slug: 'drum-island-05',
        duration: '24:00',
        summary: 'Eski kral Wapol, Baku Baku meyvesiyle güçlenerek adaya geri döner ve krallığını geri almaya çalışır. Hiluluk\'un bayrağına hakaret eder. Chopper öfkelenir. Luffy, Wapol\'ı adanın dışına yumruklar.',
      },
      {
        number: 6,
        title: 'Yeni Mürettebat Üyesi',
        slug: 'drum-island-06',
        duration: '24:30',
        summary: 'Wapol yenildikten sonra Luffy, Chopper\'ı mürettebata davet eder. Chopper önce reddeder ama Luffy\'nin ısrarıyla kabul eder ve gözyaşları içinde veda eder. Dr. Kureha, Hiluluk\'un rüyasını gerçekleştirir: pembe kiraz çiçekleri karla kaplı gökyüzünü boyar. "Lanet yaşlı adam, gerçekten de mucize yarattın."',
      },
    ],
  },
  {
    name: 'Arabasta',
    slug: 'arabasta',
    saga: 'alabasta',
    cover: '/arcs/arabasta.jpg',
    episodeCount: 15,
    summary: 'Hasır Şapkalar, Prenses Vivi\'nin krallığını kurtarmak için Shichibukai Crocodile\'a karşı savaşır. Çölün ortasında bir ülkenin kaderi belirlenir.',
    detailedSummary: 'Alabasta Sagası\'nın doruk noktası ve serinin ilk büyük final savaşı. Baroque Works\'ün planı tam olarak ortaya çıkar: Crocodile, Arabasta\'da iç savaş çıkartarak krallığı ele geçirecek ve eski silah Pluton\'u bulmak için Poneglyph\'i okutacaktır. Hasır Şapkalar, isyancı ordu ile kraliyet ordusu arasındaki savaşı durdurmak için zamana karşı yarışırlar. Her mürettebat üyesi bir Baroque Works ajanıyla eşleşir: Zoro vs Mr. 1 (çeliği kesmesini öğrenir), Sanji vs Mr. 2 (Bon Clay), Nami vs Miss Doublefinger, Chopper vs Mr. 4 ve Miss Merry Christmas, Usopp ve Chopper vs Mr. 4. Luffy, Crocodile ile üç kez savaşır ve her seferinde daha güçlü geri döner. Vivi\'nin "Lütfen savaşmayı bırakın!" çığlığı milyonlara ulaşmaz ama yağmur yağması savaşı durdurur. Robin, Crocodile\'a ihanet ederek Luffy\'yi kurtarır. Arc sonunda Robin mürettebata katılır. Vivi\'nin mürettebatla kalıp kalmama kararı ve "X işareti" vedası, serinin en duygusal anlarından biridir.',
    keyEvents: [
      'Crocodile\'ın Arabasta darbe planı',
      'Hasır Şapkalar vs Baroque Works eşleşmeleri',
      'Zoro çeliği kesmeyi öğrenir',
      'Luffy vs Crocodile (3 savaş)',
      'Vivi\'nin barış çığlığı',
      'Robin mürettebata katılır',
      'X işareti vedası',
    ],
    themes: ['Savaş ve Barış', 'Liderlik ve Sorumluluk', 'İhanet ve Güven', 'Krallık ve Halk'],
    location: 'Arabasta Krallığı (Rainbase, Alubarna, Yuba)',
    villain: 'Crocodile (Mr. 0)',
    characters: ['luffy', 'zoro', 'nami', 'sanji', 'usopp', 'chopper', 'vivi', 'robin'],
    episodes: [
      {
        number: 1,
        title: 'Çöl Krallığı',
        slug: 'arabasta-01',
        duration: '24:00',
        summary: 'Mürettebat Arabasta\'ya ulaşır. Çöl sıcağı ve kum fırtınaları zorlu koşullar yaratır. Vivi, ülkesindeki iç savaşın boyutlarını görünce yıkılır. Ace, Luffy\'nin ağabeyi olarak sürpriz bir şekilde ortaya çıkar.',
      },
      {
        number: 2,
        title: 'İsyan Başlıyor',
        slug: 'arabasta-02',
        duration: '24:30',
        summary: 'Crocodile\'ın planı netleşir: Dance Powder kullanarak kuraklık yaratmış ve halkı krala karşı kışkırtmıştır. İsyancı ordu Koza liderliğinde başkent Alubarna\'ya yürüyor. Mürettebat onları durdurmak için zamanla yarışır.',
      },
      {
        number: 3,
        title: 'Rainbase',
        slug: 'arabasta-03',
        duration: '24:00',
        summary: 'Mürettebat, Crocodile\'ın karargahı Rain Dinners kumarhanesine sızar. Ancak tuzağa düşerler ve Crocodile\'ın timsah havuzunda hapsolurlar. Sanji, "Mr. Prince" takma adıyla onları kurtarır.',
      },
      {
        number: 4,
        title: 'Crocodile\'ın Planı',
        slug: 'arabasta-04',
        duration: '24:30',
        summary: 'Crocodile\'ın asıl amacı ortaya çıkar: Arabasta\'nın altında gizli Poneglyph\'i kullanarak eski silah Pluton\'u bulmak. Robin\'i bu amaçla yanında tutmuştur. Luffy, Crocodile ile ilk kez yüzleşir.',
      },
      {
        number: 5,
        title: 'Alubarna Savaşı',
        slug: 'arabasta-05',
        duration: '25:00',
        summary: 'İsyancılar ve kraliyet ordusu Alubarna\'da çarpışmaya başlar. Mürettebat, Baroque Works ajanlarını durdurmak için ayrılır. Her biri bir ajanla eşleşir. Vivi, savaşı durdurmak için umutsuzca koşar.',
      },
      {
        number: 6,
        title: 'Zoro vs Mr. 1',
        slug: 'arabasta-06',
        duration: '24:00',
        summary: 'Zoro, vücudunu çeliğe dönüştürebilen Mr. 1 (Daz Bones) ile savaşır. Zoro, bu savaşta çeliği kesmeyi öğrenir — her şeyi kesebilen ve hiçbir şeyi kesmeyen kılıcın felsefesini kavrar. "Nefes alışını dinle."',
      },
      {
        number: 7,
        title: 'Sanji vs Mr. 2',
        slug: 'arabasta-07',
        duration: '24:30',
        summary: 'Sanji, Mane Mane meyvesiyle başkalarının yüzüne dönüşebilen Mr. 2 Bon Clay ile savaşır. Bon Clay, Nami\'nin yüzüne dönüşerek Sanji\'yi zor durumda bırakır. Ancak Sanji bir strateji geliştirir ve kazanır. İronik bir şekilde Bon Clay ile karşılıklı saygı gelişir.',
      },
      {
        number: 8,
        title: 'Luffy vs Crocodile I',
        slug: 'arabasta-08',
        duration: '25:00',
        summary: 'Luffy, Suna Suna meyvesiyle kum haline dönüşebilen Crocodile ile ilk savaşını yapar. Crocodile, kumlara dokunarak su çekme gücüyle Luffy\'yi alt eder. Luffy, kum fırtınasının ortasında yenilir ve kumlara gömülür.',
      },
      {
        number: 9,
        title: 'Luffy vs Crocodile II',
        slug: 'arabasta-09',
        duration: '24:30',
        summary: 'Luffy, Robin tarafından kurtarılır ve ikinci kez Crocodile ile savaşır. Bu sefer suyla ıslanmış yumruklarla saldırır. Crocodile\'ın zehirli kancası Luffy\'yi zehirler. Luffy yine yenilir ama vazgeçmez.',
      },
      {
        number: 10,
        title: 'Luffy vs Crocodile III',
        slug: 'arabasta-10',
        duration: '25:00',
        summary: 'Luffy, kanını kullanarak Crocodile\'a üçüncü kez saldırır. Yeraltı mezar odasında epik final savaşı. Luffy, tüm gücüyle Crocodile\'ı tavan boyunca fırlatır ve sonunda yener. "Vivi\'nin ülkesini geri ver!"',
      },
      {
        number: 11,
        title: 'Yağmur Yağıyor',
        slug: 'arabasta-11',
        duration: '24:00',
        summary: 'Crocodile yenilir ve Baroque Works\'ün planı çöker. Bomba son anda etkisiz hale getirilir. Yıllardır yağmayan yağmur yağmaya başlar. İsyancılar ve askerler silahlarını bırakır. Arabasta kurtulmuştur.',
      },
      {
        number: 12,
        title: 'Vivi\'nin Kararı',
        slug: 'arabasta-12',
        duration: '24:30',
        summary: 'Savaş bitti, Arabasta barışa kavuştu. Vivi\'nin mürettebatla kalıp kalmama kararı. Vivi, prenses olarak halkının yanında kalması gerektiğine karar verir ama bu ayrılık çok zordur.',
      },
      {
        number: 13,
        title: 'X İşareti',
        slug: 'arabasta-13',
        duration: '24:00',
        summary: 'Serinin en ikonik veda sahnelerinden biri. Mürettebat, Deniz Kuvvetleri takibinden kaçarken Vivi kıyıdan seslenir: "Tekrar arkadaş olabilir miyiz?" Mürettebat, cevap verirse Vivi\'nin suçlanacağını bildiği için sessizce kollarındaki X işaretini gösterir — dostluklarının simgesi.',
      },
      {
        number: 14,
        title: 'Nico Robin',
        slug: 'arabasta-14',
        duration: '24:30',
        summary: 'Mürettebat denize açıldıktan sonra büyük bir sürpriz: Nico Robin gemide belirir. Crocodile\'a ihanet eden Robin, Luffy\'nin onu kurtarmasına rağmen yaşamak için bir nedeni olmadığını söyler. Luffy\'den mürettebata katılmasını ister.',
      },
      {
        number: 15,
        title: 'Yeni Maceraya',
        slug: 'arabasta-15',
        duration: '24:00',
        summary: 'Robin resmi olmasa da mürettebata katılır. Herkes ona şüpheyle yaklaşır ama Robin soğukkanlı ve gizemli tavrıyla kendini kabul ettirir. Mürettebat, yeni maceralara doğru yelken açar. Arabasta Sagası sona erer.',
      },
    ],
  },
]
