import type { Arc } from '@/types'

export const DRESSROSA_ARCS: Arc[] = [
  {
    name: 'Punk Hazard',
    slug: 'punk-hazard',
    saga: 'dressrosa',
    cover: '/arcs/punk-hazard.jpg',
    episodeCount: 12,
    summary: 'Yarısı buz yarısı ateş olan gizemli ada. Caesar Clown\'ın yasadışı deneyleri ve Law ile ittifak.',
    detailedSummary: 'Yeni Dünya\'daki ilk durak: yarısı buz, yarısı ateş olan Punk Hazard. Ada, Akainu ve Aokiji\'nin 10 günlük düellosunun ardından bu hale gelmiştir. Caesar Clown — eski bilim insanı ve gaz uzmanı — burada yasadışı kitle imha silahı deneyleri yapmaktadır. Çocukları kaçırıp üzerlerinde deney yapmakta, Joker (Doflamingo) için SAD üretmektedir. SAD, yapay Zoan Şeytan Meyveleri (SMILE) için gerekli maddedir. Trafalgar Law, Luffy\'ye ittifak teklif eder: birlikte bir Yonko\'yu — Kaido\'yu — devirmek. Bunun için önce Kaido\'nun SMILE tedarik zincirini kesmek gerekir. Luffy kabul eder. Law ve Luffy birlikte Caesar\'ı yener. Smoker ve Tashigi de adadır. G-5 askerleri çocukları kurtarmaya yardım eder. İttifak, bir sonraki hedef olan Dressrosa\'ya yönelir.',
    keyEvents: [
      'Law-Luffy ittifakı kurulur',
      'Caesar Clown\'ın yasadışı deneyleri',
      'SAD ve SMILE tedarik zinciri',
      'Çocukların kurtarılması',
      'Kaido\'yu devirme planı',
      'Smoker ve Tashigi ile işbirliği',
    ],
    themes: ['Bilim ve Etik', 'İttifak ve Güven', 'Çocuk İstismarı', 'Güç Dengeleri'],
    location: 'Punk Hazard',
    villain: 'Caesar Clown',
    characters: ['luffy', 'zoro', 'law', 'smoker'],
    episodes: [
      { number: 1, title: 'Ateş ve Buz Adası', slug: 'punk-hazard-01', duration: '24:30', summary: 'Mürettebat, yarısı alev yarısı buz olan gizemli Punk Hazard\'a ulaşır. Adadan gelen acil yardım çağrısı onları çeker. İçeride devasa bir ejderha ve gizemli olaylar.' },
      { number: 2, title: 'Caesar Clown', slug: 'punk-hazard-02', duration: '24:30', summary: 'Gazlı bilim insanı Caesar Clown\'ın laboratuvarı keşfedilir. Caesar, Gasu Gasu meyvesiyle zehirli gaz üreten tehlikeli bir dehadır. Kaçırılmış çocuklar üzerinde deney yapmaktadır.' },
      { number: 3, title: 'Law\'ın Teklifi', slug: 'punk-hazard-03', duration: '24:30', summary: 'Trafalgar Law, Luffy\'ye ittifak teklif eder: birlikte Yonko Kaido\'yu devirmek. Law\'ın planı: Kaido\'nun SMILE tedarik zincirini kesmek. Luffy, Law\'ın kararlılığını görüp kabul eder.' },
      { number: 4, title: 'Çocukları Kurtarın', slug: 'punk-hazard-04', duration: '24:30', summary: 'Nami ve Chopper, Caesar tarafından kaçırılan çocukları kurtarmaya çalışır. Çocuklar, uyuşturucu karışımlı şekerlerle bağımlı yapılmıştır. Chopper tedavi yolunu arar.' },
      { number: 5, title: 'Smoker vs Vergo', slug: 'punk-hazard-05', duration: '24:30', summary: 'Smoker, eski arkadaşı ve gizli Doflamingo ajanı Vergo ile savaşır. Vergo, 15 yıldır Deniz Kuvvetleri\'ne sızmış bir casustur. Law, Ope Ope meyvesiyle Vergo\'yu keser.' },
      { number: 6, title: 'Shinokuni', slug: 'punk-hazard-06', duration: '24:30', summary: 'Caesar, ölümcül zehirli gaz Shinokuni\'yi salar. Gaz, dokunduğu her şeyi zehirler. Mürettebat, gazdan kaçarken Caesar\'ı durdurmaya çalışır.' },
      { number: 7, title: 'Luffy vs Caesar', slug: 'punk-hazard-07', duration: '24:30', summary: 'Luffy, Caesar ile savaşır. Caesar, havadan oksijeni çekerek Luffy\'yi boğmaya çalışır. Luffy, Gear 2 ve Busoshoku Haki ile Caesar\'ı tek yumrukla nakavt eder.' },
      { number: 8, title: 'Akainu vs Aokiji', slug: 'punk-hazard-08', duration: '24:30', summary: 'Adanın neden yarı buz yarı ateş olduğu açıklanır: Akainu ve Aokiji, Büyükamiral koltuğu için 10 gün boyunca burada savaşmışlardır. İklimi kalıcı olarak değiştirmişlerdir.' },
      { number: 9, title: 'SAD Fabrikası', slug: 'punk-hazard-09', duration: '24:30', summary: 'Law, SAD üretim tesisini yok eder. SAD, Doflamingo\'nun Kaido\'ya sattığı yapay Şeytan Meyveleri SMILE için gereklidir. Tedarik zincirinin ilk halkası kırılmıştır.' },
      { number: 10, title: 'Monet\'in Son Anı', slug: 'punk-hazard-10', duration: '24:30', summary: 'Doflamingo\'nun ajanı Monet, adayı havaya uçurmaya çalışır. Zoro\'nun korkutucu aurası Monet\'i felç eder. Caesar, bilmeden Monet\'in kalbi yerine kendi kalbini bıçaklar.' },
      { number: 11, title: 'Doflamingo\'nun Gölgesi', slug: 'punk-hazard-11', duration: '24:30', summary: 'Doflamingo, Caesar\'ın yakalandığını öğrenince öfkelenir. Şehirden Punk Hazard\'a doğru uçar. Law ve ittifak, bir sonraki hedef Dressrosa\'ya doğru acele eder.' },
      { number: 12, title: 'Dressrosa\'ya Doğru', slug: 'punk-hazard-12', duration: '24:30', summary: 'Mürettebat, Caesar\'ı rehine alarak Dressrosa\'ya yol alır. Law\'ın planı: Dressrosa\'daki SMILE fabrikasını yok etmek ve Doflamingo\'yu Shichibukai koltuğundan düşürmek. Büyük plan harekete geçmiştir.' },
    ],
  },
  {
    name: 'Dressrosa',
    slug: 'dressrosa',
    saga: 'dressrosa',
    cover: '/arcs/dressrosa.jpg',
    episodeCount: 28,
    summary: 'Shichibukai Doflamingo\'nun tutsak ettiği krallık. Luffy, Gear 4 formunu ilk kez kullanır. En uzun arc\'lardan biri.',
    detailedSummary: 'İspanya temalı tutkulu ülke Dressrosa, görünüşte mutlu bir krallıktır ama gerçekte Doflamingo\'nun demir yumruğuyla yönetilmektedir. Doflamingo, 10 yıl önce Riku Krallık ailesini devirerek tahta geçmiştir. Ito Ito meyvesiyle insanları kukla gibi kontrol edebilir. "Birdcage" — tüm ülkeyi kaplayan ip kafesi — ile kimse kaçamaz. Corrida Colosseum\'da bir turnuva düzenlenir ve ödül Ace\'in eski Mera Mera meyvesidir. Luffy, Lucy takma adıyla turnuvaya katılır. Sabo — Luffy\'nin öldü sandığı kardeşi — hayattadır ve Devrimci Ordunun 2 numarasıdır! Sabo, Mera Mera meyvesini kazanır ve Ace\'in mirasını devralır. Oyuncak Askerinin gerçek kimliği Kyros — Dressrosa\'nın en büyük gladyatörü — ortaya çıkar. Sugar\'ın Hobi Hobi meyvesi insanları oyuncağa çevirmiştir. Usopp, Sugar\'ı korkutarak herkesi geri döndürür ve "God Usopp" olur. Luffy, Gear 4 Boundman\'ı ilk kez kullanarak Doflamingo\'yu yener. 7 krallıktan 5600 korsan Luffy\'ye bağlılık yemini eder — Hasır Şapka Büyük Filo doğar.',
    keyEvents: [
      'Doflamingo\'nun 10 yıllık tiranlığı',
      'Corrida Colosseum turnuvası',
      'Sabo hayatta! Mera Mera meyvesini alır',
      'Sugar\'ın oyuncak laneti kırılır',
      'Usopp "God Usopp" olur',
      'Birdcage tehlikesi',
      'Luffy Gear 4 Boundman ilk kullanım',
      'Doflamingo\'nun yenilgisi',
      'Hasır Şapka Büyük Filo kurulur',
    ],
    themes: ['Tiranlık ve Devrim', 'Aile ve Miras', 'Özgürlük', 'İttifak ve Liderlik'],
    location: 'Dressrosa',
    villain: 'Donquixote Doflamingo',
    characters: ['luffy', 'zoro', 'law', 'sabo', 'doflamingo'],
    episodes: [
      { number: 1, title: 'Tutku Ülkesi Dressrosa', slug: 'dressrosa-01', duration: '24:30', summary: 'Mürettebat Dressrosa\'ya varır. Renkli, tutkulu ve dans eden insanlarla dolu bir ülke. Ancak yüzeyin altında Doflamingo\'nun demir kontrolü vardır. Oyuncak askerlerin gizemli varlığı dikkat çeker.' },
      { number: 2, title: 'Corrida Colosseum', slug: 'dressrosa-02', duration: '24:30', summary: 'Doflamingo, Ace\'in Mera Mera meyvesini ödül olarak koyduğu bir gladyatör turnuvası düzenler. Luffy, "Lucy" takma adıyla turnuvaya katılır. Güçlü savaşçılar: Cavendish, Bartolomeo, Sai ve daha fazlası.' },
      { number: 3, title: 'Lucy Arenada', slug: 'dressrosa-03', duration: '24:30', summary: 'Luffy, Lucy olarak arenada savaşır. Don Chinjao\'nun 500 milyon Berry\'lik eski korsanla karşılaşır ve Haoshoku Haki çarpışmasıyla kazanır. Turnuva kızışır.' },
      { number: 4, title: 'Sabo Yaşıyor!', slug: 'dressrosa-04', duration: '24:30', summary: 'Serinin en büyük sürprizlerinden biri: Sabo hayattadır! Luffy\'nin öldü sandığı kardeşi, Devrimci Ordunun Genelkurmay Başkanıdır. Sabo, Lucy\'nin yerine geçerek Mera Mera meyvesini almak ister.' },
      { number: 5, title: 'Oyuncak Askeri', slug: 'dressrosa-05', duration: '24:30', summary: 'Oyuncak Askeri\'nin gerçek kimliği anlatılır: Kyros, Dressrosa\'nın en büyük gladyatörüdür. Sugar\'ın Hobi Hobi meyvesiyle oyuncağa çevrilmiştir. Kızı Rebecca\'yı bile tanıyamaz.' },
      { number: 6, title: 'Sugar\'ın Laneti', slug: 'dressrosa-06', duration: '24:30', summary: 'Sugar\'ın gücü ortaya çıkar: dokunduğu herkesi oyuncağa çevirir ve herkes o kişiyi unutur. Dressrosa\'nın "mutlu" yüzeyinin altındaki korkunç gerçek: binlerce kişi oyuncak yapılmıştır.' },
      { number: 7, title: 'SOP Operasyonu', slug: 'dressrosa-07', duration: '24:30', summary: 'Law ve mürettebat, Sugar\'ı bayıltma operasyonu başlatır. Robin, Sugar\'a yaklaşmaya çalışır. Franky, Senor Pink ile savaşır — iki "sert adam"ın saygı dolu düellosu.' },
      { number: 8, title: 'God Usopp', slug: 'dressrosa-08', duration: '24:30', summary: 'Usopp, Sugar\'ı korkutarak bayıltır ve lanet bozulur! Binlerce oyuncak insan formuna döner. Herkes Usopp\'u "Tanrı Usopp" olarak anar. Usopp\'un ödülü 200 milyona çıkar.' },
      { number: 9, title: 'Birdcage', slug: 'dressrosa-09', duration: '24:30', summary: 'Doflamingo, Birdcage\'i aktive eder: tüm ülkeyi kaplayan ip kafesi her şeyi keser ve kimse kaçamaz. Cage daralmaya başlar — zamana karşı yarış.' },
      { number: 10, title: 'Sabo vs Fujitora', slug: 'dressrosa-10', duration: '24:30', summary: 'Sabo, Mera Mera meyvesini yer ve Ace\'in mirasını devralır. Ateş güçleriyle Amiral Fujitora ile savaşır. İki güçlü savaşçının çarpışması Dressrosa\'yı sarsar.' },
      { number: 11, title: 'Zoro vs Pica', slug: 'dressrosa-11', duration: '24:30', summary: 'Zoro, İshi İshi meyvesiyle taşa dönüşebilen devasa Pica ile savaşır. Pica tüm adayı taş gövdesi haline getirir. Zoro, Busoshoku Haki ile devasa taş gövdeyi ikiye böler.' },
      { number: 12, title: 'Law vs Doflamingo', slug: 'dressrosa-12', duration: '24:30', summary: 'Law, Doflamingo ile yüzleşir. Corazon\'un — Doflamingo\'nun kardeşi ve Law\'ın kurtarıcısı — hikayesi anlatılır. Corazon, Law\'ı Ope Ope meyvesiyle kurtarmak için hayatını vermiştir.' },
      { number: 13, title: 'Corazon\'un Mirası', slug: 'dressrosa-13', duration: '24:30', summary: 'Law\'ın çocukluğu ve Flevance trajedisi: Amber Lead hastalığıyla yok olan bir ülke. Doflamingo Law\'ı almış ama Corazon onu kurtarmıştır. Law, Corazon\'un intikamını almak ister.' },
      { number: 14, title: 'Doflamingo\'nun Geçmişi', slug: 'dressrosa-14', duration: '24:30', summary: 'Doflamingo\'nun Celestial Dragon kökenli olduğu ortaya çıkar. Babası insanlar arasında yaşamaya karar vermiş ama halk onları linç etmiştir. Doflamingo, babasını öldürmüş ve başını Mariejois\'a göndermiştir.' },
      { number: 15, title: 'Rebecca\'nın Gözyaşları', slug: 'dressrosa-15', duration: '24:30', summary: 'Rebecca, babası Kyros\'un oyuncak formunda bile onu koruduğunu öğrenir. Kyros, insan formuna dönerek Diamante ile savaşır. Baba-kız yeniden birleşir.' },
      { number: 16, title: 'Franky vs Senor Pink', slug: 'dressrosa-16', duration: '24:30', summary: 'Franky ve Senor Pink arasındaki "erkekler savaşı". Her ikisi de saldırıdan kaçmaz, yumrukları göğüsler. Senor Pink\'in trajik geçmişi — bebek kıyafetlerinin sebebi — ortaya çıkar. Saygı dolu final.' },
      { number: 17, title: 'Gear Fourth: Boundman', slug: 'dressrosa-17', duration: '24:30', summary: 'Luffy, Gear 4 Boundman formunu ilk kez kullanır! Vücudunu Busoshoku Haki ile kaplayarak lastik zıplama gücünü devasa bir savaş formuna çevirir. Kong Gun ile Doflamingo\'yu fırlatır.' },
      { number: 18, title: 'Luffy vs Doflamingo I', slug: 'dressrosa-18', duration: '24:30', summary: 'Gear 4 Luffy, Doflamingo\'yu domine eder. Ancak Gear 4\'ün zaman sınırı vardır. Doflamingo\'nun Awakening\'i — çevredeki her şeyi iplere dönüştürme — durumu zorlaştırır.' },
      { number: 19, title: 'Luffy vs Doflamingo II', slug: 'dressrosa-19', duration: '24:30', summary: 'Gear 4 süresi dolar ve Luffy 10 dakika boyunca Haki kullanamaz. Tüm Dressrosa Luffy\'yi korumak için Doflamingo\'ya karşı zaman kazanır. Gatz, arenayla Luffy\'nin geri sayımını yapar.' },
      { number: 20, title: 'King Kong Gun', slug: 'dressrosa-20', duration: '24:30', summary: 'Luffy, Gear 4\'e geri döner ve en güçlü tekniğini kullanır: King Kong Gun. Devasa Haki yumruğu Doflamingo\'yu yerin altına gömer ve Birdcage çöker. Dressrosa özgür!' },
      { number: 21, title: 'Dressrosa Özgür', slug: 'dressrosa-21', duration: '24:30', summary: 'Doflamingo yenilir ve tutuklanır. 10 yıllık tiranlık sona erer. Riku Ailesi tahta döner. Dressrosa halkı kutlama yapar. Kyros ve Rebecca sonunda birlikte olabilir.' },
      { number: 22, title: 'Fujitora\'nın Saygısı', slug: 'dressrosa-22', duration: '24:30', summary: 'Amiral Fujitora, kör olmasına rağmen Luffy\'nin yüzünü "görmek" ister. Hasır Şapkalara karşı saygı duyar ve onları yakalamayı reddeder. Shichibukai sisteminin kaldırılmasını önerir.' },
      { number: 23, title: 'Büyük Filo', slug: 'dressrosa-23', duration: '24:30', summary: '7 güçlü kaptan — Cavendish, Bartolomeo, Sai, Ideo, Leo, Hajrudin, Orlumbus — Luffy\'ye bağlılık yemini eder. Luffy istemese de Hasır Şapka Büyük Filo (5600 kişi) kurulmuş olur.' },
      { number: 24, title: 'Sabo\'nun Mektubu', slug: 'dressrosa-24', duration: '24:30', summary: 'Sabo, Luffy\'ye veda eder ve Ace\'in mezarını ziyaret edeceğini söyler. Mera Mera meyvesini Ace\'in onuruna kullanacaktır. Üç kardeşin bağı devam ediyor.' },
      { number: 25, title: 'Yeni Ödüller', slug: 'dressrosa-25', duration: '24:30', summary: 'Mürettebatın ödülleri güncellenir. Luffy 500 milyon, Zoro 320 milyon, Usopp (God Usopp) 200 milyon. Luffy artık "Beşinci İmparator" olarak anılmaya başlar.' },
      { number: 26, title: 'Kaido\'nun Planı', slug: 'dressrosa-26', duration: '24:30', summary: 'SMILE tedariki kesildiğini öğrenen Kaido öfkelenir. Gökyüzü adasından atlayarak intihar etmeye çalışır ama ölmez. "Sıkıcı bir dünya" — dünyanın en güçlü canlısı savaş istiyor.' },
      { number: 27, title: 'Doflamingo Ailesi', slug: 'dressrosa-27', duration: '24:30', summary: 'Doflamingo\'nun aile üyelerinin kaderi: Trebol, Diamante, Pica tutuklanır. Bellamy, Luffy tarafından affedilir. Doflamingo Impel Down\'a götürülür.' },
      { number: 28, title: 'Zou\'ya Doğru', slug: 'dressrosa-28', duration: '24:30', summary: 'Mürettebat ikiye ayrılır: bir grup Zou\'ya, diğeri Dressrosa\'da kalır. Law, ittifakın devam edeceğini söyler. Kaido\'yu devirmek için plan genişliyor. Bir sonraki durak: dev filin sırtındaki ada Zou.' },
    ],
  },
]
