import type { Arc } from '@/types'

export const DRESSROSA_ARCS: Arc[] = [
  {
    name: 'Punk Hazard',
    slug: 'punk-hazard',
    saga: 'dressrosa',
    cover: '/arcs/punk-hazard.jpg',
    episodeCount: 22,
    summary: 'Yarısı buz yarısı ateş olan gizemli ada. Caesar Clown\'ın yasadışı deneyleri ve Law ile ittifak.',
    detailedSummary: 'Yeni Dünya\'daki ilk durak: yarısı buz, yarısı ateş olan Punk Hazard. Ada, Akainu ve Aokiji\'nin 10 günlük düellosunun ardından bu hale gelmiştir. Caesar Clown — eski bilim insanı ve gaz uzmanı — burada yasadışı kitle imha silahı deneyleri yapmaktadır. Çocukları kaçırıp üzerlerinde deney yapmakta, Joker (Doflamingo) için SAD üretmektedir. SAD, yapay Zoan Şeytan Meyveleri (SMILE) için gerekli maddedir. Trafalgar Law, Luffy\'ye ittifak teklif eder: birlikte bir Yonko\'yu — Kaido\'yu — devirmek. Bunun için önce Kaido\'nun SMILE tedarik zincirini kesmek gerekir. Luffy kabul eder. Law ve Luffy birlikte Caesar\'ı yener. Smoker ve Tashigi de adadır. G-5 askerleri çocukları kurtarmaya yardım eder. İttifak, bir sonraki hedef olan Dressrosa\'ya yönelir.',
    keyEvents: [
      'Law-Luffy ittifakı kurulur',
      'Caesar Clown\'ın yasadışı deneyleri',
      'SAD ve SMILE tedarik zinciri',
      'Çocukların kurtarılması',
      'Kaido\'yu devirme planı',
      'Smoker ve Tashigi ile işbirliği',
    ],
    themes: ['Bilim ve Etik', 'İttifak ve Güven', 'Çocuk İstismarı', 'Güç Dengeleri'],
    location: 'Punk Hazard',
    villain: 'Caesar Clown',
    characters: ['luffy', 'zoro', 'law', 'smoker'],
    episodes: [
      { number: 1, title: 'Punk Hazard', slug: 'punk-hazard-01', duration: '24:30', summary: 'Mürettebat, Yeni Dünya\'daki ilk durağa varır: yarısı alev yarısı buz olan gizemli Punk Hazard. Adadan gelen acil yardım çağrısı onları çeker.' },
      { number: 2, title: 'Yanan Adadaki Macera', slug: 'punk-hazard-02', duration: '24:30', summary: 'Adada devasa bir ejderha ile karşılaşılır. Luffy ve Zoro ejderhayı yener. Gizemli tehlikeler belirmeye başlar.' },
      { number: 3, title: 'Gövdem Hakkında', slug: 'punk-hazard-03', duration: '24:30', summary: 'Mürettebat, adanın derinliklerinde gizli bir laboratuvar keşfeder. İçeride kaçırılmış dev çocuklar ve garip deneyler. Nami ve Chopper çocuklarla ilgilenir.' },
      { number: 4, title: 'Göl Kenarındaki Haydutlar', slug: 'punk-hazard-04', duration: '24:30', summary: 'Gazlı bilim insanı Caesar Clown ortaya çıkar. Gasu Gasu meyvesiyle zehirli gaz üreten tehlikeli bir dehadır. Kaçırılmış çocuklar üzerinde korkunç deneyler yapmaktadır.' },
      { number: 5, title: 'CC', slug: 'punk-hazard-05', duration: '24:30', summary: 'Çocukların durumu daha da netleşir: Caesar onları uyuşturucu karışımlı şekerlerle bağımlı yaparak dev boyutlara ulaştırmıştır. Chopper tedavi yolunu aramaya başlar.' },
      { number: 6, title: 'Havalı Yeti Kardeşler', slug: 'punk-hazard-06', duration: '24:30', summary: 'Trafalgar Law, Luffy\'ye büyük bir ittifak teklif eder: birlikte Yonko Kaido\'yu devirmek. Law\'ın planı SMILE tedarik zincirini kesmekle başlar. Luffy tereddütsüz kabul eder.' },
      { number: 7, title: 'Korsan İttifakı', slug: 'punk-hazard-07', duration: '24:30', summary: 'Laboratuvarın derinlikleri keşfedilir. Caesar\'ın deneyleri, SAD üretimi ve Joker bağlantısı ortaya çıkar. Mürettebat farklı gruplara ayrılarak adayı araştırır.' },
      { number: 8, title: 'Kar Fırtınası ve Slime', slug: 'punk-hazard-08', duration: '24:30', summary: 'Brownbeard ve kentaur adamlar hakkında gerçekler ortaya çıkar. Caesar onları "kurtardığını" iddia etmiş ama aslında denek olarak kullanmaktadır. Aldatılmış kentaurlar isyan eder.' },
      { number: 9, title: 'Adım Kin\'emon!!', slug: 'punk-hazard-09', duration: '24:30', summary: 'Caesar\'ın gerçek yüzünü öğrenen kentaurlar ayaklanır. Ancak Caesar\'ın gaz gücü karşısında çaresiz kalırlar. Luffy, Caesar\'ı durdurmaya kararlıdır.' },
      { number: 10, title: 'Vergo ve Joker!', slug: 'punk-hazard-10', duration: '24:30', summary: 'Smoker, eski arkadaşı ve gizli Doflamingo ajanı Vergo ile yüzleşir. Vergo, 15 yıldır Deniz Kuvvetleri\'ne sızmış bir casustur. Tam vücut Busoshoku Haki kullanan acımasız bir savaşçıdır.' },
      { number: 11, title: 'Shinokuni Serbest Bırakıldı!', slug: 'punk-hazard-11', duration: '24:30', summary: 'Law, Ope Ope meyvesinin gücüyle Vergo\'yu keser. Corazon\'un intikamının ilk adımı atılmıştır. Vergo\'nun 15 yıllık casusluk kariyeri sona erer.' },
      { number: 12, title: 'Karşı Saldırı Başlıyor', slug: 'punk-hazard-12', duration: '24:30', summary: 'Tashigi ve G-5 askerleri çocukları kurtarmak için savaşır. Caesar\'ın adamlarıyla çatışma kızışır. Deniz Kuvvetleri ve korsanlar ortak düşmana karşı işbirliği yapar.' },
      { number: 13, title: 'G-5\'in Fedakarlığı ve Koramiralin İhaneti!', slug: 'punk-hazard-13', duration: '24:30', summary: 'Caesar, ölümcül zehirli gaz Shinokuni\'yi salar. Gaz, dokunduğu her canlıyı anında zehirler ve taşlaştırır. Herkes laboratuvara sığınmak zorunda kalır.' },
      { number: 14, title: 'Gölgelerdeki Deha', slug: 'punk-hazard-14', duration: '24:30', summary: 'Caesar, Shinokuni\'yi bir kitle imha silahı olarak pazarlamak için canlı yayında deney yapar. Yeraltı dünyasının brokerları izlemektedir. Caesar\'ın deliliği tüm çıplaklığıyla ortaya çıkar.' },
      { number: 15, title: 'Punk Hazard\'ın Yıkımının Arkasındaki Gerçek!', slug: 'punk-hazard-15', duration: '24:30', summary: 'Shinokuni laboratuvara doğru ilerler. Mürettebat ve çocuklar gazdan kaçmak için zamana karşı yarışır. Chopper, çocukları tedavi ederken gazın etkisini azaltmaya çalışır.' },
      { number: 16, title: 'Momonosuke Adlı Ejderha', slug: 'punk-hazard-16', duration: '24:30', summary: 'Luffy, Caesar Clown ile savaşmaya başlar. Caesar, havadan oksijeni çekerek Luffy\'yi boğmaya çalışır. Ancak Luffy, Busoshoku Haki ile Caesar\'ın gaz bedenine zarar verebilir.' },
      { number: 17, title: 'Vahşi Hayvan', slug: 'punk-hazard-17', duration: '24:30', summary: 'Savaş kızışır. Caesar tüm gaz gücünü kullanır ama Luffy\'nin kararlılığı karşısında yetersiz kalır. Gear 2 ve Grizzly Magnum ile Caesar\'ı nakavt eder.' },
      { number: 18, title: 'Yeni Çağın Devralınması!', slug: 'punk-hazard-18', duration: '24:30', summary: 'Law, SAD üretim tesisini yok eder. SAD, Doflamingo\'nun Kaido\'ya sattığı yapay Şeytan Meyveleri SMILE için gereklidir. Tedarik zincirinin ilk halkası kırılmıştır.' },
      { number: 19, title: 'Dressrosa\'dan Suikastçılar!', slug: 'punk-hazard-19', duration: '24:30', summary: 'Doflamingo\'nun ajanı Monet, adayı havaya uçurmaya çalışır. Zoro\'nun korkutucu aurası Monet\'i felç eder. Caesar, bilmeden Monet\'in kalbi yerine kendi kalbini bıçaklar.' },
      { number: 20, title: 'Benim İçin Öl!', slug: 'punk-hazard-20', duration: '24:30', summary: 'Baby 5 ve Buffalo, Caesar\'ı kurtarmak için adaya gelir. Doflamingo\'nun müdahalesi yaklaşır. Franky, Baby 5 ve Buffalo ile savaşır. Doflamingo bizzat yola çıkmıştır.' },
      { number: 21, title: 'İttifak\'ın Hedefi ve Ayrılık!', slug: 'punk-hazard-21', duration: '24:30', summary: 'Mürettebat, çocukları kurtararak Punk Hazard\'dan kaçar. Smoker ve Tashigi olayları Deniz Kuvvetleri\'ne rapor edecektir. Caesar rehine alınır. Doflamingo adaya geldiğinde herkes çoktan gitmiştir.' },
      { number: 22, title: 'Gizemli Adamın Gelişi ve Haber Kuşu!', slug: 'punk-hazard-22', duration: '24:30', summary: 'Mürettebat, bir sonraki hedefe yol alır. Law\'ın planı: Dressrosa\'daki SMILE fabrikasını yok etmek ve Doflamingo\'yu Shichibukai koltuğundan düşürmek. Kaido\'yu devirmenin büyük planı harekete geçmiştir.' },
    ],
  },
  {
    name: 'Dressrosa',
    slug: 'dressrosa',
    saga: 'dressrosa',
    cover: '/arcs/dressrosa.jpg',
    episodeCount: 48,
    summary: 'Shichibukai Doflamingo\'nun tutsak ettiği krallık. Luffy, Gear 4 formunu ilk kez kullanır. En uzun arc\'lardan biri.',
    detailedSummary: 'İspanya temalı tutkulu ülke Dressrosa, görünüşte mutlu bir krallıktır ama gerçekte Doflamingo\'nun demir yumruğuyla yönetilmektedir. Doflamingo, 10 yıl önce Riku Krallık ailesini devirerek tahta geçmiştir. Ito Ito meyvesiyle insanları kukla gibi kontrol edebilir. "Birdcage" — tüm ülkeyi kaplayan ip kafesi — ile kimse kaçamaz. Corrida Colosseum\'da bir turnuva düzenlenir ve ödül Ace\'in eski Mera Mera meyvesidir. Luffy, Lucy takma adıyla turnuvaya katılır. Sabo — Luffy\'nin öldü sandığı kardeşi — hayattadır ve Devrimci Ordunun 2 numarasıdır! Sabo, Mera Mera meyvesini kazanır ve Ace\'in mirasını devralır. Oyuncak Askerinin gerçek kimliği Kyros — Dressrosa\'nın en büyük gladyatörü — ortaya çıkar. Sugar\'ın Hobi Hobi meyvesi insanları oyuncağa çevirmiştir. Usopp, Sugar\'ı korkutarak herkesi geri döndürür ve "God Usopp" olur. Luffy, Gear 4 Boundman\'ı ilk kez kullanarak Doflamingo\'yu yener. 7 krallıktan 5600 korsan Luffy\'ye bağlılık yemini eder — Hasır Şapka Büyük Filo doğar.',
    keyEvents: [
      'Doflamingo\'nun 10 yıllık tiranlığı',
      'Corrida Colosseum turnuvası',
      'Sabo hayatta! Mera Mera meyvesini alır',
      'Sugar\'ın oyuncak laneti kırılır',
      'Usopp "God Usopp" olur',
      'Birdcage tehlikesi',
      'Luffy Gear 4 Boundman ilk kullanım',
      'Doflamingo\'nun yenilgisi',
      'Hasır Şapka Büyük Filo kurulur',
    ],
    themes: ['Tiranlık ve Devrim', 'Aile ve Miras', 'Özgürlük', 'İttifak ve Liderlik'],
    location: 'Dressrosa',
    villain: 'Donquixote Doflamingo',
    characters: ['luffy', 'zoro', 'law', 'sabo', 'doflamingo'],
    episodes: [
      { number: 1, title: 'Aşk, Tutku ve Oyuncakların Ülkesindeki Macera!', slug: 'dressrosa-01', duration: '24:30', summary: 'Mürettebat Dressrosa\'ya varır. Renkli, tutkulu ve dans eden insanlarla dolu bir ülke. Ancak yüzeyin altında Doflamingo\'nun demir kontrolü gizlidir.' },
      { number: 2, title: 'Corrida Kolezyumu! Büyük Turnuva', slug: 'dressrosa-02', duration: '24:30', summary: 'Law\'ın Doflamingo\'yu Shichibukai\'den istifa ettirme planı suya düşer. Doflamingo, Dünya Hükümeti\'ni manipüle etmiştir. Tuzak kurulmuştur ve mürettebat tehlikededir.' },
      { number: 3, title: 'Kolezyumda Birçok Yeni Yüz ve Takipçi Maynard!', slug: 'dressrosa-03', duration: '24:30', summary: 'Doflamingo, Ace\'in Mera Mera meyvesini ödül olarak koyduğu bir gladyatör turnuvası düzenler. Luffy, "Lucy" takma adıyla turnuvaya katılmaya karar verir.' },
      { number: 4, title: 'Bellamy\'nin Değişen Motivasyonları ve B Bloğunun Başlangıcı!', slug: 'dressrosa-04', duration: '24:30', summary: 'Turnuvanın güçlü savaşçıları tanıtılır: Cavendish, Bartolomeo, Sai, Don Chinjao, Ideo ve daha fazlası. Her birinin kendi hikayesi ve amacı vardır.' },
      { number: 5, title: 'B Bloğu Yanıyor! Tuhaf Rakipler ve Kral Yumruğu!', slug: 'dressrosa-05', duration: '24:30', summary: 'Oyuncak Askeri ve kızı Rebecca\'nın hikayesi anlatılır. Rebecca, gladyatör olarak arenada savaşmak zorundadır. Oyuncak Askeri onu gizlice korumaktadır.' },
      { number: 6, title: 'Green Bit\'e Doğru! Cüceler Diyarındaki Macera', slug: 'dressrosa-06', duration: '24:30', summary: 'Luffy, Lucy olarak arenada ilk savaşına girer. Don Chinjao\'nun 500 milyon Berry\'lik eski korsanla Haoshoku Haki çarpışması yaşanır. Luffy arenayı sallar.' },
      { number: 7, title: 'Doflamingo Harekete Geçer! Nihai Entrikacı!', slug: 'dressrosa-07', duration: '24:30', summary: 'Bartolomeo\'nun Luffy\'ye olan fanatik hayranlığı ortaya çıkar. Bari Bari meyvesiyle dokunulmaz bariyer yaratır. Turnuvanın B bloğu kızışır.' },
      { number: 8, title: 'C Bloktaki Savaş Alanı! Lucy ve Ucy!', slug: 'dressrosa-08', duration: '24:30', summary: 'Serinin en büyük sürprizlerinden biri: Sabo hayattadır! Luffy\'nin öldü sandığı kardeşi, Devrimci Ordunun Genelkurmay Başkanıdır. Sabo, Lucy\'nin yerine geçerek turnuvaya katılır.' },
      { number: 9, title: 'C Bloğunun Alevli Savaşı ve Dressrosa\'nın Unutulanları!', slug: 'dressrosa-09', duration: '24:30', summary: 'Sabo, arenada muazzam gücünü gösterir. Ryusoken tekniğiyle rakiplerini ezer. Ace\'in meyvesini almak için kararlıdır. Luffy, kardeşini gördüğüne sevinçle ağlar.' },
      { number: 10, title: 'Tontatta İsyanı ve C Blok Finali!', slug: 'dressrosa-10', duration: '24:30', summary: 'Sugar\'ı bayıltma operasyonu (SOP) başlar. Franky dikkat çekmek için savaşırken, Robin ve Usopp Sugar\'a yaklaşmaya çalışır. Law, Doflamingo ile yüzleşir.' },
      { number: 11, title: 'Hüzünlü Bir Geçmiş! Rebecca ve Asker-san', slug: 'dressrosa-11', duration: '24:30', summary: 'Sugar\'ın Hobi Hobi meyvesinin gücü ortaya çıkar: dokunduğu herkesi oyuncağa çevirir ve herkes o kişiyi unutur. Dressrosa\'nın "mutlu" yüzeyinin altındaki korkunç gerçek: binlerce kişi oyuncak yapılmıştır.' },
      { number: 12, title: 'D Bloğunun Ateşli Başlangıcı ve Gökçe Şeytan\'ın Sırrı!', slug: 'dressrosa-12', duration: '24:30', summary: 'Usopp, Sugar\'a yaklaşır ancak plan başarısız olur. Trebol tarafından ezilir. Ancak Usopp yılmaz — Hasır Şapka korsanı olarak cesaretini kanıtlamalıdır.' },
      { number: 13, title: 'Law\'ın Yeni Stratejisi ve Kolezyum\'un Yeraltı Kabusu!', slug: 'dressrosa-13', duration: '24:30', summary: 'Usopp, Kenbunshoku Haki\'yi uyandırarak Sugar\'ı korkutup bayıltır! Lanet bozulur, binlerce oyuncak insan formuna döner. Tüm Dressrosa Usopp\'u "Tanrı Usopp" olarak anar.' },
      { number: 14, title: 'Riku Ailesi! Pusudaki Kahraman!', slug: 'dressrosa-14', duration: '24:30', summary: 'Doflamingo, Birdcage\'i aktive eder: tüm ülkeyi kaplayan ip kafesi her şeyi keser ve kimse kaçamaz. Doflamingo, isyancıların başına ödül koyar ve halkı birbirine düşürür.' },
      { number: 15, title: 'Doflamingo\'nun Acımasız Takibi!', slug: 'dressrosa-15', duration: '24:30', summary: 'Doflamingo\'nun kanlı oyunu başlar: 12 kişinin başını getirene ödül. Hedefler arasında Luffy, Law, Riku Kral ve Rebecca var. Dressrosa halkı panik içinde birbirine saldırır.' },
      { number: 16, title: 'SOP Operasyonu!', slug: 'dressrosa-16', duration: '24:30', summary: 'Law, kraliyet platosunda Doflamingo ile yüzleşir. Gamma Knife tekniğiyle Doflamingo\'nun iç organlarına zarar verir. Ancak Doflamingo, ipleriyle iç organlarını tamir eder.' },
      { number: 17, title: 'Yer Altı Dünyası', slug: 'dressrosa-17', duration: '24:30', summary: 'Savaş kızışır. Doflamingo, Law\'ı ağır yaralar ve Trebol\'ün yardımıyla köşeye sıkıştırır. Law, Corazon\'un intikamı için son gücüyle savaşır.' },
      { number: 18, title: 'Fujitora\'nın Planı', slug: 'dressrosa-18', duration: '24:30', summary: 'Corazon — Donquixote Rosinante — Law\'ın kurtarıcısının hikayesi başlar. Doflamingo\'nun öz kardeşi olan Corazon, gizlice Deniz Kuvvetleri ajanıdır. Law\'ı Amber Lead hastalığından kurtarmak ister.' },
      { number: 19, title: 'Diamante ve Pica', slug: 'dressrosa-19', duration: '24:30', summary: 'Corazon, küçük Law için Ope Ope meyvesini çalar. Nagi Nagi meyvesiyle sessizlik yaratarak Law\'ı gizler. Doflamingo\'ya ihanetinin bedeli ağır olacaktır.' },
      { number: 20, title: 'Komutan', slug: 'dressrosa-20', duration: '24:30', summary: 'Doflamingo, kardeşi Corazon\'u öldürür. Corazon, son nefesine kadar Law\'ı korur ve gülümser. Law, Corazon\'un fedakarlığının intikamını almaya yemin eder. Serinin en duygusal anlarından biri.' },
      { number: 21, title: 'Yalancı Usoland', slug: 'dressrosa-21', duration: '24:30', summary: 'Doflamingo\'nun Celestial Dragon kökenli olduğu ortaya çıkar. Babası insanlar arasında yaşamaya karar vermiş ama halk onları linç etmiştir. Doflamingo, babasını öldürmüş ve başını Mariejois\'a göndermiştir.' },
      { number: 22, title: 'Dressrosa Çalkantıda', slug: 'dressrosa-22', duration: '24:30', summary: 'Sabo, Mera Mera meyvesini yer ve Ace\'in mirasını devralır. Ateş güçleriyle Amiral Fujitora ile savaşır. İki güçlü savaşçının çarpışması Dressrosa\'yı sarsar.' },
      { number: 23, title: 'Kuş Kafesi', slug: 'dressrosa-23', duration: '24:30', summary: 'Hasır Şapka ittifakı ve Doflamingo ailesi arasında bireysel savaşlar başlar. Her kademe bir düşmanla eşleşir. Birdcage daralıyor, zaman azalıyor.' },
      { number: 24, title: 'Üst Düzey Yönetici Pica', slug: 'dressrosa-24', duration: '24:30', summary: 'Robin, Rebecca\'yı korumak için Diamante\'ye karşı savaşır. Ayçiçeği tarlasında — Scarlett\'in mezarının bulunduğu yerde — duygusal bir mücadele başlar.' },
      { number: 25, title: 'Alçaklar Ordusu İlerliyor!', slug: 'dressrosa-25', duration: '24:30', summary: 'Kyros, karısı Scarlett\'i öldüren Diamante ile hesaplaşır. Tek bacağına rağmen efsanevi gladyatör gücünü gösterir. Rebecca, babasını destekler.' },
      { number: 26, title: 'Savaş Durumu', slug: 'dressrosa-26', duration: '24:30', summary: 'Kyros, Diamante\'yi yener. Rebecca, babasının kim olduğunu ve oyuncak formunda bile onu koruduğunu tam olarak anlar. Baba-kız gözyaşları içinde birleşir.' },
      { number: 27, title: 'Savaş', slug: 'dressrosa-27', duration: '24:30', summary: 'Franky ve Senor Pink arasındaki "erkekler savaşı" başlar. Her ikisi de saldırıdan kaçmaz, yumrukları göğüsler. İki sert adamın saygı dolu düellosu.' },
      { number: 28, title: 'Bir Erkeğin Dünyası', slug: 'dressrosa-28', duration: '24:30', summary: 'Senor Pink\'in trajik geçmişi ortaya çıkar: karısı Russian komaya girmiş, bebek kıyafetleri karısının tek tepki verdiği şeydir. Franky, saygıyla savaşı kazanır.' },
      { number: 29, title: 'Koz', slug: 'dressrosa-29', duration: '24:30', summary: 'Ideo, Sai, Leo ve diğer gladyatörler Doflamingo\'nun adamlarıyla savaşır. Baby 5, Sai\'ye aşık olur. Lao G yenilir. Her cephede savaş devam eder.' },
      { number: 30, title: 'Gizli Plan', slug: 'dressrosa-30', duration: '24:30', summary: 'Dellinger ve Gladius\'a karşı savaşlar sürer. Bartolomeo, Bari Bari meyvesiyle müttefikleri korur. Cavendish\'in Hakuba kişiliği ortaya çıkar ve düşmanları biçer.' },
      { number: 31, title: 'Ope Ope Meyvesi', slug: 'dressrosa-31', duration: '24:30', summary: 'Zoro, İshi İshi meyvesiyle taşa dönüşebilen devasa Pica ile savaşmaya başlar. Pica tüm adayı taş gövdesi haline getirir ve Riku Kral\'ı hedef alır.' },
      { number: 32, title: 'Beyaz Şehir', slug: 'dressrosa-32', duration: '24:30', summary: 'Zoro, Busoshoku Haki ile devasa taş gövdeyi parçalar. Pica\'nın gerçek bedenini bularak onu yener. Zoro\'nun Yeni Dünya\'daki gücü kanıtlanmıştır.' },
      { number: 33, title: 'Kader Adası: Minion', slug: 'dressrosa-33', duration: '24:30', summary: 'Bellamy, Doflamingo\'ya sadık kalmak ile Luffy\'nin doğruluğunu kabul etmek arasında kalır. Doflamingo tarafından ihanete uğramış olmasına rağmen savaşmaya devam eder.' },
      { number: 34, title: 'Cora-san', slug: 'dressrosa-34', duration: '24:30', summary: 'Law, Trebol ile savaşır. Trebol\'ün Beta Beta meyvesiyle yapışkan tuzakları tehlikelidir. Law, son gücüyle Trebol\'ü yener ve Doflamingo\'ya yönelir.' },
      { number: 35, title: 'Korsan Bellamy', slug: 'dressrosa-35', duration: '24:30', summary: 'Luffy, Doflamingo\'ya ulaşmak için kraliyet platosuna tırmanır. Müttefikleri yolu açar. Law ağır yaralıdır ama Luffy\'nin geleceğine güvenir.' },
      { number: 36, title: 'Elbaf\'ın Mızrağı ve Don Sai', slug: 'dressrosa-36', duration: '24:30', summary: 'Luffy, sonunda Doflamingo ile yüz yüze gelir. Bellamy\'yi acı içinde yumruklar ve Doflamingo\'ya döner. Dressrosa\'nın kaderi bu savaşa bağlıdır.' },
      { number: 37, title: 'Kabak ve Lomeo', slug: 'dressrosa-37', duration: '24:30', summary: 'Luffy, Gear 4 Boundman formunu ilk kez kullanır! Vücudunu Busoshoku Haki ile kaplayarak lastik zıplama gücünü devasa bir savaş formuna çevirir. Kong Gun ile Doflamingo\'yu fırlatır.' },
      { number: 38, title: 'Russian\'a Sevgilerle', slug: 'dressrosa-38', duration: '24:30', summary: 'Gear 4 Luffy, Doflamingo\'yu domine eder. Rhino Schneider ve Culverin teknikleriyle Doflamingo\'yu savunmaya zorlar. Doflamingo ilk kez gerçek korku yaşar.' },
      { number: 39, title: 'Zoro, Pica\'ya Karşı', slug: 'dressrosa-39', duration: '24:30', summary: 'Doflamingo, Şeytan Meyvesi Awakening\'ini kullanır — çevredeki her şeyi iplere dönüştürür. Binalar, zemin, her yer iplerle kaplanır. Savaş yeni bir boyut kazanır.' },
      { number: 40, title: 'Kalp Laneti', slug: 'dressrosa-40', duration: '24:30', summary: 'Gear 4 Luffy ve Awakening Doflamingo arasındaki savaş doruğa ulaşır. Leo Bazooka ve Double Culverin ile Doflamingo\'yu sıkıştırır. Ancak Gear 4\'ün zaman sınırı yaklaşmaktadır.' },
      { number: 41, title: 'Yolumun Üzerindesiniz!', slug: 'dressrosa-41', duration: '24:30', summary: 'Gear 4 süresi dolar ve Luffy 10 dakika boyunca Haki kullanamaz. Çaresiz ve savunmasız kalan Luffy, Doflamingo\'dan kaçmak zorundadır.' },
      { number: 42, title: 'Dördüncü Vites', slug: 'dressrosa-42', duration: '24:30', summary: 'Tüm Dressrosa — gladyatörler, halk, müttefikler — Luffy\'yi korumak için Doflamingo\'ya karşı savaşır. Gatz, arenayla Luffy\'nin geri sayımını yapar. Herkes zaman kazanmaya çalışır.' },
      { number: 43, title: 'Gyats', slug: 'dressrosa-43', duration: '24:30', summary: 'Birdcage daralıyor, şehir yok olma tehlikesiyle karşı karşıya. Zoro, Fujitora ve diğerleri kafesi durdurmaya çalışır. Luffy\'nin Haki\'si geri gelene kadar herkes direnir.' },
      { number: 44, title: 'Yer ve Gök', slug: 'dressrosa-44', duration: '24:30', summary: 'Dressrosa\'nın tüm güçleri — korsanlar, Deniz Kuvvetleri, halk — Birdcage\'i durdurmak için bir araya gelir. Fujitora yerçekimi gücünü kullanır. İnsanlığın birleşik gücü kafese karşı savaşır.' },
      { number: 45, title: 'Yere Kapanma', slug: 'dressrosa-45', duration: '24:30', summary: 'Luffy\'nin Haki\'si geri gelir ve Gear 4\'e tekrar girer. Doflamingo hâlâ ayaktadır ve tüm gücüyle saldırır. Final savaşı başlamıştır.' },
      { number: 46, title: 'Sabo\'nun Macerası', slug: 'dressrosa-46', duration: '24:30', summary: 'Luffy, en güçlü tekniğini kullanır: King Kong Gun. Devasa Haki yumruğu Doflamingo\'nun God Thread\'ini parçalar ve onu yerin altına gömer. Birdcage çöker. Dressrosa özgür!' },
      { number: 47, title: 'Asker-san\'ın Kararı', slug: 'dressrosa-47', duration: '24:30', summary: 'Doflamingo yenilir ve tutuklanır. 10 yıllık tiranlık sona erer. Riku Ailesi tahta döner. Fujitora, kör olmasına rağmen Luffy\'nin yüzünü "görmek" ister ve saygıyla eğilir.' },
      { number: 48, title: 'Baba ve Oğulları', slug: 'dressrosa-48', duration: '24:30', summary: '7 kaptan — Cavendish, Bartolomeo, Sai, Ideo, Leo, Hajrudin, Orlumbus — Luffy\'ye bağlılık yemini eder. 5600 kişilik Hasır Şapka Büyük Filo doğar. Sabo veda eder. Mürettebat Zou\'ya yola çıkar.' },
    ],
  },
]
