import type { Arc } from '@/types'

export const EAST_BLUE_ARCS: Arc[] = [
  {
    name: 'Romance Dawn',
    slug: 'romance-dawn',
    saga: 'east-blue',
    cover: '/arcs/romance-dawn.jpg',
    episodeCount: 4,
    summary: 'Monkey D. Luffy, Korsanlar Kralı olmak için Foosha Köyü\'nden yola çıkar. Shanks\'ın hasır şapkasını takan Luffy, ilk mürettebat üyesini bulmaya karar verir.',
    detailedSummary: 'Monkey D. Luffy, küçük yaşta Kızıl Saçlı Shanks ile tanışır ve onun sayesinde korsan olmaya karar verir. Gomu Gomu no Mi şeytan meyvesini yanlışlıkla yiyen Luffy, lastik insan olur ama yüzme yeteneğini kaybeder. Shanks, Luffy\'yi bir deniz canavarından kurtarırken sol kolunu kaybeder ve ayrılırken ona hasır şapkasını verir. 17 yaşına gelen Luffy, Foosha Köyü\'nden küçük bir tekneyle yola çıkar. İlk durağında Koby ile tanışır ve onu Deniz Kuvvetleri\'ne katılması için teşvik eder. Shells Town\'da haksız yere tutuklanan korsan avcısı Roronoa Zoro\'yu kurtarır ve onu mürettebatına katılmaya ikna eder. Deniz Kuvvetleri Albay Morgan\'ı yenerek kasabayı kurtarırlar.',
    keyEvents: [
      'Luffy Gomu Gomu meyvesini yer',
      'Shanks sol kolunu kaybeder',
      'Luffy hasır şapkayı alır ve söz verir',
      'Koby ile tanışma',
      'Zoro mürettebata katılır',
      'Albay Morgan yenilir',
    ],
    themes: ['Rüyaların Peşinden Koşmak', 'Dostluk', 'Özgürlük', 'Söz ve Onur'],
    location: 'Foosha Köyü, Shells Town',
    villain: 'Albay Morgan',
    characters: ['luffy', 'shanks', 'koby', 'zoro'],
    episodes: [
      {
        number: 1,
        title: 'Luffy\'nin Yolculuğu Başlıyor',
        slug: 'romance-dawn-01',
        duration: '25:00',
        summary: 'Küçük Luffy, Kızıl Saçlı Shanks ve mürettebatıyla vakit geçirir. Gomu Gomu meyvesini yanlışlıkla yiyen Luffy lastik insan olur. Dağ eşkıyası Higuma\'nın tehditleri karşısında Shanks sakin kalır ama Luffy\'yi korumak için kolunu feda eder.',
      },
      {
        number: 2,
        title: 'Büyük Kılıç Ustası',
        slug: 'romance-dawn-02',
        duration: '24:30',
        summary: '17 yaşına gelen Luffy denize açılır. Yolda kaçak denizci Koby ile tanışır ve onu Deniz Kuvvetleri\'ne katılması için cesaretlendirir. Shells Town\'a varırlar ve burada korsan avcısı Roronoa Zoro\'nun haksız yere tutuklandığını öğrenirler.',
      },
      {
        number: 3,
        title: 'Morgan vs Luffy',
        slug: 'romance-dawn-03',
        duration: '24:00',
        summary: 'Luffy, Zoro\'nun kılıçlarını geri almak için üsse sızar. Albay Morgan\'ın oğlu Helmeppo\'nun halka zulmettiği ortaya çıkar. Luffy ve Zoro, Morgan\'a karşı birlikte savaşır ve onu yenerler.',
      },
      {
        number: 4,
        title: 'Denize Açılan Rüya',
        slug: 'romance-dawn-04',
        duration: '23:30',
        summary: 'Morgan yenildikten sonra Koby Deniz Kuvvetleri\'ne katılır. Luffy ve Zoro, Korsanlar Kralı olma ve Dünyanın En İyi Kılıç Ustası olma hayalleriyle birlikte denize açılırlar. Grand Line\'a doğru yolculuk başlar.',
      },
    ],
  },
  {
    name: 'Orange Town',
    slug: 'orange-town',
    saga: 'east-blue',
    cover: '/arcs/orange-town.jpg',
    episodeCount: 3,
    summary: 'Luffy ve Zoro, hırsız navigatör Nami ile karşılaşır. Birlikte, Orange Town\'ı terörize eden palyaço korsan Buggy\'ye karşı savaşırlar.',
    detailedSummary: 'Luffy ve Zoro açlıktan bitkin halde Orange Town\'a ulaşırlar. Burada harita hırsızı ve navigatör Nami ile karşılaşırlar. Nami, Buggy Korsanlarından Grand Line haritasını çalmıştır. Buggy, Bara Bara meyvesi sayesinde vücudunu parçalara ayırabilen bir korsandır ve kasabayı Buggy Topları ile terörize etmektedir. Luffy, Nami ile geçici bir ittifak kurar. Kasaba halkı saklanırken, Belediye Başkanı Boodle tek başına kasabasını korumaya çalışır. Luffy, Buggy\'yi yener ve kasabayı kurtarır. Nami, henüz resmi olarak mürettebata katılmasa da onlarla yolculuğa devam eder. Buggy\'nin Shanks ile geçmişi ve Roger Korsanları\'ndaki ortak geçmişleri ortaya çıkar.',
    keyEvents: [
      'Nami ile ilk karşılaşma',
      'Buggy\'nin Bara Bara meyvesi gücü',
      'Buggy ve Shanks\'ın ortak geçmişi',
      'Luffy Buggy\'yi yener',
      'Shushu\'nun sadakati',
    ],
    themes: ['Ev ve Aidiyet', 'Sadakat', 'Geçici İttifaklar'],
    location: 'Orange Town',
    villain: 'Buggy',
    characters: ['luffy', 'zoro', 'nami', 'buggy'],
    episodes: [
      {
        number: 1,
        title: 'Palyaço Korsan Buggy',
        slug: 'orange-town-01',
        duration: '24:00',
        summary: 'Luffy ve Zoro Orange Town\'a varır. Nami, Buggy\'nin hazinesini çalarken Luffy\'yi kafese hapseder. Buggy\'nin Bara Bara meyvesi gücü ortaya çıkar. Kasaba halkı Buggy\'nin zulmünden kaçmıştır.',
      },
      {
        number: 2,
        title: 'Nami\'nin Haritası',
        slug: 'orange-town-02',
        duration: '24:30',
        summary: 'Luffy kafesten kurtulur ve Buggy\'nin mürettebatıyla savaşır. Nami\'nin korsanlara olan nefreti ortaya çıkar. Belediye Başkanı Boodle, kasabasını korumak için Buggy\'ye karşı durur. Köpek Shushu, sahibinin hatırasını korumak için savaşır.',
      },
      {
        number: 3,
        title: 'Buggy\'nin Sonu',
        slug: 'orange-town-03',
        duration: '23:00',
        summary: 'Luffy ve Buggy arasındaki son savaş. Luffy, Buggy\'nin parçalanmış vücudunu Nami\'nin yardımıyla etkisiz hale getirir. Kasaba kurtulur. Nami, Luffy ve Zoro ile birlikte yolculuğa devam etmeye karar verir.',
      },
    ],
  },
  {
    name: 'Syrup Village',
    slug: 'syrup-village',
    saga: 'east-blue',
    cover: '/arcs/syrup-village.jpg',
    episodeCount: 5,
    summary: 'Luffy ve ekibi, yalancı hikayeler anlatan Usopp\'un köyüne gelir. Kaptan Kuro\'nun köyü yok etme planını engellemek için savaşırlar.',
    detailedSummary: 'Hasır Şapkalar, bir gemi bulmak umuduyla Syrup Köyü\'ne gelirler. Burada sürekli yalancı hikayeler anlatan Usopp ile tanışırlar. Usopp\'un babası Yasopp, Shanks\'ın mürettebatındadır. Zengin kız Kaya\'nın uşağı Klahadore\'un aslında eski korsan Kaptan Kuro olduğu ortaya çıkar. Kuro, Kaya\'nın servetini ele geçirmek için 3 yıldır plan yapmıştır. Kuro\'nun Kara Kedi Korsanları köyü basacak ve Kaya\'yı öldürecektir. Usopp gerçeği söyler ama yalancı olarak bilindiği için kimse inanmaz. Luffy ve ekibiyle birlikte yamacı savunurlar. Django\'nun hipnoz güçleri ve Kuro\'nun "Pençe" tekniği zorlu bir savaş çıkarır. Zafer sonrası Kaya, onlara Caravel tipi gemi "Going Merry"yi hediye eder ve Usopp mürettebata katılır.',
    keyEvents: [
      'Usopp ile tanışma',
      'Kaptan Kuro\'nun gerçek kimliği',
      'Yamacın savunması',
      'Going Merry\'nin hediye edilmesi',
      'Usopp mürettebata katılır',
    ],
    themes: ['Yalancılık ve Cesaret', 'Gerçek Dostluk', 'Planlamaya Karşı İrade'],
    location: 'Syrup Köyü',
    villain: 'Kaptan Kuro',
    characters: ['luffy', 'zoro', 'nami', 'usopp'],
    episodes: [
      {
        number: 1,
        title: 'Yalancı Usopp',
        slug: 'syrup-village-01',
        duration: '24:00',
        summary: 'Hasır Şapkalar Syrup Köyü\'ne varır ve sürekli "korsanlar geliyor!" diye bağıran Usopp ile tanışır. Usopp\'un babası Yasopp\'un Shanks\'ın mürettebatında olduğu ortaya çıkar. Zengin kız Kaya ve uşağı Klahadore ile tanışırlar.',
      },
      {
        number: 2,
        title: 'Kuro\'nun Planı',
        slug: 'syrup-village-02',
        duration: '24:30',
        summary: 'Usopp, Klahadore\'un aslında eski korsan Kaptan Kuro olduğunu keşfeder. Kuro\'nun Kaya\'nın mirasını ele geçirmek için köyü yok etme planı ortaya çıkar. Usopp gerçeği anlatmaya çalışır ama yalancı olarak bilindiği için kimse inanmaz.',
      },
      {
        number: 3,
        title: 'Yamacın Savunması',
        slug: 'syrup-village-03',
        duration: '25:00',
        summary: 'Kuro\'nun korsanları yamacından saldırıya geçer. Luffy, Zoro, Nami ve Usopp yamacı savunmak için savaşırlar. Usopp korkmasına rağmen cesurca savaşır ve köyünü korumak için her şeyini ortaya koyar.',
      },
      {
        number: 4,
        title: 'Django\'nun Hipnozu',
        slug: 'syrup-village-04',
        duration: '24:00',
        summary: 'Django\'nun hipnoz güçleri Luffy\'yi bile etkiler. Kuro sahneye çıkar ve kendi mürettebatına bile acımasızlığını gösterir. "Pençe" tekniğiyle son derece hızlı ve ölümcül saldırılar yapar.',
      },
      {
        number: 5,
        title: 'Going Merry',
        slug: 'syrup-village-05',
        duration: '23:30',
        summary: 'Luffy, Kuro\'yu yener ve köy kurtulur. Kaya, minnettarlığını göstermek için mürettebata Caravel tipi gemi Going Merry\'yi hediye eder. Usopp, cesur bir savaşçı olma hayaliyle mürettebata katılır ve köyüne veda eder.',
      },
    ],
  },
  {
    name: 'Baratie',
    slug: 'baratie',
    saga: 'east-blue',
    cover: '/arcs/baratie.jpg',
    episodeCount: 6,
    summary: 'Yüzen restoran Baratie\'de Luffy, aşçı Sanji ile tanışır. Don Krieg\'in devasa filosu Baratie\'yi tehdit ederken, efsanevi kılıç ustası Mihawk ortaya çıkar.',
    detailedSummary: 'Hasır Şapkalar, denizin ortasındaki yüzen restoran Baratie\'ye ulaşırlar. Luffy, yanlışlıkla restorana zarar verir ve tazminat olarak burada çalışmak zorunda kalır. Baş aşçı Sanji\'nin yemek konusundaki tutkusunu ve All Blue rüyasını keşfeder. Don Krieg\'in bitkin filosu Baratie\'ye sığınır. Grand Line\'dan kaçan Krieg, restoranı ele geçirmeye çalışır. Bu sırada efsanevi kılıç ustası Dracule Mihawk, Krieg\'in filosunun peşinden gelmiştir. Zoro, hayalinin peşinden Mihawk\'a meydan okur ama acı bir yenilgi alır. Bu yenilgi Zoro\'nun bir daha asla kaybetmeme yemini etmesine yol açar. Sanji\'nin geçmişi, açlıktan ölmek üzereyken düşmanı Zeff tarafından kurtarılması ortaya çıkar. Zeff, Sanji\'yi kurtarmak için kendi bacağını yemiştir. Luffy, Don Krieg\'i yener. Sanji, gözyaşları içinde Baratie\'ye veda eder ve mürettebata aşçı olarak katılır.',
    keyEvents: [
      'Sanji ile tanışma',
      'Don Krieg\'in tehdidi',
      'Mihawk\'ın ortaya çıkışı',
      'Zoro vs Mihawk — Zoro\'nun yenilgisi ve yemini',
      'Sanji ve Zeff\'in geçmişi',
      'Sanji mürettebata katılır',
    ],
    themes: ['Rüyalar İçin Fedakarlık', 'Açlık ve Yemek', 'Gurur ve Yenilgiyi Kabul Etme'],
    location: 'Baratie Yüzen Restoranı',
    villain: 'Don Krieg',
    characters: ['luffy', 'zoro', 'sanji', 'mihawk'],
    episodes: [
      {
        number: 1,
        title: 'Yüzen Restoran',
        slug: 'baratie-01',
        duration: '24:00',
        summary: 'Hasır Şapkalar denizin ortasındaki yüzen restoran Baratie\'ye ulaşır. Luffy yanlışlıkla restorana zarar verir ve baş aşçı Zeff\'e tazminat olarak çalışmayı kabul eder. Sanji\'nin müşterilerine olan tutumu ve yemek felsefesi dikkat çeker.',
      },
      {
        number: 2,
        title: 'Sanji\'nin Rüyası',
        slug: 'baratie-02',
        duration: '24:30',
        summary: 'Sanji\'nin All Blue — tüm denizlerin balıklarının bulunduğu efsanevi deniz — rüyası ortaya çıkar. Don Krieg\'in bitkin filosu Baratie\'ye sığınır ve Sanji, açlıktan ölmek üzere olan Krieg\'e yemek verir. Krieg güçlenince restoranı ele geçirmeye çalışır.',
      },
      {
        number: 3,
        title: 'Mihawk Geliyor',
        slug: 'baratie-03',
        duration: '25:00',
        summary: 'Dünyanın en güçlü kılıç ustası Dracule Mihawk, Don Krieg\'in filosunu tek başına yok ederek sahneye çıkar. Mihawk\'ın gücü herkesi dehşete düşürür. Zoro, hayatının en büyük fırsatını görür.',
      },
      {
        number: 4,
        title: 'Zoro vs Mihawk',
        slug: 'baratie-04',
        duration: '24:00',
        summary: 'Zoro, Mihawk\'a meydan okur. Mihawk, küçük bir bıçakla bile Zoro\'yu yener. Zoro göğsünü açarak onurlu bir yenilgi ister. Mihawk, Yoru kılıcıyla son darbeyi vurur. Zoro "Bir daha asla kaybetmeyeceğim!" diye yemin eder. Mihawk, Zoro\'nun iradesini takdir eder.',
      },
      {
        number: 5,
        title: 'Don Krieg\'in Gücü',
        slug: 'baratie-05',
        duration: '24:30',
        summary: 'Luffy, Don Krieg ile savaşır. Krieg\'in zırhı, zehirli silahları ve devasa savaş mızrağı zorlu bir rakip çıkarır. Sanji ve Zeff\'in geçmişi anlatılır: açlıktan ölmek üzereyken küçük bir kayada mahsur kalan Sanji\'yi Zeff kendi bacağını feda ederek kurtarmıştır.',
      },
      {
        number: 6,
        title: 'Aşçının Kararı',
        slug: 'baratie-06',
        duration: '24:00',
        summary: 'Luffy, Don Krieg\'i yener. Sanji, Baratie\'yi ve Zeff\'i bırakma kararını verir. Gözyaşları içinde Zeff\'e teşekkür eder: "O lanet restorandaki her şey için... teşekkür ederim!" Sanji, Hasır Şapkaların aşçısı olarak mürettebata katılır.',
      },
    ],
  },
  {
    name: 'Arlong Park',
    slug: 'arlong-park',
    saga: 'east-blue',
    cover: '/arcs/arlong-park.jpg',
    episodeCount: 10,
    summary: 'Nami\'nin karanlık geçmişi ortaya çıkar. Arlong, Nami\'nin köyünü yıllardır sömürmektedir. Luffy, Nami\'yi kurtarmak için en güçlü düşmanıyla yüzleşir.',
    detailedSummary: 'East Blue sagasının doruk noktası. Nami aniden mürettebattan ayrılır ve Arlong Korsanlarına döner. Mürettebat onu takip eder ve Nami\'nin korkunç geçmişini öğrenir. Nami, üvey annesi Bellemere\'in Arlong tarafından öldürülmesine tanık olmuştur. Arlong, Cocoyashi Köyü\'nü vergiye bağlamış ve Nami\'ye bir anlaşma sunmuştur: 100 milyon Berry toplarsa köyünü satın alabilir. Nami, 8 yıl boyunca Arlong için harita çizerek para biriktirmiştir. Tam parayı tamamlamak üzereyken Arlong, Deniz Kuvvetleri ile işbirliği yaparak parayı çaldırır. Umudunu kaybeden Nami, ilk kez yardım ister. Luffy, hasır şapkasını Nami\'ye bırakır ve Arlong Park\'ı yıkar. Nami\'nin harita odasını tamamen parçalar: "Elbette sana yardım edeceğim!" Bu an, serinin en ikonik sahnelerinden biridir.',
    keyEvents: [
      'Nami\'nin geçmişi ve Bellemere\'in ölümü',
      'Arlong\'un köyü sömürmesi',
      'Nami\'nin 100 milyon Berry anlaşması',
      '"Luffy... Yardım et!" sahnesi',
      'Luffy Arlong Park\'ı yıkar',
      'Nami resmi olarak mürettebata katılır',
    ],
    themes: ['Kölelik ve Özgürlük', 'Aile Bağları', 'Yardım İsteme Cesareti', 'Adaletsizliğe Başkaldırı'],
    location: 'Cocoyashi Köyü, Arlong Park',
    villain: 'Arlong',
    characters: ['luffy', 'zoro', 'nami', 'sanji', 'usopp'],
    episodes: [
      {
        number: 1,
        title: 'Nami\'nin Sırrı',
        slug: 'arlong-park-01',
        duration: '24:00',
        summary: 'Nami, mürettebattan ayrılır ve Arlong Korsanlarına döner. Luffy ve ekip, Nami\'nin peşinden Conomi Adaları\'na gider. Arlong\'un Balık-Adam olduğu ve East Blue\'yu kontrol ettiği ortaya çıkar.',
      },
      {
        number: 2,
        title: 'Arlong\'un Egemenliği',
        slug: 'arlong-park-02',
        duration: '24:30',
        summary: 'Arlong\'un Cocoyashi Köyü üzerindeki zulmü anlatılır. Balık-Adamların insanlardan fiziksel olarak çok daha güçlü olduğu gösterilir. Usopp, Arlong tarafından yakalanır.',
      },
      {
        number: 3,
        title: 'Cocoyashi Köyü',
        slug: 'arlong-park-03',
        duration: '24:00',
        summary: 'Köy halkının Arlong\'un zulmü altındaki yaşamı. Nami\'nin köylüler arasındaki konumu ve onun için duydukları sevgi. Nojiko, Nami\'nin üvey kız kardeşi, mürettebata Nami\'nin geçmişini anlatmaya başlar.',
      },
      {
        number: 4,
        title: 'Bellemere\'in Fedakarlığı',
        slug: 'arlong-park-04',
        duration: '25:00',
        summary: 'Nami ve Nojiko\'nun geçmişi. Deniz Kuvvetleri eski askeri Bellemere, savaş alanında iki yetim bebeği bulur ve evlat edinir. Arlong köye geldiğinde, kızlarını korumak için hayatını feda eder: "Onlar benim kızlarım!"',
      },
      {
        number: 5,
        title: 'Nami\'nin Gözyaşları',
        slug: 'arlong-park-05',
        duration: '24:30',
        summary: 'Nami\'nin 8 yıllık acı dolu mücadelesi. Arlong için harita çizerek 100 milyon Berry biriktirmiştir. Tam hedefine ulaşacakken Arlong, yolsuz Denizci Nezumi\'ye parayı çaldırır. Umudunu kaybeden Nami, Arlong\'un dövmesini bıçakla kazımaya çalışır.',
      },
      {
        number: 6,
        title: 'Yardım Et, Luffy!',
        slug: 'arlong-park-06',
        duration: '24:00',
        summary: 'Serinin en ikonik sahnesi. Nami, ilk kez yardım ister: "Luffy... Yardım et!" Luffy, hasır şapkasını Nami\'nin başına koyar ve "Elbette!" diyerek Arlong Park\'a doğru yürür. Mürettebat tam kadro saldırıya geçer.',
      },
      {
        number: 7,
        title: 'Zoro vs Hatchan',
        slug: 'arlong-park-07',
        duration: '24:30',
        summary: 'Zoro, Mihawk\'tan aldığı yaralar henüz iyileşmemişken altı kollu kılıç ustası Hatchan ile savaşır. Ağır yaralı olmasına rağmen kazanır. Zoro\'nun inanılmaz dayanıklılığı ortaya çıkar.',
      },
      {
        number: 8,
        title: 'Sanji vs Kuroobi',
        slug: 'arlong-park-08',
        duration: '24:00',
        summary: 'Sanji, Balık-Adam karatecisi Kuroobi ile savaşır. Suyun altında dezavantajlı olmasına rağmen zekice bir stratejiyle kazanır. Usopp da Chew\'a karşı korku içinde ama cesurca savaşır.',
      },
      {
        number: 9,
        title: 'Luffy vs Arlong',
        slug: 'arlong-park-09',
        duration: '25:00',
        summary: 'Luffy ve Arlong arasındaki epik final savaşı. Arlong\'un Kiribachi testere kılıcı ve Balık-Adam gücü zorlu bir mücadele çıkarır. Luffy, Nami\'nin harita odasını görünce öfkelenir ve odayı tamamen parçalar: "Bu oda seni acı çektiriyor!"',
      },
      {
        number: 10,
        title: 'Özgürlük',
        slug: 'arlong-park-10',
        duration: '24:00',
        summary: 'Luffy, Arlong\'u yener ve Arlong Park\'ı tamamen yıkar. 8 yıl sonra Cocoyashi Köyü özgürdür. Nami, yeni bir Arlong dövmesi yerine mandalina ve fırıldak dövmesi yaptırır. Resmi olarak Hasır Şapkaların navigatörü olur. İlk ödül posterleri yayınlanır.',
      },
    ],
  },
  {
    name: 'Loguetown',
    slug: 'loguetown',
    saga: 'east-blue',
    cover: '/arcs/loguetown.jpg',
    episodeCount: 3,
    summary: 'Korsanlar Kralı Gold Roger\'ın doğduğu ve idam edildiği şehir. Luffy, Grand Line\'a girmeden önce bu efsanevi şehri ziyaret eder.',
    detailedSummary: 'Hasır Şapkalar, Grand Line\'a girmeden önceki son durak olan Loguetown\'a varırlar. Bu şehir, Korsanlar Kralı Gold Roger\'ın hem doğduğu hem de 22 yıl önce idam edildiği yerdir — "Başlangıç ve Son Şehri" olarak bilinir. Luffy, Roger\'ın idam edildiği platformu ziyaret eder. Buggy ve Alvida, Luffy\'yi yakalamak için şehirdedir. Kaptan Smoker, Moku Moku meyvesiyle Luffy\'yi köşeye sıkıştırır. Tam Buggy Luffy\'yi idam platformunda öldürecekken, gizemli bir yıldırım düşer ve Luffy kurtulur. Dragon — Luffy\'nin babası — ilk kez gizlice sahneye çıkar. Mürettebat, fırtınanın ortasında Grand Line\'a doğru yola çıkar. Reverse Mountain\'ın önünde herkes hayallerini ilan eder ve kadehlerini kırar.',
    keyEvents: [
      'Luffy Roger\'ın idam platformunu ziyaret eder',
      'Smoker ile ilk karşılaşma',
      'Dragon\'ın gizemli müdahalesi',
      'Mürettebatın Grand Line yemini',
      'Büyük macera başlıyor',
    ],
    themes: ['Kader ve Miras', 'Yeni Başlangıçlar', 'Korsan Çağının Ruhu'],
    location: 'Loguetown',
    villain: 'Smoker, Buggy',
    characters: ['luffy', 'zoro', 'nami', 'sanji', 'usopp', 'smoker'],
    episodes: [
      {
        number: 1,
        title: 'Başlangıç ve Son Şehri',
        slug: 'loguetown-01',
        duration: '24:00',
        summary: 'Mürettebat Loguetown\'a varır. Luffy, Gold Roger\'ın idam platformunu ziyaret eder. Zoro usta bir kılıç dükkânında efsanevi kılıçlar keşfeder. Sanji yemek malzemeleri alırken Nami alışveriş yapar. Smoker, Luffy\'nin geldiğini öğrenir.',
      },
      {
        number: 2,
        title: 'İdam Sehpası',
        slug: 'loguetown-02',
        duration: '24:30',
        summary: 'Buggy ve Alvida, Luffy\'yi yakalar ve Roger\'ın idam edildiği platformda halka açık infaz düzenler. Luffy, son anında gülümser — tıpkı Roger gibi. Tam o anda gizemli bir yıldırım platformu parçalar ve Luffy kurtulur. Dragon\'ın gizli müdahalesi.',
      },
      {
        number: 3,
        title: 'Grand Line\'a Giriş',
        slug: 'loguetown-03',
        duration: '24:00',
        summary: 'Smoker Luffy\'yi yakalamaya çalışır ama Dragon araya girer. Mürettebat fırtınanın ortasında Loguetown\'dan kaçar. Grand Line\'ın girişinde herkes hayallerini ilan eder ve bir fıçının üzerine ayaklarını koyarak yemin eder. East Blue\'ya veda, büyük macera başlıyor.',
      },
    ],
  },
]
