import type { Arc } from '@/types'

export const EAST_BLUE_ARCS: Arc[] = [
  {
    name: 'Romance Dawn',
    slug: 'romance-dawn',
    saga: 'east-blue',
    cover: '/arcs/romance-dawn.webp',
    episodeCount: 4,
    summary: 'Monkey D. Luffy, Korsanlar Kralı olmak için Foosha Köyü\'nden yola çıkar. Shanks\'ın hasır şapkasını takan Luffy, ilk mürettebat üyesini bulmaya karar verir.',
    detailedSummary: 'Monkey D. Luffy, küçük yaşta Kızıl Saçlı Shanks ile tanışır ve onun sayesinde korsan olmaya karar verir. Gomu Gomu no Mi şeytan meyvesini yanlışlıkla yiyen Luffy, lastik insan olur ama yüzme yeteneğini kaybeder. Shanks, Luffy\'yi bir deniz canavarından kurtarırken sol kolunu kaybeder ve ayrılırken ona hasır şapkasını verir. 17 yaşına gelen Luffy, Foosha Köyü\'nden küçük bir tekneyle yola çıkar. İlk durağında Koby ile tanışır ve onu Deniz Kuvvetleri\'ne katılması için teşvik eder. Shells Town\'da haksız yere tutuklanan korsan avcısı Roronoa Zoro\'yu kurtarır ve onu mürettebatına katılmaya ikna eder. Deniz Kuvvetleri Albay Morgan\'ı yenerek kasabayı kurtarırlar.',
    keyEvents: [
      'Luffy Gomu Gomu meyvesini yer',
      'Shanks sol kolunu kaybeder',
      'Luffy hasır şapkayı alır ve söz verir',
      'Koby ile tanışma',
      'Zoro mürettebata katılır',
      'Albay Morgan yenilir',
    ],
    themes: ['Rüyaların Peşinden Koşmak', 'Dostluk', 'Özgürlük', 'Söz ve Onur'],
    location: 'Foosha Köyü, Shells Town',
    villain: 'Albay Morgan',
    characters: ['luffy', 'shanks', 'koby', 'zoro'],
    episodes: [
      {
        number: 1,
        title: 'Maceranın Başlangıcı',
        slug: 'romance-dawn-01',
        duration: '14:10',
        summary: 'Küçük Luffy, Kızıl Saçlı Shanks ve mürettebatıyla vakit geçirir. Gomu Gomu meyvesini yanlışlıkla yiyen Luffy lastik insan olur. Dağ eşkıyası Higuma\'nın tehditleri karşısında Shanks sakin kalır ama Luffy\'yi korumak için kolunu feda eder.',
      },
      {
        number: 2,
        title: 'Hasır Şapkalı Luffy',
        slug: 'romance-dawn-02',
        duration: '19:47',
        summary: '17 yaşına gelen Luffy denize açılır. Yolda kaçak denizci Koby ile tanışır ve onu Deniz Kuvvetleri\'ne katılması için cesaretlendirir. Shells Town\'a varırlar ve burada korsan avcısı Roronoa Zoro\'nun haksız yere tutuklandığını öğrenirler.',
      },
      {
        number: 3,
        title: 'Korsanlar Kralı ve En İyi Kılıç Ustası',
        slug: 'romance-dawn-03',
        duration: '27:21',
        summary: 'Luffy, Zoro\'nun kılıçlarını geri almak için üsse sızar. Albay Morgan\'ın oğlu Helmeppo\'nun halka zulmettiği ortaya çıkar. Luffy ve Zoro, Morgan\'a karşı birlikte savaşır ve onu yenerler.',
      },
      {
        number: 4,
        title: 'Bir Numara',
        slug: 'romance-dawn-04',
        duration: '16:41',
        summary: 'Morgan yenildikten sonra Koby Deniz Kuvvetleri\'ne katılır. Luffy ve Zoro, Korsanlar Kralı olma ve Dünyanın En İyi Kılıç Ustası olma hayalleriyle birlikte denize açılırlar. Grand Line\'a doğru yolculuk başlar.',
      },
    ],
  },
  {
    name: 'Orange Town',
    slug: 'orange-town',
    saga: 'east-blue',
    cover: '/arcs/orange-town.webp',
    episodeCount: 3,
    summary: 'Luffy ve Zoro, hırsız navigatör Nami ile karşılaşır. Birlikte, Orange Town\'ı terörize eden palyaço korsan Buggy\'ye karşı savaşırlar.',
    detailedSummary: 'Luffy ve Zoro açlıktan bitkin halde Orange Town\'a ulaşırlar. Burada harita hırsızı ve navigatör Nami ile karşılaşırlar. Nami, Buggy Korsanlarından Grand Line haritasını çalmıştır. Buggy, Bara Bara meyvesi sayesinde vücudunu parçalara ayırabilen bir korsandır ve kasabayı Buggy Topları ile terörize etmektedir. Luffy, Nami ile geçici bir ittifak kurar. Kasaba halkı saklanırken, Belediye Başkanı Boodle tek başına kasabasını korumaya çalışır. Luffy, Buggy\'yi yener ve kasabayı kurtarır. Nami, henüz resmi olarak mürettebata katılmasa da onlarla yolculuğa devam eder. Buggy\'nin Shanks ile geçmişi ve Roger Korsanları\'ndaki ortak geçmişleri ortaya çıkar.',
    keyEvents: [
      'Nami ile ilk karşılaşma',
      'Buggy\'nin Bara Bara meyvesi gücü',
      'Buggy ve Shanks\'ın ortak geçmişi',
      'Luffy Buggy\'yi yener',
      'Shushu\'nun sadakati',
    ],
    themes: ['Ev ve Aidiyet', 'Sadakat', 'Geçici İttifaklar'],
    location: 'Orange Town',
    villain: 'Buggy',
    characters: ['luffy', 'zoro', 'nami', 'buggy'],
    episodes: [
      {
        number: 1,
        title: 'Nami',
        slug: 'orange-town-01',
        duration: '27:19',
        summary: 'Luffy ve Zoro Orange Town\'a varır. Nami, Buggy\'nin hazinesini çalarken Luffy\'yi kafese hapseder. Buggy\'nin Bara Bara meyvesi gücü ortaya çıkar. Kasaba halkı Buggy\'nin zulmünden kaçmıştır.',
      },
      {
        number: 2,
        title: 'Hazine',
        slug: 'orange-town-02',
        duration: '35:42',
        summary: 'Luffy kafesten kurtulur ve Buggy\'nin mürettebatıyla savaşır. Nami\'nin korsanlara olan nefreti ortaya çıkar. Belediye Başkanı Boodle, kasabasını korumak için Buggy\'ye karşı durur. Köpek Shushu, sahibinin hatırasını korumak için savaşır.',
      },
      {
        number: 3,
        title: 'Korsan Palyaço Buggy',
        slug: 'orange-town-03',
        duration: '21:28',
        summary: 'Luffy ve Buggy arasındaki son savaş. Luffy, Buggy\'nin parçalanmış vücudunu Nami\'nin yardımıyla etkisiz hale getirir. Kasaba kurtulur. Nami, Luffy ve Zoro ile birlikte yolculuğa devam etmeye karar verir.',
      },
    ],
  },
  {
    name: 'Syrup Village',
    slug: 'syrup-village',
    saga: 'east-blue',
    cover: '/arcs/syrup-village.webp',
    episodeCount: 7,
    summary: 'Luffy ve ekibi, yalancı hikayeler anlatan Usopp\'un köyüne gelir. Kaptan Kuro\'nun köyü yok etme planını engellemek için savaşırlar.',
    detailedSummary: 'Hasır Şapkalar, bir gemi bulmak umuduyla Syrup Köyü\'ne gelirler. Burada sürekli yalancı hikayeler anlatan Usopp ile tanışırlar. Usopp\'un babası Yasopp, Shanks\'ın mürettebatındadır. Zengin kız Kaya\'nın uşağı Klahadore\'un aslında eski korsan Kaptan Kuro olduğu ortaya çıkar. Kuro, Kaya\'nın servetini ele geçirmek için 3 yıldır plan yapmıştır. Kuro\'nun Kara Kedi Korsanları köyü basacak ve Kaya\'yı öldürecektir. Usopp gerçeği söyler ama yalancı olarak bilindiği için kimse inanmaz. Luffy ve ekibiyle birlikte yamacı savunurlar. Django\'nun hipnoz güçleri ve Kuro\'nun "Pençe" tekniği zorlu bir savaş çıkarır. Zafer sonrası Kaya, onlara Caravel tipi gemi "Going Merry"yi hediye eder ve Usopp mürettebata katılır.',
    keyEvents: [
      'Usopp ile tanışma',
      'Kaptan Kuro\'nun gerçek kimliği',
      'Yamacın savunması',
      'Going Merry\'nin hediye edilmesi',
      'Usopp mürettebata katılır',
    ],
    themes: ['Yalancılık ve Cesaret', 'Gerçek Dostluk', 'Planlamaya Karşı İrade'],
    location: 'Syrup Köyü',
    villain: 'Kaptan Kuro',
    characters: ['luffy', 'zoro', 'nami', 'usopp'],
    episodes: [
      {
        number: 1,
        title: 'Kaptan Usopp',
        slug: 'syrup-village-01',
        duration: '28:36',
        summary: 'Hasır Şapkalar Syrup Köyü\'ne varır ve sürekli "korsanlar geliyor!" diye bağıran Usopp ile tanışır. Usopp\'un babası Yasopp\'un Shanks\'ın mürettebatında olduğu ortaya çıkar. Zengin kız Kaya ve uşağı Klahadore ile tanışırlar.',
      },
      {
        number: 2,
        title: 'Kaptan Kuro',
        slug: 'syrup-village-02',
        duration: '20:55',
        summary: 'Usopp, Klahadore\'un aslında eski korsan Kaptan Kuro olduğunu keşfeder. Kuro\'nun Kaya\'nın mirasını ele geçirmek için köyü yok etme planı ortaya çıkar. Usopp gerçeği anlatmaya çalışır ama yalancı olarak bilindiği için kimse inanmaz.',
      },
      {
        number: 3,
        title: 'Yokuş',
        slug: 'syrup-village-03',
        duration: '24:27',
        summary: 'Kuro\'nun korsanları yamacından saldırıya geçer. Luffy, Zoro, Nami ve Usopp yamacı savunmak için savaşırlar. Usopp korkmasına rağmen cesurca savaşır ve köyünü korumak için her şeyini ortaya koyar.',
      },
      {
        number: 4,
        title: 'Sessiz Adam',
        slug: 'syrup-village-04',
        duration: '30:28',
        summary: 'Django\'nun hipnoz güçleri Luffy\'yi bile etkiler. Kuro sahneye çıkar ve kendi mürettebatına bile acımasızlığını gösterir. "Pençe" tekniğiyle son derece hızlı ve ölümcül saldırılar yapar.',
      },
      {
        number: 5,
        title: 'Bin Planlı Kaptan Kuro',
        slug: 'syrup-village-05',
        duration: '22:30',
        summary: 'Luffy, Kuro\'yu yener ve köy kurtulur. Kaya, minnettarlığını göstermek için mürettebata Caravel tipi gemi Going Merry\'yi hediye eder. Usopp, cesur bir savaşçı olma hayaliyle mürettebata katılır ve köyüne veda eder.',
      },
      {
        number: 6,
        title: 'Çanlar Kimin İçin Çalacak',
        slug: 'syrup-village-06',
        duration: '16:03',
        summary: 'Luffy ve Kaptan Kuro arasındaki son savaş. Kuro, ölümcül hız tekniği "Shakushi" ile görünmez hızda saldırılar yapar ve kendi mürettebatını bile biçer. Luffy, Kuro\'nun hızına rağmen onu yakalar ve güçlü bir yumrukla yere serer. Kuro\'nun 3 yıllık planı suya düşer.',
      },
      {
        number: 7,
        title: 'Denize Doğru',
        slug: 'syrup-village-07',
        duration: '18:06',
        summary: 'Savaş sona erer ve köy kurtulur. Kaya, minnettarlığını göstermek için mürettebata Caravel tipi gemi Going Merry\'yi hediye eder. Usopp, cesur bir denizci olma hayaliyle köyüne veda eder ve Hasır Şapkaların nişancısı olarak mürettebata katılır. Yeni bir gemiyle yeni maceralar başlar.',
      },
    ],
  },
  {
    name: 'Gaimon',
    slug: 'gaimon',
    saga: 'east-blue',
    cover: '/arcs/gaimon.webp',
    episodeCount: 1,
    summary: 'Hazine sandığına sıkışmış adam Gaimon ile karşılaşma. Kısa ama anlamlı bir macera.',
    detailedSummary: 'Hasır Şapkalar, tuhaf bir adaya ulaşırlar. Burada yıllardır bir hazine sandığının içine sıkışmış olan Gaimon ile karşılaşırlar. Gaimon, adayı ve hayvanlarını koruyarak yaşamaktadır. Luffy, Gaimon\'un hikayesini dinler ve ona yardım etmeye çalışır. Kısa ama dostluk ve hazine kavramını sorgulatan anlamlı bir macera.',
    keyEvents: [
      'Gaimon ile karşılaşma',
      'Gaimon\'un sandığa sıkışma hikayesi',
    ],
    themes: ['Dostluk', 'Gerçek Hazine'],
    location: 'Gaimon Adası',
    villain: '-',
    characters: ['luffy', 'nami'],
    episodes: [
      {
        number: 1,
        title: 'Sen Tuhaf Bir Hayvansın',
        slug: 'gaimon-01',
        duration: '20:16',
        summary: 'Hasır Şapkalar tuhaf bir adaya ulaşır ve hazine sandığına sıkışmış Gaimon ile tanışırlar. Gaimon\'un adayı ve hayvanlarını koruyarak geçen yaşamı ortaya çıkar.',
      },
    ],
  },
  {
    name: 'Baratie',
    slug: 'baratie',
    saga: 'east-blue',
    cover: '/arcs/baratie.webp',
    episodeCount: 8,
    summary: 'Yüzen restoran Baratie\'de Luffy, aşçı Sanji ile tanışır. Don Krieg\'in devasa filosu Baratie\'yi tehdit ederken, efsanevi kılıç ustası Mihawk ortaya çıkar.',
    detailedSummary: 'Hasır Şapkalar, denizin ortasındaki yüzen restoran Baratie\'ye ulaşırlar. Luffy, yanlışlıkla restorana zarar verir ve tazminat olarak burada çalışmak zorunda kalır. Baş aşçı Sanji\'nin yemek konusundaki tutkusunu ve All Blue rüyasını keşfeder. Don Krieg\'in bitkin filosu Baratie\'ye sığınır. Grand Line\'dan kaçan Krieg, restoranı ele geçirmeye çalışır. Bu sırada efsanevi kılıç ustası Dracule Mihawk, Krieg\'in filosunun peşinden gelmiştir. Zoro, hayalinin peşinden Mihawk\'a meydan okur ama acı bir yenilgi alır. Bu yenilgi Zoro\'nun bir daha asla kaybetmeme yemini etmesine yol açar. Sanji\'nin geçmişi, açlıktan ölmek üzereyken düşmanı Zeff tarafından kurtarılması ortaya çıkar. Zeff, Sanji\'yi kurtarmak için kendi bacağını yemiştir. Luffy, Don Krieg\'i yener. Sanji, gözyaşları içinde Baratie\'ye veda eder ve mürettebata aşçı olarak katılır.',
    keyEvents: [
      'Sanji ile tanışma',
      'Don Krieg\'in tehdidi',
      'Mihawk\'ın ortaya çıkışı',
      'Zoro vs Mihawk — Zoro\'nun yenilgisi ve yemini',
      'Sanji ve Zeff\'in geçmişi',
      'Sanji mürettebata katılır',
    ],
    themes: ['Rüyalar İçin Fedakarlık', 'Açlık ve Yemek', 'Gurur ve Yenilgiyi Kabul Etme'],
    location: 'Baratie Yüzen Restoranı',
    villain: 'Don Krieg',
    characters: ['luffy', 'zoro', 'sanji', 'mihawk'],
    episodes: [
      {
        number: 1,
        title: 'Sanji',
        slug: 'baratie-01',
        duration: '29:06',
        summary: 'Hasır Şapkalar denizin ortasındaki yüzen restoran Baratie\'ye ulaşır. Luffy yanlışlıkla restorana zarar verir ve baş aşçı Zeff\'e tazminat olarak çalışmayı kabul eder. Sanji\'nin müşterilerine olan tutumu ve yemek felsefesi dikkat çeker.',
      },
      {
        number: 2,
        title: 'Korsan Komodor Don Krieg',
        slug: 'baratie-02',
        duration: '30:18',
        summary: 'Sanji\'nin All Blue — tüm denizlerin balıklarının bulunduğu efsanevi deniz — rüyası ortaya çıkar. Don Krieg\'in bitkin filosu Baratie\'ye sığınır ve Sanji, açlıktan ölmek üzere olan Krieg\'e yemek verir. Krieg güçlenince restoranı ele geçirmeye çalışır.',
      },
      {
        number: 3,
        title: 'Yemin',
        slug: 'baratie-03',
        duration: '36:47',
        summary: 'Dünyanın en güçlü kılıç ustası Dracule Mihawk, Don Krieg\'in filosunu tek başına yok ederek sahneye çıkar. Mihawk\'ın gücü herkesi dehşete düşürür. Zoro, hayatının en büyük fırsatını görür.',
      },
      {
        number: 4,
        title: 'Pearl',
        slug: 'baratie-04',
        duration: '19:00',
        summary: 'Zoro, Mihawk\'a meydan okur. Mihawk, küçük bir bıçakla bile Zoro\'yu yener. Zoro göğsünü açarak onurlu bir yenilgi ister. Mihawk, Yoru kılıcıyla son darbeyi vurur. Zoro "Bir daha asla kaybetmeyeceğim!" diye yemin eder. Mihawk, Zoro\'nun iradesini takdir eder.',
      },
      {
        number: 5,
        title: 'Bir Hayal Yüzünden',
        slug: 'baratie-05',
        duration: '20:29',
        summary: 'Luffy, Don Krieg ile savaşır. Krieg\'in zırhı, zehirli silahları ve devasa savaş mızrağı zorlu bir rakip çıkarır. Sanji ve Zeff\'in geçmişi anlatılır: açlıktan ölmek üzereyken küçük bir kayada mahsur kalan Sanji\'yi Zeff kendi bacağını feda ederek kurtarmıştır.',
      },
      {
        number: 6,
        title: 'MH5',
        slug: 'baratie-06',
        duration: '26:45',
        summary: 'Luffy, Don Krieg\'i yener. Sanji, Baratie\'yi ve Zeff\'i bırakma kararını verir. Gözyaşları içinde Zeff\'e teşekkür eder: "O lanet restorandaki her şey için... teşekkür ederim!" Sanji, Hasır Şapkaların aşçısı olarak mürettebata katılır.',
      },
      {
        number: 7,
        title: 'Kudretli Savaş Mızrağı',
        slug: 'baratie-07',
        duration: '26:21',
        summary: 'Sanji ve Zeff\'in geçmişi derinlemesine anlatılır. Küçük Sanji, Orbit gemisinde çırak aşçıyken gemi fırtınada batar. Zeff, Sanji\'yi kurtarır ve ikisi ıssız bir kayalıkta mahsur kalır. Zeff, tüm yiyecekleri Sanji\'ye verir ve hayatta kalmak için kendi bacağını feda eder. Bu fedakarlık, Sanji\'nin yemek felsefesini sonsuza dek şekillendirir.',
      },
      {
        number: 8,
        title: 'Dördüncü',
        slug: 'baratie-08',
        duration: '17:28',
        summary: 'Luffy ve Don Krieg arasındaki son savaş doruk noktasına ulaşır. Krieg\'in zırhını ve silahlarını parçalayan Luffy, onu denize gömer. Savaş sona erdiğinde Sanji, gözyaşları içinde Baratie\'ye ve Zeff\'e veda eder. Zeff sessizce "Hasta olma, oğlum" der. Sanji, All Blue rüyasının peşinden Hasır Şapkaların aşçısı olarak denize açılır.',
      },
    ],
  },
  {
    name: 'Arlong Park',
    slug: 'arlong-park',
    saga: 'east-blue',
    cover: '/arcs/arlong-park.webp',
    episodeCount: 10,
    summary: 'Nami\'nin karanlık geçmişi ortaya çıkar. Arlong, Nami\'nin köyünü yıllardır sömürmektedir. Luffy, Nami\'yi kurtarmak için en güçlü düşmanıyla yüzleşir.',
    detailedSummary: 'East Blue sagasının doruk noktası. Nami aniden mürettebattan ayrılır ve Arlong Korsanlarına döner. Mürettebat onu takip eder ve Nami\'nin korkunç geçmişini öğrenir. Nami, üvey annesi Bellemere\'in Arlong tarafından öldürülmesine tanık olmuştur. Arlong, Cocoyashi Köyü\'nü vergiye bağlamış ve Nami\'ye bir anlaşma sunmuştur: 100 milyon Berry toplarsa köyünü satın alabilir. Nami, 8 yıl boyunca Arlong için harita çizerek para biriktirmiştir. Tam parayı tamamlamak üzereyken Arlong, Deniz Kuvvetleri ile işbirliği yaparak parayı çaldırır. Umudunu kaybeden Nami, ilk kez yardım ister. Luffy, hasır şapkasını Nami\'ye bırakır ve Arlong Park\'ı yıkar. Nami\'nin harita odasını tamamen parçalar: "Elbette sana yardım edeceğim!" Bu an, serinin en ikonik sahnelerinden biridir.',
    keyEvents: [
      'Nami\'nin geçmişi ve Bellemere\'in ölümü',
      'Arlong\'un köyü sömürmesi',
      'Nami\'nin 100 milyon Berry anlaşması',
      '"Luffy... Yardım et!" sahnesi',
      'Luffy Arlong Park\'ı yıkar',
      'Nami resmi olarak mürettebata katılır',
    ],
    themes: ['Kölelik ve Özgürlük', 'Aile Bağları', 'Yardım İsteme Cesareti', 'Adaletsizliğe Başkaldırı'],
    location: 'Cocoyashi Köyü, Arlong Park',
    villain: 'Arlong',
    characters: ['luffy', 'zoro', 'nami', 'sanji', 'usopp'],
    episodes: [
      {
        number: 1,
        title: 'Arlong Park',
        slug: 'arlong-park-01',
        duration: '29:27',
        summary: 'Nami, mürettebattan ayrılır ve Arlong Korsanlarına döner. Luffy ve ekip, Nami\'nin peşinden Conomi Adaları\'na gider. Arlong\'un Balık-Adam olduğu ve East Blue\'yu kontrol ettiği ortaya çıkar.',
      },
      {
        number: 2,
        title: 'Grand Line\'ın Canavarları',
        slug: 'arlong-park-02',
        duration: '20:49',
        summary: 'Arlong\'un Cocoyashi Köyü üzerindeki zulmü anlatılır. Balık-Adamların insanlardan fiziksel olarak çok daha güçlü olduğu gösterilir. Usopp, Arlong tarafından yakalanır.',
      },
      {
        number: 3,
        title: 'Deniz Haritaları ve Balıkadamlar',
        slug: 'arlong-park-03',
        duration: '23:25',
        summary: 'Köy halkının Arlong\'un zulmü altındaki yaşamı. Nami\'nin köylüler arasındaki konumu ve onun için duydukları sevgi. Nojiko, Nami\'nin üvey kız kardeşi, mürettebata Nami\'nin geçmişini anlatmaya başlar.',
      },
      {
        number: 4,
        title: 'Bell-mère',
        slug: 'arlong-park-04',
        duration: '26:47',
        summary: 'Nami ve Nojiko\'nun geçmişi. Deniz Kuvvetleri eski askeri Bellemere, savaş alanında iki yetim bebeği bulur ve evlat edinir. Arlong köye geldiğinde, kızlarını korumak için hayatını feda eder: "Onlar benim kızlarım!"',
      },
      {
        number: 5,
        title: 'Yaşamak İçin',
        slug: 'arlong-park-05',
        duration: '29:29',
        summary: 'Nami\'nin 8 yıllık acı dolu mücadelesi. Arlong için harita çizerek 100 milyon Berry biriktirmiştir. Tam hedefine ulaşacakken Arlong, yolsuz Denizci Nezumi\'ye parayı çaldırır. Umudunu kaybeden Nami, Arlong\'un dövmesini bıçakla kazımaya çalışır.',
      },
      {
        number: 6,
        title: 'Tamam, Hadi Karşı Koyalım!',
        slug: 'arlong-park-06',
        duration: '24:47',
        summary: 'Serinin en ikonik sahnesi. Nami, ilk kez yardım ister: "Luffy... Yardım et!" Luffy, hasır şapkasını Nami\'nin başına koyar ve "Elbette!" diyerek Arlong Park\'a doğru yürür. Mürettebat tam kadro saldırıya geçer.',
      },
      {
        number: 7,
        title: 'Kahramanlık, Balıkadam Karatesine Karşı',
        slug: 'arlong-park-07',
        duration: '25:49',
        summary: 'Zoro, Mihawk\'tan aldığı yaralar henüz iyileşmemişken altı kollu kılıç ustası Hatchan ile savaşır. Ağır yaralı olmasına rağmen kazanır. Zoro\'nun inanılmaz dayanıklılığı ortaya çıkar.',
      },
      {
        number: 8,
        title: 'Benim Sıram',
        slug: 'arlong-park-08',
        duration: '25:25',
        summary: 'Sanji, Balık-Adam karatecisi Kuroobi ile savaşır. Suyun altında dezavantajlı olmasına rağmen zekice bir stratejiyle kazanır. Usopp da Chew\'a karşı korku içinde ama cesurca savaşır.',
      },
      {
        number: 9,
        title: 'İkinci',
        slug: 'arlong-park-09',
        duration: '24:35',
        summary: 'Luffy ve Arlong arasındaki epik final savaşı. Arlong\'un Kiribachi testere kılıcı ve Balık-Adam gücü zorlu bir mücadele çıkarır. Luffy, Nami\'nin harita odasını görünce öfkelenir ve odayı tamamen parçalar: "Bu oda seni acı çektiriyor!"',
      },
      {
        number: 10,
        title: 'Dön, Rüzgâr Gülü, Dön',
        slug: 'arlong-park-10',
        duration: '20:41',
        summary: 'Luffy, Arlong\'u yener ve Arlong Park\'ı tamamen yıkar. 8 yıl sonra Cocoyashi Köyü özgürdür. Nami, yeni bir Arlong dövmesi yerine mandalina ve fırıldak dövmesi yaptırır. Resmi olarak Hasır Şapkaların navigatörü olur. İlk ödül posterleri yayınlanır.',
      },
    ],
  },
  {
    name: 'Buggy\'nin Tayfasının Maceraları',
    slug: 'buggys-crew',
    saga: 'east-blue',
    cover: '/arcs/buggys-crew.webp',
    episodeCount: 1,
    summary: 'Buggy\'nin dağılan mürettebatının yeniden bir araya gelme macerası.',
    detailedSummary: 'Luffy tarafından yenilen Buggy\'nin mürettebatı dağılmıştır. Buggy\'nin Bara Bara meyvesi sayesinde parçalanmış vücudu farklı yerlere savrulmuştur. Mürettebat üyeleri kaptanlarını aramaya başlar ve çeşitli maceralar yaşayarak sonunda yeniden bir araya gelirler.',
    keyEvents: [
      'Buggy\'nin mürettebatının yeniden toplanması',
      'Buggy\'nin parçalarının bir araya gelmesi',
    ],
    themes: ['Sadakat', 'Yeniden Bir Araya Gelme'],
    location: 'East Blue',
    villain: '-',
    characters: ['buggy'],
    episodes: [
      {
        number: 1,
        title: 'Buggy\'nin Tayfasının Maceraları',
        slug: 'buggys-crew-01',
        duration: '22:10',
        summary: 'Luffy tarafından yenildikten sonra dağılan Buggy mürettebatının yeniden bir araya gelme macerası. Buggy\'nin parçalanmış vücudu farklı yerlere savrulmuş, mürettebatı onu aramaktadır.',
      },
    ],
  },
  {
    name: 'Loguetown',
    slug: 'loguetown',
    saga: 'east-blue',
    cover: '/arcs/loguetown.webp',
    episodeCount: 3,
    summary: 'Korsanlar Kralı Gold Roger\'ın doğduğu ve idam edildiği şehir. Luffy, Grand Line\'a girmeden önce bu efsanevi şehri ziyaret eder.',
    detailedSummary: 'Hasır Şapkalar, Grand Line\'a girmeden önceki son durak olan Loguetown\'a varırlar. Bu şehir, Korsanlar Kralı Gold Roger\'ın hem doğduğu hem de 22 yıl önce idam edildiği yerdir — "Başlangıç ve Son Şehri" olarak bilinir. Luffy, Roger\'ın idam edildiği platformu ziyaret eder. Buggy ve Alvida, Luffy\'yi yakalamak için şehirdedir. Kaptan Smoker, Moku Moku meyvesiyle Luffy\'yi köşeye sıkıştırır. Tam Buggy Luffy\'yi idam platformunda öldürecekken, gizemli bir yıldırım düşer ve Luffy kurtulır. Dragon — Luffy\'nin babası — ilk kez gizlice sahneye çıkar. Mürettebat, fırtınanın ortasında Grand Line\'a doğru yola çıkar. Reverse Mountain\'ın önünde herkes hayallerini ilan eder ve kadehlerini kırar.',
    keyEvents: [
      'Luffy Roger\'ın idam platformunu ziyaret eder',
      'Smoker ile ilk karşılaşma',
      'Dragon\'ın gizemli müdahalesi',
      'Mürettebatın Grand Line yemini',
      'Büyük macera başlıyor',
    ],
    themes: ['Kader ve Miras', 'Yeni Başlangıçlar', 'Korsan Çağının Ruhu'],
    location: 'Loguetown',
    villain: 'Smoker, Buggy',
    characters: ['luffy', 'zoro', 'nami', 'sanji', 'usopp', 'smoker'],
    episodes: [
      {
        number: 1,
        title: 'Başlangıcın ve Sonun Şehri',
        slug: 'loguetown-01',
        duration: '27:28',
        summary: 'Mürettebat Loguetown\'a varır. Luffy, Gold Roger\'ın idam platformunu ziyaret eder. Zoro usta bir kılıç dükkânında efsanevi kılıçlar keşfeder. Sanji yemek malzemeleri alırken Nami alışveriş yapar. Smoker, Luffy\'nin geldiğini öğrenir.',
      },
      {
        number: 2,
        title: 'Paralellikler',
        slug: 'loguetown-02',
        duration: '31:23',
        summary: 'Buggy ve Alvida, Luffy\'yi yakalar ve Roger\'ın idam edildiği platformda halka açık infaz düzenler. Luffy, son anında gülümser — tıpkı Roger gibi. Tam o anda gizemli bir yıldırım platformu parçalar ve Luffy kurtulur. Dragon\'ın gizli müdahalesi.',
      },
      {
        number: 3,
        title: 'Efsane Başlıyor',
        slug: 'loguetown-03',
        duration: '35:54',
        summary: 'Smoker Luffy\'yi yakalamaya çalışır ama Dragon araya girer. Mürettebat fırtınanın ortasında Loguetown\'dan kaçar. Grand Line\'ın girişinde herkes hayallerini ilan eder ve bir fıçının üzerine ayaklarını koyarak yemin eder. East Blue\'ya veda, büyük macera başlıyor.',
      },
    ],
  },
]
