import type { Arc } from '@/types'

export const FINAL_ARCS: Arc[] = [
  {
    name: 'Egghead',
    slug: 'egghead',
    saga: 'final',
    cover: '/arcs/egghead.webp',
    episodeCount: 20,
    summary: 'Dünyanın en zeki insanı Vegapunk\'ın gelecek adası. Void Century\'nin sırları ortaya çıkmaya başlar.',
    detailedSummary: 'Final Saga\'nın ilk arcı. Mürettebat, Vegapunk\'ın geleceğin teknolojisiyle dolu adası Egghead\'e ulaşır. Vegapunk, 6 farklı uyduya — Shaka, Lilith, Edison, Pythagoras, Atlas, York — bölünmüştür. Her biri kişiliğinin bir yönünü temsil eder. Vegapunk, Void Century hakkında araştırma yapmıştır ve tüm dünyaya bir mesaj yayınlamak istemektedir. Dünya Hükümeti, bunu engellemek için Egghead\'e büyük bir güç gönderir: CP0, Seraphim (eski Shichibukai\'lerin klonları) ve Amiral Kizaru. Bonney — Kuma\'nın kızı — babasının geçmişini ve fedakarlığını öğrenir. Kuma, bir Buccaneer soyundandır ve Nika efsanesine inanmıştır. Vegapunk\'ın mesajı dünyaya yayınlanır: "800 yıl önce Antik Krallık, 20 kralın ittifakıyla yıkıldı. One Piece..." Mesaj kesilir. Saturn — Gorosei\'nin bir üyesi — Egghead\'e gelir. Luffy, Gear 5 ile Kizaru ve Gorosei ile savaşır. Dev Robot — 200 yıl önce Mariejois\'a saldıran Joy Boy\'un robotu — harekete geçer.',
    keyEvents: [
      'Vegapunk\'ın 6 uydusu',
      'Seraphim — Shichibukai klonları',
      'Bonney ve Kuma\'nın hikayesi',
      'Void Century mesajı yayını',
      'Saturn ve Gorosei Egghead\'de',
      'Luffy vs Kizaru',
      'Dev Robot\'un uyanışı',
      'Vegapunk\'ın "ölümü" ve mesajı',
    ],
    themes: ['Bilim ve Gerçek', 'Void Century', 'Baba-Kız İlişkisi', 'Tarihin Gizlenmesi', 'Son Savaşa Hazırlık'],
    location: 'Egghead (Gelecek Adası)',
    villain: 'Gorosei (Saturn), CP0',
    characters: ['luffy', 'zoro', 'nami', 'robin', 'kizaru', 'vegapunk'],
    episodes: [
      { number: 1, title: 'Gelecek Adası', slug: 'egghead-01', duration: '24:25', summary: 'Mürettebat, geleceğin teknolojisiyle dolu Egghead adasına ulaşır. Uçan arabalar, hologramlar, otomatik savunma sistemleri. Vegapunk\'ın uydusu Lilith ile karşılaşırlar.' },
      { number: 2, title: 'Vegapunk\'ın Uyduları', slug: 'egghead-02', duration: '23:31', summary: 'Vegapunk\'ın 6 uydusu tanıtılır: Shaka (iyi), Lilith (kötü), Edison (düşünür), Pythagoras (bilge), Atlas (şiddet), York (açgözlülük). Her biri bağımsız hareket eder ama ana Vegapunk\'a bağlıdır.' },
      { number: 3, title: 'Bonney\'in Arayışı', slug: 'egghead-03', duration: '28:58', summary: 'Jewelry Bonney, babası Kuma\'nın Vegapunk tarafından ne yapıldığını öğrenmek için adadır. Kuma\'nın Pacifista\'ya dönüştürülme sürecinin arkasındaki gerçekler ortaya çıkmaya başlar.' },
      { number: 4, title: 'Kuma\'nın Geçmişi', slug: 'egghead-04', duration: '30:12', summary: 'Bartholomew Kuma\'nın hikayesi: Buccaneer soyundan, çocukken köle yapılmış, Nika efsanesine inanan bir adam. Bonney\'i korumak için kendi bilincini feda etmiştir. Vegapunk\'la anlaşması.' },
      { number: 5, title: 'Seraphim', slug: 'egghead-05', duration: '32:22', summary: 'Seraphim — eski Shichibukai\'lerin çocuk klonları — ortaya çıkar. Mihawk, Hancock, Kuma ve diğerlerinin Lunarian kanıyla güçlendirilmiş versiyonları. Son derece güçlü ve tehlikeli.' },
      { number: 6, title: 'York\'un İhaneti', slug: 'egghead-06', duration: '19:29', summary: 'Vegapunk\'ın uydusu York, Dünya Hükümeti ile işbirliği yapmıştır. York, Celestial Dragon olmak istemektedir. Diğer uyduları ve Vegapunk\'ı öldürmeye çalışır.' },
      { number: 7, title: 'CP0 Saldırısı', slug: 'egghead-07', duration: '31:49', summary: 'CP0 ajanları — Lucci, Kaku ve Stussy — Egghead\'e gelir. Stussy\'nin aslında MADS\'in eski üyesi ve Vegapunk\'ın casusu olduğu ortaya çıkar. Lucci, Luffy ile tekrar karşılaşır.' },
      { number: 8, title: 'Luffy vs Lucci', slug: 'egghead-08', duration: '33:27', summary: 'Luffy ve Lucci\'nin tekrar karşılaşması. Luffy Gear 5, Lucci Awakened Zoan formu kullanır. Luffy, eskisi kadar zorlanmaz — güç farkı açılmıştır.' },
      { number: 9, title: 'Vegapunk\'ın Mesajı', slug: 'egghead-09', duration: '34:38', summary: 'Vegapunk, ölümünden sonra aktive olacak bir mesaj hazırlamıştır. Tüm dünyaya yayınlanacak: Void Century\'nin gerçeği, Antik Krallık ve One Piece hakkında.' },
      { number: 10, title: 'Amiral Kizaru', slug: 'egghead-10', duration: '34:32', summary: 'Amiral Kizaru, büyük bir donanmayla Egghead\'e gelir. Vegapunk\'ın eski arkadaşıdır ama görevini yapmak zorundadır. Kizaru\'nun acı yüzü — dostunu öldürmek zorunda olan asker.' },
      { number: 11, title: 'Luffy vs Kizaru', slug: 'egghead-11', duration: '29:56', summary: 'Gear 5 Luffy vs Amiral Kizaru. Sabaody\'de çaresiz kaldığı adamla tekrar savaşır ama bu sefer eşit düzeyde. Luffy, Kizaru\'nun ışık hızı saldırılarını yakalar ve geri fırlatır.' },
      { number: 12, title: 'Saturn Geliyor', slug: 'egghead-12', duration: '26:55', summary: 'Gorosei\'nin bir üyesi Saturn, Egghead\'e bizzat gelir. Şeytani bir forma dönüşür — böcek-örümcek benzeri dev bir yaratık. Gücü, sıradan insanları bakışıyla öldürebilecek düzeydedir.' },
      { number: 13, title: 'Gorosei\'nin Gerçek Yüzü', slug: 'egghead-13', duration: '14:17', summary: 'Gorosei — 5 Yıldız Yaşlısı — aslında ölümsüz şeytani varlıklardır. 800 yıldır dünyayı yönetmektedirler. Saturn\'ün gücü, regenerasyon ve lanet yeteneği herkesi dehşete düşürür.' },
      { number: 14, title: 'Kuma\'nın Koşusu', slug: 'egghead-14', duration: '37:38', summary: 'Bilinçsiz Pacifista Kuma, Bonney\'i korumak için Red Line\'ı yürüyerek aşar. Programlama olmadan, saf içgüdüyle kızına ulaşmaya çalışır. Bir babanın sonsuz sevgisi.' },
      { number: 15, title: 'Void Century Yayını', slug: 'egghead-15', duration: '30:11', summary: 'Vegapunk\'ın mesajı dünyaya yayınlanmaya başlar: "800 yıl önce büyük bir krallık vardı. 20 kral birleşerek onu yıktı. Dünya Hükümeti gerçeği gizliyor..." Tüm dünya dinliyor.' },
      { number: 16, title: 'Dev Robot', slug: 'egghead-16', duration: '23:19', summary: '200 yıl önce Mariejois\'a saldıran dev robot harekete geçer. Joy Boy\'un mirası olan bu robot, Luffy\'nin Gear 5 enerjisiyle uyanmıştır. Nika\'nın bukleli saçlarına benzer parçaları vardır.' },
      { number: 17, title: 'Bonney ve Nika', slug: 'egghead-17', duration: '18:47', summary: 'Bonney, Kuma\'nın anılarını görür ve babasının Nika\'ya olan inancını anlar. Toshi Toshi meyvesiyle Nika formuna dönüşmeye çalışır. Kuma\'nın fedakarlığının gerçek nedeni: Bonney\'in özgürlüğü.' },
      { number: 18, title: 'Kaçış Planı', slug: 'egghead-18', duration: '33:00', summary: 'Mürettebat, Egghead\'den kaçmak için plan yapar. Franky\'nin Vegapunk teknolojisiyle güçlendirilmiş Sunny, denize açılmaya hazırlanır. Ama Gorosei ve donanma kaçışı engellemektedir.' },
      { number: 19, title: 'Elbaf\'a Doğru', slug: 'egghead-19', duration: '29:22', summary: 'Dev filoya karşı epik kaçış. Dorry ve Brogy — Little Garden\'dan tanıdık devler — sürpriz şekilde yardıma gelir! Dev Savaşçı Korsanları mürettebatı kurtarır. Bir sonraki durak: Dev ülkesi Elbaf!' },
      { number: 20, title: 'Vegapunk\'ın Mirası', slug: 'egghead-20', duration: '28:38', summary: 'Vegapunk\'ın mesajı tamamlanamadan kesilir ama dünya artık gerçeği sorgulamaya başlamıştır. Mürettebat Elbaf\'a doğru yol alır. Final Saga\'nın ilk adımı atılmıştır. Son savaş yaklaşıyor.' },
    ],
  },
]
