import type { Arc } from '@/types'

export const FISH_MAN_ISLAND_ARCS: Arc[] = [
  {
    name: 'Return to Sabaody',
    slug: 'return-to-sabaody',
    saga: 'fish-man-island',
    cover: '/arcs/return-sabaody.jpg',
    episodeCount: 3,
    summary: '2 yıl sonra mürettebat tekrar bir araya gelir. Herkes güçlenmiş ve Yeni Dünya\'ya hazırdır.',
    detailedSummary: '2 yıllık eğitimden sonra mürettebat Sabaody Archipelago\'da buluşur. Herkes fiziksel olarak ve yetenekleriyle büyük gelişim göstermiştir. Luffy, tam kontrollü Haki kullanabilir. Zoro, bir gözünü kapatmış ve çok daha güçlüdür. Sanji burun kanaması sorunuyla gelir. Sahte Hasır Şapkalar ortaya çıkar — ünlü korsanları taklit eden bir grup. Luffy, Haoshoku Haki ile sahteleri tek bakışla bayıltır. Rayleigh, Thousand Sunny\'yi kaplayarak hazırlamıştır. Sentoumaru ve Pacifista\'lar gelir ama Luffy, 2 yıl önce zorlandığı Pacifista\'yı tek yumrukla yok eder. Mürettebat, güçlerini göstererek Fish-Man Island\'a doğru dalışa geçer.',
    keyEvents: [
      '2 yıl sonra buluşma',
      'Herkesin yeni güçleri',
      'Sahte Hasır Şapkalar',
      'Pacifista\'yı tek yumrukla yok etme',
      'Fish-Man Island\'a dalış',
    ],
    themes: ['Yeniden Birleşme', 'Gelişim ve Güç', 'Yeni Başlangıç'],
    location: 'Sabaody Archipelago',
    characters: ['luffy', 'zoro', 'nami', 'sanji', 'usopp', 'chopper', 'robin', 'franky', 'brook'],
    episodes: [
      { number: 1, title: '2 Yıl Sonra Sabaody', slug: 'return-sabaody-01', duration: '24:30', summary: 'Mürettebat tek tek Sabaody\'ye gelir. Herkes değişmiş ve güçlenmiştir. Luffy daha olgun, Zoro bir gözü kapalı, Nami saçları uzamış, Franky devasa robotik bir gövde kazanmış. Sahte Hasır Şapkalar sorun çıkarır.' },
      { number: 2, title: 'Yeni Güçler', slug: 'return-sabaody-02', duration: '24:30', summary: 'Luffy, Haoshoku Haki ile sahte Luffy\'yi ve adamlarını bayıltır. Zoro, tek kılıçla gemiyi ikiye böler. Sanji, Skywalk ile havada yürür. Her mürettebat üyesi 2 yılın meyvelerini gösterir.' },
      { number: 3, title: 'Yeni Dünya\'ya Dalış', slug: 'return-sabaody-03', duration: '24:30', summary: 'Sentoumaru ve Pacifista\'lar gelir ama Luffy, 2 yıl önce zorluk çektiği Pacifista\'yı Haki yumruğuyla tek hamlede yok eder. Thousand Sunny, Rayleigh\'in kaplamasıyla denizin altına dalış yapar. Fish-Man Island\'a doğru!' },
    ],
  },
  {
    name: 'Fish-Man Island',
    slug: 'fish-man-island',
    saga: 'fish-man-island',
    cover: '/arcs/fish-man-island.jpg',
    episodeCount: 15,
    summary: '10.000 metre derinlikteki Fish-Man Island\'da ırkçılık ve ayrımcılık temaları işlenir. Luffy, Yeni Dünya\'daki ilk gerçek testini geçer.',
    detailedSummary: 'Denizin 10.000 metre altındaki Fish-Man Island, Balık-Adamlar ve Deniz Kızlarının vatanıdır. Ada, Beyaz Sakal\'ın koruması altındaydı ama ölümünden sonra tehlikeye girmiştir. Big Mom şimdi koruyucudur ama karşılığında şeker istemektedir. Prenses Shirahoshi, devasa bir deniz kızıdır ve antik silah Poseidon\'un ta kendisidir. Hody Jones, insanlara karşı nefret dolu bir Balık-Adam milliyetçisidir. İlginç olan, Hody\'nin insanlardan hiç kötülük görmemiş olmasıdır — nefreti tamamen öğretilmiştir. Bu, ırkçılığın nasıl nesilden nesile aktarıldığının güçlü bir alegorisidir. Fisher Tiger\'ın hikayesi ve Otohime Kraliçe\'nin barış çabaları anlatılır. Luffy, Hody\'yi Gear 2 ve Busoshoku Haki ile yener. Ada, artık Luffy\'nin koruması altındadır — Big Mom\'a karşı. Luffy, Big Mom\'u arayarak "Fish-Man Island benim bölgem!" diye ilan eder.',
    keyEvents: [
      'Fish-Man Island\'a ulaşış',
      'Shirahoshi — Antik Silah Poseidon',
      'Hody Jones\'un ırkçı isyanı',
      'Fisher Tiger ve Otohime\'nin hikayeleri',
      'Luffy Hody\'yi yener',
      'Luffy Fish-Man Island\'ı sahiplenir',
      'Big Mom\'a meydan okuma',
    ],
    themes: ['Irkçılık ve Ayrımcılık', 'Nefretin Nesiller Arası Aktarımı', 'Barış ve Hoşgörü', 'Miras ve Koruma'],
    location: 'Fish-Man Island (10.000m derinlik)',
    villain: 'Hody Jones',
    characters: ['luffy', 'jinbe'],
    episodes: [
      { number: 1, title: 'Denizin Altındaki Cennet', slug: 'fish-man-island-01', duration: '24:30', summary: 'Mürettebat, 10.000 metre derindeki Fish-Man Island\'a ulaşır. Dev bir balon içinde korunan muhteşem bir sualtı şehri. Deniz Kızları ve Balık-Adamlar burada yaşar.' },
      { number: 2, title: 'Prenses Shirahoshi', slug: 'fish-man-island-02', duration: '24:30', summary: 'Luffy, devasa deniz kızı Prenses Shirahoshi ile tanışır. Shirahoshi, 10 yıldır odasına kapatılmıştır — Vander Decken tarafından takip edilmektedir. Luffy onu dışarı çıkarmaya karar verir.' },
      { number: 3, title: 'Hody Jones', slug: 'fish-man-island-03', duration: '24:30', summary: 'Hody Jones ve Yeni Balık-Adam Korsanları, Ryugu Krallığı\'nı ele geçirmeye çalışır. İnsanlara karşı derin bir nefretle doludur. Energy Steroid ilacıyla güçlenmektedir.' },
      { number: 4, title: 'Fisher Tiger\'ın Hikayesi', slug: 'fish-man-island-04', duration: '24:30', summary: 'Fisher Tiger\'ın hikayesi anlatılır: Celestial Dragonlardan kaçmış ve Mariejois\'daki tüm köleleri serbest bırakmıştır. İnsanlardan nefret etmesine rağmen kan bağışını reddetmemiştir — ama insanlar onun kanını reddetmiştir.' },
      { number: 5, title: 'Otohime\'nin Rüyası', slug: 'fish-man-island-05', duration: '24:30', summary: 'Kraliçe Otohime, insanlarla barış için mücadele etmiştir. İmza kampanyası düzenlemiş ama bir suikastçı tarafından öldürülmüştür. Otohime\'nin barış mirası hâlâ yaşamaktadır.' },
      { number: 6, title: 'Antik Silah Poseidon', slug: 'fish-man-island-06', duration: '24:30', summary: 'Robin, Poneglyph\'i okur ve şok edici gerçeği öğrenir: Shirahoshi, antik silah Poseidon\'un ta kendisidir. Deniz Krallarını kontrol edebilme gücüne sahiptir. Bu bilgi dünyayı sarsabilir.' },
      { number: 7, title: 'Luffy vs Hody I', slug: 'fish-man-island-07', duration: '24:30', summary: 'Luffy, Hody Jones ile savaşır. Hody, Energy Steroidlerle güçlenmiş olmasına rağmen Luffy\'nin Haki\'si karşısında zorlanır. Suyun altında bile Luffy üstünlüğünü korur.' },
      { number: 8, title: 'Zoro vs Hyouzou', slug: 'fish-man-island-08', duration: '24:30', summary: 'Zoro, zehirli kılıç ustası Hyouzou ile savaşır. Busoshoku Haki ile kılıçlarını sertleştirerek tek hamlede yener. Zoro\'nun 2 yıllık eğitiminin meyvesi görülür.' },
      { number: 9, title: 'Jinbe\'nin Kararı', slug: 'fish-man-island-09', duration: '24:30', summary: 'Jinbe, Luffy\'ye Fish-Man Island\'ın geçmişini anlatır. Nefret döngüsünü kırmanın önemini vurgular. Luffy, Jinbe\'yi mürettebata davet eder ama Jinbe henüz hazır değildir — yapması gereken işler vardır.' },
      { number: 10, title: 'Noah\'ın Düşüşü', slug: 'fish-man-island-10', duration: '24:30', summary: 'Vander Decken, devasa gemi Noah\'ı Fish-Man Island\'a doğru fırlatır. Adayı yok edecek büyüklüktedir. Luffy, Noah\'ı durdurmak için denizin altında savaşır.' },
      { number: 11, title: 'Luffy vs Hody II', slug: 'fish-man-island-11', duration: '24:30', summary: 'Luffy, Gear 3 ve Busoshoku Haki kombinasyonuyla Hody\'yi kesin olarak yener. Hody\'nin nefreti boş ve temelsizdir — hiç kötülük görmemiş birinin aktarılan nefreti.' },
      { number: 12, title: 'Deniz Kralları', slug: 'fish-man-island-12', duration: '24:30', summary: 'Shirahoshi, bilinçsizce Deniz Krallarını çağırır. Devasa yaratıklar Noah\'ı durdurur ve adayı kurtarır. Poseidon\'un gücü ilk kez görülür. Joy Boy ve antik anlaşma hakkında ipuçları.' },
      { number: 13, title: 'Big Mom\'a Meydan Okuma', slug: 'fish-man-island-13', duration: '24:30', summary: 'Fish-Man Island, Big Mom\'a şeker göndermektedir. Luffy, Den Den Mushi ile Big Mom\'u arar: "Fish-Man Island benim bölgem! Kavgayı istiyorsan, gel!" Bir Yonko\'ya meydan okuma!' },
      { number: 14, title: 'Kan Bağışı', slug: 'fish-man-island-14', duration: '24:30', summary: 'Luffy ağır yaralıdır ve kan kaybetmektedir. Fish-Man Island halkı, Fisher Tiger\'ın aksine, Luffy\'ye kan bağışı yapar. Irklar arası barışın sembolik anı. Jinbe gözyaşlarına boğulur.' },
      { number: 15, title: 'Yeni Dünya\'ya', slug: 'fish-man-island-15', duration: '24:30', summary: 'Mürettebat Fish-Man Island\'dan ayrılır ve sonunda Yeni Dünya\'ya çıkar. Güneş, 2 yıl sonra ilk kez yüzlerine vurur. Yeni Dünya — Grand Line\'ın ikinci yarısı — her şeyin daha tehlikeli olduğu sular. Macera devam ediyor!' },
    ],
  },
]
