import type { Arc } from '@/types'

export const FISH_MAN_ISLAND_ARCS: Arc[] = [
  {
    name: 'Return to Sabaody',
    slug: 'return-to-sabaody',
    saga: 'fish-man-island',
    cover: '/arcs/return-sabaody.jpg',
    episodeCount: 3,
    summary: '2 yıl sonra mürettebat tekrar bir araya gelir. Herkes güçlenmiş ve Yeni Dünya\'ya hazırdır.',
    detailedSummary: '2 yıllık eğitimden sonra mürettebat Sabaody Archipelago\'da buluşur. Herkes fiziksel olarak ve yetenekleriyle büyük gelişim göstermiştir. Luffy, tam kontrollü Haki kullanabilir. Zoro, bir gözünü kapatmış ve çok daha güçlüdür. Sanji burun kanaması sorunuyla gelir. Sahte Hasır Şapkalar ortaya çıkar — ünlü korsanları taklit eden bir grup. Luffy, Haoshoku Haki ile sahteleri tek bakışla bayıltır. Rayleigh, Thousand Sunny\'yi kaplayarak hazırlamıştır. Sentoumaru ve Pacifista\'lar gelir ama Luffy, 2 yıl önce zorlandığı Pacifista\'yı tek yumrukla yok eder. Mürettebat, güçlerini göstererek Fish-Man Island\'a doğru dalışa geçer.',
    keyEvents: [
      '2 yıl sonra buluşma',
      'Herkesin yeni güçleri',
      'Sahte Hasır Şapkalar',
      'Pacifista\'yı tek yumrukla yok etme',
      'Fish-Man Island\'a dalış',
    ],
    themes: ['Yeniden Birleşme', 'Gelişim ve Güç', 'Yeni Başlangıç'],
    location: 'Sabaody Archipelago',
    characters: ['luffy', 'zoro', 'nami', 'sanji', 'usopp', 'chopper', 'robin', 'franky', 'brook'],
    episodes: [
      { number: 1, title: 'İki Yıl Sonra', slug: 'return-sabaody-01', duration: '24:30', summary: 'Mürettebat tek tek Sabaody\'ye gelir. Herkes değişmiş ve güçlenmiştir. Luffy daha olgun, Zoro bir gözü kapalı, Nami saçları uzamış, Franky devasa robotik bir gövde kazanmış. Sahte Hasır Şapkalar sorun çıkarır.' },
      { number: 2, title: 'Yeni Başlangıçların Adası', slug: 'return-sabaody-02', duration: '24:30', summary: 'Luffy, Haoshoku Haki ile sahte Luffy\'yi ve adamlarını bayıltır. Zoro, tek kılıçla gemiyi ikiye böler. Sanji, Skywalk ile havada yürür. Her mürettebat üyesi 2 yılın meyvelerini gösterir.' },
      { number: 3, title: 'Dal, Dal, Dal!', slug: 'return-sabaody-03', duration: '24:30', summary: 'Sentoumaru ve Pacifista\'lar gelir ama Luffy, 2 yıl önce zorluk çektiği Pacifista\'yı Haki yumruğuyla tek hamlede yok eder. Thousand Sunny, Rayleigh\'in kaplamasıyla denizin altına dalış yapar. Fish-Man Island\'a doğru!' },
    ],
  },
  {
    name: 'Fish-Man Island',
    slug: 'fish-man-island',
    saga: 'fish-man-island',
    cover: '/arcs/fish-man-island.jpg',
    episodeCount: 24,
    summary: '10.000 metre derinlikteki Fish-Man Island\'da ırkçılık ve ayrımcılık temaları işlenir. Luffy, Yeni Dünya\'daki ilk gerçek testini geçer.',
    detailedSummary: 'Denizin 10.000 metre altındaki Fish-Man Island, Balık-Adamlar ve Deniz Kızlarının vatanıdır. Ada, Beyaz Sakal\'ın koruması altındaydı ama ölümünden sonra tehlikeye girmiştir. Big Mom şimdi koruyucudur ama karşılığında şeker istemektedir. Prenses Shirahoshi, devasa bir deniz kızıdır ve antik silah Poseidon\'un ta kendisidir. Hody Jones, insanlara karşı nefret dolu bir Balık-Adam milliyetçisidir. İlginç olan, Hody\'nin insanlardan hiç kötülük görmemiş olmasıdır — nefreti tamamen öğretilmiştir. Bu, ırkçılığın nasıl nesilden nesile aktarıldığının güçlü bir alegorisidir. Fisher Tiger\'ın hikayesi ve Otohime Kraliçe\'nin barış çabaları anlatılır. Luffy, Hody\'yi Gear 2 ve Busoshoku Haki ile yener. Ada, artık Luffy\'nin koruması altındadır — Big Mom\'a karşı. Luffy, Big Mom\'u arayarak "Fish-Man Island benim bölgem!" diye ilan eder.',
    keyEvents: [
      'Fish-Man Island\'a ulaşış',
      'Shirahoshi — Antik Silah Poseidon',
      'Hody Jones\'un ırkçı isyanı',
      'Fisher Tiger ve Otohime\'nin hikayeleri',
      'Luffy Hody\'yi yener',
      'Luffy Fish-Man Island\'ı sahiplenir',
      'Big Mom\'a meydan okuma',
    ],
    themes: ['Irkçılık ve Ayrımcılık', 'Nefretin Nesiller Arası Aktarımı', 'Barış ve Hoşgörü', 'Miras ve Koruma'],
    location: 'Fish-Man Island (10.000m derinlik)',
    villain: 'Hody Jones',
    characters: ['luffy', 'jinbe'],
    episodes: [
      { number: 1, title: 'Derinliklere Doğru!', slug: 'fish-man-island-01', duration: '24:30', summary: 'Mürettebat, Thousand Sunny ile denizin derinliklerine dalış yapar. 10.000 metre derinliğe inerken tehlikeli akıntılar ve devasa deniz canavarlarıyla karşılaşır. Yeni Dünya\'ya giden yol denizin altından geçmektedir.' },
      { number: 2, title: 'Okyanusun Derinliklerinde Macera!', slug: 'fish-man-island-02', duration: '24:30', summary: 'Devasa bir Kraken yollarını keser. Luffy, Zoro ve Sanji denizin altında savaşmak zorunda kalır. Luffy, Kraken\'i evcilleştirmeye karar verir ve ona Surume adını verir. Mürettebat, Kraken\'in yardımıyla yolculuğa devam eder.' },
      { number: 3, title: 'Balık Adam Adası\'na Varış!', slug: 'fish-man-island-03', duration: '24:30', summary: 'Mürettebat, dev bir balon içinde korunan muhteşem sualtı şehri Fish-Man Island\'a ulaşır. Deniz Kızları ve Balık-Adamların vatanı olan bu yer, renkli mercan yapıları ve biyolüminesan ışıklarla aydınlanmaktadır. Ancak mürettebat dağılır ve farklı bölgelere düşer.' },
      { number: 4, title: 'Burun Kanaması ve Çarpıcı Kehanet!', slug: 'fish-man-island-04', duration: '24:30', summary: 'Luffy, Ryugu Sarayı\'na girer ve devasa deniz kızı Prenses Shirahoshi ile tanışır. Shirahoshi, 10 yıldır odasına kapatılmıştır çünkü Vander Decken onu takip etmektedir. Shirahoshi\'nin gözyaşları ve yalnızlığı Luffy\'yi etkiler.' },
      { number: 5, title: 'Balık Adam Adası\'nın Kralı', slug: 'fish-man-island-05', duration: '24:30', summary: 'Vander Decken IX, Mato Mato no Mi meyvesinin gücüyle Shirahoshi\'ye sürekli silahlar fırlatmaktadır. Luffy, Shirahoshi\'yi Megalo\'nun içine saklayarak saraydan kaçırır. Shirahoshi, ilk kez dış dünyayı görür ve annesinin mezarını ziyaret etmek ister.' },
      { number: 6, title: 'Koukaku Kulesi\'ndeki Deniz Kızı Prenses', slug: 'fish-man-island-06', duration: '24:30', summary: 'Hody Jones, insanlara karşı derin bir nefretle dolu Balık-Adam milliyetçisidir. Energy Steroid ilacıyla kendini ve tayfasını güçlendirmektedir. Yeni Balık-Adam Korsanları\'nın amacı, insanlarla tüm bağları koparmak ve Balık-Adamların üstünlüğünü ilan etmektir.' },
      { number: 7, title: 'Mato Mato Laneti', slug: 'fish-man-island-07', duration: '24:30', summary: 'Hody Jones ve adamları Ryugu Sarayı\'nı basarak Kral Neptune\'ü ve prenslerini esir alır. Zoro, Usopp ve Brook da sarayda yakalanır. Hody, krallığı devirmeyi ve insanlığa savaş açmayı planlamaktadır.' },
      { number: 8, title: 'İntikam Planının Başlangıcı!', slug: 'fish-man-island-08', duration: '24:30', summary: 'Hody Jones, Gyoncorde Meydanı\'nda halka darbesini ilan edecektir. Kral Neptune\'ün idamını planlar. Nami, insanlara karşı nefret propagandası yapıldığını görür. Decken ve Hody ittifak kurarak adanın kontrolünü ele geçirmeye çalışır.' },
      { number: 9, title: 'Deniz Ormanı\'nda', slug: 'fish-man-island-09', duration: '24:30', summary: 'Fisher Tiger\'ın hikayesi anlatılır: Celestial Dragon\'ların kölesi olarak Mariejois\'da yıllarca acı çekmiş, ardından kaçarak Mariejois\'a tırmanmış ve tüm köleleri — insan dahil — serbest bırakmıştır. Güneş Korsanları\'nı kurarak köle damgalarını güneş sembolüyle örtmüştür.' },
      { number: 10, title: 'Otohime, Fisher Tiger ve Güneş Korsanları', slug: 'fish-man-island-10', duration: '24:30', summary: 'Fisher Tiger, bir savaşta ağır yaralanır. Hayatını kurtarmak için insan kanına ihtiyacı vardır ama yılların acısıyla insan kanını kabul edemez. Son nefesinde "nefreti bir sonraki nesle aktarmayın" vasiyetini bırakır. Jinbe, kaptanının ölümüne tanık olur.' },
      { number: 11, title: 'Tiger\'ın Şok Edici Sırrı!', slug: 'fish-man-island-11', duration: '24:30', summary: 'Kraliçe Otohime, insanlarla barış içinde yaşamak için yıllarca mücadele etmiştir. Yüzey dünyasına göç imza kampanyası düzenlemiş ve halkı ikna etmeye çalışmıştır. Bir Celestial Dragon\'ın gemisi adaya geldiğinde bile barışçıl yaklaşımını sürdürmüştür.' },
      { number: 12, title: 'Geleceği Mühürleyen Kurşun', slug: 'fish-man-island-12', duration: '24:30', summary: 'Otohime sonunda yeterli imzayı toplar ama toplanan imzalar ateşe verilir ve Otohime suikaste kurban gider. Katil, Hody Jones\'tur — ama bunu yıllar sonra öğrenilecektir. Otohime\'nin son sözleri çocuklarına: "İnsanlardan nefret etmeyin." Güneş Korsanları\'nın parçalanması ve Jinbe\'nin Shichibukai olması anlatılır.' },
      { number: 13, title: 'Luffy, Jinbe\'ye Karşı!', slug: 'fish-man-island-13', duration: '24:30', summary: 'Hody Jones, Gyoncorde Meydanı\'nda darbesini ilan eder. Kral Neptune\'ü idam etmeye hazırlanır. Energy Steroidlerle güçlenmiş 100.000 kişilik bir ordu toplamıştır. Luffy ve mürettebat, adayı kurtarmak için harekete geçer.' },
      { number: 14, title: 'Gyoncorde Meydanı Toplanması!', slug: 'fish-man-island-14', duration: '24:30', summary: 'Jinbe, Luffy\'nin yanında savaşmak için gelir. Luffy\'ye Hody\'yi yenmesini ama Fish-Man Island\'ın kahramanı olmamasını öğütler — çünkü bir insanın Balık-Adamları kurtarması nefret döngüsünü kırmaz. Jinbe\'nin planı, halkın kendi kurtarıcıları olmasıdır.' },
      { number: 15, title: 'Hody\'nin Karanlık Sırrı!', slug: 'fish-man-island-15', duration: '24:30', summary: 'Luffy, Haoshoku Haki ile Hody\'nin 100.000 kişilik ordusunun yarısını tek bakışla bayıltır. Mürettebatın her üyesi kendi rakibini seçer. Devasa bir meydan savaşı başlar — Hasır Şapkalar\'ın 2 yıllık eğitiminin gerçek sınavı.' },
      { number: 16, title: '100,000\'e Karşı 10!', slug: 'fish-man-island-16', duration: '24:30', summary: 'Zoro, zehirli kılıç ustası Hyouzou ile karşılaşır. Hyouzou, Energy Steroidlerle güçlenmiş olmasına rağmen Zoro\'nun Busoshoku Haki\'si karşısında şansı yoktur. Zoro, tek hamleyle savaşı bitirir — 2 yıllık eğitiminin meyvesi açıkça görülür.' },
      { number: 17, title: 'Balık Adam Adası\'nın Yok Oluş Krizi', slug: 'fish-man-island-17', duration: '24:30', summary: 'Sanji, Wadatsumi\'ye karşı Diable Jambe ile savaşır. Franky, Shogun modunu açar. Robin, klonlarıyla düşmanları alt eder. Chopper, Monster Point\'i kontrollü kullanır. Brook, ruhunu bedeninden ayırarak savaşır. Her mürettebat üyesi yeni yeteneklerini sergiler.' },
      { number: 18, title: 'Her Şeyi Koruyacağım!', slug: 'fish-man-island-18', duration: '24:30', summary: 'Luffy, Hody Jones ile savaşmaya başlar. Hody, Energy Steroidlerle sürekli güçlenmektedir ama Luffy\'nin Busoshoku Haki\'si her saldırısını etkisiz kılar. Suyun altında bile Luffy üstünlüğünü korur. Hody\'nin nefreti onu körleştirmektedir.' },
      { number: 19, title: 'Nesin Sen?', slug: 'fish-man-island-19', duration: '24:30', summary: 'Luffy, Gear 2 ve Gear 3 kombinasyonuyla Hody\'ye ağır darbeler indirir. Hody itiraf eder: insanlardan hiçbir kötülük görmemiştir, nefreti tamamen öğretilmiştir. Bu itiraf, ırkçılığın boş ve temelsiz doğasını gözler önüne serer. Luffy, Red Hawk ile Hody\'yi yener.' },
      { number: 20, title: 'Hayali', slug: 'fish-man-island-20', duration: '24:30', summary: 'Vander Decken, devasa gemi Noah\'ı Fish-Man Island\'a doğru fırlatır. Adayı tamamen yok edecek büyüklüktedir. Luffy, Noah\'ı durdurmak için tek başına gemiye çıkar ve Elephant Gun ile parçalamaya çalışır. Ama gemiyi yok etmek Joy Boy\'un mirasını da yok etmek demektir.' },
      { number: 21, title: 'Ölüm de Bir İntikamdır', slug: 'fish-man-island-21', duration: '24:30', summary: 'Shirahoshi, bilinçsizce Deniz Krallarını çağırır. Devasa yaratıklar Noah\'ı durdurur ve adayı kurtarır. Robin, Poneglyph\'i okuyarak şok edici gerçeği öğrenir: Shirahoshi, antik silah Poseidon\'un ta kendisidir. Joy Boy ve antik anlaşma hakkında ipuçları ortaya çıkar.' },
      { number: 22, title: 'Güneşe Çıkan Yol', slug: 'fish-man-island-22', duration: '24:30', summary: 'Hody Jones ve Yeni Balık-Adam Korsanları tamamen yenilir. Luffy ağır yaralıdır ve kan kaybetmektedir. Fish-Man Island halkı, yüzyıllık yasağı çiğneyerek Luffy\'ye kan bağışı yapar — Fisher Tiger\'ın aksine. Irklar arası barışın en güçlü sembolik anı. Jinbe gözyaşlarına boğulur.' },
      { number: 23, title: 'Yeni Dünya\'dan Gelen Ses', slug: 'fish-man-island-23', duration: '24:30', summary: 'Luffy, Jinbe\'yi mürettebata katılmaya davet eder ama Jinbe henüz yapması gereken işler olduğunu söyler — Big Mom ile bağını koparması gerekmektedir. "İşlerimi bitirdiğimde kesinlikle katılacağım" sözünü verir. Ada, artık Luffy\'nin koruması altındadır.' },
      { number: 24, title: 'Kahramanın Şapkası', slug: 'fish-man-island-24', duration: '24:30', summary: 'Mürettebat Fish-Man Island\'dan ayrılmaya hazırlanır. Luffy, Den Den Mushi ile Big Mom\'u arar: "Fish-Man Island benim bölgem! Kavgayı istiyorsan gel!" Bir Yonko\'ya meydan okuma! Thousand Sunny yüzeye çıkar ve güneş 2 yıl sonra ilk kez yüzlerine vurur. Yeni Dünya\'ya adım atılır.' },
    ],
  },
]
