import type { Arc } from '@/types'

export const FOUR_EMPERORS_ARCS: Arc[] = [
  {
    name: 'Zou',
    slug: 'zou',
    saga: 'four-emperors',
    cover: '/arcs/zou.jpg',
    episodeCount: 10,
    summary: 'Dev bir filin sırtında yaşayan Mink kabilesi. Road Poneglyph\'lerin sırrı ve Kaido ile Big Mom tehlikesi ortaya çıkar.',
    detailedSummary: '1000 yıldır okyanusta yürüyen dev fil Zunisha\'nın sırtında yaşayan Mink kabilesi. Minkler, insan-hayvan melezi savaşçılardır ve Electro tekniğini kullanırlar. Jack — Kaido\'nun sağ kolu — Minklere saldırmış ve adayı harap etmiştir. Raizo\'yu aramaktadır. "Raizo güvendedir!" açıklaması Minklerin fedakarlığını gösterir. Sanji, Big Mom\'un kızı Pudding ile zorla evlendirilmek üzere kaçırılmıştır. Road Poneglyph\'ler keşfedilir — One Piece\'e ulaşmak için 4 Road Poneglyph gereklidir. Biri Zou\'da, biri Big Mom\'da, biri Kaido\'da, dördüncüsü kayıptır. Kozuki Momonosuke ve Kinemon\'un Wano\'dan geldiği ortaya çıkar. Plan: bir grup Sanji\'yi kurtarmak için Whole Cake Island\'a, diğeri Wano\'ya gidecektir.',
    keyEvents: [
      'Mink kabilesi ve Zunisha',
      'Jack\'in saldırısı',
      'Raizo\'nun güvende olması',
      'Road Poneglyph\'lerin keşfi',
      'Sanji\'nin kaçırılması',
      'Kozuki ailesi ve Wano bağlantısı',
      'Mürettebatın ikiye ayrılması',
    ],
    themes: ['Sadakat ve Fedakarlık', 'Dünya Tarihi', 'Aile Zorunlulukları'],
    location: 'Zou (Zunisha\'nın sırtı)',
    villain: 'Jack',
    characters: ['luffy', 'zoro', 'law', 'sanji', 'carrot'],
    episodes: [
      { number: 1, title: 'Zou', slug: 'zou-01', duration: '24:30', summary: 'Mürettebat, 1000 yıldır yürüyen dev fil Zunisha\'nın sırtındaki Zou adasına ulaşır. Mink kabilesi — insan-hayvan melezleri — burada yaşamaktadır. Ada harap haldedir.' },
      { number: 2, title: 'Mink Kabilesi', slug: 'zou-02', duration: '24:30', summary: 'Minklerin Electro savaş tekniği ve kültürleri tanıtılır. İnek Mink Wanda ve köpek Mink Carrot mürettebatı karşılar. Nami grubu daha önce gelmiş ve Minklere yardım etmiştir.' },
      { number: 3, title: 'Sağ Böğür Kalesi', slug: 'zou-03', duration: '24:30', summary: 'Kaido\'nun sağ kolu Jack, Minklere saldırmıştır. Caesar\'ın zehirli gazını kullanarak adayı harap etmiştir. Minkler, büyük kayıplar vererek direnmiştir. Sanji onları kurtarmış ama sonra kaybolmuştur.' },
      { number: 4, title: 'Dük Inuarashi ve Efendi Nekomamushi', slug: 'zou-04', duration: '24:30', summary: 'Jack\'in aradığı ninja Raizo, Minkler tarafından saklanmıştır. Tüm adayı yok etme pahasına Raizo\'yu teslim etmemişlerdir. "Raizo güvendedir!" — Minklerin fedakarlığının kanıtı.' },
      { number: 5, title: 'Kıvırcık Şapka Korsanları Yetişir', slug: 'zou-05', duration: '24:30', summary: 'Robin, Zou\'daki Road Poneglyph\'i okur. One Piece\'e ulaşmak için 4 Road Poneglyph gereklidir. Her biri bir koordinat verir — dördü birleşince Laugh Tale\'in konumu ortaya çıkar.' },
      { number: 6, title: 'Çay Partisi Davetiyesi', slug: 'zou-06', duration: '24:30', summary: 'Sanji\'nin Big Mom\'un kızı Charlotte Pudding ile zorla evlendirilmek üzere Whole Cake Island\'a götürüldüğü ortaya çıkar. Sanji\'nin asıl soy adı Vinsmoke\'dur — Germa 66 krallık ailesinin prensesidir.' },
      { number: 7, title: 'Nekomamushi Efendi\'yi Görmeye Gidelim!', slug: 'zou-07', duration: '24:30', summary: 'Momonosuke ve Kinemon\'un Wano Ülkesi\'nden geldikleri ortaya çıkar. Kozuki ailesi, Poneglyph\'leri oluşturan taş işçileridir. Wano, Kaido tarafından 20 yıldır işgal edilmektedir.' },
      { number: 8, title: 'Sis Raizo', slug: 'zou-08', duration: '24:30', summary: 'Plan belirlenir: Luffy, Nami, Chopper ve Brook Sanji\'yi kurtarmak için Whole Cake Island\'a; Zoro, Law ve diğerleri Wano\'ya gidecektir. Carrot gizlice gemiye biner. İki paralel macera başlar.' },
      { number: 9, title: 'Kozuki Ailesi\'nin Varisi Momonosuke', slug: 'zou-09', duration: '24:30', summary: 'Mink kültürü derinlemesine incelenir. Inuarashi gündüz, Nekomamushi gece hüküm sürer — ikisi arasındaki çatışma Oden\'in ölümünden bu yana sürmektedir. Zou\'nun antik tarihi ve Minklerin savaşçı gelenekleri anlatılır.' },
      { number: 10, title: 'Anlaşıldı', slug: 'zou-10', duration: '24:30', summary: 'Ninja-Korsan-Mink-Samuray İttifakı resmen kurulur. Luffy, Law, Inuarashi, Nekomamushi, Kinemon ve Momonosuke el ele vererek Kaido\'yu devirme yemini eder. Wano\'yu kurtarma operasyonunun temelleri atılır.' },
    ],
  },
  {
    name: 'Whole Cake Island',
    slug: 'whole-cake-island',
    saga: 'four-emperors',
    cover: '/arcs/whole-cake-island.jpg',
    episodeCount: 39,
    summary: 'Sanji\'yi kurtarma operasyonu. Yonko Big Mom\'un tatlılardan yapılmış çılgın krallığında hayatta kalma mücadelesi.',
    detailedSummary: 'Luffy ve küçük bir ekip, Sanji\'yi kurtarmak için Yonko Big Mom\'un bölgesine girer. Whole Cake Island, tatlılardan yapılmış bir çılgınlık diyarıdır — ağaçlar, evler, hatta zemin bile yenilebilir. Big Mom\'un Soru Soru meyvesiyle canlılara can verdiği Homie\'ler her yerdedir. Sanji\'nin geçmişi tam olarak ortaya çıkar: Vinsmoke ailesi tarafından başarısız sayılıp dışlanmış, aşçılığı "zayıflık" olarak görülmüştür. Babası Judge, Sanji\'yi duygusuz bir silaha dönüştürmek istemiştir. Sanji, ailesinden nefret eder ama yine de onları korur — çünkü Zeff ona "gerçek bir beyefendi asla bir kadına vurmaz, hiç kimseyi aç bırakmaz" diye öğretmiştir. Luffy, Sanji\'yi bulmak için her şeyi göze alır. Sanji, Luffy\'yi yumruklar ve gitmesini söyler ama Luffy yerinden kıpırdamaz: "Senin yemeklerin olmadan Korsanlar Kralı olamam!" Pedro kendini feda eder. Carrot Sulong formuna girer. Luffy, Katakuri ile Gear 4 Snake Man kullanarak epik bir savaş yapar. Mürettebat son anda kaçar.',
    keyEvents: [
      'Big Mom\'un tatlı imparatorluğu',
      'Sanji\'nin Vinsmoke geçmişi',
      'Luffy ve Sanji\'nin yeniden birleşmesi',
      'Pedro\'nun fedakarlığı',
      'Carrot Sulong formu',
      'Luffy vs Katakuri — Gelecek Görüşü',
      'Big Mom\'dan kaçış',
      'Jinbe resmi olarak katılır',
    ],
    themes: ['Aile ve Ret', 'Yemek ve Sevgi', 'Asla Vazgeçmemek', 'Gelecek Görüşü'],
    location: 'Whole Cake Island (Totto Land)',
    villain: 'Big Mom, Katakuri',
    characters: ['luffy', 'nami', 'sanji', 'chopper', 'brook', 'jinbe', 'carrot', 'bigmom'],
    episodes: [
      { number: 1, title: 'Dünya Hareketleniyor', slug: 'wci-01', duration: '24:30', summary: 'Luffy, Nami, Chopper, Brook ve Carrot, Sanji\'yi kurtarmak için Totto Land\'a doğru yola çıkar. Pekoms rehberlik eder. Yolda Big Mom\'un bölgesinin tehlikeleri ile ilk kez karşılaşırlar.' },
      { number: 2, title: '0 ve 4', slug: 'wci-02', duration: '24:30', summary: 'Mürettebat, tatlılardan yapılmış Totto Land\'a girer. Her şey yenilebilir — ağaçlar, evler, zemin. Big Mom\'un Soru Soru meyvesiyle canlılara can verdiği Homie\'ler her yerdedir.' },
      { number: 3, title: 'Totto Land', slug: 'wci-03', duration: '24:30', summary: 'Seducing Woods\'da mürettebat tuzağa düşer. Ağaçlar, hayvanlar ve zemin — hepsi Homie\'dir ve mürettebatı yönlendirmeye çalışır. Luffy, ormanın içinde kaybolur ve kendisiyle savaşır.' },
      { number: 4, title: 'Yonko, Charlotte Linlin', slug: 'wci-04', duration: '24:30', summary: 'Sanji\'nin nişanlısı Charlotte Pudding ile tanışılır. Pudding, masum ve sevimli görünür. Sanji\'yi gerçekten sevdiğini söyler ama gerçek niyeti henüz belirsizdir.' },
      { number: 5, title: 'Gizemli Ormanda Macera', slug: 'wci-05', duration: '24:30', summary: 'Sanji\'nin ailesi Vinsmoke\'lar tanıtılır. Babası Judge, Kuzey Deniz\'in savaşçı krallığı Germa 66\'yı yönetir. Sanji\'nin kardeşleri — Ichiji, Niji, Yonji — duygusuz ve acımasız savaş makineleridir.' },
      { number: 6, title: 'Vinsmoke Judge', slug: 'wci-06', duration: '24:30', summary: 'Sanji\'nin acı geçmişi: kardeşleri tarafından dövülmüş, babası tarafından "başarısız" ilan edilip hapsedilmiştir. Sadece annesi Sora ve ablası Reiju onu sevmiştir. Sora, çocuklarının duygusuz olmaması için ilaç almış ve hayatını kaybetmiştir.' },
      { number: 7, title: 'Lola\'nın Vivre Kartı', slug: 'wci-07', duration: '24:30', summary: 'Germa 66\'nın bilim ordusu detaylandırılır. Klonlanmış askerler, Raid Suit teknolojisi ve Judge\'ın dünyayı fethetme planı. Sanji, Germa\'dan kaçarak Baratie\'ye sığınmış ve Zeff tarafından büyütülmüştür.' },
      { number: 8, title: 'Luffy, Komutan Cracker\'a Karşı', slug: 'wci-08', duration: '24:30', summary: 'Sanji, ailesini ve Zeff\'i korumak için düğünü kabul etmek zorunda hisseder. Big Mom, Sanji kaçarsa Baratie\'yi yok etmekle tehdit etmektedir. Sanji, mürettebatını korumak için onlardan uzak durur.' },
      { number: 9, title: 'Demir Maske', slug: 'wci-09', duration: '24:30', summary: 'Charlotte Linlin — Big Mom\'un gerçek gücü gösterilir. Soru Soru meyvesiyle insanların ruhlarından ömür çalır. Prometheus, Zeus ve Napoleon — üç güçlü Homie\'si. Yonko\'nun mutlak hakimiyeti.' },
      { number: 10, title: 'Doğu Mavi\'ye', slug: 'wci-10', duration: '24:30', summary: 'Totto Land\'ın her köşesinde Homie\'ler yaşar. Her ada farklı bir tatlı temasındadır. Big Mom\'un çocukları — 85 çocuk — her adayı yönetir. Charlotte ailesinin devasa yapısı ortaya çıkar.' },
      { number: 11, title: 'Luffy, Sanji\'ye Karşı', slug: 'wci-11', duration: '24:30', summary: 'Luffy, Sanji\'yi bulur ama Sanji mürettebatı korumak için Luffy\'yi yumruklar ve "Git!" der. Luffy karşılık vermez. Sanji\'nin tekmeleri acıtır ama Luffy yerinden kıpırdamaz.' },
      { number: 12, title: 'Öfkeli Ordu', slug: 'wci-12', duration: '24:30', summary: 'Luffy, yağmur altında bekler ve bağırır: "Senin yemeklerin olmadan Korsanlar Kralı olamam!" Sanji çöker ve gerçek duygularını itiraf eder. İkisi birlikte ağlar. Serinin en duygusal anlarından biri.' },
      { number: 13, title: 'Luffy ve Big Mom', slug: 'wci-13', duration: '24:30', summary: 'Luffy, Sanji geri dönene kadar o noktada bekleyeceğine söz verir. Açlıktan ölmek pahasına yerinden kıpırdamaz. "Ben sadece senin elinden yemek yiyeceğim!" — Luffy\'nin Sanji\'ye olan güveni.' },
      { number: 14, title: 'Umut Işığı', slug: 'wci-14', duration: '24:30', summary: 'Pudding\'in üçüncü gözü ve gerçek kişiliği ortaya çıkar. Big Mom\'un düğünde Vinsmoke ailesini öldürme planı ifşa olur. Pudding, Sanji\'yi aldatmak için rol yapmaktadır. Sanji, gerçeği öğrenir.' },
      { number: 15, title: 'Germa\'nın Başarısızlığı', slug: 'wci-15', duration: '24:30', summary: 'Sanji, Luffy\'nin yanına döner ve birlikte plan yaparlar. Mürettebat yeniden birleşir. Big Mom\'u durdurmak ve düğünü sabote etmek için Capone Bege ile gizli ittifak kurulur.' },
      { number: 16, title: 'Burada Değil!', slug: 'wci-16', duration: '24:30', summary: 'Bege\'nin planı: düğün sırasında Mother Carmel\'in fotoğrafını kırmak ve Big Mom\'u şoka sokmak. Bu anda Big Mom savunmasız kalacak ve Caesar\'ın silahıyla vurulacak. Riskli ama tek şans.' },
      { number: 17, title: 'Yalancı', slug: 'wci-17', duration: '24:30', summary: 'Mink savaşçısı Pedro\'nun geçmişi: yıllar önce Big Mom bölgesine gelmiş ve ömründen 50 yıl çaldırılmıştır. Pedro, "Şafak"ın geleceğine inanır ve mürettebatı o şafağa taşıyacak kişiler olarak görür.' },
      { number: 18, title: 'Kale', slug: 'wci-18', duration: '24:30', summary: 'Brook, tek başına Big Mom\'un hazine odasına sızar ve Road Poneglyph\'in kopyasını alır. Big Mom ile savaşır — yenilir ama görevi tamamlar. "Zaten ölüyüm, yohohoho!"' },
      { number: 19, title: 'Yonko Suikast Planı', slug: 'wci-19', duration: '24:30', summary: 'Düğün günü gelir. Herkes pozisyon alır. Sanji, Pudding\'le sunağa yürür. Big Mom\'un çocukları kutlama yapar. Perde arkasında Luffy ve Bege son hazırlıkları tamamlar.' },
      { number: 20, title: 'Mükemmel Oyuncu', slug: 'wci-20', duration: '24:30', summary: 'Jinbe, Big Mom\'a karşı durur ve resmi olarak Hasır Şapkalara katıldığını ilan eder. Big Mom\'un "ömründen yıl çalma" saldırısına karşı korkusuz durur — çünkü Luffy\'nin yanında korkacak bir şey yoktur.' },
      { number: 21, title: 'Onurlu', slug: 'wci-21', duration: '24:30', summary: 'Big Mom\'un çay partisi ve düğün töreni başlar. Tüm Charlotte ailesi, müttefikler ve konuklar meydandadır. Tamatebako kutusu hediye olarak sunulur. Gerilim dorukta.' },
      { number: 22, title: 'Hey, Anne', slug: 'wci-22', duration: '24:30', summary: 'Luffy, dev bir pasta içinden fırlar ve Mother Carmel fotoğrafını kırar. Big Mom çığlık atar — Haoshoku Haki dalgası yayılır. Plan kısmen işe yarar ama Big Mom\'u öldürmek imkansızdır.' },
      { number: 23, title: 'Mutlu Yıllar', slug: 'wci-23', duration: '24:30', summary: 'Big Mom\'un çığlığı her şeyi yerle bir eder. Vinsmoke ailesi suikast girişiminden son anda kurtulur. Sanji, nefret ettiği ailesini bile korur — çünkü Zeff ona "asla kimseyi ölüme terk etme" diye öğretmiştir.' },
      { number: 24, title: 'Kuşatma Altında', slug: 'wci-24', duration: '24:30', summary: 'Düğün mekanı çöker. Bege, "Big Father" formuna girerek herkesi korur. Tamatebako kutusu patlar ve Whole Cake Chateau devrilmeye başlar. Mürettebat dağılır — herkes farklı yönlere kaçar.' },
      { number: 25, title: 'Yardır, Caesar!!', slug: 'wci-25', duration: '24:30', summary: 'Big Mom, düğün pastasının yıkılmasıyla "Hunger Pang" krizine girer. Wedding Cake istiyordur ve onu bulana kadar her şeyi yok edecektir. Kontrolden çıkmış bir Yonko, herkes için tehlikedir.' },
      { number: 26, title: 'Hizmetkarım Ol', slug: 'wci-26', duration: '24:30', summary: 'Oven, Daifuku, Smoothie ve diğer Charlotte çocukları mürettebatın peşine düşer. Her biri güçlü bir şeytan meyvesi kullanıcısıdır. Nami, Zeus\'u ele geçirerek güçlü saldırılar yapar.' },
      { number: 27, title: 'Bir Kadının Gururu', slug: 'wci-27', duration: '24:30', summary: 'Sanji, Big Mom\'u durdurmak için hayatının en iyi düğün pastasını yapmaya karar verir. Pudding ve Chiffon ile birlikte çalışır. Sanji\'nin yemek yeteneği bir Yonko\'yu durdurabilecek tek silahtır.' },
      { number: 28, title: 'Mink Kabilesi Muhafız Şefi Pedro', slug: 'wci-28', duration: '24:30', summary: 'Luffy ve mürettebat, Big Mom\'un bölgesinden kaçmaya çalışırken sürekli savaşır. Brook ve Chopper, Sunny\'yi korur. Big Mom\'un filosu peşlerindedir. Germa 66 beklenmedik şekilde araya girer.' },
      { number: 29, title: 'Kaçma Şansı %0', slug: 'wci-29', duration: '24:30', summary: 'Luffy, Charlotte Katakuri ile Brûlée\'nin ayna dünyasına çekilir. Katakuri — Big Mom\'un en güçlü oğlu — Mochi Mochi meyvesi ve mükemmel Gelecek Görüşü Haki\'siyle Luffy\'den çok üstündür.' },
      { number: 30, title: 'Dalga Odası', slug: 'wci-30', duration: '24:30', summary: 'Katakuri, Luffy\'nin her saldırısını önceden görür ve karşılık verir. Luffy defalarca yenilir ama her seferinde ayağa kalkar. Katakuri, Luffy\'nin iradesine hayret eder.' },
      { number: 31, title: 'Merienda', slug: 'wci-31', duration: '24:30', summary: 'Luffy, savaş sırasında Gelecek Görüşü Haki\'sini geliştirmeye başlar. Katakuri\'nin gizli yüzü ortaya çıkar. İki savaşçı birbirini zorlayarak büyür. Katakuri, Luffy\'ye saygı duymaya başlar.' },
      { number: 32, title: 'Hayatı Yaşamak', slug: 'wci-32', duration: '24:30', summary: 'Luffy, Gear 4\'ün yeni formu Snake Man\'i açığa çıkarır! Yılan gibi kıvrılan, hızlanan ve izlenemez yumruklar. Black Mamba ve King Cobra teknikleriyle Katakuri\'yi zorlar. Epik son çarpışma!' },
      { number: 33, title: 'Dolunay Aslanı', slug: 'wci-33', duration: '24:30', summary: 'Mink savaşçısı Pedro, mürettebatın kaçışı için kendini feda eder. Perospero\'yu durdurmak için bombayla patlar: "Bu gün gelmeli!" Carrot yıkılır. Pedro\'nun mirası mürettebatı ileri taşır.' },
      { number: 34, title: 'Bilinmeyen Mama', slug: 'wci-34', duration: '24:30', summary: 'Carrot, dolunayda Sulong formuna girer — Mink savaşçılarının en güçlü formu. Beyaz, vahşi ve inanılmaz hızlı. Big Mom\'un filosuna tek başına saldırır ve birçok gemiyi devre dışı bırakır.' },
      { number: 35, title: 'Bana Güveniyorlar', slug: 'wci-35', duration: '24:30', summary: 'Epik son darbe: Luffy ve Katakuri birbirlerinin yüzüne yumruk atar. İkisi de yere düşer ama Luffy ayağa kalkar. Katakuri şapkasını Luffy\'nin ağzını örtmek için kullanır — karşılıklı saygı.' },
      { number: 36, title: 'Luffy, Katakuri\'ye Karşı', slug: 'wci-36', duration: '24:30', summary: 'Mürettebat, Big Mom\'un bölgesinden kaçmaya çalışır. Oven, Daifuku ve diğer Charlotte çocukları peşlerindedir. Germa 66 sürpriz bir şekilde yardıma gelir — Sanji\'nin ailesi borçlarını öder.' },
      { number: 37, title: 'Son İstek', slug: 'wci-37', duration: '24:30', summary: 'Sanji\'nin düğün pastası Big Mom\'a ulaşır. Big Mom bir lokma aldığında mutluluktan bayılır ve Hunger Pang krizi sona erer. Sanji\'nin yemek yeteneği bir Yonko\'yu durdurur.' },
      { number: 38, title: 'Kötü Son Müzikali', slug: 'wci-38', duration: '24:30', summary: 'Thousand Sunny, Coup de Burst ile Big Mom\'un bölgesinden fırlar. Son anda kurtulurlar. Mürettebat canını zor kurtarmış ama görevini tamamlamıştır — Sanji geri döndü, Poneglyph kopyası alındı.' },
      { number: 39, title: 'Son Düzlük', slug: 'wci-39', duration: '24:30', summary: 'Dünya çapında haberler: Luffy\'nin Big Mom\'la savaşması onu "Beşinci İmparator" yapar. Ödülü 1.5 milyara çıkar. Sanji, Luffy için özel bir yemek hazırlar. Mürettebat yeniden tamam ve Wano\'ya doğru yola çıkar.' },
    ],
  },
  {
    name: 'Reverie',
    slug: 'reverie',
    saga: 'four-emperors',
    cover: '/arcs/reverie.jpg',
    episodeCount: 3,
    summary: 'Dünya liderlerinin toplandığı Reverie\'de büyük kararlar alınır. Sabo ve Devrimciler sahneye çıkar.',
    detailedSummary: 'Dört yılda bir toplanan dünya liderler konseyi Reverie, Mariejois\'da düzenlenir. 50 ülkenin kralı ve kraliçesi katılır. Vivi, Shirahoshi, Dalton ve diğer tanıdık yüzler sahneye çıkar. Devrimci Ordu komutanları — Sabo, Karasu, Morley, Lindbergh — Celestial Dragonlara karşı harekete geçer. Im-sama — dünya tahtında oturan gizemli figür — ilk kez gösterilir. Dünya Hükümeti\'nin gerçek hükümdarı kimdir? Shichibukai sisteminin kaldırılması oylanır ve kabul edilir. Cobra Nefertari, Void Century hakkında soru sorar. Reverie sonrası dünya çapında büyük olaylar yaşanır: Sabo\'nun "ölümü" haberleri, Vivi\'nin kaybolması, Cobra\'nın ölümü.',
    keyEvents: [
      'Reverie toplantısı',
      'Im-sama ilk kez görülür',
      'Shichibukai sistemi kaldırılır',
      'Devrimcilerin Mariejois saldırısı',
      'Cobra\'nın soruları ve ölümü',
      'Vivi\'nin kaybolması',
    ],
    themes: ['Dünya Siyaseti', 'Gizli Güç', 'Devrim', 'Void Century Sırları'],
    location: 'Mariejois (Reverie)',
    characters: ['vivi', 'sabo', 'shanks'],
    episodes: [
      { number: 1, title: 'Beşinci İmparator', slug: 'reverie-01', duration: '24:30', summary: 'Dünyanın dört bir yanından krallar Reverie için Mariejois\'a toplanır. Vivi, Shirahoshi, Dalton ve Cobra gibi tanıdık yüzler. Dünya liderlerinin kararları milyarlarca insanı etkileyecek.' },
      { number: 2, title: 'Güzel Bir Dünya', slug: 'reverie-02', duration: '24:30', summary: 'Boş tahtın aslında boş olmadığı ortaya çıkar: Im-sama, dünyanın gerçek hükümdarıdır. Gorosei\'nin bile üstünde bir otorite. Luffy, Blackbeard, Shirahoshi ve Vivi\'nin fotoğraflarını inceler.' },
      { number: 3, title: 'Boş Taht', slug: 'reverie-03', duration: '24:30', summary: 'Sabo ve Devrimci Ordu komutanları, Celestial Dragonlara karşı harekete geçer. Shichibukai sistemi kaldırılır. Reverie sonrası şok haberler: Sabo\'nun "ölümü", Cobra\'nın ölümü, Vivi kayıp. Dünya sarsılır.' },
    ],
  },
  {
    name: 'Wano',
    slug: 'wano',
    saga: 'four-emperors',
    cover: '/arcs/wano.jpg',
    episodeCount: 55,
    summary: 'Japonya temalı izole ülke Wano\'da Yonko Kaido\'ya karşı devasa bir savaş. Luffy, Gear 5\'i açığa çıkarır ve Joy Boy\'un mirasını devralır.',
    detailedSummary: 'One Piece\'in en uzun ve en epik arcı. Japonya temalı izole ülke Wano, 20 yıldır Yonko Kaido tarafından işgal edilmektedir. Kaido, Orochi ile birlikte ülkeyi sömürmüş, halkı açlıktan öldürmüş ve SMILE fabrikalarıyla zehirlemiştir. 20 yıl önce Kozuki Oden, Kaido tarafından idam edilmiştir. Oden\'in karısı Toki, Momonosuke ve sadık samuraiları 20 yıl ileriye göndermiştir. Şimdi intikam zamanıdır. Dev ittifak: Hasır Şapkalar, Heart Korsanları, Kid Korsanları, Mink kabilesi, Wano samuraiları — hepsi Onigashima\'da Kaido\'ya karşı savaşır. Kaido ve Big Mom ittifak kurmuştur! Zoro, Enma kılıcını edinir. Sanji, Germa modifikasyonunun uyanmasıyla dış iskelet kazanır. Luffy, Kaido ile çatıda savaşırken yenilir ve "ölür" — ama Gomu Gomu meyvesinin gerçek adı ortaya çıkar: Hito Hito no Mi, Model: Nika. Luffy, Joy Boy olarak uyanır ve Gear 5\'i aktive eder! Tüm kuralları yıkan, çizgi film fiziğiyle savaşan, gülümseyen bir tanrı. Luffy, Kaido\'yu yener. Wano özgürdür. Momonosuke yeni Shogun olur.',
    keyEvents: [
      'Wano\'nun 20 yıllık işgali',
      'Kozuki Oden\'in hikayesi ve idamı',
      'Onigashima savaşı — en büyük savaş',
      'Kaido-Big Mom ittifakı',
      'Zoro Enma kılıcını alır, Haoshoku Haki',
      'Sanji Germa uyanışı',
      'Luffy "ölür" ve Joy Boy olarak uyanır',
      'Gear 5 — Hito Hito no Mi Model Nika',
      'Luffy vs Kaido final',
      'Wano özgürlüğü',
    ],
    themes: ['Japonya Kültürü ve Samuray Onuru', 'Tiranlık ve Devrim', 'Miras ve Nesiller', 'Özgürlük ve Gülüş', 'Tanrı ve İnsan'],
    location: 'Wano Ülkesi (Kuri, Onigashima)',
    villain: 'Kaido, Orochi',
    characters: ['luffy', 'zoro', 'law', 'kid', 'kaido', 'yamato', 'bigmom'],
    episodes: [
      { number: 1, title: 'Wano\'ya Doğru', slug: 'wano-01', duration: '24:30', summary: 'Luffy, izole ülke Wano\'ya ulaşır. Japonya temalı mimari, samuraylar ve geleneksel kıyafetler. İlk gördüğü: açlıktan ölen halk ve zehirlenmiş nehirler. Kaido\'nun zulmü her yerdedir.' },
      { number: 2, title: 'Seppuku', slug: 'wano-02', duration: '24:30', summary: 'Luffy, küçük kız Tama ile tanışır. Tama, açlıktan ölmek üzeredir. Ace\'in eski bir sözünü hatırlar: "Herkesin karnının doyduğu bir Wano yaratacağım." Luffy, Ace\'in sözünü yerine getirmeye karar verir.' },
      { number: 3, title: 'Amigasa Köyü', slug: 'wano-03', duration: '24:30', summary: 'Mürettebat, Wano\'da gizli kimliklerle yaşamaktadır. Zoro "Zorojuro" samurai, Usopp "Usohachi" tüccar, Robin "O-Robi" geyşa olarak. Kinemon\'un planına göre Onigashima savaşına hazırlanıyorlar.' },
      { number: 4, title: 'Tsuru İyiliği Geri Ödüyor', slug: 'wano-04', duration: '24:30', summary: 'Luffy ve Zoro, Bakura kasabasına gider. Kaido\'nun adamları halkı ezmektedir. Hawkins ile karşılaşırlar. Luffy, SMILE meyveleri hakkında öğrenir — başarısız olanlar sadece gülmek zorunda kalır.' },
      { number: 5, title: 'Okobore Kasabası', slug: 'wano-05', duration: '24:30', summary: 'Haydut lideri Shutenmaru (Ashura Doji) tanıtılır — eski Kızıl Kın üyelerinden. Kinemon onu ittifaka katılmaya ikna etmeye çalışır. Jack Wano\'ya saldırır ve Shutenmaru ile çatışır.' },
      { number: 6, title: 'Wano\'nun Büyük Sumo Turnuvası', slug: 'wano-06', duration: '24:30', summary: 'Luffy, Kaido ile ilk kez karşılaşır. Kaido, ejderha formunda gökyüzünden iner. Luffy, tüm gücüyle Gear 3 saldırısı yapar ama Kaido tek darbeyle Luffy\'yi bayıltır. Güç farkı devasa.' },
      { number: 7, title: 'Değerli Erzak Gemisi', slug: 'wano-07', duration: '24:30', summary: 'Luffy, Udon\'daki işçi kampına hapsedilir. Burada yaşlı Hyogoro ile tanışır. Deniz taşı kelepçelerle ağır işçilik yaptırılır. Kid de hapishanededir — ikisi arasında rekabet başlar.' },
      { number: 8, title: 'Oden Kalesi\'nin Kalıntıları', slug: 'wano-08', duration: '24:30', summary: 'Luffy, Hyogoro\'dan Busoshoku Haki\'nin ileri seviyesini — Ryuo — öğrenmeye başlar. Haki\'yi vücudundan dışarı akıtarak düşmana içeriden zarar verme tekniği. Kaido\'nun sert derisini delmenin tek yolu.' },
      { number: 9, title: 'Oden\'i Seviyorum', slug: 'wano-09', duration: '24:30', summary: 'Robin, Orochi\'nin sarayına sızar ve istihbarat toplar. Nami, Shinobu ile birlikte çalışır. Wano\'nun altında gizli silah fabrikaları ve SMILE üretim tesisleri keşfedilir.' },
      { number: 10, title: 'Shutenmaru', slug: 'wano-10', duration: '24:30', summary: 'Neşeli yaşlı adam Tonoyasu (Yasuie), Ebisu kasabasının sevilen lideridir. Aslında eski Daimyo Shimotsuki Yasuie\'dir. SMILE meyvesinin lanetini taşıyan halk sadece gülebilir — ağlayamazlar.' },
      { number: 11, title: 'İmparator Kaido, Luffy\'ye Karşı', slug: 'wano-11', duration: '24:30', summary: 'Orochi, Yasuie\'yi idam eder. Yasuie, ölmeden önce isyan planının şifresini değiştirerek ittifakı kurtarır. Halk gülerken ağlar — SMILE\'ın laneti yüzünden acılarını gösteremezler. Zoro öfkeyle titrer.' },
      { number: 12, title: 'Ha', slug: 'wano-12', duration: '24:30', summary: 'Sanji, Nami, Shinobu ve Robin, Orochi\'nin hamamında gizli bilgi toplarken yakalanırlar. Drake ve Hawkins müdahale eder. Sanji\'nin görünmezlik Raid Suit\'i ilk kez kullanılır.' },
      { number: 13, title: 'Boşluk', slug: 'wano-13', duration: '24:30', summary: 'Big Mom, Wano\'ya gelir! Şelaleden düşerek hafızasını kaybeder ve "O-Lin" olarak Tama ile arkadaş olur. Udon hapishanesinde Queen ile karşılaşır ve hapishanenin altını üstüne getirir.' },
      { number: 14, title: 'Kamuro Otoko', slug: 'wano-14', duration: '24:30', summary: 'Luffy ve Kid, Udon hapishanesinde isyan başlatır. Big Mom\'un karışmasıyla kaos çıkar. Luffy, Ryuo\'yu ilk kez başarıyla kullanır. Mahkumlar serbest kalır ve ittifaka katılır.' },
      { number: 15, title: 'Oiran Komurasaki Sahne Alıyor', slug: 'wano-15', duration: '24:30', summary: 'Zoro, Hiyori\'den Kozuki Oden\'in efsanevi kılıcı Enma\'yı alır. Shusui\'yi Wano\'ya geri verir. Enma, kullanıcısının Haki\'sini zorla çeker — kontrol etmek son derece zordur ama gücü muazzamdır.' },
      { number: 16, title: 'Soba Maskesi', slug: 'wano-16', duration: '24:30', summary: 'Kinemon, tüm müttefikleri bir araya toplar. Kızıl Kınlar, Minkler, korsanlar ve samuraylar. Kanjuro\'nun hain olduğu henüz bilinmemektedir. Savaş planı son haline getirilir.' },
      { number: 17, title: 'Şogun ve Oiran', slug: 'wano-17', duration: '24:30', summary: 'Kozuki Oden\'in hikayesi başlar. Gençliğinde asi, güçlü ve özgür ruhlu bir savaşçıydı. Wano\'nun kurallarını yıkmış, Kuri bölgesini haydutlardan temizleyerek Daimyo olmuştur.' },
      { number: 18, title: 'Çiçek Hyogoro', slug: 'wano-18', duration: '24:30', summary: 'Oden, Beyaz Sakal ile tanışır ve mürettebatına katılır. Denizleri keşfeder, Toki ile evlenir. Momonosuke ve Hiyori dünyaya gelir. Oden\'in macera ruhu onu sürekli ileri iter.' },
      { number: 19, title: 'Soyguncu Köprüsü\'ndeki Gyukimaru', slug: 'wano-19', duration: '24:30', summary: 'Oden, Roger\'ın mürettebatına geçer ve son yolculuğa çıkar. Lodestar\'dan sonra Roger, Poneglyph\'leri takip ederek son adaya ulaşır. Laugh Tale — One Piece\'i gördüler ve güldüler.' },
      { number: 20, title: 'Kadının Sırrı', slug: 'wano-20', duration: '24:30', summary: 'Roger: "Joy Boy, biz 800 yıl erken geldik." Oden, Wano\'nun sınırlarını açma görevini üstlenir ve geri döner. Ancak Wano\'da Orochi iktidarı ele geçirmiş ve Kaido ile ittifak kurmuştur.' },
      { number: 21, title: 'İsyan Kıvılcımları', slug: 'wano-21', duration: '24:30', summary: 'Oden, Kaido\'ya karşı savaşır. İki kılıcıyla — Enma ve Ame no Habakiri — Kaido\'yu yaralar. Ancak Orochi\'nin hilesiyle — rehineler kullanılarak — bir anlık dikkatsizlikte yenilir.' },
      { number: 22, title: 'Hakumai\'nin Daimyosu, Shimotsuki Yasuie', slug: 'wano-22', duration: '24:30', summary: 'Oden\'in idamı: kaynar yağda pişirilir. 9 sadık samuraisını — Kızıl Kınlar — sırtında taşıyarak 1 saat dayandı. "Wano\'nun sınırlarını açın!" vasiyetiyle öldü. Toki, çocukları ve samuraiları 20 yıl ileriye gönderir.' },
      { number: 23, title: 'GÜLÜCÜK', slug: 'wano-23', duration: '24:30', summary: 'Şok gerçek: Kanjuro, başından beri Orochi\'nin casusu olmuştur. Kurozumi klanından gelen Kanjuro, tüm planları sızdırmıştır. Saldırı planı tehlikeye girer — müttefikler limanda bekler ama gemiler yok edilmiştir.' },
      { number: 24, title: 'Olin', slug: 'wano-24', duration: '24:30', summary: 'Her şeye rağmen ittifak yola çıkar. Fırtınalı denizde Onigashima\'ya doğru ilerlerler. Kinemon liderlik eder. Jinbe, tam zamanında gelir ve mürettebata katılır. Dümenci olarak Sunny\'nin başına geçer.' },
      { number: 25, title: 'Queen, Olin\'e Karşı', slug: 'wano-25', duration: '24:30', summary: 'Dev ittifak ordusu Onigashima\'ya çıkar. Kaido\'nun 30.000 kişilik Hayvan Korsanları karşılarındadır. Kaido ve Big Mom ittifak kurmuştur — iki Yonko birden! En büyük savaş başlıyor.' },
      { number: 26, title: 'Mumya', slug: 'wano-26', duration: '24:30', summary: 'Kaido, Big Mom ile birlikte "Yeni Onigashima Projesi"ni ilan eder: Wano\'yu kalıcı silah fabrikasına dönüştürmek. Orochi\'yi öldürür — artık işine yaramıyor. Momonosuke\'yi idam etmekle tehdit eder.' },
      { number: 27, title: 'Savaşçıların Hayali', slug: 'wano-27', duration: '24:30', summary: 'Kaido\'nun kızı Yamato, Luffy ile karşılaşır. Oden\'e olan hayranlığından kendini Oden olarak tanıtır. Oden\'in günlüğünü okumuş ve Joy Boy\'un geleceğini bilmektedir. Babasına karşı savaşır.' },
      { number: 28, title: 'Hidret', slug: 'wano-28', duration: '24:30', summary: 'Tama\'nın Kibi Kibi meyvesinden ürettiği Kibi Dango, SMILE kullanıcılarını kontrol edebilir. Düşman ordusunun bir kısmı taraf değiştirir. Usopp ve Nami, Tama\'yı koruyarak savaşın dengesini değiştirir.' },
      { number: 29, title: 'Bir Zamanlar Bir Tilki', slug: 'wano-29', duration: '24:30', summary: '9 Kızıl Kın, 20 yıllık intikamları için Kaido ile savaşır. Oden\'in iki kılıç stilini birlikte kullanarak Kaido\'yu yaralarlar. Ancak Kaido çok güçlüdür — Kızıl Kınlar yenilir.' },
      { number: 30, title: 'Enma', slug: 'wano-30', duration: '24:30', summary: 'Kaido\'nun elit altılısı Tobi Roppo devreye girer: Who\'s-Who, Black Maria, Sasaki, Ulti, Page One ve X Drake. Her biri antik Zoan meyvesi kullanıcısıdır. Hasır Şapkalar dağılarak savaşır.' },
      { number: 31, title: 'Büyük Haberler', slug: 'wano-31', duration: '24:30', summary: 'Franky, General Franky ile Sasaki\'ye karşı savaşır. Robin, Black Maria ile karşılaşır ve Demonio Fleur formunu açığa çıkarır — devasa bir iblis formu. Robin\'in en güçlü savaşı.' },
      { number: 32, title: 'Nihai', slug: 'wano-32', duration: '24:30', summary: 'Jinbe, Who\'s-Who ile savaşır. Who\'s-Who, Güneş Tanrısı Nika efsanesinden bahseder — Jinbe\'nin kulağına ilk kez bu isim çalınır. Brook, ağır düşmanlarla savaşarak mürettebatı destekler.' },
      { number: 33, title: 'Sözleşilen Liman', slug: 'wano-33', duration: '24:30', summary: 'Nami, Ulti ile savaşır. Zeus, Big Mom\'dan koparak kalıcı olarak Nami\'nin Clima-Tact\'ına yerleşir. Usopp, Page One ve Ulti\'ye karşı Tama\'yı korur. İkili, güçlerinin ötesinde savaşır.' },
      { number: 34, title: 'Dağ Tanrısı Olayı', slug: 'wano-34', duration: '24:30', summary: 'Kurozumi Orochi, birçok kez öldürülmesine rağmen Hebi Hebi meyvesiyle her seferinde geri gelmiştir. Bu sefer Hiyori ve Denjiro tarafından kesin olarak yok edilir. 20 yıllık zulmü sona erer.' },
      { number: 35, title: 'Daimyo ve Hizmetkârları', slug: 'wano-35', duration: '24:30', summary: 'Kızıl Kın Ashura Doji, Kanjuro\'nun bomba tuzağını vücuduyla engeller. 20 yıl boyunca Oden\'in dönüşünü beklemiştir. "Oden-sama, sözümüzü tuttuk." Fedakarlığı müttefikleri kurtarır.' },
      { number: 36, title: 'Oden\'in Macerası', slug: 'wano-36', duration: '24:30', summary: 'Sanji, Queen ile savaşırken Germa modifikasyonu uyanır — dış iskelet, süper iyileşme ve dayanıklılık. Sanji, insanlığını kaybetmekten korkar ama iradesiyle duygularını korur.' },
      { number: 37, title: 'Roger ve Beyazsakal', slug: 'wano-37', duration: '24:30', summary: 'Sanji, Ifrit Jambe\'yi açığa çıkarır — cehennem ateşi tekmeleri. Germa dayanıklılığı ve aşçı ruhu birleşir. Queen\'i yener. "Ben Vinsmoke değilim — Hasır Şapka Korsanlarının aşçısıyım!"' },
      { number: 38, title: 'Roger\'ın Macerası', slug: 'wano-38', duration: '24:30', summary: 'Zoro, Kaido\'nun sağ kolu King ile savaşır. King, Lunarian — ateşe dayanıklı soyu tükenmiş bir ırk. Zoro, Enma kılıcını tam kontrol ederek Haoshoku Haki\'yi kılıcına akıtır ve kazanır.' },
      { number: 39, title: 'Aptal Daimyo', slug: 'wano-39', duration: '24:30', summary: 'Law ve Kid, birlikte Big Mom ile savaşır. Big Mom\'un gücü ezicidir — Prometheus, Hera ve Napoleon ile saldırır. İki Supernova defalarca yenilir ama vazgeçmez.' },
      { number: 40, title: 'Oden Dediğin Haşlanır', slug: 'wano-40', duration: '24:30', summary: 'Law\'ın Awakening\'i — K-Room ve Puncture Wille — Big Mom\'un içini parçalar. Kid\'in Assign tekniği Big Mom\'u dev mıknatıslara yapıştırır. İki Supernova bir Yonko\'yu yener ve magmaya gömer!' },
      { number: 41, title: 'Kozuki Hanesi', slug: 'wano-41', duration: '24:30', summary: 'Luffy, Zoro, Law, Kid ve Killer, Onigashima\'nın çatısında Kaido ve Big Mom ile savaşır. 5\'e 2 — ama Yonko\'ların gücü hâlâ ezicidir. Zoro, Haoshoku Haki kaplandığı saldırıyla Kaido\'yu yaralar!' },
      { number: 42, title: 'Kin\'emon\'un Zekice Planı', slug: 'wano-42', duration: '24:30', summary: 'Luffy, çatıda Kaido ile 1\'e 1 kalır. Gear 4\'ün tüm formlarını kullanır. Kaido, ejderha ve insan formları arasında geçiş yapar. Her ikisi de Haoshoku Haki kullanır — yumruklar çarpışınca gökyüzü yarılır.' },
      { number: 43, title: 'Parti Sona Erdi!!!', slug: 'wano-43', duration: '24:30', summary: 'Kaido, sarhoş formları arasında geçiş yaparak savaşır. Luffy, ileri seviye Haoshoku Haki\'yi ustalaşır — yumruklarını Haki ile kaplar. İki iradenin çarpışması Onigashima\'yı sallar.' },
      { number: 44, title: 'Aile Meselesi', slug: 'wano-44', duration: '24:30', summary: 'Kaido\'nun geçmişi: Vodka Krallığı\'ndan, Rocks Korsanları\'nın üyesi, God Valley olayı. Kaido, Joy Boy\'u beklemektedir. "Bu dünya sıkıcı — savaş her şeyi belirler." Luffy\'nin Joy Boy olup olmadığını test eder.' },
      { number: 45, title: 'Dövüş Müziği', slug: 'wano-45', duration: '24:30', summary: 'CP0 ajanları Onigashima\'da gizlice hareket eder. Dünya Hükümeti\'nin emriyle Luffy\'yi öldürmeye çalışırlar. Bir ajan, Luffy\'nin dikkatsiz anında müdahale eder. Kaido, fırsatı kullanarak son darbeyi vurur.' },
      { number: 46, title: 'Yıldırım', slug: 'wano-46', duration: '24:30', summary: 'Kaido, Luffy\'yi yener. Luffy "ölür" — kalbi durur. Kaido zaferini ilan eder. Ama Zunisha hisseder: "Joy Boy geri döndü!" Luffy\'nin vücudunda bir değişim başlar — meyvesi uyanmaktadır.' },
      { number: 47, title: 'Kutsal Kitabım', slug: 'wano-47', duration: '24:30', summary: 'Şok gerçek: Gomu Gomu no Mi aslında Hito Hito no Mi, Model: Nika\'dır — Güneş Tanrısı Nika\'nın Zoan meyvesi. 800 yıldır Dünya Hükümeti bu meyveyi aramaktadır. Luffy, Joy Boy\'un mirasçısı olarak uyanır.' },
      { number: 48, title: 'Şanlı Hizmetkârlar', slug: 'wano-48', duration: '24:30', summary: 'Luffy, Gear 5\'i aktive eder! Saçları beyazlaşır, gözleri kırmızılaşır, kıyafetleri beyazlaşır. Çizgi film fiziği — her şey mümkün. Kaido\'nun gözlerini lastik gibi çeker, yeri lastik yapar, yıldırımları yakalar.' },
      { number: 49, title: 'Kaybetmeyecekmişiz Gibi', slug: 'wano-49', duration: '24:30', summary: 'Gear 5 Luffy, hayal gücünün sınırlarıyla savaşır. Dev bir yumruk — gözleri fırlayan, dili sarkan çizgi film stili. Kaido bile gülmekten kendini alamaz. "Bu savaşın en komik hali!"' },
      { number: 50, title: 'Tek Kişilik Ordu', slug: 'wano-50', duration: '24:30', summary: 'Gear 5 Luffy ve Kaido arasında epik son savaş. Luffy, Kaido\'yu dev lastik top gibi zıplatır. Kaido, en güçlü Boro Breath ve magma ejderha formunu kullanır. İki irade çarpışır.' },
      { number: 51, title: 'Kalıntılar', slug: 'wano-51', duration: '24:30', summary: 'Yamato, babasına karşı son savaşını verir. İnu İnu meyvesi Model Makami ile buz ateşi kullanır. Luffy\'nin geri dönmesi için zaman kazanır. Oden\'in ruhunu taşıyan kız, tiranlığa karşı durur.' },
      { number: 52, title: 'Kunoichi\'nin Yemini', slug: 'wano-52', duration: '24:30', summary: 'Kaido\'nun bulutları zayıflar ve Onigashima adası Çiçek Başkenti\'ne doğru düşmeye başlar. Momonosuke, ejderha formunda adayı taşımaya çalışır — ama çok korkaktır. Yamato, bombaları etkisiz hale getirir.' },
      { number: 53, title: 'Alev Bulutları', slug: 'wano-53', duration: '24:30', summary: 'Momonosuke, korkusunu yener ve Bolo Breath kullanarak Onigashima\'yı iter. 8 yaşında bir çocuğun 28 yaşında bir bedende ülkesini kurtarması. Zunisha yanlarındadır.' },
      { number: 54, title: 'Seninle İçmek İçin Hazırladığım Sake', slug: 'wano-54', duration: '24:30', summary: 'Luffy, devasa bir yumruk — Bajrang Gun — hazırlar. Onigashima kadar büyük bir lastik yumruk! Kaido, en güçlü tekniği Kaen Daiko ile karşılık verir. İki güç çarpışır — Luffy kazanır! Kaido, Wano\'nun altına gömülür.' },
      { number: 55, title: 'Hasır Şapkalı Luffy', slug: 'wano-55', duration: '24:30', summary: 'Kaido ve Big Mom yenilir. 20 yıllık tiranlık sona erer. Wano halkı kutlama yapar — herkes ağlar ve güler. Tama artık her gün karnını doyurabilecek. Ace\'in sözü gerçek olmuştur.' },
    ],
  },
]
