import type { Arc } from '@/types'

export const FOUR_EMPERORS_ARCS: Arc[] = [
  {
    name: 'Zou',
    slug: 'zou',
    saga: 'four-emperors',
    cover: '/arcs/zou.jpg',
    episodeCount: 8,
    summary: 'Dev bir filin sırtında yaşayan Mink kabilesi. Road Poneglyph\'lerin sırrı ve Kaido ile Big Mom tehlikesi ortaya çıkar.',
    detailedSummary: '1000 yıldır okyanusta yürüyen dev fil Zunisha\'nın sırtında yaşayan Mink kabilesi. Minkler, insan-hayvan melezi savaşçılardır ve Electro tekniğini kullanırlar. Jack — Kaido\'nun sağ kolu — Minklere saldırmış ve adayı harap etmiştir. Raizo\'yu aramaktadır. "Raizo güvendedir!" açıklaması Minklerin fedakarlığını gösterir. Sanji, Big Mom\'un kızı Pudding ile zorla evlendirilmek üzere kaçırılmıştır. Road Poneglyph\'ler keşfedilir — One Piece\'e ulaşmak için 4 Road Poneglyph gereklidir. Biri Zou\'da, biri Big Mom\'da, biri Kaido\'da, dördüncüsü kayıptır. Kozuki Momonosuke ve Kinemon\'un Wano\'dan geldiği ortaya çıkar. Plan: bir grup Sanji\'yi kurtarmak için Whole Cake Island\'a, diğeri Wano\'ya gidecektir.',
    keyEvents: [
      'Mink kabilesi ve Zunisha',
      'Jack\'in saldırısı',
      'Raizo\'nun güvende olması',
      'Road Poneglyph\'lerin keşfi',
      'Sanji\'nin kaçırılması',
      'Kozuki ailesi ve Wano bağlantısı',
      'Mürettebatın ikiye ayrılması',
    ],
    themes: ['Sadakat ve Fedakarlık', 'Dünya Tarihi', 'Aile Zorunlulukları'],
    location: 'Zou (Zunisha\'nın sırtı)',
    villain: 'Jack',
    characters: ['luffy', 'zoro', 'law', 'sanji', 'carrot'],
    episodes: [
      { number: 1, title: 'Dev Filin Sırtı', slug: 'zou-01', duration: '24:30', summary: 'Mürettebat, 1000 yıldır yürüyen dev fil Zunisha\'nın sırtındaki Zou adasına ulaşır. Mink kabilesi — insan-hayvan melezleri — burada yaşamaktadır. Ada harap haldedir.' },
      { number: 2, title: 'Mink Kabilesi', slug: 'zou-02', duration: '24:30', summary: 'Minklerin Electro savaş tekniği ve kültürleri tanıtılır. İnek Mink Wanda ve köpek Mink Carrot mürettebatı karşılar. Nami grubu daha önce gelmiş ve Minklere yardım etmiştir.' },
      { number: 3, title: 'Jack\'in Saldırısı', slug: 'zou-03', duration: '24:30', summary: 'Kaido\'nun sağ kolu Jack, Minklere saldırmıştır. Caesar\'ın zehirli gazını kullanarak adayı harap etmiştir. Minkler, büyük kayıplar vererek direnmiştir. Sanji onları kurtarmış ama sonra kaybolmuştur.' },
      { number: 4, title: 'Raizo Güvende', slug: 'zou-04', duration: '24:30', summary: 'Jack\'in aradığı ninja Raizo, Minkler tarafından saklanmıştır. Tüm adayı yok etme pahasına Raizo\'yu teslim etmemişlerdir. "Raizo güvendedir!" — Minklerin fedakarlığının kanıtı.' },
      { number: 5, title: 'Road Poneglyph', slug: 'zou-05', duration: '24:30', summary: 'Robin, Zou\'daki Road Poneglyph\'i okur. One Piece\'e ulaşmak için 4 Road Poneglyph gereklidir. Her biri bir koordinat verir — dördü birleşince Laugh Tale\'in konumu ortaya çıkar.' },
      { number: 6, title: 'Sanji\'nin Durumu', slug: 'zou-06', duration: '24:30', summary: 'Sanji\'nin Big Mom\'un kızı Charlotte Pudding ile zorla evlendirilmek üzere Whole Cake Island\'a götürüldüğü ortaya çıkar. Sanji\'nin asıl soy adı Vinsmoke\'dur — Germa 66 krallık ailesinin prensesidir.' },
      { number: 7, title: 'Kozuki Ailesi', slug: 'zou-07', duration: '24:30', summary: 'Momonosuke ve Kinemon\'un Wano Ülkesi\'nden geldikleri ortaya çıkar. Kozuki ailesi, Poneglyph\'leri oluşturan taş işçileridir. Wano, Kaido tarafından 20 yıldır işgal edilmektedir.' },
      { number: 8, title: 'İki Yolculuk', slug: 'zou-08', duration: '24:30', summary: 'Plan belirlenir: Luffy, Nami, Chopper ve Brook Sanji\'yi kurtarmak için Whole Cake Island\'a; Zoro, Law ve diğerleri Wano\'ya gidecektir. Carrot gizlice gemiye biner. İki paralel macera başlar.' },
    ],
  },
  {
    name: 'Whole Cake Island',
    slug: 'whole-cake-island',
    saga: 'four-emperors',
    cover: '/arcs/whole-cake-island.jpg',
    episodeCount: 22,
    summary: 'Sanji\'yi kurtarma operasyonu. Yonko Big Mom\'un tatlılardan yapılmış çılgın krallığında hayatta kalma mücadelesi.',
    detailedSummary: 'Luffy ve küçük bir ekip, Sanji\'yi kurtarmak için Yonko Big Mom\'un bölgesine girer. Whole Cake Island, tatlılardan yapılmış bir çılgınlık diyarıdır — ağaçlar, evler, hatta zemin bile yenilebilir. Big Mom\'un Soru Soru meyvesiyle canlılara can verdiği Homie\'ler her yerdedir. Sanji\'nin geçmişi tam olarak ortaya çıkar: Vinsmoke ailesi tarafından başarısız sayılıp dışlanmış, aşçılığı "zayıflık" olarak görülmüştür. Babası Judge, Sanji\'yi duygusuz bir silaha dönüştürmek istemiştir. Sanji, ailesinden nefret eder ama yine de onları korur — çünkü Zeff ona "gerçek bir beyefendi asla bir kadına vurmaz, hiç kimseyi aç bırakmaz" diye öğretmiştir. Luffy, Sanji\'yi bulmak için her şeyi göze alır. Sanji, Luffy\'yi yumruklar ve gitmesini söyler ama Luffy yerinden kıpırdamaz: "Senin yemeklerin olmadan Korsanlar Kralı olamam!" Pedro kendini feda eder. Carrot Sulong formuna girer. Luffy, Katakuri ile Gear 4 Snake Man kullanarak epik bir savaş yapar. Mürettebat son anda kaçar.',
    keyEvents: [
      'Big Mom\'un tatlı imparatorluğu',
      'Sanji\'nin Vinsmoke geçmişi',
      'Luffy ve Sanji\'nin yeniden birleşmesi',
      'Pedro\'nun fedakarlığı',
      'Carrot Sulong formu',
      'Luffy vs Katakuri — Gelecek Görüşü',
      'Big Mom\'dan kaçış',
      'Jinbe resmi olarak katılır',
    ],
    themes: ['Aile ve Ret', 'Yemek ve Sevgi', 'Asla Vazgeçmemek', 'Gelecek Görüşü'],
    location: 'Whole Cake Island (Totto Land)',
    villain: 'Big Mom, Katakuri',
    characters: ['luffy', 'nami', 'sanji', 'chopper', 'brook', 'jinbe', 'carrot', 'bigmom'],
    episodes: [
      { number: 1, title: 'Tatlı Ülke', slug: 'wci-01', duration: '24:30', summary: 'Mürettebat, tatlılardan yapılmış Totto Land\'a girer. Her şey yenilebilir — ağaçlar, evler, zemin. Big Mom\'un Homie\'leri (cansız nesnelere can verilmiş yaratıklar) her yerdedir.' },
      { number: 2, title: 'Vinsmoke Ailesi', slug: 'wci-02', duration: '24:30', summary: 'Sanji\'nin geçmişi: Vinsmoke ailesi, Kuzey Deniz\'in savaşçı krallığı Germa 66\'yı yönetir. Sanji, kardeşleri gibi duygusuz bir silah olamamıştır. Babası Judge onu "başarısız" ilan edip hapsederek aileden silmiştir.' },
      { number: 3, title: 'Sanji\'nin Acısı', slug: 'wci-03', duration: '24:30', summary: 'Sanji\'nin çocukluğu: kardeşleri tarafından dövülmüş, sadece annesi Sora ve ablası Reiju onu sevmiştir. Sora, çocuklarının duygusuz olmaması için ilaç almış ve hayatını kaybetmiştir. Sanji, Germa\'dan kaçarak Baratie\'ye sığınmıştır.' },
      { number: 4, title: 'Luffy vs Sanji', slug: 'wci-04', duration: '24:30', summary: 'Sanji, mürettebatı korumak için Luffy\'yi yumruklar ve "Git!" der. Luffy karşılık vermez ve yerinden kıpırdamaz: "Biliyorum, yalan söylüyorsun. Senin yemeklerin olmadan Korsanlar Kralı olamam!" Sanji çöker.' },
      { number: 5, title: 'Düğün Planı', slug: 'wci-05', duration: '24:30', summary: 'Big Mom\'un gerçek planı: düğünde Vinsmoke ailesini öldürmek ve Germa 66 teknolojisini ele geçirmek. Pudding, Sanji\'yi aldatmak için rol yapmaktadır. Bege ile gizli ittifak kurulur.' },
      { number: 6, title: 'Çay Partisi', slug: 'wci-06', duration: '24:30', summary: 'Big Mom\'un çay partisi başlar. Plan: Mother Carmel\'in fotoğrafını kırmak ve Big Mom\'u şoka sokmak. Brook, Poneglyph\'i çalmayı başarmıştır. Her şey düğün anında patlayacak.' },
      { number: 7, title: 'Düğün Kaosı', slug: 'wci-07', duration: '24:30', summary: 'Luffy, dev bir pasta içinden fırlar ve Mother Carmel fotoğrafını kırar. Big Mom çığlık atar — Haoshoku Haki dalgası. Plan işe yarar ama Big Mom\'u öldürmek imkansızdır. Kaos başlar.' },
      { number: 8, title: 'Big Mom\'un Öfkesi', slug: 'wci-08', duration: '24:30', summary: 'Big Mom, düğün pastasının yıkılmasıyla çılgına döner. "Wedding Cake" istiyordur ve onu bulana kadar her şeyi yok edecektir. Sanji, Big Mom\'u durdurmak için pastayı yapmaya karar verir.' },
      { number: 9, title: 'Pedro\'nun Fedakarlığı', slug: 'wci-09', duration: '24:30', summary: 'Mink savaşçısı Pedro, mürettebatın kaçışı için kendini feda eder. Perospero\'yu durdurmak için bombayla patlar: "Bu gün gelmeli!" Carrot yıkılır. Pedro\'nun mirası mürettebatı ileri taşır.' },
      { number: 10, title: 'Carrot Sulong', slug: 'wci-10', duration: '24:30', summary: 'Carrot, dolunayda Sulong formuna girer — Mink savaşçılarının en güçlü formu. Beyaz, vahşi ve inanılmaz hızlı. Big Mom\'un filosuna tek başına saldırır ve birçok gemiyi devre dışı bırakır.' },
      { number: 11, title: 'Luffy vs Katakuri I', slug: 'wci-11', duration: '24:30', summary: 'Charlotte Katakuri — Big Mom\'un en güçlü oğlu. Mochi Mochi meyvesiyle mochi üretir ve Gelecek Görüşü Haki\'siyle saldırıları önceden görür. Luffy, ayna dünyasında Katakuri ile kapanır.' },
      { number: 12, title: 'Luffy vs Katakuri II', slug: 'wci-12', duration: '24:30', summary: 'Katakuri, Luffy\'den her açıdan üstündür. Luffy defalarca yenilir ama kalkar. Katakuri\'nin gizli yüzü — devasa bir ağız — ortaya çıkar. Katakuri, Luffy\'nin iradesine saygı duymaya başlar.' },
      { number: 13, title: 'Gelecek Görüşü', slug: 'wci-13', duration: '24:30', summary: 'Luffy, savaş sırasında Gelecek Görüşü Haki\'sini (ileri seviye Kenbunshoku) geliştirmeye başlar. Katakuri\'nin saldırılarını önceden görmeye başlar. İki savaşçı birbirini zorlayarak büyür.' },
      { number: 14, title: 'Snake Man', slug: 'wci-14', duration: '24:30', summary: 'Luffy, Gear 4\'ün yeni formu Snake Man\'i açığa çıkarır! Yılan gibi kıvrılan, hızlanan ve izlenemez yumruklar. Katakuri ile son çarpışma — Black Mamba ve King Cobra teknikleri.' },
      { number: 15, title: 'Katakuri Düşüyor', slug: 'wci-15', duration: '24:30', summary: 'Epik son darbe: Luffy ve Katakuri birbirlerinin yüzüne yumruk atar. İkisi de yere düşer ama Luffy ayağa kalkar. Katakuri şapkasını Luffy\'nin ağzını örtmek için kullanır — saygı gösterisi.' },
      { number: 16, title: 'Sanji\'nin Pastası', slug: 'wci-16', duration: '24:30', summary: 'Sanji, hayatının en iyi düğün pastasını yapar. Big Mom bir lokma aldığında mutluluktan bayılır. Sanji\'nin yemek yeteneği bir Yonko\'yu durdurur. Mürettebat kaçış fırsatı bulur.' },
      { number: 17, title: 'Jinbe\'nin Kararı', slug: 'wci-17', duration: '24:30', summary: 'Jinbe, Big Mom\'a karşı durur ve resmi olarak Hasır Şapkalara katıldığını ilan eder. Big Mom\'un "ömründen yıl çalma" saldırısına karşı korkusuz durur — çünkü Luffy\'nin yanında korkacak bir şey yoktur.' },
      { number: 18, title: 'Kaçış Operasyonu', slug: 'wci-18', duration: '24:30', summary: 'Mürettebat, Big Mom\'un bölgesinden kaçmaya çalışır. Oven, Daifuku ve diğer Charlotte çocukları peşlerindedir. Germa 66 sürpriz bir şekilde yardıma gelir — Sanji\'nin ailesi.' },
      { number: 19, title: 'Coup de Burst', slug: 'wci-19', duration: '24:30', summary: 'Thousand Sunny, Coup de Burst ile Big Mom\'un bölgesinden fırlar. Son anda kurtulurlar. Big Mom peşlerinden gelecektir ama şimdilik güvendedirler.' },
      { number: 20, title: 'Reverie\'ye Doğru', slug: 'wci-20', duration: '24:30', summary: 'Mürettebat Wano\'ya doğru yol alır. Dünya çapında haberler: Luffy\'nin Big Mom\'la savaşması onu "Beşinci İmparator" yapar. Ödülü 1.5 milyara çıkar.' },
      { number: 21, title: 'Sanji ve Luffy', slug: 'wci-21', duration: '24:30', summary: 'Sanji, Luffy için özel bir yemek hazırlar. Luffy, Sanji\'nin yemeklerini gözyaşlarıyla yer. İkisinin bağı her zamankinden güçlüdür. Mürettebat yeniden tamam.' },
      { number: 22, title: 'Wano\'ya Hazırlık', slug: 'wci-22', duration: '24:30', summary: 'Wano operasyonunun detayları planlanır. Kaido\'yu devirmek için büyük bir ittifak gerekecek. Law, Zoro ve diğerleri Wano\'da hazırlık yapmaktadır. En büyük savaş yaklaşıyor.' },
    ],
  },
  {
    name: 'Reverie',
    slug: 'reverie',
    saga: 'four-emperors',
    cover: '/arcs/reverie.jpg',
    episodeCount: 3,
    summary: 'Dünya liderlerinin toplandığı Reverie\'de büyük kararlar alınır. Sabo ve Devrimciler sahneye çıkar.',
    detailedSummary: 'Dört yılda bir toplanan dünya liderler konseyi Reverie, Mariejois\'da düzenlenir. 50 ülkenin kralı ve kraliçesi katılır. Vivi, Shirahoshi, Dalton ve diğer tanıdık yüzler sahneye çıkar. Devrimci Ordu komutanları — Sabo, Karasu, Morley, Lindbergh — Celestial Dragonlara karşı harekete geçer. Im-sama — dünya tahtında oturan gizemli figür — ilk kez gösterilir. Dünya Hükümeti\'nin gerçek hükümdarı kimdir? Shichibukai sisteminin kaldırılması oylanır ve kabul edilir. Cobra Nefertari, Void Century hakkında soru sorar. Reverie sonrası dünya çapında büyük olaylar yaşanır: Sabo\'nun "ölümü" haberleri, Vivi\'nin kaybolması, Cobra\'nın ölümü.',
    keyEvents: [
      'Reverie toplantısı',
      'Im-sama ilk kez görülür',
      'Shichibukai sistemi kaldırılır',
      'Devrimcilerin Mariejois saldırısı',
      'Cobra\'nın soruları ve ölümü',
      'Vivi\'nin kaybolması',
    ],
    themes: ['Dünya Siyaseti', 'Gizli Güç', 'Devrim', 'Void Century Sırları'],
    location: 'Mariejois (Reverie)',
    characters: ['vivi', 'sabo', 'shanks'],
    episodes: [
      { number: 1, title: 'Dünya Konseyi', slug: 'reverie-01', duration: '24:30', summary: 'Dünyanın dört bir yanından krallar Reverie için Mariejois\'a toplanır. Vivi, Shirahoshi, Dalton ve Cobra gibi tanıdık yüzler. Dünya liderlerinin kararları milyarlarca insanı etkileyecek.' },
      { number: 2, title: 'Im-sama', slug: 'reverie-02', duration: '24:30', summary: 'Boş tahtın aslında boş olmadığı ortaya çıkar: Im-sama, dünyanın gerçek hükümdarıdır. Gorosei\'nin bile üstünde bir otorite. Luffy, Blackbeard, Shirahoshi ve Vivi\'nin fotoğraflarını inceler.' },
      { number: 3, title: 'Devrimcilerin Saldırısı', slug: 'reverie-03', duration: '24:30', summary: 'Sabo ve Devrimci Ordu komutanları, Celestial Dragonlara karşı harekete geçer. Shichibukai sistemi kaldırılır. Reverie sonrası şok haberler: Sabo\'nun "ölümü", Cobra\'nın ölümü, Vivi kayıp. Dünya sarsılır.' },
    ],
  },
  {
    name: 'Wano',
    slug: 'wano',
    saga: 'four-emperors',
    cover: '/arcs/wano.jpg',
    episodeCount: 40,
    summary: 'Japonya temalı izole ülke Wano\'da Yonko Kaido\'ya karşı devasa bir savaş. Luffy, Gear 5\'i açığa çıkarır ve Joy Boy\'un mirasını devralır.',
    detailedSummary: 'One Piece\'in en uzun ve en epik arcı. Japonya temalı izole ülke Wano, 20 yıldır Yonko Kaido tarafından işgal edilmektedir. Kaido, Orochi ile birlikte ülkeyi sömürmüş, halkı açlıktan öldürmüş ve SMILE fabrikalarıyla zehirlemiştir. 20 yıl önce Kozuki Oden, Kaido tarafından idam edilmiştir. Oden\'in karısı Toki, Momonosuke ve sadık samuraiları 20 yıl ileriye göndermiştir. Şimdi intikam zamanıdır. Dev ittifak: Hasır Şapkalar, Heart Korsanları, Kid Korsanları, Mink kabilesi, Wano samuraiları — hepsi Onigashima\'da Kaido\'ya karşı savaşır. Kaido ve Big Mom ittifak kurmuştur! Zoro, Enma kılıcını edinir. Sanji, Germa modifikasyonunun uyanmasıyla dış iskelet kazanır. Luffy, Kaido ile çatıda savaşırken yenilir ve "ölür" — ama Gomu Gomu meyvesinin gerçek adı ortaya çıkar: Hito Hito no Mi, Model: Nika. Luffy, Joy Boy olarak uyanır ve Gear 5\'i aktive eder! Tüm kuralları yıkan, çizgi film fiziğiyle savaşan, gülümseyen bir tanrı. Luffy, Kaido\'yu yener. Wano özgürdür. Momonosuke yeni Shogun olur.',
    keyEvents: [
      'Wano\'nun 20 yıllık işgali',
      'Kozuki Oden\'in hikayesi ve idamı',
      'Onigashima savaşı — en büyük savaş',
      'Kaido-Big Mom ittifakı',
      'Zoro Enma kılıcını alır, Haoshoku Haki',
      'Sanji Germa uyanışı',
      'Luffy "ölür" ve Joy Boy olarak uyanır',
      'Gear 5 — Hito Hito no Mi Model Nika',
      'Luffy vs Kaido final',
      'Wano özgürlüğü',
    ],
    themes: ['Japonya Kültürü ve Samuray Onuru', 'Tiranlık ve Devrim', 'Miras ve Nesiller', 'Özgürlük ve Gülüş', 'Tanrı ve İnsan'],
    location: 'Wano Ülkesi (Kuri, Onigashima)',
    villain: 'Kaido, Orochi',
    characters: ['luffy', 'zoro', 'law', 'kid', 'kaido', 'yamato', 'bigmom'],
    episodes: [
      { number: 1, title: 'Wano\'ya Giriş', slug: 'wano-01', duration: '24:30', summary: 'Luffy, izole ülke Wano\'ya ulaşır. Japonya temalı mimari, samuraylar ve geleneksel kıyafetler. İlk gördüğü: açlıktan ölen halk ve zehirlenmiş nehirler. Kaido\'nun zulmü her yerdedir.' },
      { number: 2, title: 'O-Tama', slug: 'wano-02', duration: '24:30', summary: 'Luffy, küçük kız Tama ile tanışır. Tama, açlıktan ölmek üzeredir. Ace\'in eski bir sözünü hatırlar: "Herkesin karnının doyduğu bir Wano yaratacağım." Luffy, Ace\'in sözünü yerine getirmeye karar verir.' },
      { number: 3, title: 'Gizli Kimlikler', slug: 'wano-03', duration: '24:30', summary: 'Mürettebat, Wano\'da gizli kimliklerle yaşamaktadır. Zoro "Zorojuro" samurai, Usopp "Usohachi" tüccar, Robin "O-Robi" geyşa olarak. Kinemon\'un planına göre Onigashima savaşına hazırlanıyorlar.' },
      { number: 4, title: 'Kaido\'nun Gücü', slug: 'wano-04', duration: '24:30', summary: 'Luffy, Kaido ile ilk kez karşılaşır. Kaido, ejderha formunda gökyüzünden iner. Luffy, tüm gücüyle Gear 3 saldırısı yapar ama Kaido tek darbeyle Luffy\'yi bayıltır. Güç farkı devasa.' },
      { number: 5, title: 'Udon Hapishanesi', slug: 'wano-05', duration: '24:30', summary: 'Luffy, Udon\'daki işçi kampına hapsedilir. Burada yaşlı Hyogoro ile tanışır ve Busoshoku Haki\'nin ileri seviyesini — Ryuo — öğrenmeye başlar. Deniz taşı kelepçelerle bile antrenman yapar.' },
      { number: 6, title: 'Kozuki Oden', slug: 'wano-06', duration: '24:30', summary: 'Wano\'nun efsanevi samuraisı Kozuki Oden\'in hikayesi başlar. Oden, gençliğinde asi ve güçlü bir savaşçıydı. Beyaz Sakal ile tanıştı ve daha sonra Roger\'ın mürettebatına katıldı.' },
      { number: 7, title: 'Laugh Tale', slug: 'wano-07', duration: '24:30', summary: 'Oden, Roger ile birlikte son adaya — Laugh Tale\'e — ulaştı. One Piece\'i gördüler ve güldüler. Roger "Joy Boy, biz 800 yıl erken geldik" dedi. Oden, Wano\'nun sınırlarını açma görevini üstlendi.' },
      { number: 8, title: 'Oden\'in İdamı', slug: 'wano-08', duration: '24:30', summary: 'Oden, Kaido\'ya karşı savaştı ama Orochi\'nin hilesiyle yenildi. İdam olarak kaynar yağda pişirildi. 9 sadık samuraisını — Kızıl Kınlar — sırtında taşıyarak 1 saat dayandı. "Wano\'nun sınırlarını açın!" vasiyetiyle öldü.' },
      { number: 9, title: 'Onigashima\'ya Hazırlık', slug: 'wano-09', duration: '24:30', summary: 'Ateş Festivali gecesi, Onigashima\'ya saldırı planı. Ancak casus Kanjuro tüm planları Orochi\'ye sızdırmıştır. Mürettebat büyük bir engelle karşılaşır ama yine de saldırıya geçer.' },
      { number: 10, title: 'Onigashima Savaşı Başlıyor', slug: 'wano-10', duration: '24:30', summary: 'Dev ittifak ordusu Onigashima\'ya çıkar. Kaido\'nun 30.000 kişilik Hayvan Korsanları karşılarındadır. Kaido ve Big Mom ittifak kurmuştur — iki Yonko birden! En büyük savaş başlıyor.' },
      { number: 11, title: 'Tama\'nın Kibi Dangosu', slug: 'wano-11', duration: '24:30', summary: 'Tama\'nın Kibi Kibi meyvesinden ürettiği Kibi Dango, SMILE kullanıcılarını kontrol edebilir. Düşman ordusunun bir kısmı taraf değiştirir. Savaşın dengesi değişmeye başlar.' },
      { number: 12, title: 'Çatıdaki Beşli', slug: 'wano-12', duration: '24:30', summary: 'Luffy, Zoro, Law, Kid ve Killer, Onigashima\'nın çatısında Kaido ve Big Mom ile savaşır. 5\'e 2 — ama Yonko\'ların gücü hâlâ ezicidir. Zoro, Haoshoku Haki kaplandığı saldırıyla Kaido\'yu yaralar!' },
      { number: 13, title: 'Zoro vs King', slug: 'wano-13', duration: '24:30', summary: 'Zoro, Kaido\'nun sağ kolu King ile savaşır. King, Lunarian — ateşe dayanıklı soyu tükenmiş bir ırk. Zoro, Enma kılıcını tam kontrol ederek Haoshoku Haki\'yi kılıcına akıtır ve kazanır.' },
      { number: 14, title: 'Sanji vs Queen', slug: 'wano-14', duration: '24:30', summary: 'Sanji, Kaido\'nun sol kolu Queen ile savaşır. Savaş sırasında Germa modifikasyonu uyanır — dış iskelet ve iyileşme. Sanji, Ifrit Jambe — cehennem ateşi tekmeleri — ile Queen\'i yener.' },
      { number: 15, title: 'Law ve Kid vs Big Mom', slug: 'wano-15', duration: '24:30', summary: 'Law ve Kid, birlikte Big Mom ile savaşır. Law\'ın Awakening\'i — K-Room ve Puncture Wille — Big Mom\'un içini parçalar. Kid\'in Assign tekniği Big Mom\'u mıknatıslar. İki Supernova bir Yonko\'yu yener!' },
      { number: 16, title: 'Luffy vs Kaido I', slug: 'wano-16', duration: '24:30', summary: 'Luffy, çatıda Kaido ile 1\'e 1 savaşır. Gear 4\'ün tüm formlarını kullanır. Kaido, ejderha ve insan formları arasında geçiş yapar. Her ikisi de Haoshoku Haki kullanır — yumruklar çarpışınca gökyüzü yarılır.' },
      { number: 17, title: 'Luffy vs Kaido II', slug: 'wano-17', duration: '24:30', summary: 'Kaido, Luffy\'yi yener ve denize atar. CP0 müdahale etmiştir. Luffy "ölür" — kalbi durur. Zunisha: "Joy Boy geri döndü!" Luffy\'nin meyvesi uyanmaktadır.' },
      { number: 18, title: 'Gomu Gomu\'nun Gerçek Adı', slug: 'wano-18', duration: '24:30', summary: 'Şok gerçek: Gomu Gomu no Mi aslında Hito Hito no Mi, Model: Nika\'dır — Güneş Tanrısı Nika\'nın Zoan meyvesi. 800 yıldır Dünya Hükümeti bu meyveyi aramaktadır. Luffy, Joy Boy\'un mirasçısıdır.' },
      { number: 19, title: 'Gear 5', slug: 'wano-19', duration: '24:30', summary: 'Luffy, Gear 5\'i aktive eder! Saçları beyazlaşır, gözleri kırmızılaşır, kıyafetleri beyazlaşır. Çizgi film fiziği — her şey mümkün. Kaido\'nun gözlerini lastik gibi çeker, yeri lastik yapar, yıldırımları yakalar. "Bu savaşın en komik hali!"' },
      { number: 20, title: 'Güneş Tanrısı Nika', slug: 'wano-20', duration: '24:30', summary: 'Gear 5 Luffy, dünyayı "hayal gücünün sınırlarıyla" savaşarak Kaido\'yla eşitlenir. Dev bir yumruk — gözleri fırlayan, dili sarkan çizgi film stili. Kaido bile gülmekten kendini alamaz.' },
      { number: 21, title: 'Yamato', slug: 'wano-21', duration: '24:30', summary: 'Kaido\'nun kızı Yamato, babasına karşı savaşır. Oden\'e olan hayranlığından kendini Oden olarak tanıtır. İnu İnu meyvesi Model Makami ile buz ateşi kullanır. Yamato, Luffy\'ye katılmak ister.' },
      { number: 22, title: 'Kaido\'nun Geçmişi', slug: 'wano-22', duration: '24:30', summary: 'Kaido\'nun geçmişi: Vodka Krallığı\'ndan, Rocks Korsanları\'nın üyesi, God Valley olayı. Kaido, Joy Boy\'u beklemektedir. "Bu dünya sıkıcı — savaş her şeyi belirler." diye inanır.' },
      { number: 23, title: 'Son Darbe', slug: 'wano-23', duration: '24:30', summary: 'Luffy, devasa bir yumruk — Bajrang Gun — hazırlar. Kaido, en güçlü tekniği ile karşılık verir. İki güç çarpışır ve Luffy kazanır! Kaido, Wano\'nun altına gömülür. 20 yıllık tiranlık sona erer.' },
      { number: 24, title: 'Wano Özgür!', slug: 'wano-24', duration: '24:30', summary: 'Kaido ve Big Mom yenilir. Onigashima düşmeden önce Momonosuke ejderha formunda adayı taşır. Wano halkı kutlama yapar. Herkes ağlar ve güler. 20 yıllık acı sona ermiştir.' },
      { number: 25, title: 'Yeni Shogun', slug: 'wano-25', duration: '24:30', summary: 'Momonosuke, Wano\'nun yeni Shogun\'u ilan edilir. 8 yaşından 28 yaşına hızlandırılmış olmasına rağmen hâlâ çocuksu. Hiyori (Kozuki Hiyori) kardeşiyle tekrar birleşir.' },
      { number: 26, title: 'Yeni Yonko', slug: 'wano-26', duration: '24:30', summary: 'Dünya çapında haber: Kaido ve Big Mom düştü! Yeni Dört İmparator ilan edilir: Luffy, Blackbeard, Shanks ve Buggy. Luffy\'nin ödülü 3 milyar Berry\'ye çıkar. "Beşinci İmparator" değil, gerçek Yonko!' },
      { number: 27, title: 'Pluton\'un Sırrı', slug: 'wano-27', duration: '24:30', summary: 'Robin, Wano\'daki Poneglyph\'i okur: eski silah Pluton, Wano\'nun sınırlarının altında gizlidir. Wano\'nun sınırlarını açmak Pluton\'u ortaya çıkaracaktır. Momonosuke bu bilgiyle ne yapacağına karar vermelidir.' },
      { number: 28, title: 'Veda ve Bağlar', slug: 'wano-28', duration: '24:30', summary: 'Mürettebat Wano\'dan ayrılmaya hazırlanır. Yamato, Wano\'yu korumak için geride kalır. Kinemon, Momonosuke ve samuraylar veda eder. Carrot, Zou\'nun yeni lideri olur.' },
      { number: 29, title: 'Ryokugyu', slug: 'wano-29', duration: '24:30', summary: 'Yeni Amiral Ryokugyu (Aramaki), Wano\'ya gelir ve savaş sonrası zayıflamış korsanlara saldırır. Ancak Shanks, uzaktan Haoshoku Haki göndererek onu durdurur. Shanks\'ın gücü hâlâ korkutucudur.' },
      { number: 30, title: 'Kozuki Oden\'in Mirası', slug: 'wano-30', duration: '24:30', summary: 'Oden\'in günlüğü okunur. Laugh Tale, Joy Boy, antik krallık hakkında ipuçları. Momonosuke, günlüğün son sayfalarını yırtmıştır — henüz dünya bu bilgiyi öğrenmeye hazır değildir.' },
      { number: 31, title: 'Orochi\'nin Sonu', slug: 'wano-31', duration: '24:30', summary: 'Kurozumi Orochi, birçok kez öldürülmesine rağmen Hebi Hebi meyvesiyle her seferinde geri gelmiştir. Bu sefer Hiyori ve Denjiro tarafından kesin olarak yok edilir. Orochi\'nin zulmü sona erer.' },
      { number: 32, title: 'Kızıl Kınların Zaferi', slug: 'wano-32', duration: '24:30', summary: '9 Kızıl Kın — Oden\'in sadık samuraiları — 20 yıllık bekleyişlerinin meyvesini alır. Kinemon, Denjiro, Ashura Doji ve diğerleri. Bazıları bu savaşta hayatını kaybetmiştir ama Oden\'in vasiyeti yerine getirilmiştir.' },
      { number: 33, title: 'Marco ve İzato', slug: 'wano-33', duration: '24:30', summary: 'Beyaz Sakal\'ın 1. Bölük Komutanı Marco, savaşta büyük rol oynamıştır. Phoenix formuyla herkesin yaralarını iyileştirmiştir. Ace\'in vasiyetini yerine getirmiştir: "Kardeşimi koru."' },
      { number: 34, title: 'Killer ve Kid', slug: 'wano-34', duration: '24:30', summary: 'Kid ve Killer\'ın Wano maceraları. Kaido tarafından yakalanıp işkence edilmişlerdir. Killer, SMILE meyvesiyle zorla güldürülmüş ve "Kamazou" olmuştur. Bu savaş onların intikamıdır.' },
      { number: 35, title: 'Zunisha\'nın Sırrı', slug: 'wano-35', duration: '24:30', summary: 'Dev fil Zunisha, Wano\'nun kıyılarına gelir. Zunisha, 800 yıl önce bir suç işlemiş ve ceza olarak sonsuza dek yürümeye mahkum edilmiştir. Joy Boy\'un eski arkadaşıdır. Momonosuke onunla konuşabilir.' },
      { number: 36, title: 'Ashura Doji\'nin Fedakarlığı', slug: 'wano-36', duration: '24:30', summary: 'Kızıl Kın Ashura Doji, Kanjuro\'nun bomba tuzağını vücuduyla engeller. 20 yıl boyunca Oden\'in dönüşünü beklemiştir. "Oden-sama, sözümüzü tuttuk."' },
      { number: 37, title: 'Izo\'nun Son Savaşı', slug: 'wano-37', duration: '24:30', summary: 'Izo, eski Beyaz Sakal Korsanı ve Kızıl Kın üyesi, CP0 ajanlarına karşı son savaşını verir. Wano\'yu korumak için hayatını feda eder.' },
      { number: 38, title: 'Nefes Aldık', slug: 'wano-38', duration: '24:30', summary: 'Savaş sonrası: yaralar sarılır, ölüler anılır, kutlamalar yapılır. Wano halkı 20 yıl sonra ilk kez temiz su içer ve karnını doyurur. Tama\'nın günlük pirinci yoktur ama artık herkes tok.' },
      { number: 39, title: 'Çapraz Yollar', slug: 'wano-39', duration: '24:30', summary: 'Law ve Kid, kendi yollarına gider. Luffy ve mürettebat, bir sonraki maceraya hazırlanır. Dünya değişmiştir: Yonko sistemi sarsılmış, Shichibukai sistemi kalkmış, Dünya Hükümeti tehdit altındadır.' },
      { number: 40, title: 'Son Adaya Doğru', slug: 'wano-40', duration: '24:30', summary: 'Mürettebat Wano\'dan ayrılır. 3 Road Poneglyph ellerindedir — dördüncüsünü bulmak kalıyor. Laugh Tale, One Piece ve Joy Boy\'un mirası — her şeyin cevabı son adada. Korsanlar Kralı olma yolculuğu son düzlüğe girdi.' },
    ],
  },
]
