import type { Arc } from '@/types'

export const SKY_ISLAND_ARCS: Arc[] = [
  {
    name: 'Jaya',
    slug: 'jaya',
    saga: 'sky-island',
    cover: '/arcs/jaya.jpg',
    episodeCount: 4,
    summary: 'Gökyüzü adası efsanesinin peşine düşen Hasır Şapkalar, Jaya adasında Bellamy ile karşılaşır ve devasa geyserleri keşfeder.',
    detailedSummary: 'Bir gökten düşen gemi mürettebatı şaşırtır ve gökyüzü adaları efsanesini araştırmaya başlarlar. Jaya adasının Mock Town kasabasında korsanlar rüyalara inanmaz ve onlarla alay eder. Bellamy, Spring Spring meyvesiyle Luffy\'ye saldırır ama Luffy karşılık vermez — çünkü "kavga etmeye değmez." Blackbeard (Marshall D. Teach) ile ilk karşılaşma burada gerçekleşir. Teach, Luffy\'nin rüyasının büyüklüğünü takdir eder: "İnsanların hayalleri asla bitmez!" Mürettebat, dalgıç Mont Blanc Cricket\'i bulur. Cricket, 400 yıl önce gökyüzü adalarının varlığını iddia edip "yalancı" ilan edilen atası Noland\'ın onurunu kurtarmaya çalışmaktadır. Bellamy, Cricket\'in altınlarını çalar. Luffy tek bir yumrukla Bellamy\'yi yener. Cricket ve arkadaşları, mürettebatın gökyüzüne çıkması için devasa geyser Knock-Up Stream\'i bulmalarına yardım eder.',
    keyEvents: [
      'Gökyüzü adası araştırması başlar',
      'Bellamy ile karşılaşma',
      'Blackbeard ile ilk tanışma',
      'Mont Blanc Cricket ve Noland efsanesi',
      'Luffy tek yumrukla Bellamy\'yi yener',
      'Knock-Up Stream ile gökyüzüne çıkış',
    ],
    themes: ['Rüyalara İnanmak', 'Alay ve Direnç', 'Efsaneler ve Gerçeklik'],
    location: 'Jaya, Mock Town',
    villain: 'Bellamy',
    characters: ['luffy', 'zoro', 'nami', 'robin', 'blackbeard'],
    episodes: [
      {
        number: 1,
        title: 'Mock Town',
        slug: 'jaya-01',
        duration: '24:00',
        summary: 'Gökten düşen bir gemi ve harita mürettebatı gökyüzü adalarının peşine düşürür. Mock Town\'da korsanların rüyalarla alay ettiği vahşi bir atmosfer vardır. Bellamy, gökyüzü adalarına inanan herkesle alay eder.',
      },
      {
        number: 2,
        title: 'Bellamy\'nin Aşağılaması',
        slug: 'jaya-02',
        duration: '24:30',
        summary: 'Bellamy ve adamları Luffy ve Zoro\'yu döver ama ikisi karşılık vermez. Nami öfkelenir ama Luffy "Bu kavga etmeye değmez" der. Blackbeard ile karşılaşırlar: "İnsanların hayalleri asla bitmez!" derece farklı bir korsan.',
      },
      {
        number: 3,
        title: 'Tek Yumruk',
        slug: 'jaya-03',
        duration: '24:00',
        summary: 'Mont Blanc Cricket, atası Noland\'ın "yalancı" damgasını temizlemek için deniz altında altın şehri arıyor. Bellamy, Cricket\'in altınlarını çalar. Luffy, Bellamy\'yi tek bir yumrukla yere serer — önceki sessizliğinin sebebi bu: savaşmaya değmeyen birine güç kullanmazdı.',
      },
      {
        number: 4,
        title: 'Gökyüzüne Yükseliş',
        slug: 'jaya-04',
        duration: '24:30',
        summary: 'Cricket ve arkadaşları Going Merry\'yi gökyüzüne çıkış için hazırlar. Devasa geyser Knock-Up Stream patlar ve gemiyi 10.000 metre yukarı fırlatır. Mürettebat, bulutların üstündeki Beyaz Deniz\'e ulaşır. Gökyüzü adası gerçekmiş!',
      },
    ],
  },
  {
    name: 'Skypiea',
    slug: 'skypiea',
    saga: 'sky-island',
    cover: '/arcs/skypiea.jpg',
    episodeCount: 18,
    summary: '10.000 metre yükseklikteki gökyüzü adası Skypiea\'da, kendini tanrı ilan eden Enel\'e karşı epik bir savaş. Altın şehir efsanesi gerçek olabilir mi?',
    detailedSummary: 'Hasır Şapkalar, 10.000 metre yükseklikte bulutlardan oluşan gökyüzü adası Skypiea\'ya ulaşırlar. Ada, "Tanrı" Enel tarafından korku imparatorluğu ile yönetilmektedir. Enel, Goro Goro (yıldırım) meyvesiyle inanılmaz güçlüdür ve Mantra (Kenbunshoku Haki\'nin Skypiea versiyonu) ile adada olan her şeyi duyabilir. Enel\'in planı adayı yok edip Ay\'a gitmektir. Adanın iki halkı — Skypiea yerlileri ve Shandora savaşçıları — 400 yıldır savaşmaktadır. 400 yıl önce Knock-Up Stream, Jaya\'nın bir parçasını gökyüzüne fırlatmıştır. Altın şehir Shandora bu parçanın üzerindeydi! Mont Blanc Noland yalancı değildi — altın şehir gökyüzüne uçmuştu. Enel\'in "Hayatta Kalma Oyunu"nda herkes birbirine karşı savaştırılır. Luffy, lastik vücudu sayesinde yıldırıma karşı bağışıklık taşıyan tek kişidir. Enel\'i yener ve Altın Çan\'ı çalarak 400 yıl sonra sesin yeryüzüne ulaşmasını sağlar. Cricket sonunda atası Noland\'ın haklı olduğunu duyar.',
    keyEvents: [
      'Skypiea\'ya ulaşış ve gökyüzü kültürü',
      'Enel\'in korku yönetimi',
      'Shandora savaşçıları vs Skypiea yerlileri',
      'Altın şehir Shandora\'nın gökyüzünde olduğu gerçeği',
      'Enel\'in Hayatta Kalma Oyunu',
      'Luffy vs Enel — lastik yıldırıma bağışık',
      'Altın Çan\'ın 400 yıl sonra çalması',
      'Noland\'ın masumiyetinin kanıtı',
    ],
    themes: ['Tanrılık İddiası ve Kibir', 'Toprak Savaşları', 'Efsanelerin Gerçekliği', '400 Yıllık Yanlış Anlama'],
    location: 'Skypiea, Upper Yard (Eski Shandora)',
    villain: 'Enel',
    characters: ['luffy', 'zoro', 'nami', 'sanji', 'usopp', 'chopper', 'robin', 'enel'],
    episodes: [
      {
        number: 1,
        title: 'Beyaz Deniz',
        slug: 'skypiea-01',
        duration: '24:00',
        summary: 'Mürettebat bulutların üstündeki Beyaz Deniz\'e ulaşır. Gökyüzü insanları, sırtlarında küçük kanatlar taşır. Conis ve babası mürettebatı karşılar. Gökyüzünde farklı kurallar ve kültür vardır.',
      },
      {
        number: 2,
        title: 'Angel Island',
        slug: 'skypiea-02',
        duration: '24:30',
        summary: 'Angel Island\'da gökyüzü kültürünü keşfederler. Dial teknolojisi — deniz kabuklarına depolanan enerji — her yerde kullanılmaktadır. Mürettebat, Tanrı Enel\'in yasalarını çiğneyerek Upper Yard\'a girmeye karar verir.',
      },
      {
        number: 3,
        title: 'Tanrı Enel',
        slug: 'skypiea-03',
        duration: '24:00',
        summary: 'Enel\'in gücü ve Mantra yeteneği ortaya çıkar. Goro Goro meyvesiyle yıldırım oluşturabilir ve Mantra ile adada olan her şeyi duyabilir. Rahipleri Upper Yard\'ı korumaktadır. Kim girerse "Tanrının gazabı"yla cezalandırılır.',
      },
      {
        number: 4,
        title: 'Hayatta Kalma Oyunu',
        slug: 'skypiea-04',
        duration: '24:30',
        summary: 'Enel, acımasız bir "Hayatta Kalma Oyunu" başlatır. 80 kişiden sadece 5\'i hayatta kalacaktır. Shandora savaşçıları, Enel\'in rahipleri ve Hasır Şapkalar birbirlerine karşı savaştırılır.',
      },
      {
        number: 5,
        title: 'Shandora\'nın Savaşçıları',
        slug: 'skypiea-05',
        duration: '25:00',
        summary: 'Shandora savaşçılarının 400 yıllık mücadelesi anlatılır. Kalgara ve Mont Blanc Noland\'ın dostluk hikayesi ortaya çıkar. Noland, Shandora\'ya gelmiş ve Kalgara ile dost olmuştur. Jaya\'nın gökyüzüne fırlatılmasıyla ayrılmışlardır.',
      },
      {
        number: 6,
        title: 'Maxim',
        slug: 'skypiea-06',
        duration: '24:00',
        summary: 'Enel\'in gerçek planı ortaya çıkar: Maxim adlı devasa gemisiyle Skypiea\'yı yok edip Ay\'a gidecektir. Enel, tüm adayı yıldırımlarla vurmaya başlar. Panik ve kaos yayılır.',
      },
      {
        number: 7,
        title: 'Luffy vs Enel',
        slug: 'skypiea-07',
        duration: '25:00',
        summary: 'Luffy, Enel ile yüzleşir. Enel, 200 milyon voltluk yıldırım atar ama Luffy etkilenmez — lastik elektriği iletmez! Enel şok olur: "Bu imkansız!" Luffy, Enel\'in en büyük kabusu olur.',
      },
      {
        number: 8,
        title: 'Altın Çan',
        slug: 'skypiea-08',
        duration: '24:30',
        summary: 'Luffy, altından yapılmış bir top kullanarak kolunu Enel\'in gemisine doğru fırlatır. Enel\'i son darbeyle yener ve devasa Altın Çan\'ı çalar. 400 yıl sonra çanın sesi yeryüzüne ulaşır.',
      },
      {
        number: 9,
        title: 'Noland\'ın Mirası',
        slug: 'skypiea-09',
        duration: '24:00',
        summary: 'Altın Çan\'ın sesi Jaya\'ya kadar ulaşır. Cricket, atası Noland\'ın haklı olduğunu duyar ve gözyaşlarına boğulur. Altın şehir gerçekmiş ve gökyüzündeymiş! 400 yıllık "yalancı" damgası silinir.',
      },
      {
        number: 10,
        title: 'Barış ve Kutlama',
        slug: 'skypiea-10',
        duration: '24:30',
        summary: 'Enel yenildikten sonra Skypiea ve Shandora halkları 400 yıl sonra barış yapar. Dev bir kutlama düzenlenir. Mürettebat, gökyüzü insanlarıyla birlikte şölen yapar.',
      },
      {
        number: 11,
        title: 'Poneglyph\'in Sırrı',
        slug: 'skypiea-11',
        duration: '24:00',
        summary: 'Robin, Upper Yard\'daki Poneglyph\'i okur. Üzerinde eski silah Poseidon\'un bilgileri yazmaktadır. Gold Roger\'ın da buraya geldiğini ve Poneglyph\'e bir mesaj bıraktığını keşfeder.',
      },
      {
        number: 12,
        title: 'Altın Hazine',
        slug: 'skypiea-12',
        duration: '24:30',
        summary: 'Mürettebat, Shandora\'nın altın hazinelerinden bir miktar alır. Nami, altın diallerle dolu bir çanta bulur. Skypiea\'dan ayrılış hazırlıkları başlar.',
      },
      {
        number: 13,
        title: 'Gökyüzünden İniş',
        slug: 'skypiea-13',
        duration: '24:00',
        summary: 'Mürettebat, Octopus Balon ile gökyüzünden iner. Aşağıda onları bekleyen maceralara hazırlanırlar. Altın hazineler ve Dial teknolojisi yanlarındadır.',
      },
      {
        number: 14,
        title: 'Enel\'in Ay Yolculuğu',
        slug: 'skypiea-14',
        duration: '24:30',
        summary: 'Enel, Maxim ile Ay\'a ulaşır. Orada eski bir medeniyetin kalıntılarını ve otomatik robotları bulur. Ay\'daki eski şehir, gökyüzü insanlarının kökenini açığa çıkarır.',
      },
      {
        number: 15,
        title: 'Long Ring Long Land\'a Doğru',
        slug: 'skypiea-15',
        duration: '24:00',
        summary: 'Mürettebat, Jaya yakınlarına iner. Altınları paraya çevirirler. Yeni maceralar için hazırlanırken Log Pose bir sonraki adayı işaret eder.',
      },
      {
        number: 16,
        title: 'Ödüller Güncelleniyor',
        slug: 'skypiea-16',
        duration: '24:30',
        summary: 'Hasır Şapkaların ödülleri güncellenir. Luffy\'nin ödülü 100 milyondan 300 milyona çıkar. Zoro\'nun da ilk ödül posteri yayınlanır. Dünya Hükümeti, Hasır Şapkaları ciddiye almaya başlar.',
      },
      {
        number: 17,
        title: 'Denizde Yeni Günler',
        slug: 'skypiea-17',
        duration: '24:00',
        summary: 'Mürettebat, günlük hayatlarına devam eder. Robin artık grubun bir parçası olmuştur. Luffy, Usopp ve Chopper balık tutarken Sanji yeni tarifler dener. Nami harita çizer.',
      },
      {
        number: 18,
        title: 'Altın Çanın Sesi',
        slug: 'skypiea-18',
        duration: '24:30',
        summary: 'Skypiea macerası tamamen sona erer. Cricket ve Masira, denizde altın çanın sesini dinleyerek huzur bulur. Mürettebat yeni adalara doğru ilerler. Gökyüzü adası serüveni, One Piece\'in en büyülü arclarından biri olarak tarihe geçer.',
      },
    ],
  },
]
