import type { Arc } from '@/types'

export const SKY_ISLAND_ARCS: Arc[] = [
  {
    name: 'Jaya',
    slug: 'jaya',
    saga: 'sky-island',
    cover: '/arcs/jaya.webp',
    episodeCount: 8,
    summary: 'Gökyüzü adası efsanesinin peşine düşen Hasır Şapkalar, Jaya adasında Bellamy ile karşılaşır ve devasa geyserleri keşfeder.',
    detailedSummary: 'Bir gökten düşen gemi mürettebatı şaşırtır ve gökyüzü adaları efsanesini araştırmaya başlarlar. Jaya adasının Mock Town kasabasında korsanlar rüyalara inanmaz ve onlarla alay eder. Bellamy, Spring Spring meyvesiyle Luffy\'ye saldırır ama Luffy karşılık vermez — çünkü "kavga etmeye değmez." Blackbeard (Marshall D. Teach) ile ilk karşılaşma burada gerçekleşir. Teach, Luffy\'nin rüyasının büyüklüğünü takdir eder: "İnsanların hayalleri asla bitmez!" Mürettebat, dalgıç Mont Blanc Cricket\'i bulur. Cricket, 400 yıl önce gökyüzü adalarının varlığını iddia edip "yalancı" ilan edilen atası Noland\'ın onurunu kurtarmaya çalışmaktadır. Bellamy, Cricket\'in altınlarını çalar. Luffy tek bir yumrukla Bellamy\'yi yener. Cricket ve arkadaşları, mürettebatın gökyüzüne çıkması için devasa geyser Knock-Up Stream\'i bulmalarına yardım eder.',
    keyEvents: [
      'Gökyüzü adası araştırması başlar',
      'Bellamy ile karşılaşma',
      'Blackbeard ile ilk tanışma',
      'Mont Blanc Cricket ve Noland efsanesi',
      'Luffy tek yumrukla Bellamy\'yi yener',
      'Knock-Up Stream ile gökyüzüne çıkış',
    ],
    themes: ['Rüyalara İnanmak', 'Alay ve Direnç', 'Efsaneler ve Gerçeklik'],
    location: 'Jaya, Mock Town',
    villain: 'Bellamy',
    characters: ['luffy', 'zoro', 'nami', 'robin', 'blackbeard'],
    episodes: [
      {
        number: 1,
        title: 'Seyir Pusulası Neden Yukarıyı Gösteriyor?',
        slug: 'jaya-01',
        duration: '24:00',
        summary: 'Gökyüzünden düşen eski bir gemi mürettebatı şaşkına çevirir. İçinden çıkan harita ve eşyalar gökyüzü adalarının varlığına işaret eder. Mürettebat araştırmaya başlar ve South Bird avına çıkar.',
      },
      {
        number: 2,
        title: 'Asla Hayal Kurma',
        slug: 'jaya-02',
        duration: '24:00',
        summary: 'Jaya adasının Mock Town kasabasına varırlar. Korsanların rüyalarla alay ettiği vahşi bir atmosfer vardır. Gökyüzü adalarından bahsetmek gülünç karşılanır ve mürettebat hor görülür.',
      },
      {
        number: 3,
        title: 'İnsanların Hayalleri',
        slug: 'jaya-03',
        duration: '24:30',
        summary: 'Bellamy ve adamları Luffy ve Zoro\'yu döver ama ikisi karşılık vermez. Nami öfkelenir ama Luffy "Bu kavga etmeye değmez" der. Blackbeard ile karşılaşırlar: "İnsanların hayalleri asla bitmez!" diyen farklı bir korsan.',
      },
      {
        number: 4,
        title: 'Yalancı Noland',
        slug: 'jaya-04',
        duration: '24:00',
        summary: 'Mürettebat, dalgıç Mont Blanc Cricket\'i bulur. Cricket, 400 yıl önce gökyüzü adalarının varlığını iddia edip "yalancı" ilan edilen atası Noland\'ın onurunu kurtarmaya çalışmaktadır. Noland\'ın trajik hikayesi anlatılır.',
      },
      {
        number: 5,
        title: 'Hadi Yiyelim',
        slug: 'jaya-05',
        duration: '24:00',
        summary: 'Cricket, yıllardır deniz altında altın şehri aramaktadır. Maymun kıyafetli Masira ve orangutan Shoujou, Cricket\'in sadık yardımcılarıdır. Birlikte Knock-Up Stream\'in yerini ve zamanını hesaplarlar.',
      },
      {
        number: 6,
        title: 'Yüz Milyonluk Adam',
        slug: 'jaya-06',
        duration: '24:30',
        summary: 'Bellamy ve adamları Cricket\'in evine saldırır. Cricket\'in yıllarca deniz altından topladığı altınları çalar ve onu yaralar. Masira ve Shoujou da ağır yaralanır. Mürettebat durumu öğrenince öfkelenir.',
      },
      {
        number: 7,
        title: 'Dünyanın En Yüksek Otoritesi',
        slug: 'jaya-07',
        duration: '24:00',
        summary: 'Luffy, Bellamy\'yi tek bir yumrukla yere serer. Spring Spring meyvesinin gücü bile Luffy\'nin kararlılığı karşısında anlamsızdır. Önceki sessizliğinin sebebi buydu: savaşmaya değmeyen birine güç kullanmazdı. Altınlar Cricket\'e geri döner.',
      },
      {
        number: 8,
        title: 'Fırlatan Akıntı',
        slug: 'jaya-08',
        duration: '24:30',
        summary: 'Cricket ve arkadaşları Going Merry\'yi gökyüzüne çıkış için hazırlar. Devasa geyser Knock-Up Stream patlar ve gemiyi 10.000 metre yukarı fırlatır. Mürettebat, bulutların üstündeki Beyaz Deniz\'e ulaşır. Gökyüzü adası gerçekmiş!',
      },
    ],
  },
  {
    name: 'Skypiea',
    slug: 'skypiea',
    saga: 'sky-island',
    cover: '/arcs/skypiea.webp',
    episodeCount: 25,
    summary: '10.000 metre yükseklikteki gökyüzü adası Skypiea\'da, kendini tanrı ilan eden Enel\'e karşı epik bir savaş. Altın şehir efsanesi gerçek olabilir mi?',
    detailedSummary: 'Hasır Şapkalar, 10.000 metre yükseklikte bulutlardan oluşan gökyüzü adası Skypiea\'ya ulaşırlar. Ada, "Tanrı" Enel tarafından korku imparatorluğu ile yönetilmektedir. Enel, Goro Goro (yıldırım) meyvesiyle inanılmaz güçlüdür ve Mantra (Kenbunshoku Haki\'nin Skypiea versiyonu) ile adada olan her şeyi duyabilir. Enel\'in planı adayı yok edip Ay\'a gitmektir. Adanın iki halkı — Skypiea yerlileri ve Shandora savaşçıları — 400 yıldır savaşmaktadır. 400 yıl önce Knock-Up Stream, Jaya\'nın bir parçasını gökyüzüne fırlatmıştır. Altın şehir Shandora bu parçanın üzerindeydi! Mont Blanc Noland yalancı değildi — altın şehir gökyüzüne uçmuştu. Enel\'in "Hayatta Kalma Oyunu"nda herkes birbirine karşı savaştırılır. Luffy, lastik vücudu sayesinde yıldırıma karşı bağışıklık taşıyan tek kişidir. Enel\'i yener ve Altın Çan\'ı çalarak 400 yıl sonra sesin yeryüzüne ulaşmasını sağlar. Cricket sonunda atası Noland\'ın haklı olduğunu duyar.',
    keyEvents: [
      'Skypiea\'ya ulaşış ve gökyüzü kültürü',
      'Enel\'in korku yönetimi',
      'Shandora savaşçıları vs Skypiea yerlileri',
      'Altın şehir Shandora\'nın gökyüzünde olduğu gerçeği',
      'Enel\'in Hayatta Kalma Oyunu',
      'Luffy vs Enel — lastik yıldırıma bağışık',
      'Altın Çan\'ın 400 yıl sonra çalması',
      'Noland\'ın masumiyetinin kanıtı',
    ],
    themes: ['Tanrılık İddiası ve Kibir', 'Toprak Savaşları', 'Efsanelerin Gerçekliği', '400 Yıllık Yanlış Anlama'],
    location: 'Skypiea, Upper Yard (Eski Shandora)',
    villain: 'Enel',
    characters: ['luffy', 'zoro', 'nami', 'sanji', 'usopp', 'chopper', 'robin', 'enel'],
    episodes: [
      {
        number: 1,
        title: 'Cennet Kapısı',
        slug: 'skypiea-01',
        duration: '24:00',
        summary: 'Mürettebat bulutların üstündeki Beyaz Deniz\'e ulaşır. Gökyüzü insanları, sırtlarında küçük kanatlar taşır. Conis ve babası mürettebatı karşılar. Gökyüzünde farklı kurallar ve kültür vardır.',
      },
      {
        number: 2,
        title: 'Melek Sahili',
        slug: 'skypiea-02',
        duration: '24:30',
        summary: 'Angel Island\'da gökyüzü kültürünü keşfederler. Dial teknolojisi — deniz kabuklarına depolanan enerji — her yerde kullanılmaktadır. Extol ile ödeme sistemi, Island Cloud ve Sea Cloud ayrımı öğrenilir.',
      },
      {
        number: 3,
        title: 'İlahi Adalet',
        slug: 'skypiea-03',
        duration: '24:00',
        summary: 'Mürettebat, Tanrı Enel\'in yasalarını çiğneyerek Upper Yard\'a girmeye karar verir. Upper Yard, Vearth (gerçek toprak) içeren kutsal bölgedir. Enel\'in rahipleri bu toprakları korumaktadır.',
      },
      {
        number: 4,
        title: 'Test',
        slug: 'skypiea-04',
        duration: '24:00',
        summary: 'Enel\'in gücü ve Mantra yeteneği ortaya çıkar. Goro Goro meyvesiyle yıldırım oluşturabilir ve Mantra ile adada olan her şeyi duyabilir. Kim girerse "Tanrının gazabı"yla cezalandırılır.',
      },
      {
        number: 5,
        title: 'Tanrı\'nın Adası\'nda Macera',
        slug: 'skypiea-05',
        duration: '24:30',
        summary: 'Enel\'in dört rahibi tanıtılır: Satori, Shura, Gedatsu ve Ohm. Her birinin kendine özgü Dial savaş teknikleri ve sınavları vardır. Mürettebat Upper Yard ormanlarında rahiplerle karşılaşmaya başlar.',
      },
      {
        number: 6,
        title: 'Bulutlardaki Saklı Köy',
        slug: 'skypiea-06',
        duration: '24:00',
        summary: 'Luffy, Sanji ve Usopp, Top Sınavı\'nda rahip Satori ile karşılaşır. Satori\'nin Mantra yeteneği saldırıları önceden sezebilir. Impact Dial\'ın yıkıcı gücü ortaya çıkar. Zorlu bir mücadelenin ardından Satori yenilir.',
      },
      {
        number: 7,
        title: 'Uvertür',
        slug: 'skypiea-07',
        duration: '24:30',
        summary: 'Robin, Upper Yard\'da eski kalıntıları araştırır ve Shandora medeniyetinin izlerini bulur. Zoro, Nami ve Chopper ormanda tehlikeli yaratıklarla mücadele eder. Gökyüzü adasının altında saklı bir tarih vardır.',
      },
      {
        number: 8,
        title: 'Vearth',
        slug: 'skypiea-08',
        duration: '24:30',
        summary: 'Enel, acımasız bir "Hayatta Kalma Oyunu" başlatır. 80 kişiden sadece 5\'i hayatta kalacaktır. Shandora savaşçıları, Enel\'in rahipleri ve Hasır Şapkalar birbirlerine karşı savaştırılır.',
      },
      {
        number: 9,
        title: 'Dial Savaşı',
        slug: 'skypiea-09',
        duration: '24:00',
        summary: 'Shandora savaşçılarının lideri Wyper tanıtılır. 400 yıldır atalarının topraklarını geri almak için savaşan bir halk. Wyper\'ın kararlılığı ve Reject Dial\'ın ölümcül gücü ortaya çıkar.',
      },
      {
        number: 10,
        title: 'Korsan Luffy, Berserker Wyper\'a Karşı',
        slug: 'skypiea-10',
        duration: '25:00',
        summary: '400 yıl öncesine gidilir. Kaşif Mont Blanc Noland, Shandora adasına ulaşır ve savaşçı Kalgara ile karşılaşır. İlk başta düşman olan ikili, Noland\'ın halkı vebadan kurtarmasıyla dost olur.',
      },
      {
        number: 11,
        title: 'Korsan Chopper, Rahip Gedatsu\'ya Karşı',
        slug: 'skypiea-11',
        duration: '24:30',
        summary: 'Noland ve Kalgara\'nın dostluğu derinleşir. Noland, ağaçları kesmek zorunda kalır ve Kalgara bunu ihanet sanır. Yanlış anlama çözüldüğünde Noland çoktan gitmiştir. Kalgara, Altın Çan\'ı çalarak Noland\'ı geri çağırmaya çalışır.',
      },
      {
        number: 12,
        title: 'Korsan Robin, Başrahip Yama\'ya Karşı',
        slug: 'skypiea-12',
        duration: '24:00',
        summary: 'Noland, kralını altın şehre götürmek için geri döner ama ada Knock-Up Stream tarafından gökyüzüne fırlatılmıştır. Kral, Noland\'ı "yalancı" ilan edip idam ettirir. Kalgara ise gökyüzünde Noland\'ın geri döneceğine inanarak Altın Çan\'ı çalmaya devam eder.',
      },
      {
        number: 13,
        title: 'Konçerto',
        slug: 'skypiea-13',
        duration: '24:30',
        summary: 'Kalgara\'nın torununun torunu Wyper, atalarının yeminini sürdürür. Altın Çan\'ı tekrar çalarak Noland\'ın soyuna mesaj göndermek istemektedir. Hayatta Kalma Oyunu kızışır, savaşçılar birer birer elenir.',
      },
      {
        number: 14,
        title: 'Korsan Zoro, Rahip Ohm\'a Karşı',
        slug: 'skypiea-14',
        duration: '24:00',
        summary: 'Zoro, rahip Ohm ile kılıç savaşına girer. Ohm\'un Eisen Whip\'i ve Mantra yeteneği Zoro\'yu zorlar. Chopper ve Gedatsu\'nun komik ama tehlikeli karşılaşması yaşanır. Gedatsu kendi beceriksizliğiyle yenilir.',
      },
      {
        number: 15,
        title: 'Quintet',
        slug: 'skypiea-15',
        duration: '24:30',
        summary: 'Zoro, Ohm\'u yoğun bir mücadelenin ardından yener. 108 Pound Hou tekniği ile Ohm\'un demir bulutunu parçalar. Sanji, Shandora kalıntılarında Enel\'in planını keşfeder ve mürettebatı uyarmaya çalışır.',
      },
      {
        number: 16,
        title: 'Conis',
        slug: 'skypiea-16',
        duration: '24:00',
        summary: 'Enel\'in gerçek planı ortaya çıkar: Maxim adlı devasa gemisiyle Skypiea\'yı yok edip Ay\'a gidecektir. Sanji, Maxim\'i sabote etmeye çalışır ama Enel\'in yıldırımıyla yere serilir.',
      },
      {
        number: 17,
        title: 'Deathpiea',
        slug: 'skypiea-17',
        duration: '24:30',
        summary: 'Enel, tüm adayı yıldırımlarla vurmaya başlar. Devar — gökyüzü adasının bulut denizi — yok edilmeye başlanır. Panik ve kaos yayılır. Nami, Enel\'in yanında Maxim\'e götürülür.',
      },
      {
        number: 18,
        title: 'Sevdiğini Kurtarmak İçin Ön Saflarda',
        slug: 'skypiea-18',
        duration: '24:00',
        summary: 'Luffy, dev fasulye sırığını tırmanarak Enel\'e ulaşmaya çalışır. Wyper, son Reject Dial atışıyla Enel\'i vurur ama Enel kendi kalbini yıldırımla yeniden başlatır. Enel yenilmez görünmektedir.',
      },
      {
        number: 19,
        title: 'Tanrı Katili',
        slug: 'skypiea-19',
        duration: '25:00',
        summary: 'Luffy, Enel ile yüzleşir. Enel, 200 milyon voltluk yıldırım atar ama Luffy etkilenmez — lastik elektriği iletmez! Enel şok olur: "Bu imkansız!" Luffy, Enel\'in en büyük kabusu olur.',
      },
      {
        number: 20,
        title: 'Shandora\'nın Ateşi',
        slug: 'skypiea-20',
        duration: '25:00',
        summary: 'Luffy ve Enel\'in savaşı Maxim\'in üzerinde devam eder. Enel, yıldırım işe yaramayınca fiziksel saldırılara ve altın topuzla Luffy\'nin kolunu etkisiz hale getirmeye çalışır. Luffy altın topuzu silah olarak kullanmaya karar verir.',
      },
      {
        number: 21,
        title: 'Raigo',
        slug: 'skypiea-21',
        duration: '24:30',
        summary: 'Enel, en güçlü tekniği Raigou\'yu kullanarak devasa bir yıldırım küresi oluşturur. Tüm Angel Island\'ı yok etmekle tehdit eder. Usopp ve diğerleri Maxim\'in motorunu sabote ederek Raigou\'yu zayıflatır.',
      },
      {
        number: 22,
        title: 'Adanın Şarkısı',
        slug: 'skypiea-22',
        duration: '24:30',
        summary: 'Luffy, altından yapılmış topuzu kullanarak kolunu Altın Çan\'a doğru fırlatır. Enel\'i son darbeyle yener ve devasa Altın Çan\'ı çalar. 400 yıl sonra çanın sesi gökyüzünden yeryüzüne ulaşır.',
      },
      {
        number: 23,
        title: 'Fantazi',
        slug: 'skypiea-23',
        duration: '24:00',
        summary: 'Altın Çan\'ın sesi Jaya\'ya kadar ulaşır. Cricket, atası Noland\'ın haklı olduğunu duyar ve gözyaşlarına boğulur. Altın şehir gerçekmiş ve gökyüzündeymiş! 400 yıllık "yalancı" damgası silinir. Wyper ve Skypiea halkı barış yapar.',
      },
      {
        number: 24,
        title: 'Buraya Kadar Başardım',
        slug: 'skypiea-24',
        duration: '24:30',
        summary: 'Skypiea ve Shandora halkları 400 yıl sonra barış yapar ve dev bir kutlama düzenlenir. Robin, Poneglyph\'i okur ve Gold Roger\'ın mesajını keşfeder. Mürettebat altın hazinelerle birlikte ayrılış hazırlığı yapar.',
      },
      {
        number: 25,
        title: 'Final',
        slug: 'skypiea-25',
        duration: '24:00',
        summary: 'Mürettebat, Octopus Balon ile gökyüzünden iner. Conis ve tüm ada halkı onları selamlar. Enel, Maxim ile Ay\'a ulaşır ve eski bir medeniyetin kalıntılarını bulur. Gökyüzü adası serüveni, One Piece\'in en büyülü arclarından biri olarak sona erer.',
      },
    ],
  },
]
