import type { Arc } from '@/types'

export const SUMMIT_WAR_ARCS: Arc[] = [
  {
    name: 'Sabaody Archipelago',
    slug: 'sabaody-archipelago',
    saga: 'summit-war',
    cover: '/arcs/sabaody.jpg',
    episodeCount: 11,
    summary: 'Yeni Dünya\'ya geçiş noktası Sabaody\'de 11 Supernova bir araya gelir. Celestial Dragon olayı mürettebatın ayrılmasına yol açar.',
    detailedSummary: 'Red Line\'ın önündeki son durak Sabaody Archipelago — dev mangrove ağaçlarından oluşan takımadalar. Burada 11 Supernova (200 milyon Berry üstü ödüle sahip çaylak korsanlar) bir araya gelir: Luffy, Zoro, Law, Kid, Bonney ve diğerleri. Rayleigh — Korsan Kralı Roger\'ın sağ kolu — burada gemi kaplama ustası olarak gizlenmektedir. Luffy, bir Celestial Dragon\'ın köleye şiddet uygulamasına dayanamaz ve onu yumruklar. Bu, bir Amiral çağırılmasına neden olur. Kizaru, Sentoumaru ve Pacifista\'lar gelir. Mürettebat, bu güce karşı tamamen acizdir. Kuma belirir ve mürettebatı tek tek farklı adalara fırlatır. Luffy, arkadaşlarını kurtaramadan izlemek zorunda kalır. "Arkadaşlarımı koruyamadım" — Luffy\'nin en karanlık anı.',
    keyEvents: [
      '11 Supernova\'nın bir araya gelmesi',
      'Rayleigh ile tanışma',
      'Luffy Celestial Dragon\'ı yumruklar',
      'Amiral Kizaru\'nun gelişi',
      'Kuma mürettebatı ayırır',
      'Luffy\'nin çaresizliği',
    ],
    themes: ['Güç Farkı Gerçeği', 'Kölelik ve Eşitsizlik', 'Celestial Dragon Sistemi', 'Kayıp ve Çaresizlik'],
    location: 'Sabaody Archipelago',
    villain: 'Kizaru, Sentoumaru',
    characters: ['luffy', 'zoro', 'nami', 'sanji', 'law', 'kid', 'kizaru'],
    episodes: [
      { number: 1, title: 'Uçan Balık Binicileri', slug: 'sabaody-01', duration: '24:30', summary: 'Mürettebat, dev mangrove ağaçlarından oluşan Sabaody\'ye ulaşır. Sabun kabarcıklarıyla kaplı renkli bir ada. Ancak karanlık yüzü var: köle ticareti ve Celestial Dragonların zulmü.' },
      { number: 2, title: 'Demir Maske Duval', slug: 'sabaody-02', duration: '24:30', summary: 'Sabaody\'de 200 milyon Berry üstü ödüle sahip 11 çaylak korsan bir araya gelir. Trafalgar Law, Eustass Kid, X Drake, Bonney ve diğerleri. Herkes birbirini ölçer ve süzer.' },
      { number: 3, title: 'Duval\'in Trajedisi', slug: 'sabaody-03', duration: '24:30', summary: 'Celestial Dragon Saint Charlos, bir köleyi silahla vurur. Luffy dayanamaz ve Charlos\'u yumruklar. Bu, Marine HQ\'dan bir Amiral çağırılması anlamına gelir. Herkes şoktadır.' },
      { number: 4, title: 'Dans Eden Kabarcık Takımadası Macerası', slug: 'sabaody-04', duration: '24:30', summary: 'Silvers Rayleigh — Korsan Kralı Roger\'ın sağ kolu, "Karanlık Kral" — köle pazarında ortaya çıkar. Haki ile herkesi bayıltır. Roger\'ın yolculuğu hakkında ipuçları verir ama "One Piece var mı?" sorusuna cevap vermez.' },
      { number: 5, title: 'Tarihin Közleri', slug: 'sabaody-05', duration: '24:30', summary: 'Amiral Kizaru, Pika Pika meyvesiyle ışık hızında Sabaody\'ye gelir. Supernova\'ları tek tek yener. Luffy bile Kizaru\'ya karşı çaresizdir. Güç farkı korkunçtur.' },
      { number: 6, title: 'Müzayede Evi Olayı', slug: 'sabaody-06', duration: '24:30', summary: 'Kuma benzeri robotlar Pacifista\'lar sahneye çıkar. Mürettebat, bir Pacifista\'yı bile zar zor yener. Sentoumaru ve daha fazla Pacifista gelir. Durum umutsuzlaşır.' },
      { number: 7, title: 'Kaos İçinde Bir Ada', slug: 'sabaody-07', duration: '24:30', summary: 'Supernova\'lar Pacifista\'lara ve Marine\'lere karşı kendi savaşlarını verir. Kid ve Law kendi yollarıyla direnir. Zoro ağır yaralı halde Kuma\'nın önünde durur. Her korsan için hayatta kalma mücadelesi.' },
      { number: 8, title: 'Roger ve Rayleigh', slug: 'sabaody-08', duration: '24:30', summary: 'Rayleigh, Roger Korsanları\'nın yolculuğundan parçalar anlatır. Gemi kaplaması için gereken süreyi açıklar. Luffy ve mürettebat, Yeni Dünya\'ya geçiş planını öğrenir ama planlar altüst olmak üzeredir.' },
      { number: 9, title: 'Kizaru Gelir', slug: 'sabaody-09', duration: '24:30', summary: 'Gerçek Kuma belirir ve Nikyu Nikyu meyvesiyle mürettebat üyelerini tek tek farklı adalara fırlatır. Zoro, Nami, Robin, Franky, Brook... birer birer kaybolur. Luffy çaresizce izler.' },
      { number: 10, title: 'Kizaru, 4 Kaptana Karşı', slug: 'sabaody-10', duration: '24:30', summary: 'Her mürettebat üyesi farklı bir diyara fırlatılır. Zoro Kuraigana Adası\'na, Nami Weatheria\'ya, Sanji Kamabakka Krallığı\'na, Robin Tequila Wolf\'a düşer. Herkes yalnız ve çaresizdir.' },
      { number: 11, title: 'Hiçbirini Kurtaramadım!!!', slug: 'sabaody-11', duration: '24:30', summary: 'Son kalan Luffy da Kuma tarafından fırlatılır. "Arkadaşlarımı koruyamadım!" — Luffy\'nin en karanlık anı. Mürettebat dünyanın dört bir yanına dağılmıştır. Her biri farklı bir adada, farklı bir macerada.' },
    ],
  },
  {
    name: 'Amazon Lily',
    slug: 'amazon-lily',
    saga: 'summit-war',
    cover: '/arcs/amazon-lily.jpg',
    episodeCount: 5,
    summary: 'Luffy, sadece kadınların yaşadığı Amazon Lily adasına düşer. Shichibukai Boa Hancock ile karşılaşır.',
    detailedSummary: 'Kuma tarafından fırlatılan Luffy, Calm Belt\'teki Amazon Lily adasına düşer. Bu ada, Kuja kabilesinin yaşadığı ve erkeklerin yasak olduğu bir yerdir. Kadın savaşçılar Haki kullanabilmektedir. Ada\'nın imparatoriçesi ve Shichibukai Boa Hancock, dünyanın en güzel kadınıdır. Mero Mero meyvesiyle insanları taşa çevirebilir — ama Luffy etkilenmez! Hancock\'un geçmişi ortaya çıkar: çocukken Celestial Dragonlar tarafından köle yapılmış ve Şeytan Meyvesi yemeye zorlanmıştır. Fisher Tiger sayesinde kurtulmuştur. Luffy, Hancock\'un sırtındaki köle damgasını görünce öfkelenir — Celestial Dragonlara karşı. Hancock, Luffy\'ye aşık olur ve onu Impel Down\'a ulaştırmak için yardım eder. Luffy, ağabeyi Ace\'in idam edileceğini öğrenmiştir.',
    keyEvents: [
      'Luffy Amazon Lily\'ye düşer',
      'Boa Hancock ile tanışma',
      'Hancock\'un kölelik geçmişi',
      'Luffy Mero Mero\'ya bağışık',
      'Ace\'in idamı haberi',
      'Hancock Luffy\'ye yardım eder',
    ],
    themes: ['Güzellik ve Acı', 'Kölelik ve Özgürlük', 'Aşk', 'Kardeşlik'],
    location: 'Amazon Lily',
    villain: undefined,
    characters: ['luffy', 'hancock'],
    episodes: [
      { number: 1, title: 'Kadınlar Adası\'ndaki Macera', slug: 'amazon-lily-01', duration: '24:30', summary: 'Luffy, sadece kadınların yaşadığı Amazon Lily\'ye düşer. Erkeklerin yasak olduğu adada saklanmaya çalışır. Kuja savaşçıları onu yakalar ve arenaya götürür.' },
      { number: 2, title: 'Korsan İmparatoriçe Boa Hancock', slug: 'amazon-lily-02', duration: '24:30', summary: 'Boa Hancock, Mero Mero meyvesiyle Luffy\'yi taşa çevirmeye çalışır ama Luffy etkilenmez — çünkü Hancock\'un güzelliğine karşı tamamen ilgisizdir. Hancock şok olur.' },
      { number: 3, title: 'Arena', slug: 'amazon-lily-03', duration: '24:30', summary: 'Luffy, arenada Hancock\'un kız kardeşleri Sandersonia ve Marigold ile savaşır. Boa kardeşlerin Zoan dönüşümleri ve Haki kullanımları Luffy\'yi zorlar. Luffy, sırtlarındaki köle damgasını korur ve Kuja savaşçılarının saygısını kazanır.' },
      { number: 4, title: 'Hancock\'un İtirafı', slug: 'amazon-lily-04', duration: '24:30', summary: 'Hancock\'un karanlık geçmişi: Celestial Dragonlar tarafından köle yapılmış, sırtına köle damgası vurulmuştur. Luffy, damgayı görünce öfkelenir — Hancock\'a değil, Celestial Dragonlara. Hancock ilk kez birine güvenir.' },
      { number: 5, title: 'Artık Bunu Kimse Durduramaz', slug: 'amazon-lily-05', duration: '24:30', summary: 'Luffy, ağabeyi Ace\'in Marine HQ\'da idam edileceğini öğrenir. Ace\'i kurtarmak için Impel Down\'a gitmeye karar verir. Hancock, Luffy\'ye aşık olmuştur ve onu gizlice Marine gemisiyle Impel Down\'a götürmeyi kabul eder.' },
    ],
  },
  {
    name: 'Impel Down',
    slug: 'impel-down',
    saga: 'summit-war',
    cover: '/arcs/impel-down.jpg',
    episodeCount: 10,
    summary: 'Luffy, ağabeyi Ace\'i kurtarmak için dünyanın en güvenli hapishanesine sızar. 6 katmanı geçmek zorundadır.',
    detailedSummary: 'Dünyanın en güvenli hapishanesi Impel Down, denizin altında 6 katmandan oluşur. Her katman daha ağır cezalar içerir: kan göletli orman, buz cehennemi, açlık cehennemi ve nihayet Level 6 — varlığı bile gizli tutulan sonsuz cehennem. Luffy, Hancock\'un yardımıyla gizlice hapishaneye sızar. Yolda beklenmedik müttefikler bulur: Mr. 2 Bon Clay (eski düşman, şimdi dost), Buggy (kaçış peşinde), Mr. 3 ve hatta Crocodile (ortak düşmana karşı). Hapishane müdürü Magellan\'ın Doku Doku meyvesi ölümcüldür. Luffy, zehirlenerek ölümün eşiğine gelir. Ivankov — Devrimci Ordunun komutanı, hormon insanı — Luffy\'yi tedavi eder ama ömründen 10 yıl çalar. Luffy, Ace\'e zamanında ulaşamaz — Ace zaten Marine HQ\'ya götürülmüştür. Luffy, hapishane kaçkınlarıyla birlikte Marine HQ\'ya yönelir. Mr. 2, herkesin kaçışı için kendini feda eder — kapıyı açık tutar ve arkasında kalır.',
    keyEvents: [
      'Luffy Impel Down\'a sızar',
      'Hapishane katmanları ve işkenceler',
      'Bon Clay ile tekrar karşılaşma',
      'Magellan\'ın zehiri ve Luffy\'nin zehirlenmesi',
      'Ivankov\'un tedavisi — 10 yıl ömür kaybı',
      'Crocodile ve Jinbe ile ittifak',
      'Ace\'e yetişememe',
      'Mr. 2\'nin fedakarlığı',
    ],
    themes: ['Kardeşlik ve Fedakarlık', 'Cehennem ve Kurtuluş', 'Eski Düşmanlar Yeni Dostlar', 'Zamana Karşı Yarış'],
    location: 'Impel Down',
    villain: 'Magellan',
    characters: ['luffy', 'buggy', 'crocodile', 'jinbe'],
    episodes: [
      { number: 1, title: 'Su Altı Hapishanesi Impel Down', slug: 'impel-down-01', duration: '24:30', summary: 'Luffy, Hancock\'un yardımıyla Impel Down\'a gizlice girer. Dünyanın en güvenli hapishanesi denizin altında devasa bir yapıdır. İlk katman: Kızıl Cehennem — zehirli orman ve kan göletleri.' },
      { number: 2, title: 'Denizin Şövalyesi Jinbe', slug: 'impel-down-02', duration: '24:30', summary: 'Luffy, Level 2 Vahşi Hayvanlar Cehennemi\'ne iner. Devasa Basilisk ve Manticore\'larla savaşır. Buggy ile karşılaşıp geçici ittifak kurar. Level 3\'te eski düşman Mr. 2 Bon Clay\'le tekrar karşılaşır — artık sadık bir dosttur.' },
      { number: 3, title: 'Bir Cehennemden Ötekine', slug: 'impel-down-03', duration: '24:30', summary: 'Hapishane müdürü Magellan, Doku Doku meyvesiyle Luffy\'ye saldırır. Zehir hidra başları Luffy\'yi sarar. Luffy ağır şekilde zehirlenir ve ölümün eşiğine gelir. Bon Clay, onu taşıyarak kaçırmaya çalışır.' },
      { number: 4, title: 'Kızgın Cehennem', slug: 'impel-down-04', duration: '24:30', summary: 'Gizli Level 5.5\'te Devrimci Ordu komutanı Emporio Ivankov ortaya çıkar. Hormon gücüyle Luffy\'yi tedavi eder. Tedavi 10 saat sürer ve Luffy\'nin ömründen 10 yıl çalar. Luffy, inanılmaz iradesiyle ayağa kalkar.' },
      { number: 5, title: 'Arkadaş', slug: 'impel-down-05', duration: '24:30', summary: 'Luffy, Level 5 Dondurucu Cehennem\'i geçerek varlığı gizli tutulan Level 6\'ya iner. Burada tarihin en tehlikeli suçluları vardır: Crocodile, Jinbe ve daha nicesi. Ace\'in hücresine ulaşır ama Ace zaten Marine HQ\'ya götürülmüştür!' },
      { number: 6, title: 'Umut Işığı', slug: 'impel-down-06', duration: '24:30', summary: 'Luffy, eski düşmanı Crocodile\'ı serbest bırakır. Jinbe de onlara katılır. Amaç: Impel Down\'dan kaçıp Marine HQ\'ya ulaşmak ve Ace\'i kurtarmak. Eski düşmanlar ortak düşmana karşı birleşir.' },
      { number: 7, title: 'Sonsuz Cehennem', slug: 'impel-down-07', duration: '24:30', summary: 'Luffy, Crocodile, Jinbe, Ivankov, Buggy ve yüzlerce mahkum Impel Down\'dan kaçmaya çalışır. Magellan peşlerindedir. Level 2\'deki kapıya ulaşmak zorundalar.' },
      { number: 8, title: 'Hiç Görülmemiş Bir İsyan', slug: 'impel-down-08', duration: '24:30', summary: 'Mr. 3\'ün mum gücü Magellan\'ın zehrine karşı kalkan oluşturur. Luffy, mumla kaplı yumruklarıyla Magellan\'a karşı durur. Kaçış gemisine ulaşmak için son düz.' },
      { number: 9, title: 'Güneş Işığına ve Özgürlüğe', slug: 'impel-down-09', duration: '24:30', summary: 'Kaçış kapısı içeriden açılmalıdır. Bon Clay, herkesin kaçması için kapıyı açık tutar ve arkada kalır. Magellan\'a karşı tek başına durur. "Dostluk yolunda pişmanlık yok!" — One Piece\'in en acı fedakarlıklarından biri.' },
      { number: 10, title: 'Teşekkürler', slug: 'impel-down-10', duration: '24:30', summary: 'Luffy ve müttefikleri Impel Down\'dan kaçar ve Marine HQ Marineford\'a doğru yol alır. Ace\'in idamına saatler kalmıştır. Beyaz Sakal korsanları da aynı hedefe ilerlemektedir. Tarihin en büyük savaşı başlamak üzere.' },
    ],
  },
  {
    name: 'Hasır Şapkaların Maceraları',
    slug: 'straw-hats-adventures',
    saga: 'summit-war',
    cover: '/arcs/straw-hats-adventures.webp',
    episodeCount: 1,
    summary: 'Hasır Şapka mürettebatının Kuma tarafından farklı adalara gönderilmesinin ardından yaşadıkları maceralar.',
    detailedSummary: 'Sabaody Takımadası\'nda Kuma tarafından dünyanın dört bir yanına fırlatılan Hasır Şapka mürettebatı üyelerinin her birinin düştüğü adalardaki maceraları anlatılır.',
    keyEvents: [
      'Mürettebat üyelerinin farklı adalardaki maceraları',
    ],
    themes: ['Ayrılık', 'Bireysel Gelişim'],
    location: 'Çeşitli Adalar',
    villain: '-',
    characters: ['luffy', 'zoro', 'nami', 'sanji', 'usopp', 'chopper', 'robin', 'franky', 'brook'],
    episodes: [
      { number: 1, title: 'Herhangi Bir Yere Gidebilseydin...', slug: 'straw-hats-adventures-01', duration: '24:30', summary: 'Hasır Şapka mürettebatının Kuma tarafından farklı adalara gönderilmesinin ardından yaşadıkları maceralar.' },
    ],
  },
  {
    name: 'Marineford',
    slug: 'marineford',
    saga: 'summit-war',
    cover: '/arcs/marineford.jpg',
    episodeCount: 17,
    summary: 'One Piece\'in en epik savaşı. Beyaz Sakal korsanları, Ace\'i kurtarmak için Deniz Kuvvetleri karargahına saldırır. Dünya değişir.',
    detailedSummary: 'One Piece tarihinin en büyük savaşı. Beyaz Sakal Edward Newgate, evlat edindiği Ace\'i kurtarmak için tüm filosuyla Marine HQ\'ya saldırır. Karşısında 3 Amiral (Akainu, Aokiji, Kizaru), Shichibukai\'ler ve 100.000 denizci vardır. Luffy, Impel Down kaçkınlarıyla birlikte savaşa katılır. Beyaz Sakal\'ın Gura Gura meyvesiyle deprem yaratması, Aokiji\'nin denizi dondurması, Marco\'nun Phoenix formu — her kare epiktir. Luffy, savaş alanının ortasından geçerek Ace\'e ulaşmaya çalışır. Haoshoku Haki\'yi ilk kez bilinçsizce kullanır ve 100.000 askeri bayıltır. Ace\'in kelepçeleri açılır ve kurtarılır! Ancak Ace, Akainu\'nun Luffy\'ye yönelik saldırısını vücuduyla engeller. Ace, Luffy\'nin kollarında ölür: "Beni sevdiğiniz için teşekkür ederim." Beyaz Sakal da sayısız yara almasına rağmen savaşmaya devam eder ve ayakta ölür. Blackbeard, Beyaz Sakal\'ın meyvesini çalar. Shanks savaşı durdurur. Dünya dengesi değişir.',
    keyEvents: [
      'Beyaz Sakal vs Marine HQ',
      '3 Amiral sahada',
      'Luffy Haoshoku Haki kullanır',
      'Ace kurtarılır ama...',
      'Ace\'in ölümü',
      'Beyaz Sakal ayakta ölür',
      'Blackbeard Gura Gura meyvesini çalar',
      'Shanks savaşı durdurur',
      'Dünya dengesi değişir',
    ],
    themes: ['Savaş ve Ölüm', 'Kardeşlik', 'Adalet ve Güç', 'Çağın Sonu', 'Fedakarlık'],
    location: 'Marineford (Marine HQ)',
    villain: 'Akainu, Blackbeard',
    characters: ['luffy', 'ace', 'whitebeard', 'akainu', 'shanks', 'blackbeard', 'hancock', 'garp'],
    episodes: [
      { number: 1, title: 'Donanma Karargâhı', slug: 'marineford-01', duration: '24:30', summary: 'Ace idam platformunda. Beyaz Sakal\'ın filosu denizden yükselir. Gura Gura meyvesiyle denizi yararak karargaha saldırır. Tarihte ilk kez Marine HQ\'ya cepheden saldırı.' },
      { number: 2, title: 'Ace ve Beyazsakal', slug: 'marineford-02', duration: '24:30', summary: 'Beyaz Sakal\'ın deprem gücü havayı ve denizi yarar. Aokiji denizi dondurarak savaş alanı oluşturur. Beyaz Sakal komutanları — Marco, Jozu, Vista — Amirallere karşı savaşır.' },
      { number: 3, title: 'Zirvedekilerin Savaşı', slug: 'marineford-03', duration: '24:30', summary: 'Luffy, Impel Down kaçkınlarıyla birlikte savaş alanına düşer. Buggy, Crocodile, Ivankov ve Jinbe yanındadır. Luffy, Ace\'e ulaşmak için savaş alanının ortasından koşar.' },
      { number: 4, title: 'Adalet Kazanacak!', slug: 'marineford-04', duration: '24:30', summary: 'Hancock, Luffy\'yi korumak için kendi tarafına saldırır. Mihawk, Luffy\'ya kılıcını çeker ama Vista araya girer. Doflamingo savaşın kaosunu eğlence olarak görür. Moria zombilerini sürer.' },
      { number: 5, title: 'Luffy ve Beyazsakal', slug: 'marineford-05', duration: '24:30', summary: 'Beyaz Sakal mürettebatının devi Ozu Jr., Ace\'e ulaşmak için savaş alanını yıkar. Moria\'nın gölge alanına girmesine rağmen ilerler. Doflamingo bacaklarını keser. Ozu Jr. düşer ama yolu açmıştır.' },
      { number: 6, title: 'Impel Down Mahkûmları', slug: 'marineford-06', duration: '24:30', summary: 'Luffy, idam platformuna yaklaşırken bir milyon askerle karşılaşır. Aşırı stres altında Haoshoku Haki\'yi bilinçsizce kullanır ve etrafındaki 100.000 askeri bayıltır. Herkes şok olur — bu güce milyonda bir kişi sahiptir.' },
      { number: 7, title: 'Girdap Örümcek', slug: 'marineford-07', duration: '24:30', summary: 'Luffy, idam platformuna ulaşır ama 3 Amiral yolunu keser. Garp, platformun önünde durur — torununa karşı savaşması gerekir. Garp, Luffy\'nin geçmesine "izin verir" — yumruğu havada durur.' },
      { number: 8, title: 'Dünyayı Sarsan Adam', slug: 'marineford-08', duration: '24:30', summary: 'Mr. 3\'ün mum anahtarıyla Ace\'in deniz taşı kelepçeleri açılır. Ace serbest! İki kardeş yan yana savaşır — ateş ve lastik. Beyaz Sakal, çekilme emri verir. Zafer göründüğü anda...' },
      { number: 9, title: 'Hücum', slug: 'marineford-09', duration: '24:30', summary: 'Akainu, Ace\'i provoke eder: Beyaz Sakal\'a hakaret eder. Ace, onurunu korumak için döner ve Akainu ile savaşır. Magma, ateşi yakar — Akainu\'nun Magu Magu meyvesi Ace\'in Mera Mera\'sından üstündür.' },
      { number: 10, title: 'Oris Meydanı', slug: 'marineford-10', duration: '24:30', summary: 'Akainu, Luffy\'ye yönelik ölümcül bir saldırı yapar. Ace, vücuduyla Luffy\'yi korur — magma yumruğu göğsünü deler. Ace, Luffy\'nin kollarında ölür: "Beni sevdiğiniz için teşekkür ederim." Luffy çöker.' },
      { number: 11, title: 'Beyaz Canavar', slug: 'marineford-11', duration: '24:30', summary: 'Beyaz Sakal, öfkeyle Akainu\'ya saldırır ve Marine HQ\'yu yarıya böler. Yüzlerce yara almış, organları delinmiş olmasına rağmen savaşmaya devam eder. "Tek bir adım bile geri atmadı" — ayakta ölür.' },
      { number: 12, title: 'İdam Platformu', slug: 'marineford-12', duration: '24:30', summary: 'Blackbeard, Level 6 mahkumlarıyla savaş alanına gelir. Beyaz Sakal\'ın cesedinden Gura Gura meyvesini çalar — tarihte iki Şeytan Meyvesine sahip ilk kişi. Yeni bir çağ başlıyor.' },
      { number: 13, title: 'Değişim Sürecindeki Çağ', slug: 'marineford-13', duration: '24:30', summary: 'Savaş kontrolden çıkmıştır. Akainu kendi askerlerini bile öldürür. Koby, anlamsız ölümlere dayanamaz ve savaş alanının ortasında haykırır: "Durun! Hayatları boşa harcıyorsunuz!" Koby\'nin cesareti bir an için herkesi durdurur.' },
      { number: 14, title: 'Beni Sevdiğiniz için Teşekkür Ederim', slug: 'marineford-14', duration: '24:30', summary: 'Kızıl Saçlı Shanks, mürettebatıyla savaş alanına gelir ve savaşı durdurur. "Bu savaş yeter!" Marine tarafı da kabul eder — Shanks\'a karşı savaşacak güçleri kalmamıştır. Ace ve Beyaz Sakal\'ın cenazeleri Shanks tarafından düzgün gömülür.' },
      { number: 15, title: 'Edward Newgate', slug: 'marineford-15', duration: '24:30', summary: 'Şoktan çöken Luffy, Jinbe tarafından savaş alanından çıkarılır. Akainu peşlerindedir. Jinbe, Luffy\'yi korumak için her şeyi göze alır. Law\'ın denizaltısı onları kurtarır.' },
      { number: 16, title: 'Yeni Bir Çağa Hediye', slug: 'marineford-16', duration: '24:30', summary: 'Savaşın sonuçları: Beyaz Sakal ve Ace ölmüştür. Blackbeard yeni bir Yonko adayıdır. Sengoku istifa eder, Akainu yeni Büyükamiral olur. Korsan çağında yeni bir dönem başlar.' },
      { number: 17, title: 'Savaşın Sonu', slug: 'marineford-17', duration: '24:30', summary: 'Luffy, Law\'ın denizaltısında ağır yaralı halde Amazon Lily\'ye götürülür. Ace\'in ölümünü kabullenemez ve çığlıklar atar. Jinbe yanındadır. Luffy\'nin hayatının en karanlık dönemi başlar.' },
    ],
  },
  {
    name: 'Post-War',
    slug: 'post-war',
    saga: 'summit-war',
    cover: '/arcs/post-war.jpg',
    episodeCount: 8,
    summary: 'Savaşın ardından Luffy\'nin iyileşme süreci. 2 yıllık antrenman kararı ve 3D2Y mesajı.',
    detailedSummary: 'Ace\'in ölümünden sonra Luffy Amazon Lily\'de iyileşir ama ruhsal olarak yıkılmıştır. Jinbe, Luffy\'ye hayatta kalanları hatırlatır: "Ace\'i kaybettin ama hâlâ mürettebatın var!" Luffy ayağa kalkar. Rayleigh ile buluşur ve kritik bir karar alır: 2 yıl boyunca Haki eğitimi alacaktır. Rayleigh, Luffy\'ya Rusukaina adasında Busoshoku, Kenbunshoku ve Haoshoku Haki\'yi öğretecektir. Luffy, mürettebatına gizli bir mesaj gönderir: koluna "3D2Y" yazar — "3 gün değil, 2 yıl" anlamında. Her mürettebat üyesi mesajı alır ve kendi eğitimine başlar. Zoro Mihawk\'tan eğitim alır, Sanji Kamabakka Krallığı\'nda, Nami Weatheria\'da, Usopp Boin Archipelago\'da, Chopper Torino Krallığı\'nda, Robin Devrimci Ordu\'yla, Franky Vegapunk\'ın eski laboratuvarında, Brook müzik dünyasında. 2 yıl sonra herkes güçlenmiş olarak buluşacaktır.',
    keyEvents: [
      'Luffy\'nin ruhsal çöküşü ve toparlanması',
      'Jinbe\'nin sözleri: "Hâlâ mürettebatın var"',
      'Rayleigh ile Haki eğitimi kararı',
      '3D2Y mesajı',
      '2 yıllık antrenman başlar',
      'Her mürettebat üyesinin eğitimi',
    ],
    themes: ['Kayıp ve İyileşme', 'Güçlenme Kararlılığı', 'Zaman Atlayışı', 'Bireysel Gelişim'],
    location: 'Amazon Lily, Rusukaina',
    characters: ['luffy', 'jinbe', 'shanks'],
    episodes: [
      { number: 1, title: 'Ürpertici Gelecek', slug: 'post-war-01', duration: '24:30', summary: 'Luffy, Amazon Lily\'de iyileşir ama Ace\'in ölümünü kabullenemez. Ormanı yıkar, ağlar, çığlık atar. Jinbe yanından ayrılmaz ve Luffy\'ye hayatta kalanları hatırlatır.' },
      { number: 2, title: 'Gri Terminal', slug: 'post-war-02', duration: '24:30', summary: 'Jinbe, Luffy\'ye kritik soruyu sorar: "Ace\'i kaybettin ama hâlâ neyin var?" Luffy, mürettebatını hatırlar ve toparlanmaya başlar. Hancock, Luffy\'nin bakımını üstlenir. İyileşme hem fiziksel hem ruhsaldır.' },
      { number: 3, title: 'Kardeşlik Yemini', slug: 'post-war-03', duration: '24:30', summary: 'Luffy\'nin çocukluğu: Ace ve Sabo ile Goa Krallığı\'nda geçen günler. Üç kardeş sake içerek kardeşlik yemini eder. Sabo\'nun "ölümü", Ace\'in öfkesi ve Luffy\'nin masumiyeti. ASL bağının derinliği ortaya çıkar.' },
      { number: 4, title: 'Sabo\'nun Denizi', slug: 'post-war-04', duration: '24:30', summary: 'Sabo\'nun soylu ailesi ve kaçışı. Gray Terminal yangını ve Celestial Dragon gemisinin Sabo\'nun teknesini batırması. Dragon\'un Sabo\'yu kurtarması. Ace ve Luffy, Sabo\'nun öldüğünü sanır — bu acı ikisini sonsuza dek etkiler.' },
      { number: 5, title: 'Rüzgarların İradesi', slug: 'post-war-05', duration: '24:30', summary: 'Marineford Savaşı\'nın yankıları tüm dünyayı sarar. Yeni korsan dalgası başlar, Beyaz Sakal\'ın toprakları savunmasız kalır. Blackbeard hızla güç kazanır. Devrimci Ordu harekete geçer. Dünya Hükümeti yeni düzeni kurmaya çalışır.' },
      { number: 6, title: 'Nara', slug: 'post-war-06', duration: '24:30', summary: 'Rayleigh, Luffy\'ye gelir ve Haki eğitimi teklif eder. Luffy, mürettebatına gizli mesaj gönderir: Marine HQ\'da kolundaki "3D2Y" dövmesiyle — 3 gün sonra değil, 2 yıl sonra buluşacaklar.' },
      { number: 7, title: 'HABER', slug: 'post-war-07', duration: '24:30', summary: 'Her mürettebat üyesinin 2 yıllık eğitimi gösterilir. Zoro, Mihawk\'tan kılıç ve Haki eğitimi alır. Sanji, Kamabakka\'da savaş yemekleri ve Skywalk öğrenir. Nami, hava bilimini ustalaşır. Usopp, Pop Green bitki silahlarını keşfeder.' },
      { number: 8, title: '3D2Y', slug: 'post-war-08', duration: '24:30', summary: 'Chopper Torino Krallığı\'nda tıp bilgisini ilerletir, Robin Devrimci Ordu ile çalışır, Franky Vegapunk\'ın laboratuvarında kendini yeniler, Brook müzik dünyasında yıldız olur. 2 yıl geçer ve Hasır Şapkalar güçlenmiş olarak Sabaody\'de buluşacaklardır.' },
    ],
  },
]
