import type { Arc } from '@/types'

export const THRILLER_BARK_ARCS: Arc[] = [
  {
    name: 'Thriller Bark',
    slug: 'thriller-bark',
    saga: 'thriller-bark',
    cover: '/arcs/thriller-bark.webp',
    episodeCount: 22,
    summary: 'Devasa gemi-ada Thriller Bark\'ta gölgeleri çalan Shichibukai Gecko Moria ile karşılaşma. Brook mürettebata katılır.',
    detailedSummary: 'Mürettebat, Florian Üçgeni\'nde devasa bir gemi-ada olan Thriller Bark\'a ulaşır. Bu korku temalı ada, Shichibukai Gecko Moria\'nın üssüdür. Moria, Kage Kage meyvesiyle insanların gölgelerini çalıp zombilere yerleştirmektedir. Gölgesi çalınan kişi güneş ışığında yok olur. Mürettebatın gölgeleri de çalınır! Brook — 50 yıldır tek başına denizde dolaşan iskelet müzisyen — ile karşılaşırlar. Brook, Yomi Yomi meyvesiyle ölümden dönen Rumbar Korsanlarının son üyesidir. Laboon\'un onu beklediğini hâlâ bilmektedir. Mürettebat, zombi ordusuyla, Absalom\'un görünmezlik gücüyle ve Perona\'nın negatif hayaletleriyle savaşır. Luffy, Nightmare Luffy formuna girerek Moria\'nın gölge devi Oars ile savaşır. Moria yenildikten sonra, daha büyük bir tehdit belirir: Shichibukai Bartholomew Kuma. Zoro, mürettebatı korumak için Luffy\'nin tüm acısını kendi üstüne alır. "Hiçbir şey olmadı" — Zoro\'nun en ikonik sahnesi.',
    keyEvents: [
      'Brook ile karşılaşma',
      'Gölgelerin çalınması ve zombi ordusu',
      'Nightmare Luffy formu',
      'Mürettebat vs Oars',
      'Luffy vs Gecko Moria',
      'Kuma\'nın müdahalesi',
      'Zoro\'nun fedakarlığı: "Hiçbir şey olmadı"',
      'Brook mürettebata katılır',
    ],
    themes: ['Ölüm ve Diriliş', 'Gölge ve Işık', 'Fedakarlık', 'Yalnızlık ve Aidiyet'],
    location: 'Thriller Bark (Florian Üçgeni)',
    villain: 'Gecko Moria',
    characters: ['luffy', 'zoro', 'nami', 'sanji', 'usopp', 'chopper', 'robin', 'franky', 'brook', 'kuma'],
    episodes: [
      { number: 1, title: 'Gizemli Deniz ve İskelet Brook', slug: 'thriller-bark-01', duration: '24:30', summary: 'Mürettebat, sislerle kaplı Florian Üçgeni\'ne girer. Denizde sürüklenen bir iskelet gemi belirir. Gemide konuşan, yemek yiyen ve müzik çalan bir iskelet vardır — Brook! Yomi Yomi meyvesiyle ölümden dönmüş ama gölgesi çalınmıştır.' },
      { number: 2, title: 'Hayalet Adasındaki Macera', slug: 'thriller-bark-02', duration: '24:30', summary: 'Sisin içinden devasa Thriller Bark belirir. Mürettebat bu gemi-adaya ayak basar ve karanlık koridorları keşfetmeye başlar. Gizemli yaratıklarla ve hareketli cesetlerle ilk karşılaşmalar yaşanır.' },
      { number: 3, title: 'Görünmez Adam ve Malikanenin Sırları', slug: 'thriller-bark-03', duration: '24:30', summary: 'Adanın üç komutanı ortaya çıkar: doktor Hogback, hayalet prenses Perona ve görünmez adam Absalom. Mürettebat gruplara ayrılarak adayı keşfeder ve zombi ordusunun varlığını öğrenir.' },
      { number: 4, title: 'General Zombilerin Gecesi', slug: 'thriller-bark-04', duration: '24:30', summary: 'Brook\'un geçmişi anlatılmaya başlar. 50 yıl önce Rumbar Korsanları neşeli bir mürettebattı. Reverse Mountain\'da yavru balina Laboon ile karşılaşmış ve ona geri döneceklerine söz vermişlerdir.' },
      { number: 5, title: 'Perona\'nın Harika Bahçesi', slug: 'thriller-bark-05', duration: '24:30', summary: 'Rumbar Korsanları zehirli bir düşmanla karşılaşır ve tüm mürettebat ölür. Son nefeslerinde Laboon için "Binks\'in Sake\'si"ni kaydederler. Brook dirilir ama 50 yıl boyunca sisli denizde tek başına dolaşır. Gölgesi de Moria tarafından çalınmıştır.' },
      { number: 6, title: 'Lola\'nın Peşinden ve Mırıldanan Kılıç Ustası', slug: 'thriller-bark-06', duration: '24:30', summary: 'Shichibukai Gecko Moria\'nın gücü ortaya çıkar: Kage Kage meyvesiyle insanların gölgelerini çalıp zombilere yerleştirir. Gölgesi çalınan kişi güneş ışığında yok olur. Efsanevi samuray Ryuma\'nın zombisi Brook\'un gölgesini taşımaktadır.' },
      { number: 7, title: 'Gölge Meyvesinin Korkunç Yeteneği!', slug: 'thriller-bark-07', duration: '24:30', summary: 'Moria, mürettebatın gölgelerini çalmaya başlar. Luffy\'nin gölgesi dev zombi Oars\'a yerleştirilir. Zoro, Sanji ve diğerlerinin gölgeleri de tehlike altındadır. Tuzdan zombilerin zayıf noktası olduğu keşfedilir.' },
      { number: 8, title: 'Brook, Ryuma\'ya Karşı!', slug: 'thriller-bark-08', duration: '24:30', summary: 'Perona\'nın Horo Horo meyvesiyle ürettiği negatif hayaletler, dokunduğu herkesi derin bir depresyona sokar. Mürettebat üyeleri birer birer çöker. Ancak Usopp, doğası gereği zaten negatif olduğundan hayaletlerden etkilenmez!' },
      { number: 9, title: 'İskeletin Umut ve Çaresizliği', slug: 'thriller-bark-09', duration: '24:30', summary: 'Absalom, Suke Suke meyvesiyle görünmez olarak Nami\'yi takip eder ve onu zorla gelin yapmaya çalışır. Sanji öfkeyle müdahale eder — görünmezlik meyvesi onun hayaliydi! Chopper ve Robin da adanın sırlarını araştırır.' },
      { number: 10, title: 'Her Zaman Negatif', slug: 'thriller-bark-10', duration: '24:30', summary: 'Luffy\'nin gölgesi yerleştirilen 500 yıllık dev zombi Oars uyanır. Luffy\'nin kişiliğini taşıyan bu devasa yaratık et ister, kavga ister ve durdurulamaz bir güçle adayı yıkmaya başlar.' },
      { number: 11, title: 'Sanji, Absalom\'a Karşı', slug: 'thriller-bark-11', duration: '24:30', summary: 'Mürettebat Oars\'ı durdurmaya çalışır ama devin gücü karşısında yetersiz kalır. Oars, Luffy\'nin savaş içgüdüleriyle hareket eder ve Gomu Gomu tekniklerini kullanmaya başlar. Aynı zamanda bireysel savaşlar kızışır.' },
      { number: 12, title: 'Korsan Usopp, Gizemli Perona\'ya Karşı', slug: 'thriller-bark-12', duration: '24:30', summary: 'Usopp, negatif hayaletlere bağışıklığını kullanarak Perona ile tek başına savaşır. Zekası ve yaratıcı silahlarıyla Perona\'nın gerçek bedenini bulur. Usopp\'un en parlak zaferlerinden biri — korkak savaşçı korku prensesini yener!' },
      { number: 13, title: 'Zoro, Samuray Ryuma\'ya Karşı', slug: 'thriller-bark-13', duration: '24:30', summary: 'Sanji, Nami\'ye saldıran Absalom\'la hesaplaşır. Görünmez düşmana karşı Diable Jambe tekniğini kullanır. Sanji\'nin öfkesi ve şövalyelik duygusu onu zafere taşır. Nami kurtarılır.' },
      { number: 14, title: 'Tayfanın Umutsuz Karşı Saldırısı!', slug: 'thriller-bark-14', duration: '24:30', summary: 'Zoro, Brook\'un gölgesini taşıyan efsanevi samuray Ryuma\'nın zombisiyle kılıç savaşına girer. Zorlu bir düellonun ardından Zoro galip gelir ve Ryuma\'nın efsanevi kılıcı Shusui\'yi kazanır. Brook\'un gölgesi serbest kalır.' },
      { number: 15, title: 'Zombie 900\'e Karşı Büyük Savaş!', slug: 'thriller-bark-15', duration: '24:30', summary: 'Tüm mürettebat Oars\'a karşı güçlerini birleştirir. Herkesin özel yetenekleri bir strateji dahilinde kullanılır. Franky\'nin Taktik 15\'i, Robin\'in el çiçekleri ve Chopper\'ın analiziyle devin zayıf noktaları hedef alınır.' },
      { number: 16, title: 'Gizemli Ziyaretçi!', slug: 'thriller-bark-16', duration: '24:30', summary: 'Mürettebat, koordineli saldırılarla Oars\'ı köşeye sıkıştırır. Brook da savaşa katılır. Oars\'ın omurgası kırılır ama Moria devin içinden gölge gücünü kullanmaya devam eder. Son darbe için Luffy gereklidir.' },
      { number: 17, title: 'Beyin ve Kas Kombinasyonu!', slug: 'thriller-bark-17', duration: '24:30', summary: 'Luffy, ada sakinlerinin yardımıyla 100 gölgeyi aynı anda vücuduna alarak Nightmare Luffy formuna girer. Devasa, kas dolu ve inanılmaz güçlü bu formda Oars\'a yıkıcı darbeler indirir. Geçici ama muazzam bir güç gösterisi.' },
      { number: 18, title: 'Oz, Kabus Luffy\'ye Karşı', slug: 'thriller-bark-18', duration: '24:30', summary: 'Luffy, Gecko Moria ile son savaşını yapar. Moria, 1000 gölgeyi aynı anda emerek Shadow Asgard formuna girer ve devasa bir yaratığa dönüşür. Luffy, Gear 2 ve Gear 3 kombinasyonuyla Moria\'yı yener. Tüm gölgeler sahiplerine döner.' },
      { number: 19, title: 'Hasır Şapkalar\'ın Nihai Saldırısı!', slug: 'thriller-bark-19', duration: '24:30', summary: 'Zafer kutlaması kısa sürer. Shichibukai Bartholomew Kuma, Dünya Hükümeti\'nin emriyle belirir. Nikyu Nikyu meyvesiyle her şeyi fırlatabilir. Görevi mürettebatı yok etmektir. Yorgun ve yaralı mürettebat umutsuz bir durumdadır.' },
      { number: 20, title: 'Her Şeyi Saptırabilecek Güç!', slug: 'thriller-bark-20', duration: '24:30', summary: 'Serinin en ikonik sahnesi. Kuma, Luffy\'nin tüm acı ve yorgunluğunu bir balon halinde çıkarır. Zoro, mürettebatı korumak için kendi hayatını feda etmeye hazırdır ve Luffy\'nin tüm acısını üstüne alır. Sanji onu kan içinde bulur. Zoro: "Hiçbir şey olmadı."' },
      { number: 21, title: 'Rumbar Korsanları ve Laboon!', slug: 'thriller-bark-21', duration: '24:30', summary: 'Gölgeler geri döner ve herkes iyileşmeye başlar. Luffy, Brook\'u mürettebata davet eder. Brook, 50 yıllık yalnızlığından sonra gözyaşlarıyla kabul eder. Laboon\'a verdiği sözü yerine getirmek için Hasır Şapkalar\'a katılır.' },
      { number: 22, title: 'Brook\'un Sözü!', slug: 'thriller-bark-22', duration: '24:30', summary: 'Brook, mürettebatla birlikte "Binks\'in Sake\'si"ni söyler — 50 yıl önce ölen arkadaşlarının son şarkısı. Thriller Bark\'tan ayrılırlar. Mürettebat tam kadro: 9 kişi. Laboon\'un beklediği müzisyen sonunda yolda. Red Line ve Yeni Dünya onları bekliyor!' },
    ],
  },
]
