import type { Arc } from '@/types'

export const WATER_7_ARCS: Arc[] = [
  {
    name: 'Long Ring Long Land',
    slug: 'long-ring-long-land',
    saga: 'water-7',
    cover: '/arcs/long-ring-long-land.webp',
    episodeCount: 6,
    summary: 'Foxy korsanları ile Davy Back Fight! Mürettebat üyelerini kaybetme riskiyle dolu eğlenceli bir turnuva.',
    detailedSummary: 'Mürettebat, her şeyin uzun olduğu garip bir adaya ulaşır. Burada Gümüş Tilki Foxy ve korsanlarıyla karşılaşırlar. Foxy, Hasır Şapkaları "Davy Back Fight" — korsan geleneklerine dayanan bir turnuva — için zorlar. Kurallar basittir: kaybeden taraf, kazanana bir mürettebat üyesi vermek zorundadır. Chopper geçici olarak kaybedilir ama Luffy geri kazanır. Donut yarışı, Groggy Ring dövüşü ve kaptan vs kaptan maçları yapılır. Foxy\'nin Noro Noro meyvesiyle her şeyi yavaşlatma gücü sinir bozucu olsa da Luffy sonunda kazanır. Turnuva sonrası Amiral Aokiji ile ilk karşılaşma gerçekleşir. Aokiji, Robin\'in geçmişi hakkında uyarır ve gücünü göstererek mürettebatı dondurur.',
    keyEvents: [
      'Davy Back Fight turnuvası',
      'Foxy\'nin Noro Noro meyvesi',
      'Amiral Aokiji ile ilk karşılaşma',
      'Robin\'in geçmişine dair uyarılar',
      'Aokiji\'nin buzla mürettebatı dondurması',
    ],
    themes: ['Korsan Gelenekleri', 'Mürettebat Bağı', 'Güç Farkı Gerçeği'],
    location: 'Long Ring Long Land',
    villain: 'Foxy',
    characters: ['luffy', 'zoro', 'nami', 'sanji', 'usopp', 'chopper', 'robin', 'aokiji'],
    episodes: [
      {
        number: 1,
        title: 'Uzun Bir Adada Macera',
        slug: 'long-ring-01',
        duration: '24:00',
        summary: 'Mürettebat, her şeyin uzun olduğu garip bir adaya ulaşır. Burada Gümüş Tilki Foxy ve korsanlarıyla karşılaşırlar. Foxy, Hasır Şapkaları Davy Back Fight\'a — korsan geleneklerine dayanan bir turnuvaya — zorlar.',
      },
      {
        number: 2,
        title: 'Donut Yarışı!!',
        slug: 'long-ring-02',
        duration: '24:00',
        summary: 'Davy Back Fight başlar! İlk etkinlik Donut Yarışı\'dır. Foxy\'nin Noro Noro meyvesiyle yavaşlatma hileleri ortaya çıkar. Nami ve Usopp yarışta mücadele ederken Foxy Korsanları kirli oyunlarını sergiler.',
      },
      {
        number: 3,
        title: 'Sersem Halka!!',
        slug: 'long-ring-03',
        duration: '24:30',
        summary: 'Groggy Ring maçında Sanji ve Zoro birlikte savaşmak zorunda kalır ama sürekli birbirleriyle kavga ederler. Chopper geçici olarak kaybedilir. Luffy, Chopper\'ı geri kazanmak için kararlıdır.',
      },
      {
        number: 4,
        title: 'Dövüş',
        slug: 'long-ring-04',
        duration: '24:00',
        summary: 'Turnuvanın diğer etkinlikleri devam eder. Roller yarışında Foxy Korsanlarının hileleri giderek artar. Mürettebat üyelerini kaybetme riski büyüktür. Luffy, son kaptan maçına hazırlanır.',
      },
      {
        number: 5,
        title: 'Nakavt',
        slug: 'long-ring-05',
        duration: '24:30',
        summary: 'Luffy vs Foxy final maçı! Foxy\'nin Noro Noro meyvesiyle yavaşlatma gücü Luffy\'yi zorlar. Foxy, arenayı kendi avantajına göre düzenlemiştir. Ancak Luffy, ayna kullanarak Noro ışınlarını geri yansıtır ve Foxy\'yi kendi silahıyla yener.',
      },
      {
        number: 6,
        title: 'Donanma Karargâhı Amirali Aokiji',
        slug: 'long-ring-06',
        duration: '24:00',
        summary: 'Luffy turnuvayı kazanır ve Chopper\'ı geri alır. Foxy Korsanları bozguna uğramıştır. Mürettebat kutlama yapar ve Long Ring Long Land\'dan ayrılmaya hazırlanır. Huzurlu bir an ama ufukta karanlık bir gölge belirir.',
      },
    ],
  },
  {
    name: 'Water Seven',
    slug: 'water-seven',
    saga: 'water-7',
    cover: '/arcs/water-seven.webp',
    episodeCount: 20,
    summary: 'Su şehri Water Seven\'da Going Merry\'nin tamir edilemeyeceği ortaya çıkar. Usopp mürettebattan ayrılır, Robin kaybolur. Her şey alt üst olur.',
    detailedSummary: 'Water Seven, dünyanın en iyi gemi ustalarının yaşadığı su şehridir. Mürettebat, Skypiea altınlarını paraya çevirip Going Merry\'yi tamir ettirmek ister. Ancak usta gemi ustaları Going Merry\'nin artık tamir edilemeyeceğini, omurgasının kırık olduğunu söyler. Luffy yeni gemi almaya karar verir ama Usopp buna şiddetle karşı çıkar — Merry onların arkadaşıdır! Luffy ve Usopp arasında duygusal bir düello yaşanır ve Usopp mürettebattan ayrılır. Bu sırada Robin gizemli bir şekilde kaybolur ve CP9 ajanlarına teslim olur. Iceburg\'a suikast girişimi Hasır Şapkaların üzerine yıkılır. Robin\'in aslında mürettebatı korumak için kendini feda ettiği ortaya çıkar: Dünya Hükümeti, Robin teslim olmazsa mürettebatı Buster Call ile yok edecektir. Franky, yeraltı şehri Frank House\'un lideri ve usta gemi ustasıdır. Tom\'un öğrencisi olan Franky, geçmişte büyük bir trajedi yaşamıştır.',
    keyEvents: [
      'Going Merry\'nin tamir edilemez olduğu gerçeği',
      'Luffy vs Usopp düellosu',
      'Usopp mürettebattan ayrılır',
      'Robin\'in kaybolması ve CP9\'a teslim olması',
      'Iceburg suikast girişimi',
      'CP9 ajanlarının gerçek kimliği (Lucci, Kaku, Kalifa, Blueno)',
      'Franky ve Tom\'un hikayesi',
      'Aqua Laguna fırtınası',
      'Robin\'in gerçek sebebi: mürettebatı korumak',
    ],
    themes: ['Ayrılık ve Sadakat', 'Fedakarlık', 'Değişim Korkusu', 'Geçmişin Yükü'],
    location: 'Water Seven',
    villain: 'CP9 (Rob Lucci)',
    characters: ['luffy', 'zoro', 'nami', 'sanji', 'usopp', 'chopper', 'robin', 'franky'],
    episodes: [
      { number: 1, title: 'Su Şehri, Water Seven', slug: 'water-seven-01', duration: '24:30', summary: 'Mürettebat, su kanallarıyla örülmüş muhteşem Water Seven şehrine ulaşır. Skypiea altınlarını paraya çevirirler. Şehrin usta gemi ustaları Galley-La şirketi tanıtılır. Iceburg, şehrin belediye başkanı ve baş gemi ustasıdır.' },
      { number: 2, title: 'Iceburg-san', slug: 'water-seven-02', duration: '24:30', summary: 'Kaku, Going Merry\'yi inceledikten sonra şok edici haberi verir: geminin omurgası kırıktır ve tamir edilemez. Luffy yeni gemi almaya karar verir ama Usopp bu haberi kabul edemez.' },
      { number: 3, title: 'Korsan Kaçırma Olayı', slug: 'water-seven-03', duration: '24:30', summary: 'Usopp, Going Merry\'yi bırakmayı reddeder ve Luffy\'ye düello challenge eder. İkisi gözyaşları içinde savaşır. Usopp kaybeder ama Luffy de parçalanmıştır. Usopp mürettebattan ayrılır ve Going Merry\'yi alır.' },
      { number: 4, title: 'Büyük Tartışma', slug: 'water-seven-04', duration: '24:30', summary: 'Robin gizemli bir şekilde ortadan kaybolur. Son görüldüğünde maskeli bir adamla (CP9) konuşuyordu. Mürettebat Robin\'i aramaya başlar. Iceburg\'a suikast girişimi gerçekleşir ve Hasır Şapkalar suçlanır.' },
      { number: 5, title: 'Luffy, Usopp\'a Karşı', slug: 'water-seven-05', duration: '24:30', summary: 'Şok edici gerçek: Galley-La çalışanları Lucci, Kaku, Kalifa ve Blueno aslında Dünya Hükümeti\'nin gizli ajanları CP9\'dur. 5 yıldır gizlice çalışmışlardır. Robin\'i ve Pluton planlarını almak görevleridir.' },
      { number: 6, title: 'Uyarı', slug: 'water-seven-06', duration: '24:30', summary: 'Robin\'in neden CP9\'a teslim olduğu ortaya çıkar: Dünya Hükümeti, Robin karşılığında mürettebatın güvenliğini garanti etmiştir. Robin, 20 yıldır kaçtığı karanlıktan bıkmıştır ve arkadaşlarını korumak için kendini feda eder.' },
      { number: 7, title: 'Söylentiler', slug: 'water-seven-07', duration: '24:30', summary: 'Franky\'nin hikayesi: usta gemi yapımcısı Tom\'un öğrencisidir. Tom, Sea Train\'i yapmış ve Roger\'ın gemisi Oro Jackson\'ı inşa etmiştir. Tom, Pluton planlarını korumak için kendini feda etmiştir. Franky, treni durdurmaya çalışırken ezilmiş ve cyborg olmuştur.' },
      { number: 8, title: 'Şeytan', slug: 'water-seven-08', duration: '24:30', summary: 'Devasa Aqua Laguna fırtınası Water Seven\'ı tehdit eder. CP9, Robin ve Franky\'yi Sea Train ile Enies Lobby\'ye götürür. Mürettebat, Rocket Man treniyle peşlerine düşer.' },
      { number: 9, title: 'Cipher Pol No. 9', slug: 'water-seven-09', duration: '24:30', summary: 'Mürettebat, Rocket Man ile Sea Train\'in peşinden gider. Sanji, trene zaten sızmıştır. Yolda Franky Ailesi ve Galley-La ustaları da katılır. Fırtınanın ortasında epik bir tren takibi.' },
      { number: 10, title: '6 Güç', slug: 'water-seven-10', duration: '24:30', summary: 'Sanji, tren içinde CP9 ajanlarıyla savaşır. Wanze\'nin yemekle savaş tekniği Sanji\'yi sinir eder. Franky, Robin ile konuşur ve onun kararlılığını görür.' },
      { number: 11, title: 'Klabautermann', slug: 'water-seven-11', duration: '24:30', summary: 'Robin\'in çocukluğu anlatılır. Ohara adasında büyümüş, 8 yaşında arkeolog olmuştur. Annesi Olvia, Poneglyph araştırması için denize çıkmış ve yakalanmıştır. Robin, küçük yaşta dışlanmış ve yalnız bırakılmıştır.' },
      { number: 12, title: 'Efsanevi Gemi Marangozu', slug: 'water-seven-12', duration: '24:30', summary: 'Ohara\'nın yıkımı: Dünya Hükümeti, Void Century\'yi araştırdıkları için tüm adayı Buster Call ile yok eder. Profesör Clover ve akademisyenler öldürülür. Aokiji, küçük Robin\'i kaçmasına izin verir. Robin, 20 yıl boyunca kaçak olarak yaşar.' },
      { number: 13, title: 'Tom-san', slug: 'water-seven-13', duration: '24:30', summary: 'Mürettebat, Enies Lobby\'ye yaklaşır. Adalet Adası\'nın devasa yapıları görünür. Luffy kararlıdır: "Robin\'i geri alacağız!" Tüm mürettebat savaşa hazırlanır.' },
      { number: 14, title: 'Tam İsabet', slug: 'water-seven-14', duration: '24:30', summary: 'Tom\'un tam hikayesi anlatılır. Roger\'ın gemisini yaptığı için yargılanan Tom, Sea Train\'i yaparak affedilmiştir. Ancak Spandam, Pluton planlarını almak için onu tekrar suçlamıştır. Tom kendini feda eder.' },
      { number: 15, title: 'Birazdan Hareket Edecek', slug: 'water-seven-15', duration: '24:30', summary: 'Franky, Tom\'un ölümünden kendini sorumlu tutar. Sea Train\'i durdurmaya çalışırken ezilmiş, hurda metallerle kendini cyborg olarak yeniden inşa etmiştir. Pluton planlarını Tom\'un vasiyeti olarak korumaktadır.' },
      { number: 16, title: 'Aqua Laguna', slug: 'water-seven-16', duration: '24:30', summary: 'CP9 ajanlarının Rokushiki — altı süper insan tekniği — ustası olduğu ortaya çıkar. Lucci\'nin Doriki seviyesi 4000\'dir. Luffy bile bu güce karşı zorlanacaktır.' },
      { number: 17, title: 'Sogeking', slug: 'water-seven-17', duration: '24:30', summary: 'Mürettebat, Enies Lobby\'ye saldırı planı yapar. Franky Ailesi, Galley-La ustaları ve Hasır Şapkalar birleşir. Tüm güçler Robin\'i kurtarmak için harekete geçer.' },
      { number: 18, title: 'Ramen Kenpo', slug: 'water-seven-18', duration: '24:30', summary: 'Usopp, mürettebattan ayrılmış olmasına rağmen Robin\'i kurtarmak ister. "Sogeking" maskesini takarak farklı bir kimlikle savaşa katılır. Herkes onun Usopp olduğunu bilir ama saygı gösterir.' },
      { number: 19, title: 'Takdire Şayan Yüzbaşı T-Bone', slug: 'water-seven-19', duration: '24:30', summary: 'Rocket Man, fırtına dalgalarını aşarak Enies Lobby\'ye yaklaşır. Kokoro-baa treni sürerken mürettebat son hazırlıklarını yapar. Yokoi ve Kiwi, Franky için savaşmaya hazırdır.' },
      { number: 20, title: 'Gerekli Kötülük', slug: 'water-seven-20', duration: '24:30', summary: 'Mürettebat Enies Lobby\'nin kapılarına ulaşır. Binlerce asker onları beklemektedir. Luffy, tek başına kapıyı yıkar ve içeri dalar. Dünyanın en güçlü adalet kalesine saldırı başlamıştır.' },
    ],
  },
  {
    name: 'Enies Lobby',
    slug: 'enies-lobby',
    saga: 'water-7',
    cover: '/arcs/enies-lobby.webp',
    episodeCount: 25,
    summary: 'Robin\'i kurtarmak için Dünya Hükümeti\'nin adalet adasına saldırı! Hasır Şapkaların en epik savaşı. "Yaşamak istiyorum!" çığlığı her şeyi değiştirir.',
    detailedSummary: 'One Piece\'in en epik ve duygusal arcı. Hasır Şapkalar, Dünya Hükümeti\'nin yargılama öncesi tutukevi Enies Lobby\'ye tam cepheden saldırır. Binlerce askere karşı sadece birkaç kişilik mürettebat! Robin, Adalet Kapısı\'nın üstünde durur ve CP9 tarafından zorla götürülmektedir. Luffy, Robin\'e seslenir: "Yaşamak istediğini söyle!" Robin, 20 yıldır bastırdığı duygularını ilk kez dışa vurur: "Yaşamak istiyorum! Beni denize götürün!" Bu sahne, tüm anime tarihinin en güçlü anlarından biridir. Sogeking (Usopp), Dünya Hükümeti bayrağını ateşe verir — bu, tüm dünyaya savaş ilanıdır. Her mürettebat üyesi bir CP9 ajanıyla eşleşir: Luffy vs Lucci, Zoro vs Kaku, Sanji vs Jabra, Nami vs Kalifa, Chopper vs Kumadori, Franky vs Fukuro, Sogeking vs Spandam. Luffy, Gear 2 ve Gear 3\'ü ilk kez kullanır. Final savaşında Luffy ve Lucci arasındaki düello serinin en uzun ve en yoğun tek tek savaşıdır. Buster Call — 5 savaş gemisi ve 10 savaş gemisi ile toplam bombardıman — Enies Lobby\'yi yok eder. Mürettebat son anda kaçar.',
    keyEvents: [
      'Robin\'in "Yaşamak istiyorum!" çığlığı',
      'Dünya Hükümeti bayrağının yakılması',
      'Her mürettebat üyesi vs CP9 ajanı',
      'Luffy Gear 2 ve Gear 3\'ü ilk kez kullanır',
      'Luffy vs Rob Lucci epik final',
      'Buster Call\'ın tetiklenmesi',
      'Franky\'nin mürettebata katılma kararı',
    ],
    themes: ['Var Olma Hakkı', 'Dünyaya Karşı Durma Cesareti', 'Dostluk İçin Her Şeyi Göze Alma', 'Güç Sınırlarını Aşma'],
    location: 'Enies Lobby (Adalet Adası)',
    villain: 'Rob Lucci, Spandam',
    characters: ['luffy', 'zoro', 'nami', 'sanji', 'usopp', 'chopper', 'robin', 'franky'],
    episodes: [
      { number: 1, title: 'Enies Lobby\'nin Süper İnsanları', slug: 'enies-lobby-01', duration: '24:30', summary: 'Mürettebat, binlerce askerin beklediği Enies Lobby\'ye cepheden saldırır. Luffy, Rocket Man treniyle kapıyı parçalar. Franky Ailesi ve Galley-La ustaları destek verir. Tarihte ilk kez bu kaleye saldırılmaktadır.' },
      { number: 2, title: 'Yargı Adası\'nda Büyük Hesaplaşma!', slug: 'enies-lobby-02', duration: '24:30', summary: 'Ana kapıyı koruyan dev muhafızlar Oimo ve Kashii, aslında 50 yıldır yalanla kandırılmıştır. Sogeking ve Usopp, devleri gerçeği anlatarak taraflarına çeker. Devler yolu açar.' },
      { number: 3, title: 'Enies Lobby Ana Ada Treni', slug: 'enies-lobby-03', duration: '24:30', summary: 'Mürettebat Adalet Kulesi\'ne sızar. CP9 ajanlarıyla ilk çatışmalar başlar. Blueno\'nun Doa Doa meyvesiyle oluşturduğu boyut kapıları engeldir. Luffy, yeni bir teknik hazırlamaktadır.' },
      { number: 4, title: 'Kovuldular!', slug: 'enies-lobby-04', duration: '24:30', summary: 'Luffy, Gear 2\'yi ilk kez kullanır! Kan dolaşımını hızlandırarak süper hız ve güç kazanır. Blueno\'yu tek hamlede yener. CP9 ajanları Luffy\'nin bu yeni gücüne şok olur.' },
      { number: 5, title: 'Karşı Saldırı İşareti', slug: 'enies-lobby-05', duration: '24:30', summary: 'Serinin en ikonik sahnesi. Robin, Adalet Kapısı\'nda durmaktadır. Luffy seslenir: "Yaşamak istediğini henüz duymadık!" Robin, 20 yıldır bastırdığı duygularını haykırır: "Yaşamak istiyorum! Beni denize götürün!" Gözyaşları ve kararlılık.' },
      { number: 6, title: 'Eşi Benzeri Görülmemiş', slug: 'enies-lobby-06', duration: '24:30', summary: 'Luffy, Sogeking\'e emreder: "O bayrağı yak!" Sogeking, Dünya Hükümeti\'nin bayrağını ateşe verir. Bu, tüm dünyaya savaş ilanıdır. Mürettebat, Robin\'i geri almak için her şeyi göze almıştır.' },
      { number: 7, title: 'İkinci Vites', slug: 'enies-lobby-07', duration: '24:30', summary: 'Her mürettebat üyesi bir CP9 ajanıyla eşleşir. Savaşlar Adalet Kulesi\'nin farklı katlarında aynı anda başlar. Nami Kalifa\'yı, Chopper Kumadori\'yi, Franky Fukuro\'yu arar. Anahtar kovalamacası başlar.' },
      { number: 8, title: 'Şeytan Denen Kız', slug: 'enies-lobby-08', duration: '24:30', summary: 'Nami, Awa Awa meyvesiyle köpük üreten Kalifa ile savaşır. Kalifa\'nın dokunuşu vücudu kayganlaştırır. Nami, Perfect Clima-Tact ile yıldırım çağırarak kazanır.' },
      { number: 9, title: 'Ohara, Dünya Hükümeti\'ne Karşı', slug: 'enies-lobby-09', duration: '24:30', summary: 'Chopper, kontrolsüz Rumble Ball kullanarak Monster Point formuna girer. Devasa ve kontrolsüz bir canavara dönüşür. Kumadori\'yi yener ama kendini de tehlikeye atar. Franky onu denize atarak kurtarır.' },
      { number: 10, title: 'Savaş İlanı', slug: 'enies-lobby-10', duration: '24:30', summary: 'Franky, Soru tekniğiyle hızlı Fukuro ile savaşır. Cola yakıtı biten Franky zor durumda kalır. Yedek cola bulunca Coup de Vent ile kazanır.' },
      { number: 11, title: 'Şelaleye Atla!', slug: 'enies-lobby-11', duration: '24:30', summary: 'Zoro, Ushi Ushi meyvesiyle zürafaya dönüşen Kaku ile savaşır. Kaku\'nun uzun boynu ve Rokushiki teknikleri zorlu bir rakip çıkarır. Zoro, Ashura formunu ilk kez kullanarak kazanır.' },
      { number: 12, title: 'Korsanlar, CP9\'a Karşı', slug: 'enies-lobby-12', duration: '24:30', summary: 'Sanji, Inu Inu meyvesiyle kurda dönüşen Jabra ile savaşır. Jabra\'nın Tekkai Kenpo tekniği güçlüdür. Sanji, Diable Jambe — ayağını ateşe veren teknik — ile ilk kez ortaya çıkar ve kazanır.' },
      { number: 13, title: 'Bay Kibar', slug: 'enies-lobby-13', duration: '24:30', summary: 'Sogeking (Usopp), Robin\'in kelepçelerinin anahtarını almak için Spandam\'la uğraşır. Spandam, tarihte en düşük güce sahip CP9 lideridir ama elinde Funkfreed kılıç-fil vardır. Robin\'in kelepçeleri açılır!' },
      { number: 14, title: 'Hayata Dönüş', slug: 'enies-lobby-14', duration: '24:30', summary: 'Spandam yanlışlıkla Buster Call\'ı tetikler. 10 savaş gemisi Enies Lobby\'ye doğru yola çıkar. Mürettebat, kalan CP9 savaşlarını bir an önce bitirmek zorundadır. Ada bombalanmaya başlar.' },
      { number: 15, title: 'Canavar', slug: 'enies-lobby-15', duration: '24:30', summary: 'Buster Call tam güçle başlar. Savaş gemileri Enies Lobby\'yi bombalıyor. Ohara\'nın yıkımını yaşamış Robin için bu kabusun tekrarıdır. Mürettebat, savaşırken bir yandan da kaçış yolu aramalıdır. Ada parça parça yok olmaktadır.' },
      { number: 16, title: 'Korkunç Yayın', slug: 'enies-lobby-16', duration: '24:30', summary: 'Serinin en epik savaşı başlar. Rob Lucci, CP9 tarihinin en güçlü ajanıdır. Neko Neko meyvesiyle leopara dönüşür. 4000 Doriki ile Luffy\'yi zorlar. Gear 2 bile yeterli değildir.' },
      { number: 17, title: 'Avcı', slug: 'enies-lobby-17', duration: '24:30', summary: 'Savaş kızışır. Lucci\'nin Rokuogan tekniği Luffy\'nin iç organlarına zarar verir. Luffy defalarca yere düşer ama kalkar. Usopp, uzaktan Luffy\'ye seslenir ve onu ayağa kaldırır: "Kalk Luffy!"' },
      { number: 18, title: 'Sanji, Jabra\'ya Karşı', slug: 'enies-lobby-18', duration: '24:30', summary: 'Luffy, Gear 3\'ü kullanır — kemiklerine hava üfleyerek kolunu dev boyutuna getirir. Gigant Pistol ile Lucci\'yi fırlatır. Ancak Gear 3\'ün yan etkisi Luffy\'yi geçici olarak küçültür.' },
      { number: 19, title: 'Zoro, Kaku\'ya Karşı', slug: 'enies-lobby-19', duration: '24:30', summary: 'Luffy ve Lucci\'nin son çarpışması. İkisi de ayakta zor durmaktadır. Luffy, Jet Gatling ile art arda yüzlerce yumruk atar. Lucci sonunda yere düşer ve kalkamaz. "Benim mürettebatım var!"' },
      { number: 20, title: 'Yıkım Çağrısı', slug: 'enies-lobby-20', duration: '24:30', summary: 'Buster Call adayı yok ederken mürettebat kaçış yolu bulamaz. O anda Going Merry kendi başına gelir — geminin ruhu (Klabautermann) onu getirmiştir. Merry, son kez mürettebatını kurtarır ve herkesi alır.' },
      { number: 21, title: 'Rob Lucci', slug: 'enies-lobby-21', duration: '24:30', summary: 'Serinin en duygusal sahnelerinden biri. Going Merry artık dayanamaz ve parçalanmaktadır. Mürettebat, Merry\'ye denizin ortasında Viking cenaze töreni yapar. Merry konuşur: "Çok mutluydum... teşekkür ederim." Herkes ağlar.' },
      { number: 22, title: 'Deniz Kızı Efsanesi', slug: 'enies-lobby-22', duration: '24:30', summary: 'Mürettebat Water Seven\'a döner. Herkes yaralıdır ve dinlenmeye ihtiyaç vardır. Galley-La ustaları onları saklar. Enies Lobby\'nin yıkımı dünya çapında haber olur.' },
      { number: 23, title: 'Burası Cehennem Falan Değil', slug: 'enies-lobby-23', duration: '24:30', summary: 'Mürettebatın ödülleri güncellenir. Luffy 300 milyon, Zoro 120 milyon, Robin 80 milyon. Sanji\'nin posteri çizim olarak çıkar — fotoğrafçı lensi kapattığı için. Sogeking\'in posteri yayınlanır.' },
      { number: 24, title: 'Net Yenilgi', slug: 'enies-lobby-24', duration: '24:30', summary: 'Iceburg, Franky\'yi Hasır Şapkalara katılması için ikna eder. Franky, gözyaşlarıyla kabul eder. Tom\'un mirasını sürdürmek ve dünyanın sonuna ulaşan gemiyi yapmak istiyordur.' },
      { number: 25, title: 'Yadigâra Düşen Karlar', slug: 'enies-lobby-25', duration: '24:30', summary: 'Franky, efsanevi Adam Ağacı\'ndan rüya gemisi Thousand Sunny\'yi inşa etmeye başlar. Geminin planları ortaya çıkar: Coup de Burst, Soldier Dock sistemi ve daha fazlası. Yeni bir çağın gemisi şekillenmektedir.' },
    ],
  },
  {
    name: 'Post-Enies Lobby',
    slug: 'post-enies-lobby',
    saga: 'water-7',
    cover: '/arcs/post-enies-lobby.webp',
    episodeCount: 5,
    summary: 'Enies Lobby sonrası kutlamalar, Franky\'nin katılması ve Going Merry\'ye son veda. Thousand Sunny\'nin doğuşu.',
    detailedSummary: 'Enies Lobby\'den dönen mürettebat iyileşir ve kutlamalar yapar. Franky, Adam Ağacı\'ndan yapılmış rüya gemisi Thousand Sunny\'yi inşa eder. Garp, Luffy\'nin dedesi olarak ortaya çıkar ve yanında Koby ve Helmeppo vardır. Usopp, mürettebata geri dönmek ister ama gururu engel olur. Zoro sert bir tavır alır: "Kaptanına meydan okuyan biri kolayca geri dönemez." Usopp sonunda özür diler ve gözyaşlarıyla geri kabul edilir. Mürettebat, yeni gemileri Thousand Sunny ile denize açılır.',
    keyEvents: [
      'Thousand Sunny\'nin inşası',
      'Garp\'ın Luffy\'nin dedesi olduğu gerçeği',
      'Usopp\'un özrü ve geri dönüşü',
      'Franky resmi olarak katılır',
      'Yeni gemiyle yolculuk başlar',
    ],
    themes: ['Affetme ve Geri Dönüş', 'Yeni Başlangıçlar', 'Aile Sırları'],
    location: 'Water Seven',
    characters: ['luffy', 'zoro', 'nami', 'sanji', 'usopp', 'chopper', 'robin', 'franky', 'garp'],
    episodes: [
      { number: 1, title: 'En Güçlü Aile Soyu! Koramiral ve Devrimciler!', slug: 'post-enies-lobby-01', duration: '24:00', summary: 'Deniz Kuvvetleri Tümamirali Garp, Water Seven\'a gelir — Luffy\'nin dedesidir! Luffy\'nin babası Dragon\'ın Devrimci Ordu lideri olduğu ortaya çıkar. Koby ve Helmeppo büyümüştür.' },
      { number: 2, title: 'Grand Line\'ın Sınırı ve 600 Milyon Belilik Tayfa!', slug: 'post-enies-lobby-02', duration: '24:00', summary: 'Franky, efsanevi Adam Ağacı\'ndan yaptığı rüya gemisi Thousand Sunny\'yi tamamlar. Gemi, Going Merry\'nin ruhunu taşıyacak bir başyapıttır. Coup de Burst, Soldier Dock sistemi ve daha fazlası.' },
      { number: 3, title: 'Kendini Affet! Franky Ayrılıyor!', slug: 'post-enies-lobby-03', duration: '24:00', summary: 'Ace, eski mürettebat arkadaşı Kara Sakal Teach\'i takip etmektedir. İkisi Banaro Adası\'nda karşılaşır. Teach\'in Yami Yami meyvesinin karanlık gücü ortaya çıkar. Ateş ve karanlık çarpışır. Bu savaşın sonucu dünyayı değiştirecektir.' },
      { number: 4, title: 'Şaşırtıcı Thousand Sunny ve Usopp\'un Gözyaşlı Özrü!', slug: 'post-enies-lobby-04', duration: '24:00', summary: 'Usopp, mürettebata geri dönmek ister ama gururu engel olur. Zoro, Luffy\'ye net konuşur: "Kaptanına meydan okuyan biri kolay kolay geri dönemez." Usopp sonunda gözyaşları içinde özür diler ve tekrar kabul edilir.' },
      { number: 5, title: 'Çemberdeki Ödüller ve Banaro Adası\'ndaki Düello!', slug: 'post-enies-lobby-05', duration: '24:00', summary: 'Tam kadro mürettebat kutlama yapar ve yeni gemileri Thousand Sunny ile Water Seven\'dan ayrılır. Iceburg, Franky Ailesi ve Galley-La ustaları veda eder. Yeni maceralar başlıyor. Thriller Bark\'a doğru!' },
    ],
  },
]
