export type Battle = {
  name: string
  slug: string
  arc: string
  arcSlug: string
  participants: { side1: string[]; side2: string[] }
  participantSlugs?: { side1: string[]; side2: string[] }
  winner: 'side1' | 'side2' | 'draw' | 'interrupted'
  significance: string
  description: string
  keyMoments: string[]
  emotionalWeight: 1 | 2 | 3 | 4 | 5 // 5 = maximum emotional impact
  powerLevel: 1 | 2 | 3 | 4 | 5 // 5 = world-shaking
  category: 'epic' | 'emotional' | 'rivalry' | 'war' | 'turning-point'
  episodes?: string // e.g. "110-130" or "Bölüm 126"
}

export const BATTLE_CATEGORIES: Record<string, { label: string; color: string }> = {
  epic: { label: 'Destansı', color: 'text-gold' },
  emotional: { label: 'Duygusal', color: 'text-sea-light' },
  rivalry: { label: 'Rekabet', color: 'text-luffy' },
  war: { label: 'Savaş', color: 'text-purple-400' },
  'turning-point': { label: 'Dönüm Noktası', color: 'text-emerald-400' },
}

export const BATTLES: Battle[] = [
  {
    name: 'Luffy vs Crocodile',
    slug: 'luffy-vs-crocodile',
    arc: 'Arabasta',
    arcSlug: 'arabasta',
    participants: {
      side1: ['Monkey D. Luffy'],
      side2: ['Sir Crocodile'],
    },
    participantSlugs: { side1: ['luffy'], side2: ['crocodile'] },
    episodes: 'Bölüm 110-130',
    winner: 'side1',
    significance: 'Luffy\'nin ilk Shichibukai\'yi yendiği savaş. Arabasta Krallığı\'nı kurtardı.',
    description: 'Üç aşamada gerçekleşen epik savaş. İlk iki seferde Crocodile galip geldi — Luffy hem kurutuldu hem de zehirlendi. Üçüncü seferde Luffy, kendi kanını kullanarak Crocodile\'ın kum formunu katılaştırdı ve onu yendi. "Yenilmez" Shichibukai\'nin devrilmesi dünyayı sarstı.',
    keyMoments: [
      'Crocodile Luffy\'yi kurutarak birinci maçı kazandı',
      'Luffy zehirli kanca ile yaralanmasına rağmen ayağa kalktı',
      'Luffy kendi kanını kullanarak kumu katılaştırdı',
      'Son yumrukla Crocodile\'ı yerin altından göğe fırlattı',
      'Yağmur yağmaya başladı — Arabasta kurtuldu',
    ],
    emotionalWeight: 4,
    powerLevel: 3,
    category: 'turning-point',
  },
  {
    name: 'Zoro vs Mihawk',
    slug: 'zoro-vs-mihawk',
    arc: 'Baratie',
    arcSlug: 'baratie',
    participants: {
      side1: ['Roronoa Zoro'],
      side2: ['Dracule Mihawk'],
    },
    participantSlugs: { side1: ['zoro'], side2: ['mihawk'] },
    episodes: 'Bölüm 24',
    winner: 'side2',
    significance: 'Zoro\'nun dünyanın en güçlü kılıç ustasıyla karşılaşması. Yenilgisi onu daha güçlü yaptı.',
    description: 'Zoro, rüyasının somut hedefi Mihawk\'a meydan okudu. Mihawk başlangıçta onu ciddiye almadı ve küçük bir bıçakla savaştı. Zoro\'nun iradesi karşısında etkilenen Mihawk, Yoru kılıcını çekti ve tek hamleyle Zoro\'yu yenilgiye uğrattı. Zoro\'nun son sözleri: "Sırtımdan vurulmaktansa ölmeyi tercih ederim." Bu irade Mihawk\'ı derinden etkiledi.',
    keyMoments: [
      'Mihawk küçük bıçakla savaştı — Zoro\'yu ciddiye almadı',
      'Zoro üç kılıcını aynı anda kullandı ama yine de yetersizdi',
      'Mihawk Yoru\'yu çekti — "Güçlü olanın saygısı"',
      'Zoro göğsünü açtı: "Sırtımdan vurmak utanç verici"',
      'Zoro\'nun yemini: "Bir daha asla kaybetmeyeceğim!"',
      'Luffy\'ye: "Sorun olur mu, Korsanlar Kralı?"',
    ],
    emotionalWeight: 5,
    powerLevel: 2,
    category: 'emotional',
  },
  {
    name: 'Luffy vs Rob Lucci',
    slug: 'luffy-vs-lucci',
    arc: 'Enies Lobby',
    arcSlug: 'enies-lobby',
    participants: {
      side1: ['Monkey D. Luffy'],
      side2: ['Rob Lucci'],
    },
    participantSlugs: { side1: ['luffy'], side2: ['rob-lucci'] },
    episodes: 'Bölüm 294-312',
    winner: 'side1',
    significance: 'Luffy\'nin Gear 2 ve Gear 3\'ü ilk kez kullandığı savaş. Robin\'i kurtarmak için Dünya Hükümeti\'ne meydan okudu.',
    description: 'CP9\'un en güçlü üyesi Rob Lucci ile One Piece\'in en uzun 1v1 savaşlarından biri. Luffy, Gear 2 ile hız avantajı, Gear 3 ile güç avantajı kazandı. Lucci\'nin Rokushiki teknikleri ve Zoan formu Luffy\'yi defalarca yere serdi. Sonunda Usopp\'un "Ayağa kalk!" çığlığıyla güç bulan Luffy, Jet Gatling ile Lucci\'yi yendi.',
    keyMoments: [
      'Luffy Gear 2\'yi ilk kez kullandı — Soru Soru ile süper hız',
      'Gear 3\'le devasa yumruk — ama sonra küçüldü (yan etki)',
      'Lucci\'nin altı güç tekniğiyle (Rokushiki) Luffy\'yi ezdiği anlar',
      'Usopp\'un uzaktan "Ayağa kalk Luffy!" diye bağırması',
      'Gomu Gomu no Jet Gatling — final saldırısı',
      'Robin özgür — "Yaşamak istiyorum" sözünün karşılığı',
    ],
    emotionalWeight: 5,
    powerLevel: 4,
    category: 'epic',
  },
  {
    name: 'Marineford Savaşı',
    slug: 'marineford-war',
    arc: 'Marineford',
    arcSlug: 'marineford',
    participants: {
      side1: ['Whitebeard Korsanları', '43 Müttefik Mürettebat', 'Monkey D. Luffy', 'Impel Down kaçakları'],
      side2: ['Deniz Kuvvetleri', '3 Amiral', 'Shichibukai'],
    },
    participantSlugs: { side1: ['whitebeard', 'luffy', 'ace'], side2: ['akainu'] },
    episodes: 'Bölüm 457-489',
    winner: 'side2',
    significance: 'One Piece tarihinin en büyük savaşı. Ace ve Whitebeard\'ın ölümü, Büyük Korsan Çağı\'nın yeni döneminin başlangıcı.',
    description: 'Portgas D. Ace\'in idamını engellemek için Whitebeard tüm gücüyle Marineford\'a saldırdı. Luffy Impel Down\'dan kaçarak savaşa katıldı. Ace kurtarıldı ancak Akainu\'nun magma yumruğuyla öldürüldü. Whitebeard, son nefesinde "One Piece gerçek!" diye haykırdı. Shanks savaşı durdurdu. Blackbeard, Whitebeard\'ın Gura Gura meyvesini çaldı.',
    keyMoments: [
      'Whitebeard\'ın deprem gücüyle Marineford\'u sarsması',
      'Luffy\'nin Haoshoku Haki\'yi bilinçsizce uyandırması',
      'Ace\'in kurtarılması — kısa süren sevinç',
      'Akainu\'nun Ace\'i öldürmesi — Luffy\'nin çöküşü',
      'Whitebeard\'ın son sözleri: "ONE PIECE... GERÇEK!"',
      'Shanks\'ın gelişi ve savaşı durdurması',
      'Blackbeard\'ın iki meyve gücü çalması',
    ],
    emotionalWeight: 5,
    powerLevel: 5,
    category: 'war',
  },
  {
    name: 'Luffy vs Katakuri',
    slug: 'luffy-vs-katakuri',
    arc: 'Whole Cake Island',
    arcSlug: 'whole-cake-island',
    participants: {
      side1: ['Monkey D. Luffy'],
      side2: ['Charlotte Katakuri'],
    },
    participantSlugs: { side1: ['luffy'], side2: ['katakuri'] },
    episodes: 'Bölüm 850-871',
    winner: 'side1',
    significance: 'Luffy\'nin Gelecek Görüşü Haki\'yi (Future Sight) öğrendiği savaş. Karşılıklı saygı üzerine kurulu epik düello.',
    description: 'Ayna dünyasında 11 saatten fazla süren savaş. Katakuri başlangıçta Luffy\'den çok üstündü — Gelecek Görüşü Haki\'siyle her saldırıyı önceden gördü. Luffy, savaş içinde büyüdü ve Katakuri\'nin seviyesine ulaştı. Katakuri, Luffy\'nin iradesine saygı duyarak sonunda yenilgiyi kabul etti. Snakeman formu bu savaşta ortaya çıktı.',
    keyMoments: [
      'Katakuri\'nin Gelecek Görüşü ile her saldırıyı engellemesi',
      'Katakuri\'nin ağzını gizlediği sırrın ortaya çıkması',
      'Katakuri\'nin kendini yaralaması — "Adil savaş"',
      'Luffy\'nin Snakeman formunu açması',
      'Katakuri\'nin sırt üstü düşmesi: "Sen... geleceği görebilecek misin?"',
      'Karşılıklı saygı — düşmandan fazlası',
    ],
    emotionalWeight: 4,
    powerLevel: 4,
    category: 'rivalry',
  },
  {
    name: 'Luffy vs Kaido (Final)',
    slug: 'luffy-vs-kaido',
    arc: 'Wano',
    arcSlug: 'wano',
    participants: {
      side1: ['Monkey D. Luffy'],
      side2: ['Kaido'],
    },
    participantSlugs: { side1: ['luffy'], side2: ['kaido'] },
    episodes: 'Bölüm 1015-1076',
    winner: 'side1',
    significance: 'Luffy\'nin Gear 5\'i uyandırdığı ve Joy Boy\'un mirasçısı olduğu savaş. Bir Yonko\'yu 1v1\'de yenen ilk savaş.',
    description: 'Onigashima\'nın tepesinde gerçekleşen Yonko düzeyinde savaş. Luffy birçok kez yenildi ve hatta "öldü". Ancak her seferinde geri döndü — son seferde Gomu Gomu meyvesinin gerçek uyanışı olan Gear 5\'i aktive etti. Güneş Tanrısı Nika olarak Kaido\'yu yendi. "Kauçuk adam değil, en özgür adam."',
    keyMoments: [
      'Luffy\'nin Haoshoku İnfüzyonu\'nu öğrenmesi',
      'Kaido\'nun Luffy\'yi defalarca yere sermesi',
      'Luffy\'nin kalp atışının durması — "ölüm"',
      'Gear 5 uyanışı — Davulların sesi (Drums of Liberation)',
      'Nika formu ile çizgi film fiziği savaşı',
      'Bajrang Gun — ada boyutunda yumrukla final darbesi',
      'Wano özgür! 20 yıllık esaret sona erdi',
    ],
    emotionalWeight: 5,
    powerLevel: 5,
    category: 'epic',
  },
  {
    name: 'Hasır Şapkalar vs Oars + Moria',
    slug: 'straw-hats-vs-oars',
    arc: 'Thriller Bark',
    arcSlug: 'thriller-bark',
    participants: {
      side1: ['Hasır Şapka Korsanları (tüm mürettebat)'],
      side2: ['Oars (Luffy\'nin gölgesiyle)', 'Gecko Moria'],
    },
    participantSlugs: { side1: ['luffy', 'zoro', 'sanji', 'robin'], side2: ['gecko-moria'] },
    episodes: 'Bölüm 362-381',
    winner: 'side1',
    significance: 'Tüm mürettebatın birlikte savaştığı nadir anlardan biri. "Hiçbir şey olmadı" sahnesinin prelüdü.',
    description: 'Luffy\'nin gölgesi yerleştirilen dev Oars\'a karşı tüm mürettebat birlikte savaştı. Her üyenin özel yeteneği kombine edilerek Oars yenildi. Sonrasında Kuma\'nın müdahalesi ve Zoro\'nun ikonik fedakarlığı.',
    keyMoments: [
      'Tüm mürettebatın taktik olarak savaşması',
      'Robin\'in Oars\'ın sırtını kırması',
      'Luffy Nightmare formu',
      'Zoro\'nun Kuma\'dan Luffy\'nin tüm acısını alması',
      '"Hiçbir şey olmadı" — One Piece\'in en ikonik sahnesi',
    ],
    emotionalWeight: 5,
    powerLevel: 3,
    category: 'emotional',
  },
  {
    name: 'Sanji vs Queen',
    slug: 'sanji-vs-queen',
    arc: 'Wano',
    arcSlug: 'wano',
    participants: {
      side1: ['Vinsmoke Sanji'],
      side2: ['Queen'],
    },
    participantSlugs: { side1: ['sanji'], side2: ['queen'] },
    episodes: 'Bölüm 1034-1036',
    winner: 'side1',
    significance: 'Sanji\'nin Germa genetik uyanışını yaşadığı ve kimliğini kabul ettiği savaş.',
    description: 'Sanji, savaş sırasında Germa genetik modifikasyonunun uyanışını yaşadı — dış iskeleti aktive oldu ve süper dayanıklılık kazandı. "Baba gibi olmak istemiyorum" ile "Bu gücü kendi yolumda kullanacağım" arasındaki iç çatışma. Ifrit Jambe ile Queen\'i yendi.',
    keyMoments: [
      'Sanji\'nin dış iskeletinin uyanması — "Ben canavar mı oluyorum?"',
      'Sanji\'nin Zoro\'ya söz vermesi — "Eğer insan olmaktan çıkarsam, beni öldür"',
      'Raid Suit\'i yok etmesi — kendi gücünü seçme',
      'Ifrit Jambe — cehennem ateşi tekmeleri',
    ],
    emotionalWeight: 4,
    powerLevel: 4,
    category: 'turning-point',
  },
  {
    name: 'Zoro vs King',
    slug: 'zoro-vs-king',
    arc: 'Wano',
    arcSlug: 'wano',
    participants: {
      side1: ['Roronoa Zoro'],
      side2: ['King'],
    },
    participantSlugs: { side1: ['zoro'], side2: ['king'] },
    episodes: 'Bölüm 1027-1036',
    winner: 'side1',
    significance: 'Zoro\'nun Haoshoku Haki\'yi kılıcına akıtmayı öğrendiği ve Enma\'yı tam olarak kontrol ettiği savaş.',
    description: 'Kaido\'nun sağ kolu King, son Lunarian ırkından bir savaşçı. Zoro, King\'in savunma ve saldırı arasında geçiş yapan benzersiz savaş tarzını çözdü. Enma kılıcının tüm Haki\'sini çekmesine izin vererek Haoshoku Haki\'yi kılıcına akıttı.',
    keyMoments: [
      'King\'in Lunarian ırkının sırlarının ortaya çıkması',
      'Zoro\'nun Enma\'nın Haki emişine boyun eğmesi',
      'Haoshoku Haki\'nin kılıca akıtılması — farkında olmadan',
      '"Korsanlar Kralı\'nın mürettebatının kılıç ustası olmak, bundan azı kabul edilemez"',
    ],
    emotionalWeight: 3,
    powerLevel: 4,
    category: 'epic',
  },
  {
    name: 'Luffy vs Arlong',
    slug: 'luffy-vs-arlong',
    arc: 'Arlong Park',
    arcSlug: 'arlong-park',
    participants: {
      side1: ['Monkey D. Luffy'],
      side2: ['Arlong'],
    },
    participantSlugs: { side1: ['luffy'], side2: ['arlong'] },
    episodes: 'Bölüm 37-44',
    winner: 'side1',
    significance: 'Nami\'nin özgürlüğü. "Bana yardım et" sahnesi ve Luffy\'nin şapkasını Nami\'ye vermesi.',
    description: 'Nami\'nin 8 yıllık acısına son veren savaş. Luffy, Arlong\'un harita odasını — Nami\'nin gözyaşlarıyla çizdiği haritaların olduğu odayı — yumruklarıyla paramparça etti. "Bu odayı, bu kalemi, bu masayı — HEPSİNİ YOK EDECEĞİM!" Arlong Park yıkıldı, Nami özgürleşti.',
    keyMoments: [
      'Nami\'nin "Luffy... bana yardım et" demesi',
      'Luffy\'nin hasır şapkayı Nami\'ye koyması',
      'Harita odasının yıkılması — Nami\'nin zincirlerinin kırılması',
      'Gomu Gomu no Ono ile final darbesi',
      '"Tabii ki yardım edeceğim!!!"',
      'Nami\'nin gülümsemesi ve "Luffy\'nin arkadaşıyım" demesi',
    ],
    emotionalWeight: 5,
    powerLevel: 2,
    category: 'emotional',
  },
  {
    name: 'Roger vs Whitebeard',
    slug: 'roger-vs-whitebeard',
    arc: 'Wano (flashback)',
    arcSlug: 'wano',
    participants: {
      side1: ['Gol D. Roger'],
      side2: ['Edward Newgate / Whitebeard'],
    },
    participantSlugs: { side1: ['roger'], side2: ['whitebeard'] },
    episodes: 'Bölüm 966',
    winner: 'draw',
    significance: 'İki efsanevi korsan arasındaki çarpışma. Haoshoku İnfüzyonu ile gökyüzünün ikiye bölündüğü an.',
    description: 'Oden\'in flashback\'inde gösterilen efsanevi çarpışma. Roger ve Whitebeard kılıçlarını çarpıştırdığında — silahları temas etmeden — Haoshoku Haki\'nin çarpışmasıyla gökyüzü ikiye bölündü. İki dünyanın en güçlü adamının eşit düzeyde karşılaşması.',
    keyMoments: [
      'İki kılıcın çarpışması — temas olmadan Haki şoku',
      'Gökyüzünün ikiye bölünmesi',
      'Roger ve Whitebeard\'ın gülümsemesi',
      'Haoshoku İnfüzyonu\'nun ilk tam gösterimi',
    ],
    emotionalWeight: 3,
    powerLevel: 5,
    category: 'rivalry',
  },
  {
    name: 'Luffy vs Usopp',
    slug: 'luffy-vs-usopp',
    arc: 'Water Seven',
    arcSlug: 'water-seven',
    participants: {
      side1: ['Monkey D. Luffy'],
      side2: ['Usopp'],
    },
    participantSlugs: { side1: ['luffy'], side2: ['usopp'] },
    episodes: 'Bölüm 236',
    winner: 'side1',
    significance: 'Mürettebat içi en duygusal çatışma. Going Merry\'nin kaderi üzerine.',
    description: 'Going Merry\'nin tamir edilemeyecek durumda olduğu öğrenildiğinde Usopp buna itiraz etti — Merry onun Kaya\'dan aldığı en değerli şeydi. Luffy\'ye düello etti. Luffy kazandı ama ikisi de ağladı. Usopp, Enies Lobby\'de "Sogeking" maskesiyle geri döndü ama resmi olarak ancak Post-Enies Lobby\'de özür dileyerek tekrar katıldı.',
    keyMoments: [
      'Usopp\'un "Merry\'yi terk edemezsin!" çığlığı',
      'Düello — Luffy\'nin ağlayarak savaşması',
      'Luffy\'nin kazandıktan sonra "Ağırdı..." demesi',
      'İkisinin gözyaşları — mürettebat bölünmesi',
    ],
    emotionalWeight: 5,
    powerLevel: 1,
    category: 'emotional',
  },
]

export function getBattleBySlug(slug: string): Battle | undefined {
  return BATTLES.find((b) => b.slug === slug)
}
