import type { Character } from '@/types'

export const CHARACTERS: Character[] = [
  {
    name: 'Monkey D. Luffy',
    slug: 'luffy',
    image: '/characters/luffy.jpg',
    crew: 'straw-hat',
    epithet: 'Hasır Şapka',
    bounty: '3,000,000,000',
    devilFruit: 'Hito Hito no Mi, Model: Nika',
    description: 'Hasır Şapka Korsanlarının kaptanı. Korsanlar Kralı olmak en büyük hayali. Neşeli, özgürlüğüne düşkün ve inanılmaz güçlü bir savaşçı.',
    backstory: 'Monkey D. Luffy, East Blue\'daki Foosha Köyü\'nde büyüdü. Küçük yaşta Kızıl Saçlı Shanks ile tanıştı ve ondan korsan olma hayalini aldı. Gomu Gomu no Mi\'yi (aslında Hito Hito no Mi, Model: Nika) yanlışlıkla yedi ve lastik insan oldu. Shanks, Luffy\'yi bir deniz canavarından kurtarırken sol kolunu kaybetti ve ayrılırken ona hasır şapkasını verdi: "Bunu bana geri ver, harika bir korsan olduğunda." Luffy, Ace ve Sabo ile kardeşler olarak büyüdü. 17 yaşında denize açıldı. Marineford Savaşı\'nda ağabeyi Ace\'i kaybetti — hayatının en büyük travması. 2 yıl Rayleigh\'den Haki eğitimi aldı. Wano\'da meyvesinin gerçek uyanışı olan Gear 5\'i açığa çıkardı ve Joy Boy\'un mirasçısı oldu.',
    role: 'Kaptan — mürettebatın kalbi, karar verici ve en güçlü savaşçısı',
    age: '19',
    height: '174 cm',
    origin: 'Foosha Köyü, Dawn Adası, East Blue',
    firstArc: 'romance-dawn',
    appearances: ['romance-dawn', 'orange-town', 'syrup-village', 'baratie', 'arlong-park', 'loguetown', 'reverse-mountain', 'whiskey-peak', 'little-garden', 'drum-island', 'arabasta', 'jaya', 'skypiea', 'long-ring-long-land', 'water-seven', 'enies-lobby', 'post-enies-lobby', 'thriller-bark', 'sabaody-archipelago', 'amazon-lily', 'impel-down', 'marineford', 'post-war', 'return-to-sabaody', 'fish-man-island', 'punk-hazard', 'dressrosa', 'zou', 'whole-cake-island', 'wano', 'egghead'],
    abilities: ['Gear 2', 'Gear 3', 'Gear 4 (Boundman, Snakeman, Tankman)', 'Gear 5 (Nika)', 'Haoshoku Haki', 'Busoshoku Haki', 'Kenbunshoku Haki (Gelecek Görüşü)'],
  },
  {
    name: 'Roronoa Zoro',
    slug: 'zoro',
    image: '/characters/zoro.jpg',
    crew: 'straw-hat',
    epithet: 'Korsan Avcısı',
    bounty: '1,111,000,000',
    description: 'Hasır Şapkaların savaşçısı ve kılıç ustası. Dünyanın en iyi kılıç ustası olmayı hedefliyor. Üç kılıç stili (Santoryu) kullanır.',
    backstory: 'Roronoa Zoro, küçük yaşta Shimotsuki Dojo\'da kılıç eğitimi aldı. Çocukluk arkadaşı ve rakibi Kuina ile "birimiz dünyanın en iyi kılıç ustası olacak" sözü verdi. Kuina\'nın ani ölümünden sonra onun kılıcı Wado Ichimonji\'yi aldı ve yemin etti: bir daha asla kaybetmeyecek. East Blue\'da korsan avcısı olarak ün kazandı. Baratie\'de Mihawk\'a meydan okudu ve ağır bir yenilgi aldı — ama bu yenilgi onu daha güçlü yaptı. Enies Lobby\'de hayatını mürettebatı için feda etmeye hazırdı. Thriller Bark\'ta Kuma\'dan Luffy\'nin tüm acısını üstüne aldı: "Hiçbir şey olmadı." 2 yıl Mihawk\'tan eğitim aldı. Wano\'da Enma kılıcını edindi ve Haoshoku Haki\'yi kılıcına akıtmayı öğrendi.',
    role: 'Savaşçı / Yan Kaptan — mürettebatın en güçlü ikinci üyesi',
    age: '21',
    height: '181 cm',
    origin: 'Shimotsuki Köyü, East Blue',
    firstArc: 'romance-dawn',
    appearances: ['romance-dawn', 'orange-town', 'syrup-village', 'baratie', 'arlong-park', 'loguetown', 'reverse-mountain', 'whiskey-peak', 'little-garden', 'drum-island', 'arabasta', 'jaya', 'skypiea', 'long-ring-long-land', 'water-seven', 'enies-lobby', 'post-enies-lobby', 'thriller-bark', 'sabaody-archipelago', 'return-to-sabaody', 'fish-man-island', 'punk-hazard', 'dressrosa', 'zou', 'wano', 'egghead'],
    abilities: ['Santoryu (Üç Kılıç)', 'Busoshoku Haki', 'Haoshoku Haki', 'Kenbunshoku Haki', 'Ashura', 'Enma Kılıcı'],
  },
  {
    name: 'Nami',
    slug: 'nami',
    image: '/characters/nami.jpg',
    crew: 'straw-hat',
    epithet: 'Hırsız Kedi',
    bounty: '366,000,000',
    description: 'Hasır Şapkaların navigatörü. Dünyanın haritasını çizmeyi hayal eder. Hava durumunu okuma ve manipüle etme konusunda dahi.',
    backstory: 'Nami, bebek olarak Bellemere tarafından savaş alanında bulundu ve Nojiko ile birlikte evlat edinildi. Cocoyashi Köyü\'nde mutlu bir çocukluk geçirdi ama Arlong geldiğinde her şey değişti. Bellemere, kızlarını korumak için hayatını feda etti. Arlong, 8 yaşındaki Nami\'ye bir anlaşma sundu: 100 milyon Berry kazanırsa köyünü satın alabilir. 8 yıl boyunca Arlong için harita çizerek para biriktirdi ama Arlong hileyle parayı çaldırdı. Luffy\'nin Arlong Park\'ı yıkmasıyla özgürleşti. Dünyanın haritasını çizmek — tüm denizleri kendi gözleriyle görüp çizmek — en büyük rüyası.',
    role: 'Navigatör — rotayı belirleyen, haritaları çizen ve hava durumunu okuyan',
    age: '20',
    height: '170 cm',
    origin: 'Cocoyashi Köyü, Conomi Adaları, East Blue',
    firstArc: 'orange-town',
    appearances: ['orange-town', 'syrup-village', 'baratie', 'arlong-park', 'loguetown', 'reverse-mountain', 'whiskey-peak', 'little-garden', 'drum-island', 'arabasta', 'jaya', 'skypiea', 'long-ring-long-land', 'water-seven', 'enies-lobby', 'post-enies-lobby', 'thriller-bark', 'sabaody-archipelago', 'return-to-sabaody', 'fish-man-island', 'punk-hazard', 'dressrosa', 'zou', 'whole-cake-island', 'wano', 'egghead'],
    abilities: ['Clima-Tact', 'Zeus', 'Hava Manipülasyonu', 'Navigasyon Dehası'],
  },
  {
    name: 'Usopp',
    slug: 'usopp',
    image: '/characters/usopp.jpg',
    crew: 'straw-hat',
    epithet: 'Tanrı / Sogeking',
    bounty: '500,000,000',
    description: 'Hasır Şapkaların nişancısı. Yalancı hikayeleri meşhurdur ama aslında çok yetenekli bir nişancıdır. Cesur bir savaşçı olmayı hayal eder.',
    backstory: 'Usopp, Syrup Köyü\'nde annesiyle büyüdü. Babası Yasopp, Shanks\'ın mürettebatına katılarak aileyi terk etti. Annesi hasta olup öldüğünde Usopp yalnız kaldı. Her gün köyde "korsanlar geliyor!" diye bağırarak yalan söylemeye başladı — aslında babasının geri döneceğini umuyordu. Kaptan Kuro olayından sonra Luffy\'nin mürettebatına katıldı. Water Seven\'da Going Merry\'yi bırakma kararıyla sarsıldı ve Luffy\'ye düello etti. "Sogeking" maskesiyle Enies Lobby\'de savaştı. Dressrosa\'da Kenbunshoku Haki\'yi uyandırdı ve "Tanrı Usopp" olarak 200 milyon ödüle ulaştı. En büyük hayali: cesur bir deniz savaşçısı olmak.',
    role: 'Nişancı — uzun menzil savaşçısı, taktikçi ve icatçı',
    age: '19',
    height: '176 cm',
    origin: 'Syrup Köyü, East Blue',
    firstArc: 'syrup-village',
    appearances: ['syrup-village', 'baratie', 'arlong-park', 'loguetown', 'reverse-mountain', 'whiskey-peak', 'little-garden', 'drum-island', 'arabasta', 'jaya', 'skypiea', 'long-ring-long-land', 'water-seven', 'enies-lobby', 'post-enies-lobby', 'thriller-bark', 'sabaody-archipelago', 'return-to-sabaody', 'fish-man-island', 'punk-hazard', 'dressrosa', 'zou', 'whole-cake-island', 'wano', 'egghead'],
    abilities: ['Nişancılık', 'Kenbunshoku Haki', 'Pop Green', 'Kabuto', 'Yaratıcı Taktikler'],
  },
  {
    name: 'Sanji',
    slug: 'sanji',
    image: '/characters/sanji.jpg',
    crew: 'straw-hat',
    epithet: 'Kara Bacak',
    bounty: '1,032,000,000',
    devilFruit: undefined,
    description: 'Hasır Şapkaların aşçısı. All Blue\'yu bulmayı hayal eder. Sadece ayaklarıyla savaşır, ellerini asla dövüş için kullanmaz.',
    backstory: 'Sanji, Germa 66 krallık ailesi Vinsmoke\'ların üçüncü oğlu olarak doğdu. Babası Judge, çocuklarını genetik olarak modifiye ederek duygusuz silahlar yapmak istedi. Annesi Sora, bunu engellemek için ilaç aldı ve hayatını kaybetti. Sanji, kardeşleri gibi olmadığı için "başarısız" sayıldı ve hapsedildi. Kardeşleri tarafından dövüldü, sadece ablası Reiju ona yardım etti. Kaçarak Baratie\'ye sığındı. Baş aşçı Zeff ile birlikte küçük bir adada mahsur kaldı. Zeff, Sanji\'yi kurtarmak için kendi bacağını yedi. "Bir beyefendi asla bir kadına vurmaz ve asla aç birini geri çevirmez" — Zeff\'in öğretisi Sanji\'nin yaşam felsefesi oldu. All Blue — tüm denizlerin balıklarının bulunduğu efsanevi deniz — rüyası.',
    role: 'Aşçı — mürettebatın beslenme uzmanı ve en güçlü savaşçılardan biri',
    age: '21',
    height: '180 cm',
    origin: 'Germa Krallığı / Baratie, North Blue',
    firstArc: 'baratie',
    appearances: ['baratie', 'arlong-park', 'loguetown', 'reverse-mountain', 'whiskey-peak', 'little-garden', 'drum-island', 'arabasta', 'jaya', 'skypiea', 'long-ring-long-land', 'water-seven', 'enies-lobby', 'post-enies-lobby', 'thriller-bark', 'sabaody-archipelago', 'return-to-sabaody', 'fish-man-island', 'punk-hazard', 'dressrosa', 'zou', 'whole-cake-island', 'wano', 'egghead'],
    abilities: ['Diable Jambe', 'Ifrit Jambe', 'Germa Dış İskeleti', 'Kenbunshoku Haki', 'Busoshoku Haki', 'Skywalk'],
  },
  {
    name: 'Tony Tony Chopper',
    slug: 'chopper',
    image: '/characters/chopper.jpg',
    crew: 'straw-hat',
    epithet: 'Pamuk Şeker Sever',
    bounty: '1,000',
    devilFruit: 'Hito Hito no Mi',
    description: 'Hasır Şapkaların doktoru. İnsan formuna dönüşebilen bir ren geyiği. Tüm hastalıkları tedavi edecek bir ilaç bulmayı hayal eder.',
    backstory: 'Tony Tony Chopper, Drum Adası\'nda doğmuş bir ren geyiğidir. Mavi burnu yüzünden sürüsü tarafından dışlandı. Hito Hito no Mi\'yi yiyerek insan zekası kazandı ama hem hayvanlar hem insanlar onu "canavar" olarak gördü. Doktor Hiluluk onu buldu ve sevdi. Hiluluk, "tüm hastalıkları iyileştiren kiraz çiçekleri" rüyasıyla yaşayan çılgın bir doktordur. Chopper, Hiluluk\'u kurtarmak için zehirli bir mantar buldu — zehirli olduğunu bilmeden. Hiluluk, Chopper\'ın sevgisini bildiği için mantarı içti ve sonra kendini feda etti: "İnsanlar ne zaman ölür? Unutulduklarında!" Dr. Kureha\'dan tıp eğitimi alan Chopper, Luffy\'nin daveti ile mürettebata katıldı.',
    role: 'Doktor — mürettebatın sağlık uzmanı, 7 farklı forma dönüşebilir',
    age: '17',
    height: '90 cm (insan formu)',
    origin: 'Drum Adası, Grand Line',
    firstArc: 'drum-island',
    appearances: ['drum-island', 'arabasta', 'jaya', 'skypiea', 'long-ring-long-land', 'water-seven', 'enies-lobby', 'post-enies-lobby', 'thriller-bark', 'sabaody-archipelago', 'return-to-sabaody', 'fish-man-island', 'punk-hazard', 'dressrosa', 'zou', 'whole-cake-island', 'wano', 'egghead'],
    abilities: ['7 Form Dönüşümü', 'Monster Point', 'Rumble Ball', 'Tıp Bilgisi'],
  },
  {
    name: 'Nico Robin',
    slug: 'robin',
    image: '/characters/robin.jpg',
    crew: 'straw-hat',
    epithet: 'Şeytan Çocuğu',
    bounty: '930,000,000',
    devilFruit: 'Hana Hana no Mi',
    description: 'Hasır Şapkaların arkeologu. Poneglyph\'leri okuyabilen son kişi. Rio Poneglyph\'i bulmak ve gerçek tarihi öğrenmek en büyük hayali.',
    backstory: 'Nico Robin, Ohara adasında büyüdü. 8 yaşında arkeolog oldu ve Poneglyph\'leri okumayı öğrendi. Annesi Olvia, araştırma için denize çıktı ve yakalandı. Dünya Hükümeti, Ohara\'nın Void Century araştırmalarını tehdit olarak gördü ve Buster Call ile tüm adayı yok etti. Robin, Aokiji\'nin "izin vermesiyle" kaçan tek kurtulandır. 20 yıl boyunca kaçak olarak yaşadı — güvendiği herkes onu sattı. 8 yaşında 79 milyon Berry ödül konulmuştu. Crocodile\'a katıldı ama ihanet etti. Arabasta sonrası Hasır Şapkalara sığındı. Enies Lobby\'deki "Yaşamak istiyorum!" çığlığı, 20 yıl sonra ilk kez hayata tutunmasıdır.',
    role: 'Arkeolog — Poneglyph okuyucu, tarihin anahtarı',
    age: '30',
    height: '188 cm',
    origin: 'Ohara, West Blue',
    firstArc: 'arabasta',
    appearances: ['arabasta', 'jaya', 'skypiea', 'long-ring-long-land', 'water-seven', 'enies-lobby', 'post-enies-lobby', 'thriller-bark', 'sabaody-archipelago', 'return-to-sabaody', 'fish-man-island', 'punk-hazard', 'dressrosa', 'zou', 'wano', 'egghead'],
    abilities: ['Hana Hana no Mi', 'Gigante Fleur', 'Demonio Fleur', 'Arkeoloji ve Tarih Bilgisi'],
  },
  {
    name: 'Franky',
    slug: 'franky',
    image: '/characters/franky.jpg',
    crew: 'straw-hat',
    epithet: 'Cyborg',
    bounty: '394,000,000',
    description: 'Hasır Şapkaların gemi ustası. Cyborg bir usta. Thousand Sunny\'nin yapımcısı. Rüyası, kendi yaptığı gemiyle dünyanın sonuna ulaşmak.',
    backstory: 'Franky (gerçek adı Cutty Flam), South Blue\'dan terk edilmiş bir çocuk olarak Water Seven\'a geldi. Usta gemi yapımcısı Tom onu ve Iceburg\'u öğrenci olarak aldı. Tom, Roger\'ın gemisi Oro Jackson\'ı yapmış ve Sea Train\'i icat etmiştir. Franky, savaş gemileri yapardı ama bunlar Spandam tarafından kullanılarak Tom\'a iftira atıldı. Franky, Tom\'u kurtarmak için Sea Train\'in önüne atladı ve ezildi. Hurda metallerle kendini cyborg olarak yeniden inşa etti. Tom, Pluton planlarını Franky\'ye emanet etti. Enies Lobby\'den sonra, Tom\'un mirası olan Adam Ağacı\'ndan Thousand Sunny\'yi yaptı ve mürettebata katıldı.',
    role: 'Gemi Ustası — Thousand Sunny\'nin yapımcısı ve bakımcısı',
    age: '36',
    height: '240 cm',
    origin: 'South Blue / Water Seven',
    firstArc: 'water-seven',
    appearances: ['water-seven', 'enies-lobby', 'post-enies-lobby', 'thriller-bark', 'sabaody-archipelago', 'return-to-sabaody', 'fish-man-island', 'punk-hazard', 'dressrosa', 'zou', 'wano', 'egghead'],
    abilities: ['Cyborg Gövde', 'Radical Beam', 'General Franky', 'Coup de Vent', 'Mühendislik Dehası'],
  },
  {
    name: 'Brook',
    slug: 'brook',
    image: '/characters/brook.jpg',
    crew: 'straw-hat',
    epithet: 'Soul King',
    bounty: '383,000,000',
    devilFruit: 'Yomi Yomi no Mi',
    description: 'Hasır Şapkaların müzisyeni. Ölüp dirilen iskelet müzisyen. Laboon ile tekrar buluşmayı hayal eder.',
    backstory: 'Brook, Batı Deniz\'deki Rumbar Korsanlarının müzisyeniydi. 50 yıl önce mürettebatıyla birlikte Grand Line\'a girdi. Twin Cape\'de dev balina Laboon\'u bıraktılar: "Geri döneceğiz!" Ancak zehirli bir düşmanla karşılaştılar ve tüm mürettebat öldü. Brook, Yomi Yomi meyvesi sayesinde dirildi ama ruhunun geri dönmesi 1 yıl sürdü — bu sürede bedeni iskelet olmuştu. 50 yıl boyunca Florian Üçgeni\'nde tek başına dolaştı. Gölgesi Moria tarafından çalındı. Hasır Şapkalar tarafından kurtarıldıktan sonra mürettebata katıldı. Laboon\'a verdiği sözü tutmak — Binks\'in Sake\'sini çalarak geri dönmek — en büyük hayali.',
    role: 'Müzisyen — mürettebatın moral kaynağı ve ruh savaşçısı',
    age: '90',
    height: '277 cm',
    origin: 'Batı Deniz',
    firstArc: 'thriller-bark',
    appearances: ['thriller-bark', 'sabaody-archipelago', 'return-to-sabaody', 'fish-man-island', 'punk-hazard', 'dressrosa', 'zou', 'whole-cake-island', 'wano', 'egghead'],
    abilities: ['Yomi Yomi no Mi', 'Ruh Gücü', 'Soul Solid (Buz Kılıcı)', 'Müzik'],
  },
  {
    name: 'Jinbe',
    slug: 'jinbe',
    image: '/characters/jinbe.jpg',
    crew: 'straw-hat',
    epithet: 'Denizin Şövalyesi',
    bounty: '1,100,000,000',
    description: 'Hasır Şapkaların dümencisi. Balık-Adam Karate ustası ve eski Shichibukai. İnsanlar ve Balık-Adamlar arasında barış istiyor.',
    backstory: 'Jinbe, Fish-Man Island\'da doğmuş bir balina köpekbalığı Balık-Adamıdır. Fisher Tiger\'ın Güneş Korsanlarına katıldı ve Tiger\'ın ölümünden sonra kaptan oldu. Shichibukai olarak Fish-Man Island\'ı korudu. Marineford Savaşı\'nda Ace\'in idamına karşı çıkarak Shichibukai\'lik\'ten istifa etti ve Impel Down\'a hapsedildi. Luffy ile birlikte kaçtı ve Marineford\'da savaştı. Ace\'in ölümünden sonra çöken Luffy\'ye hayatta kalanlarını hatırlattı. Big Mom\'un mürettebatındaydı ama Luffy için ayrıldı. Whole Cake Island\'da resmi olarak Hasır Şapkalara katıldı. İnsanlar ve Balık-Adamlar arasında barış — Fisher Tiger ve Otohime\'nin rüyası — en büyük hedefi.',
    role: 'Dümenci — denizcilik uzmanı ve deneyimli savaşçı',
    age: '46',
    height: '301 cm',
    origin: 'Fish-Man Island, Grand Line',
    firstArc: 'impel-down',
    appearances: ['impel-down', 'marineford', 'post-war', 'fish-man-island', 'whole-cake-island', 'wano', 'egghead'],
    abilities: ['Balık-Adam Karate', 'Busoshoku Haki', 'Kenbunshoku Haki', 'Su Manipülasyonu'],
  },
  // ─── Yonko ──────────────────────────────────────────────────────────────
  {
    name: 'Shanks',
    slug: 'shanks',
    image: '/characters/shanks.jpg',
    crew: 'yonko',
    epithet: 'Kızıl Saçlı',
    bounty: '4,048,900,000',
    description: 'Kızıl Saçlı Korsanların kaptanı ve Dört İmparator\'dan biri. Luffy\'ye hasır şapkayı veren ve ona ilham kaynağı olan efsanevi korsan.',
    backstory: 'Shanks, Roger Korsanlarında çıraklık yaptı. Roger\'ın idamından sonra kendi korsanlarını kurdu ve Yonko\'lar arasına girdi. Foosha Köyü\'nde küçük Luffy ile tanıştı ve onu korumak için sol kolunu kaybetti. Hasır şapkayı Luffy\'ye emanet etti. Marineford Savaşı\'nı tek başına durdurdu. Gizemli geçmişi — Celestial Dragon kökenli olabileceği ve God Valley olayındaki rolü — hâlâ tam olarak bilinmemektedir. Haki\'nin en güçlü kullanıcılarından biridir.',
    role: 'Luffy\'nin ilham kaynağı ve koruyucu figürü',
    age: '39',
    height: '199 cm',
    origin: 'Batı Deniz',
    firstArc: 'romance-dawn',
    appearances: ['romance-dawn', 'marineford', 'post-war', 'reverie', 'wano'],
    abilities: ['Haoshoku Haki (En Güçlü)', 'Busoshoku Haki', 'Kenbunshoku Haki', 'Kılıç Ustalığı'],
  },
  {
    name: 'Kaido',
    slug: 'kaido',
    image: '/characters/kaido.jpg',
    crew: 'yonko',
    epithet: 'Yüz Hayvanın Kaido\'su',
    bounty: '4,611,100,000',
    devilFruit: 'Uo Uo no Mi, Model: Seiryu',
    description: 'Eski Dört İmparator ve Hayvan Korsanlarının kaptanı. Dünyanın en güçlü canlısı olarak bilinir. Wano\'yu 20 yıl boyunca tiranlıkla yönetti.',
    backstory: 'Kaido, Vodka Krallığı\'nda doğdu. Küçük yaşta savaşçı olarak kullanıldı ve ülkesi tarafından Deniz Kuvvetleri\'ne satıldı. Rocks Korsanlarında büyüdü ve Big Mom\'dan Uo Uo no Mi meyvesini aldı. God Valley olayından sonra kendi korsanlarını kurdu. Wano\'yu 20 yıl önce işgal etti ve Kozuki Oden\'i idam etti. Ölmek isteyip de ölemeyen "dünyanın en güçlü canlısı" olarak bilinir. Joy Boy\'u bekliyordu — ve Luffy\'nin Gear 5\'iyle karşılaştığında gülümsedi.',
    role: 'Wano sagasının ana antagonisti — tarihin en güçlü korsanlarından biri',
    age: '59',
    height: '710 cm',
    origin: 'Vodka Krallığı',
    firstArc: 'punk-hazard',
    appearances: ['punk-hazard', 'dressrosa', 'zou', 'wano'],
    abilities: ['Uo Uo no Mi (Ejderha Formu)', 'Haoshoku Haki', 'Busoshoku Haki', 'Kenbunshoku Haki', 'Thunder Bagua', 'Blazing Bagua'],
  },
  {
    name: 'Edward Newgate (Whitebeard)',
    slug: 'whitebeard',
    image: '/characters/whitebeard.jpg',
    crew: 'yonko',
    epithet: 'Beyaz Sakal',
    bounty: '5,046,000,000',
    devilFruit: 'Gura Gura no Mi',
    description: 'Eski Dört İmparator ve "Dünyanın En Güçlü Adamı". Deprem yaratabilir. Mürettebatını ailesi olarak görür.',
    backstory: 'Edward Newgate, fakir bir ülkede doğdu ve tek istediği aile oldu. Rocks Korsanlarında savaştı ama ayrılarak kendi mürettebatını kurdu. "Çocuklarım" dediği mürettebatını her şeyden çok severdi. Roger ile çağdaş ve rakipti. Ace\'i evlat edindi ve korudu. Marineford\'da Ace\'i kurtarmak için Marine HQ\'ya saldırdı. Yüzlerce yara almış, göğsü delinmiş olmasına rağmen tek bir adım bile geri atmadan ayakta öldü. Son sözleri: "ONE PIECE GERÇEK!"',
    role: 'Eski çağın en güçlü korsanı — aile değerleri ve yıkılmaz irade sembolü',
    age: '72 (ölümünde)',
    height: '666 cm',
    origin: 'Sphinx, Yeni Dünya',
    firstArc: 'marineford',
    appearances: ['marineford'],
    abilities: ['Gura Gura no Mi (Deprem)', 'Haoshoku Haki', 'Busoshoku Haki', 'Kenbunshoku Haki'],
  },
  {
    name: 'Marshall D. Teach (Blackbeard)',
    slug: 'blackbeard',
    image: '/characters/blackbeard.jpg',
    crew: 'yonko',
    epithet: 'Kara Sakal',
    bounty: '3,996,000,000',
    devilFruit: 'Yami Yami no Mi + Gura Gura no Mi',
    description: 'Kara Sakal Korsanlarının kaptanı. Tarihte iki Şeytan Meyvesi gücüne sahip tek kişi.',
    backstory: 'Marshall D. Teach, Beyaz Sakal Korsanlarında uzun yıllar gizlenerek yaşadı. Yami Yami meyvesini ele geçirmek için yoldaşı Thatch\'i öldürdü. Ace\'i yakalayarak Deniz Kuvvetleri\'ne teslim etti — bu, Marineford Savaşı\'nı tetikledi. Impel Down\'dan en tehlikeli suçluları topladı. Marineford\'da Beyaz Sakal\'ın cesedinden Gura Gura meyvesini çaldı. İki Şeytan Meyvesine sahip tarihteki tek kişi. D. soyadının taşıyıcısı olarak One Piece\'in en büyük gizemlerinden birini temsil eder.',
    role: 'Serinin en büyük antagonistlerinden biri — Luffy\'nin karanlık aynası',
    age: '40',
    height: '344 cm',
    origin: 'Bilinmiyor',
    firstArc: 'jaya',
    appearances: ['jaya', 'impel-down', 'marineford', 'post-war', 'wano'],
    abilities: ['Yami Yami no Mi (Karanlık)', 'Gura Gura no Mi (Deprem)', 'Busoshoku Haki', 'Kenbunshoku Haki'],
  },
  {
    name: 'Charlotte Linlin (Big Mom)',
    slug: 'bigmom',
    image: '/characters/bigmom.jpg',
    crew: 'yonko',
    epithet: 'Big Mom',
    bounty: '4,388,000,000',
    devilFruit: 'Soru Soru no Mi',
    description: 'Eski Dört İmparator ve Big Mom Korsanlarının kaptanı. Ruhları manipüle edebilir. 85 çocuk annesi.',
    backstory: 'Charlotte Linlin, çocukken devasa gücü yüzünden ailesi tarafından terk edildi. Yetimhanede Mother Carmel tarafından büyütüldü. 6 yaşında Elbaf devlerini bile korkutan bir canavar olmuştu. Carmel\'in gizemli kayboluşundan sonra Soru Soru meyvesini "devraldı". Rocks Korsanlarında savaştı. Totto Land\'ı kurarak 85 çocukla devasa bir aile imparatorluğu oluşturdu. Whole Cake Island\'da Luffy ile savaştı. Wano\'da Kid ve Law tarafından yenildi.',
    role: 'Whole Cake Island ve Wano sagalarının ana antagonistlerinden biri',
    age: '68',
    height: '880 cm',
    origin: 'Elbaf yakınları',
    firstArc: 'fish-man-island',
    appearances: ['fish-man-island', 'whole-cake-island', 'wano'],
    abilities: ['Soru Soru no Mi (Ruh)', 'Napoleon (Kılıç Homie)', 'Prometheus (Ateş)', 'Hera (Yıldırım)', 'Haoshoku Haki'],
  },
  {
    name: 'Buggy',
    slug: 'buggy',
    image: '/characters/buggy.jpg',
    crew: 'yonko',
    epithet: 'Şanslı Palyaço / Yıldız Palyaço',
    bounty: '3,189,000,000',
    devilFruit: 'Bara Bara no Mi',
    description: 'Eski Roger Korsanı. Şans eseri Dört İmparator arasına girmeyi başardı. Cross Guild\'in "lideri".',
    backstory: 'Buggy, Shanks ile birlikte Roger Korsanlarında çıraklık yaptı. Bara Bara meyvesini yanlışlıkla yedi. Roger\'ın idamından sonra East Blue\'da küçük çaplı korsanlık yaptı. Impel Down\'dan kaçtığında tesadüfen bir kahraman oldu. Marineford\'da Roger mürettebatı geçmişi ortaya çıkınca ünü arttı. Shichibukai sistemi kaldırıldığında Mihawk ve Crocodile ile Cross Guild\'i kurdu — ama kontrol tamamen onlardadır. Buggy "yüz" olarak kullanılmaktadır. Şans eseri Yonko ilan edildi.',
    role: 'Komedik antagonist ve şanslı anti-kahraman',
    age: '39',
    height: '192 cm',
    origin: 'Grand Line (Roger Korsanları gemisinde doğdu)',
    firstArc: 'orange-town',
    appearances: ['orange-town', 'loguetown', 'impel-down', 'marineford'],
    abilities: ['Bara Bara no Mi (Parçalanma)', 'Muggy Ball', 'Şans Faktörü', 'Karizmatik Liderlik'],
  },
  // ─── Supernova ──────────────────────────────────────────────────────────
  {
    name: 'Portgas D. Ace',
    slug: 'ace',
    image: '/characters/ace.jpg',
    crew: 'other',
    epithet: 'Ateş Yumruk',
    bounty: '550,000,000',
    devilFruit: 'Mera Mera no Mi',
    description: 'Luffy\'nin üvey ağabeyi ve Beyaz Sakal Korsanlarının 2. Bölük Komutanı. Korsanlar Kralı Gold Roger\'ın oğlu.',
    backstory: 'Portgas D. Ace, Korsanlar Kralı Gol D. Roger\'ın oğludur. Annesi Portgas D. Rouge, Ace\'i korumak için hamileliğini 20 ay uzattı ve doğumdan sonra öldü. Garp tarafından Dadan\'a bırakılarak Luffy ve Sabo ile kardeşler olarak büyüdü. "Roger\'ın oğlu olarak yaşamayı hak ediyor muyum?" sorusu onu ömür boyu takip etti. 17 yaşında denize açıldı ve Beyaz Sakal\'ın "oğlu" oldu. Blackbeard\'ı takip ederken yakalandı ve Marineford\'da idam edilmek üzere tutuldu. Kurtarıldı ama Akainu\'nun Luffy\'ye yönelik saldırısını vücuduyla engelledi ve öldü.',
    role: 'Luffy\'nin ağabeyi — motivasyonu ve en büyük kaybı',
    age: '20 (ölümünde)',
    height: '185 cm',
    origin: 'Baterilla, South Blue',
    firstArc: 'arabasta',
    appearances: ['arabasta', 'impel-down', 'marineford'],
    abilities: ['Mera Mera no Mi (Ateş)', 'Busoshoku Haki', 'Haoshoku Haki'],
  },
  {
    name: 'Trafalgar D. Law',
    slug: 'law',
    image: '/characters/law.jpg',
    crew: 'supernova',
    epithet: 'Ölüm Cerrahı',
    bounty: '3,000,000,000',
    devilFruit: 'Ope Ope no Mi',
    description: 'Heart Korsanlarının kaptanı. Luffy ile ittifak kurarak Doflamingo ve Kaido\'ya karşı savaştı.',
    backstory: 'Trafalgar D. Water Law, Flevance\'da doğdu. Flevance, Amber Lead zehirlenmesiyle yok edilen bir ülkedir. Ailesi ve tüm tanıdıkları öldürüldü. 10 yaşında Doflamingo\'ya sığındı — ölmek istiyordu. Doflamingo\'nun kardeşi Corazon (Rosinante), Law\'ı kurtardı. Ope Ope meyvesini bularak Law\'ın Amber Lead hastalığını iyileştirdi ve Doflamingo\'ya karşı hayatını feda etti. Law, Corazon\'un intikamı ve D. soyadının gizemini çözmek için Luffy ile ittifak kurdu.',
    role: 'Luffy\'nin en önemli müttefiki — stratejik deha',
    age: '26',
    height: '191 cm',
    origin: 'Flevance, North Blue',
    firstArc: 'sabaody-archipelago',
    appearances: ['sabaody-archipelago', 'marineford', 'punk-hazard', 'dressrosa', 'zou', 'wano'],
    abilities: ['Ope Ope no Mi', 'Room / Shambles', 'K-Room', 'Puncture Wille', 'Busoshoku Haki', 'Kenbunshoku Haki'],
  },
  {
    name: 'Eustass Kid',
    slug: 'kid',
    image: '/characters/kid.jpg',
    crew: 'supernova',
    epithet: 'Kaptan',
    bounty: '3,000,000,000',
    devilFruit: 'Jiki Jiki no Mi',
    description: 'Kid Korsanlarının kaptanı. Manyetizma gücüyle metali kontrol eder. Big Mom\'u Law ile birlikte yendi.',
    backstory: 'Eustass Kid, South Blue\'dan gelen agresif ve hırslı bir korsan. Sabaody\'de Luffy ile aynı dönemde ortaya çıkan Supernova\'lardan biri. Yeni Dünya\'da Kaido\'ya meydan okudu ve yakalandı, sol kolunu kaybetti. Udon hapishanesinde Luffy ile birlikte çalıştı. Wano\'da Killer ile birlikte Kaido\'nun ordusuna karşı savaştı. Law ile birlikte Big Mom\'u yendi.',
    role: 'Luffy\'nin rakibi ve paralel yolculuğun korsanı',
    age: '23',
    height: '205 cm',
    origin: 'South Blue',
    firstArc: 'sabaody-archipelago',
    appearances: ['sabaody-archipelago', 'wano'],
    abilities: ['Jiki Jiki no Mi (Manyetizma)', 'Assign', 'Damned Punk', 'Busoshoku Haki', 'Haoshoku Haki'],
  },
  {
    name: 'Boa Hancock',
    slug: 'hancock',
    image: '/characters/hancock.jpg',
    crew: 'shichibukai',
    epithet: 'Yılan Prensesi',
    bounty: '1,659,000,000',
    devilFruit: 'Mero Mero no Mi',
    description: 'Kuja Korsanlarının kaptanı ve Amazon Lily\'nin imparatoriçesi. Eski Shichibukai. Luffy\'ye aşık.',
    backstory: 'Hancock, çocukken kız kardeşleri Sandersonia ve Marigold ile birlikte Celestial Dragonlar tarafından köle yapıldı. Sırtına köle damgası vuruldu. Fisher Tiger\'ın Mariejois saldırısıyla kurtulduktan sonra Amazon Lily\'ye döndü. Güzelliğini ve gücünü kullanarak Kuja kabilesinin lideri ve Shichibukai oldu. Luffy\'nin köle damgasına gösterdiği öfke ve duyarlılık Hancock\'u etkiledi — ilk kez birine güvendi ve aşık oldu.',
    role: 'Luffy\'nin müttefiki ve aşığı',
    age: '31',
    height: '191 cm',
    origin: 'Amazon Lily, Calm Belt',
    firstArc: 'amazon-lily',
    appearances: ['amazon-lily', 'impel-down', 'marineford'],
    abilities: ['Mero Mero no Mi (Taşa Çevirme)', 'Haoshoku Haki', 'Busoshoku Haki', 'Kenbunshoku Haki'],
  },
  {
    name: 'Dracule Mihawk',
    slug: 'mihawk',
    image: '/characters/mihawk.jpg',
    crew: 'shichibukai',
    epithet: 'Şahin Gözlü',
    bounty: '3,590,000,000',
    description: 'Dünyanın en güçlü kılıç ustası. Eski Shichibukai. Zoro\'nun hedefi.',
    backstory: 'Dracule Mihawk, dünyanın en güçlü kılıç ustasıdır. Siyah kılıç Yoru ile tek başına Don Krieg\'in tüm filosunu yok etmiştir. Shanks ile eski rakiptir — Shanks kolunu kaybetmeden önce düzenli düello yaparlardı. Shichibukai sisteminin kaldırılmasından sonra Crocodile ve Buggy ile Cross Guild\'i kurdu. 2 yıl boyunca Zoro\'yu eğitmiştir — düşmanını eğitmesi, Zoro\'ya olan saygısını gösterir.',
    role: 'Zoro\'nun nihai hedefi ve geçici akıl hocası',
    age: '43',
    height: '198 cm',
    origin: 'Bilinmiyor',
    firstArc: 'baratie',
    appearances: ['baratie', 'marineford'],
    abilities: ['Dünyanın En Güçlü Kılıç Ustalığı', 'Yoru (Siyah Kılıç)', 'Busoshoku Haki', 'Kenbunshoku Haki'],
  },
  {
    name: 'Crocodile',
    slug: 'crocodile',
    image: '/characters/crocodile.jpg',
    crew: 'shichibukai',
    epithet: 'Çöl Kralı',
    bounty: '1,965,000,000',
    devilFruit: 'Suna Suna no Mi',
    description: 'Eski Shichibukai ve Baroque Works\'un lideri. Cross Guild kurucularından.',
    backstory: 'Crocodile, bir zamanlar Yeni Dünya\'da Beyaz Sakal\'a meydan okuyup yenilmiş bir korsandır. Bu yenilgi onu kırdı. East Blue\'ya dönerek Baroque Works gizli örgütünü kurdu ve Arabasta Krallığı\'nı ele geçirmeye çalıştı. Luffy tarafından 3 kez yenildi. Impel Down\'da Luffy ile geçici ittifak kurarak kaçtı ve Marineford\'da savaştı. Savaş sonrası Yeni Dünya\'ya döndü ve Mihawk ve Buggy ile Cross Guild\'i kurdu.',
    role: 'İlk büyük antagonistten müttefike dönüşen karmaşık karakter',
    age: '46',
    height: '253 cm',
    origin: 'Bilinmiyor',
    firstArc: 'arabasta',
    appearances: ['arabasta', 'impel-down', 'marineford'],
    abilities: ['Suna Suna no Mi (Kum)', 'Kum Fırtınası', 'Kanca Silahı', 'Stratejik Zeka'],
  },
  {
    name: 'Donquixote Doflamingo',
    slug: 'doflamingo',
    image: '/characters/doflamingo.jpg',
    crew: 'shichibukai',
    epithet: 'Göklerin Şeytanı / Joker',
    bounty: '340,000,000',
    devilFruit: 'Ito Ito no Mi',
    description: 'Eski Shichibukai ve Dressrosa\'nın zorba kralı. Celestial Dragon kökenli.',
    backstory: 'Donquixote Doflamingo, Celestial Dragon ailesinden doğdu. Babası Homing, insanlar arasında yaşamaya karar verince aile ayrıcalıklarını kaybetti. İnsanlar tarafından linç edildiler. Doflamingo, 10 yaşında babasını öldürdü ve başını Mariejois\'a göndererek geri kabul edilmeyi umdu ama reddedildi. Trebol\'un rehberliğinde kendi korsanlarını kurdu. Dressrosa\'yı ele geçirdi ve 10 yıl tiranlıkla yönetti. Kaido\'nun SMILE tedarikçisi olarak yeraltı dünyasının "Joker"ıydı. Luffy tarafından Gear 4 ile yenilerek Impel Down\'a gönderildi.',
    role: 'Dressrosa sagasının ana antagonisti — karizmatik ve acımasız tiran',
    age: '41',
    height: '305 cm',
    origin: 'Mariejois (Celestial Dragon)',
    firstArc: 'jaya',
    appearances: ['jaya', 'punk-hazard', 'dressrosa'],
    abilities: ['Ito Ito no Mi (İp)', 'Haoshoku Haki', 'Busoshoku Haki', 'Birdcage', 'Awakening'],
  },
  {
    name: 'Bartholomew Kuma',
    slug: 'kuma',
    image: '/characters/kuma.jpg',
    crew: 'revolutionary',
    epithet: 'Tiran',
    bounty: '296,000,000',
    devilFruit: 'Nikyu Nikyu no Mi',
    description: 'Eski Shichibukai ve Devrimci Ordunun eski komutanı. Bonney\'nin babası. Kendini feda etti.',
    backstory: 'Bartholomew Kuma, Buccaneer soyundan gelen bir adamdır. Çocukken Celestial Dragonlar tarafından köle yapıldı. Nika efsanesine — insanları kurtaran güneş tanrısı — inandı. Devrimci Orduna katıldı ve Dragon\'ın sağ kolu oldu. Kızı Bonney\'i korumak için Vegapunk ile anlaştı: bilincini tamamen feda ederek Pacifista\'ya dönüştürüldü. Thriller Bark\'ta ve Sabaody\'de Hasır Şapkaları korudu — son bilinçli eylemleri onları kurtarmak oldu.',
    role: 'Trajik kahraman — sevgi ve fedakarlığın sembolü',
    age: '47',
    height: '689 cm',
    origin: 'Sorbet Krallığı, South Blue',
    firstArc: 'thriller-bark',
    appearances: ['thriller-bark', 'sabaody-archipelago', 'egghead'],
    abilities: ['Nikyu Nikyu no Mi (Pençe)', 'Pençe Dalgası', 'Işınlanma', 'Pacifista Gövdesi'],
  },
  {
    name: 'Sabo',
    slug: 'sabo',
    image: '/characters/sabo.jpg',
    crew: 'revolutionary',
    epithet: 'Ateş İmparatoru',
    bounty: '602,000,000',
    devilFruit: 'Mera Mera no Mi',
    description: 'Devrimci Ordunun Genelkurmay Başkanı ve Luffy ile Ace\'in kardeşi.',
    backstory: 'Sabo, soylu bir aile çocuğuydu ama ailesinin baskısından kaçarak Ace ve Luffy ile kardeşler oldu. 10 yaşında tek başına denize açıldı ama Celestial Dragon\'ın gemisi tarafından vuruldu. Dragon tarafından kurtarıldı ve Devrimci Orduda büyüdü. Hafızasını kaybetmişti — Marineford\'da Ace\'in ölüm haberini duyunca her şeyi hatırladı. Dressrosa\'da Mera Mera meyvesini yiyerek Ace\'in mirasını devraldı. Reverie\'de Celestial Dragonlara karşı savaştı.',
    role: 'Luffy\'nin kardeşi ve Devrimci Ordunun askeri lideri',
    age: '22',
    height: '187 cm',
    origin: 'Goa Krallığı, East Blue',
    firstArc: 'post-war',
    appearances: ['post-war', 'dressrosa', 'reverie'],
    abilities: ['Mera Mera no Mi (Ateş)', 'Ryusoken (Ejderha Pençesi)', 'Busoshoku Haki', 'Kenbunshoku Haki'],
  },
  {
    name: 'Nefertari Vivi',
    slug: 'vivi',
    image: '/characters/vivi.jpg',
    crew: 'other',
    epithet: 'Arabasta Prensesi',
    description: 'Arabasta Krallığının prensesi. Ruhsal olarak mürettebatın bir parçası.',
    backstory: 'Nefertari Vivi, Arabasta Krallığının prensesidir. Ülkesini kurtarmak için Baroque Works\'e sızdı ve Crocodile\'ın planını keşfetti. Hasır Şapkalarla birlikte yolculuk ederek dost oldu ve birlikte Crocodile\'ı yendiler. Mürettebatla kalmak ile prenses sorumluluğu arasında kalarak ülkesinde kaldı. "X işareti" vedası serinin en duygusal sahnelerinden biridir. Reverie\'ye katıldı ama sonrasında kayboldu.',
    role: 'Luffy\'nin ilk gerçek müttefiki ve onursal mürettebat üyesi',
    age: '18',
    height: '169 cm',
    origin: 'Alubarna, Arabasta Krallığı',
    firstArc: 'whiskey-peak',
    appearances: ['whiskey-peak', 'little-garden', 'drum-island', 'arabasta', 'reverie'],
    abilities: ['Diplomasi', 'Peacock Slasher', 'Liderlik', 'Casusluk'],
  },
  {
    name: 'Enel',
    slug: 'enel',
    image: '/characters/enel.jpg',
    crew: 'other',
    epithet: 'Tanrı',
    bounty: undefined,
    devilFruit: 'Goro Goro no Mi',
    description: 'Skypiea\'nın eski tanrısı. Yıldırım gücüne sahip. Şu anda Ay\'da yaşıyor.',
    backstory: 'Enel, Birka gökyüzü adasında doğdu. Goro Goro meyvesini yiyerek yıldırım gücünü kazandı ve Birka\'yı yok etti. Skypiea\'yı ele geçirerek kendini "Tanrı" ilan etti. Mantra (Kenbunshoku Haki) ile adada olan her şeyi duyabiliyordu. Planı Skypiea\'yı yok edip Ay\'a gitmekti. Luffy, lastik vücudu sayesinde yıldırıma karşı bağışık olan tek kişi olarak onu yendi. Enel, Maxim gemisiyle Ay\'a ulaştı ve orada eski bir medeniyetin kalıntılarını keşfetti.',
    role: 'Skypiea arcının ana antagonisti — kibir ve güç sembolü',
    age: 'Bilinmiyor',
    height: '266 cm',
    origin: 'Birka (Gökyüzü Adası)',
    firstArc: 'skypiea',
    appearances: ['skypiea'],
    abilities: ['Goro Goro no Mi (Yıldırım)', 'Mantra (Kenbunshoku Haki)', 'El Thor', '200 Milyon Volt', 'Maxim Gemisi'],
  },
  // ─── Marines ──────────────────────────────────────────────────────────
  {
    name: 'Smoker',
    slug: 'smoker',
    image: '/characters/smoker.jpg',
    crew: 'marine',
    epithet: 'Beyaz Avcı',
    bounty: undefined,
    devilFruit: 'Moku Moku no Mi',
    description: 'Deniz Kuvvetleri Tümamirali. Luffy\'yi Loguetown\'dan beri takip eden adaletli denizci.',
    backstory: 'Smoker, Loguetown\'da görev yapan ilkeli bir Deniz Kuvvetleri subayıdır. Luffy\'nin idam platformundan kurtulduğuna tanık oldu ve onu takibe başladı. Arabasta\'da Hasır Şapkaların suçsuz olduğunu gördü ama resmi çizgiyi takip etmek zorunda kaldı. Punk Hazard\'da Law ve Luffy ile geçici ittifak kurdu. Vergo\'nun ihanetini keşfetti. Dressrosa sonrası Fujitora ile birlikte Shichibukai sistemini sorguladı. Kendi adaletini arayan bağımsız bir asker.',
    role: 'Luffy\'nin "değişen düşmanı" — adaleti sorgulayan denizci',
    age: '36',
    height: '209 cm',
    origin: 'Bilinmiyor',
    firstArc: 'loguetown',
    appearances: ['loguetown', 'arabasta', 'punk-hazard'],
    abilities: ['Moku Moku no Mi (Duman)', 'Busoshoku Haki', 'Nanashaku Jitte', 'Kenbunshoku Haki'],
  },
  {
    name: 'Koby',
    slug: 'koby',
    image: '/characters/koby.jpg',
    crew: 'marine',
    epithet: 'SWORD Üyesi',
    description: 'Deniz Kuvvetleri yükselen yıldızı. Luffy ile tanışarak hayatı değişen eski kaçak.',
    backstory: 'Koby, Alvida\'nın gemisinde kaçak olarak çalışan korkak bir çocuktu. Luffy ile tanışması hayatını değiştirdi. "Amiral olmak istiyorum!" — Luffy sayesinde rüyasını keşfetti. Garp\'ın eğitimi altında büyüdü. Marineford\'da savaşı durdurmak için Akainu\'nun karşısına çıktı. Water Seven\'da SWORD gizli birliğine katıldı. Amazon Lily\'de Blackbeard\'a karşı savaştı. Kenbunshoku Haki\'de üstün yetenek gösterdi.',
    role: 'Luffy\'nin Deniz Kuvvetleri\'ndeki paraleli — yeni neslin amiralı',
    age: '18',
    height: '167 cm',
    origin: 'Bilinmiyor, East Blue',
    firstArc: 'romance-dawn',
    appearances: ['romance-dawn', 'water-seven', 'marineford'],
    abilities: ['Rokushiki', 'Busoshoku Haki', 'Kenbunshoku Haki', 'Honesty Impact'],
  },
  {
    name: 'Monkey D. Garp',
    slug: 'garp',
    image: '/characters/garp.jpg',
    crew: 'marine',
    epithet: 'Deniz Kahramanı',
    description: 'Efsanevi Tümamiralı. Luffy\'nin dedesi. Gold Roger\'ı köşeye sıkıştıran adam.',
    backstory: 'Monkey D. Garp, Deniz Kuvvetleri tarihinin en güçlü savaşçılarından biridir. Roger ile defalarca savaşmış ve onu köşeye sıkıştırmıştır. Roger, ölmeden önce oğlu Ace\'i Garp\'a emanet etti. Garp, Ace\'i Dadan\'a bırakarak büyüttü — Luffy ve Sabo ile birlikte. Marineford\'da torunları Ace ve Luffy\'nin karşı tarafında savaşmak zorunda kaldı — bu onu yıktı. Ace\'in ölümü Garp\'ın en büyük pişmanlığıdır. SWORD\'un gizli destekçisi olduğu ortaya çıktı.',
    role: 'Aile ve görev arasında kalan efsanevi savaşçı',
    age: '78',
    height: '287 cm',
    origin: 'Goa Krallığı, East Blue',
    firstArc: 'water-seven',
    appearances: ['water-seven', 'post-enies-lobby', 'marineford', 'post-war'],
    abilities: ['Busoshoku Haki', 'Haoshoku Haki', 'Galaxy Impact', 'İnanılmaz Fiziksel Güç'],
  },
  {
    name: 'Sakazuki (Akainu)',
    slug: 'akainu',
    image: '/characters/akainu.jpg',
    crew: 'marine',
    epithet: 'Kırmızı Köpek',
    bounty: undefined,
    devilFruit: 'Magu Magu no Mi',
    description: 'Deniz Kuvvetleri Büyükamirali. "Mutlak Adalet" felsefesini benimser. Ace\'i öldüren kişi.',
    backstory: 'Sakazuki, "Mutlak Adalet" — suçlulara hiçbir merhamet göstermeme — felsefesiyle bilinen acımasız bir askerdir. Ohara\'nın Buster Call\'ında sivil gemisini vurdu. Marineford\'da Ace\'i öldürdü ve Luffy\'yi neredeyse öldürüyordu. Savaş sonrası Aokiji ile Büyükamiral koltuğu için 10 gün savaştı ve kazandı. Şimdi Deniz Kuvvetleri\'nin başındadır. Korsanlara ve suçlulara karşı sıfır tolerans politikası uygulamaktadır.',
    role: 'Serinin en acımasız antagonistlerinden biri — adalet ve tiranlık sınırı',
    age: '55',
    height: '306 cm',
    origin: 'North Blue',
    firstArc: 'marineford',
    appearances: ['marineford'],
    abilities: ['Magu Magu no Mi (Magma)', 'Busoshoku Haki', 'Kenbunshoku Haki', 'Magma Yumruk'],
  },
  {
    name: 'Kuzan (Aokiji)',
    slug: 'aokiji',
    image: '/characters/aokiji.jpg',
    crew: 'other',
    epithet: 'Mavi Sülün',
    bounty: undefined,
    devilFruit: 'Hie Hie no Mi',
    description: 'Eski Deniz Kuvvetleri Amirali. Akainu ile savaşıp kaybettikten sonra ayrıldı.',
    backstory: 'Kuzan, "Tembel Adalet" felsefesiyle tanınan bir Amiraldir. Ohara\'da küçük Robin\'in kaçmasına izin verdi. Long Ring Long Land\'da Hasır Şapkalarla karşılaştı ve gücünü gösterdi. Sengoku\'nun emriyle Büyükamiral adayıydı ama Akainu ile 10 günlük savaşta kaybetti. Deniz Kuvvetleri\'nden ayrıldı. Blackbeard ile birlikte çalıştığı görüldü ama asıl amacı belirsizdir. SWORD ile bağlantılı olabilir.',
    role: 'Gri alan karakter — ne tam dost ne tam düşman',
    age: '49',
    height: '298 cm',
    origin: 'Bilinmiyor',
    firstArc: 'long-ring-long-land',
    appearances: ['long-ring-long-land', 'marineford'],
    abilities: ['Hie Hie no Mi (Buz)', 'Busoshoku Haki', 'Kenbunshoku Haki', 'Ice Age'],
  },
  {
    name: 'Borsalino (Kizaru)',
    slug: 'kizaru',
    image: '/characters/kizaru.jpg',
    crew: 'marine',
    epithet: 'Sarı Maymun',
    bounty: undefined,
    devilFruit: 'Pika Pika no Mi',
    description: 'Deniz Kuvvetleri Amirali. Işık hızında hareket edebilen en hızlı savaşçılardan biri.',
    backstory: 'Borsalino, rahat ve alaycı tavırlarıyla bilinen güçlü bir Amiraldir. Sabaody\'de Supernova\'ları tek başına yendi. Marineford\'da savaştı. Egghead\'de eski arkadaşı Vegapunk\'ı öldürmek zorunda kaldı — bu görev onu derinden etkiledi. Luffy\'nin Gear 5\'i ile savaştığında, 2 yıl önceki güç farkının kapandığını gördü.',
    role: 'Güçlü ama duygusal çatışma yaşayan Amiral',
    age: '58',
    height: '302 cm',
    origin: 'Bilinmiyor',
    firstArc: 'sabaody-archipelago',
    appearances: ['sabaody-archipelago', 'marineford', 'egghead'],
    abilities: ['Pika Pika no Mi (Işık)', 'Busoshoku Haki', 'Kenbunshoku Haki', 'Işık Hızı Tekmeleri'],
  },
  // ─── Others ──────────────────────────────────────────────────────────
  {
    name: 'Yamato',
    slug: 'yamato',
    image: '/characters/yamato.jpg',
    crew: 'other',
    epithet: 'Wano\'nun Koruyucusu',
    bounty: undefined,
    devilFruit: 'Inu Inu no Mi, Model: Okuchi no Makami',
    description: 'Kaido\'nun kızı. Kozuki Oden\'e hayranlık duyar. Wano\'yu korumayı seçti.',
    backstory: 'Yamato, Kaido\'nun kızıdır ama babasından nefret eder. 8 yaşında Oden\'in idam günlüğünü buldu ve onun ruhunu benimsedi. Kendini "Kozuki Oden" olarak tanıtır. Kaido tarafından zincirlenip Onigashima\'da hapsedildi. Ace ile arkadaş olmuş ve Luffy\'nin maceralarını öğrenmiştir. Wano savaşında Kaido\'ya karşı savaştı. Mürettebata katılmak istedi ama sonunda Wano\'yu korumak için geride kaldı.',
    role: 'Wano\'nun koruyucusu — Oden\'in ruhsal mirasçısı',
    age: '28',
    height: '263 cm',
    origin: 'Onigashima, Wano',
    firstArc: 'wano',
    appearances: ['wano'],
    abilities: ['Inu Inu no Mi (Makami Formu)', 'Haoshoku Haki', 'Busoshoku Haki', 'Narikabura'],
  },
  {
    name: 'Carrot',
    slug: 'carrot',
    image: '/characters/carrot.jpg',
    crew: 'other',
    epithet: 'Garchu!',
    description: 'Zou\'dan gelen Mink kabilesi savaşçısı. Sulong formuna dönüşebilir.',
    backstory: 'Carrot, Zou\'da yaşayan tavşan Mink\'tir. Pedro\'nun öğrencisi olarak savaşçılık eğitimi almıştır. Zou\'dan gizlice Thousand Sunny\'ye binerek mürettebatla Whole Cake Island macerasına katıldı. Pedro\'nun fedakarlığı onu derinden etkiledi. Dolunayda Sulong formuna girerek Big Mom\'un filosunu tek başına dağıttı. Wano savaşına da katıldı. Savaş sonrası Pedro\'nun mirası olarak Zou\'nun yeni lideri oldu.',
    role: 'Mink savaşçısı ve geçici mürettebat yoldaşı',
    age: '15',
    height: '161 cm',
    origin: 'Zou',
    firstArc: 'zou',
    appearances: ['zou', 'whole-cake-island', 'wano'],
    abilities: ['Electro', 'Sulong Formu', 'Çeviklik', 'Mink Savaş Sanatları'],
  },
  {
    name: 'Vegapunk',
    slug: 'vegapunk',
    image: '/characters/vegapunk.jpg',
    crew: 'other',
    epithet: 'Dünyanın En Zeki İnsanı',
    bounty: undefined,
    description: 'Dünyanın en zeki bilim insanı. 6 uyduya ayrılmış deha.',
    backstory: 'Vegapunk, Karakuri Adası\'nda doğmuş bir dehadır. Nomi Nomi meyvesiyle sınırsız bilgi depolama yeteneği kazanmıştır. Judge, Caesar ve Queen ile birlikte MADS bilim grubunu kurdu. Dünya Hükümeti tarafından yakalanarak bilim danışmanı yapıldı. Pacifista\'ları, Seraphim\'leri, Sea Prism Stone silahlarını ve daha fazlasını icat etti. 6 uyduya bölünerek verimlilik artırdı. Void Century araştırmaları yüzünden Dünya Hükümeti tarafından ölüm emri verildi. Son mesajıyla dünyaya gerçeği anlatmaya çalıştı.',
    role: 'Egghead arcının merkez figürü — bilim ve gerçek arayışı',
    age: 'Bilinmiyor',
    height: 'Bilinmiyor',
    origin: 'Karakuri Adası, Grand Line',
    firstArc: 'egghead',
    appearances: ['egghead'],
    abilities: ['Nomi Nomi no Mi (Bilgi Depolama)', 'Üstün Zeka', 'Teknoloji İcatları', 'Uydu Sistemi'],
  },
  {
    name: 'Gol D. Roger',
    slug: 'roger',
    image: '/characters/roger.webp',
    crew: 'roger-pirates',
    epithet: 'Korsan Kralı',
    bounty: '5,564,800,000',
    description: 'Korsan Kralı olarak tarihe geçen tek adam. Roger Korsanları\'nın kaptanı ve Raftel\'e ulaşan ilk ve tek kişi.',
    backstory: 'Gol D. Roger, Loguetown\'da doğmuş ve tüm denizleri fethederek Grand Line\'ın sonuna — Laugh Tale\'e — ulaşan tek korsandır. Garp ile defalarca ölümcül düellolar yapmış, ancak ikisi birlikte Rocks D. Xebec\'i God Valley\'de yenmiştir. Roger, ölümcül bir hastalığa yakalandıktan sonra Crocus\'un tedavisiyle son yolculuğuna çıktı. One Piece\'i Laugh Tale\'e bırakarak kendini Deniz Kuvvetleri\'ne teslim etti. Loguetown\'daki idamında söylediği son sözler — "Hazinemi mi istiyorsunuz? Alın bakalım! Her şeyimi oraya bıraktım!" — Büyük Korsan Çağı\'nı başlattı ve dünyayı sonsuza dek değiştirdi.',
    role: 'Korsan Kralı — One Piece dünyasının en efsanevi figürü',
    age: '53 (ölüm anında)',
    height: '274 cm',
    origin: 'Loguetown, East Blue',
    firstArc: 'loguetown',
    appearances: ['romance-dawn', 'loguetown', 'skypiea', 'sabaody-archipelago', 'marineford', 'post-war', 'wano', 'egghead'],
    abilities: ['Haoshoku Haki (En Üst Seviye)', 'Busoshoku Haki', 'Kenbunshoku Haki', 'Tüm Sesleri Duyma Yeteneği', 'Kılıç Ustalığı (Ace Kılıcı)', 'Supreme Grade Sword: Ace'],
  },
  {
    name: 'Silvers Rayleigh',
    slug: 'rayleigh',
    image: '/characters/rayleigh.webp',
    crew: 'roger-pirates',
    epithet: 'Karanlık Kral',
    description: 'Roger Korsanları\'nın yan kaptanı. Haki\'nin en üst seviye kullanıcılarından biri ve Luffy\'nin eğitmeni.',
    backstory: 'Silvers Rayleigh, Roger Korsanları\'nın kurucu üyesi ve yan kaptanıdır. Roger ile Loguetown\'da bir teknede tanışmış ve onun ilk mürettebat arkadaşı olmuştur. Grand Line\'ın tamamını birlikte fethettiler ve Laugh Tale\'e ulaştılar. Roger\'ın idamından sonra Sabaody Takımadaları\'nda gemi boyacısı olarak gizlendi. Kizaru\'ya karşı bile zorluk çekmeden savaşabilecek kadar güçlüdür. Marineford Savaşı sonrası Luffy\'yi Rusukaina Adası\'na götürerek 2 yıl boyunca üç Haki türünü öğretti. Yaşına rağmen hâlâ dünyanın en tehlikeli savaşçılarından biridir.',
    role: 'Roger Korsanları Yan Kaptanı — Luffy\'nin Haki hocası',
    age: '78',
    height: '188 cm',
    origin: 'Bilinmiyor',
    firstArc: 'sabaody-archipelago',
    appearances: ['sabaody-archipelago', 'amazon-lily', 'marineford', 'post-war', 'return-to-sabaody', 'wano', 'egghead'],
    abilities: ['Haoshoku Haki (İleri Seviye)', 'Busoshoku Haki (İleri Seviye)', 'Kenbunshoku Haki', 'Kılıç Ustalığı', 'Silahsız Dövüş'],
  },
  {
    name: 'Monkey D. Dragon',
    slug: 'dragon',
    image: '/characters/dragon.webp',
    crew: 'revolutionary',
    epithet: 'Dünyanın En Tehlikeli Adamı',
    description: 'Devrimci Ordu\'nun lideri ve Monkey D. Luffy\'nin babası. Dünya Hükümeti\'ne karşı en büyük tehdit olarak kabul edilir.',
    backstory: 'Monkey D. Dragon, Deniz Kuvvetleri Kahramanı Garp\'ın oğlu ve Luffy\'nin babasıdır. Dünya Hükümeti\'nin adaletsizliğine karşı Devrimci Ordu\'yu kurmuş ve dünya çapında bir özgürlük hareketi başlatmıştır. Loguetown\'da Luffy\'yi Smoker\'dan rüzgar güçleriyle kurtardığı düşünülmektedir. Baltigo\'da Devrimci Ordu\'nun karargahını yönetir. İvankov, Kuma ve Sabo gibi güçlü komutanları vardır. Reverie sırasında Dünya Soylularına savaş ilan etti. Geçmişi hâlâ büyük ölçüde gizemlidir ve One Piece\'in en büyük soru işaretlerinden biri olmaya devam etmektedir.',
    role: 'Devrimci Ordu Lideri — Dünya Hükümeti\'nin baş düşmanı',
    age: '55',
    height: '256 cm',
    origin: 'Goa Krallığı, Dawn Adası, East Blue',
    firstArc: 'loguetown',
    appearances: ['loguetown', 'post-war', 'reverie', 'egghead'],
    abilities: ['Gizemli Rüzgar/Hava Gücü', 'Haoshoku Haki (Varsayılan)', 'Busoshoku Haki', 'Kenbunshoku Haki', 'Askeri Strateji Dehası'],
  },
  {
    name: 'Rob Lucci',
    slug: 'rob-lucci',
    image: '/characters/rob-lucci.webp',
    crew: 'cp9',
    epithet: 'Katil Silahı',
    bounty: '3,000,000,000',
    devilFruit: 'Neko Neko no Mi, Model: Leopar',
    description: 'CP9\'un en güçlü ajanı ve Rokushiki\'nin en ölümcül kullanıcısı. Egghead sonrası CP0 üyesi olarak geri döndü.',
    backstory: 'Rob Lucci, çocukluğundan beri Dünya Hükümeti tarafından bir suikastçi olarak yetiştirilmiştir. 13 yaşında 500 rehineyi kurtarmak adına tüm korsanları ve rehineleri katletmesiyle ünlendi — "Adalet zayıflık gösteremez" felsefesini benimsedi. Water Seven\'da gizli kimlikle 5 yıl boyunca Galley-La şirketinde çalıştı. Nico Robin\'i ele geçirmek için Enies Lobby\'ye götürdü. Luffy ile yaptığı epik dövüşte yenildi. Egghead Arc\'ta CP0 üyesi olarak geri döndü ve Uyanmış Zoan formunu gösterdi. Dünya Hükümeti\'nin en sadık ve acımasız silahıdır.',
    role: 'CP0 Ajanı — Dünya Hükümeti\'nin gizli suikastçisi',
    age: '30',
    height: '212 cm',
    origin: 'Bilinmiyor',
    firstArc: 'water-seven',
    appearances: ['water-seven', 'enies-lobby', 'reverie', 'egghead'],
    abilities: ['Neko Neko no Mi Model: Leopar (Uyanmış)', 'Rokushiki (Altı Güç)', 'Shigan', 'Rankyaku', 'Soru', 'Tekkai', 'Geppo', 'Rokuogan', 'Busoshoku Haki', 'Kenbunshoku Haki'],
  },
  {
    name: 'Charlotte Katakuri',
    slug: 'katakuri',
    image: '/characters/katakuri.webp',
    crew: 'big-mom-pirates',
    epithet: 'Dogtooth',
    bounty: '1,057,000,000',
    devilFruit: 'Mochi Mochi no Mi',
    description: 'Big Mom Korsanları\'nın en güçlü komutanı. Geleceği görebilen Kenbunshoku Haki ustası.',
    backstory: 'Charlotte Katakuri, Big Mom\'un ikinci oğlu ve Tatlı Komutanlardan biridir. Çocukluğunda mochi ağzı yüzünden alay konusu oldu; kız kardeşi Brûlée\'nin yüzü çizildiğinde o andan itibaren "mükemmel büyük erkek kardeş" imajını korumaya yemin etti. Yenilmez efsanesiyle 40 yılı aşkın süredir sırtını yere getirmemişti. Whole Cake Island\'da Luffy ile epik bir mochi dövüşüne girdi. Luffy\'nin geleceği görme Haki\'sini geliştirmesine vesile oldu. Savaşın sonunda Luffy\'ye saygı duyarak yenilgiyi kabul etti ve ona "ağabey" gibi davrandı. Big Mom Korsanları\'nın gerçek dayanak noktasıdır.',
    role: 'Tatlı Komutan — Big Mom Korsanları\'nın en güçlü savaşçısı',
    age: '48',
    height: '509 cm',
    origin: 'Totto Land, New World',
    firstArc: 'whole-cake-island',
    appearances: ['whole-cake-island', 'wano'],
    abilities: ['Mochi Mochi no Mi (Özel Paramecia)', 'Kenbunshoku Haki (Gelecek Görüşü)', 'Busoshoku Haki', 'Haoshoku Haki', 'Mogura (Üç Dişli Mızrak)', 'Mochi Oluşturma ve Manipülasyon'],
  },
  {
    name: 'Marco',
    slug: 'marco',
    image: '/characters/marco.webp',
    crew: 'whitebeard-pirates',
    epithet: 'Anka Kuşu',
    bounty: '1,374,000,000',
    devilFruit: 'Tori Tori no Mi, Model: Phoenix',
    description: 'Beyaz Sakal Korsanları\'nın 1. Bölük Komutanı. Efsanevi Phoenix meyvesiyle yeniden doğabilen savaşçı.',
    backstory: 'Marco, Beyaz Sakal Korsanları\'nın 1. Bölük Komutanı ve mürettebatın en kıdemli üyelerinden biridir. Çocuk yaşta Whitebeard tarafından sahiplenildi ve onun "ailesinin" en büyük oğlu gibi büyüdü. Tori Tori no Mi Model: Phoenix\'i yedi — bu Mythical Zoan ona mavi alevlerle kendini iyileştirme yeteneği verir. Marineford Savaşı\'nda Amirallere karşı savaştı ve Whitebeard\'ın ölümüne tanıklık etti. Whitebeard\'ın son sözlerini taşıyan kişidir. Payback War\'da Blackbeard\'a karşı mücadele etti ve kaybetti. Wano\'da Hasır Şapka ittifakına katılarak Kaido\'nun ordusuna karşı savaştı ve özellikle King ve Queen\'e karşı kritik rol oynadı.',
    role: '1. Bölük Komutanı — Beyaz Sakal Korsanları\'nın mirasçısı',
    age: '45',
    height: '188 cm',
    origin: 'Bilinmiyor',
    firstArc: 'marineford',
    appearances: ['marineford', 'post-war', 'wano'],
    abilities: ['Tori Tori no Mi Model: Phoenix', 'Mavi Alev İyileştirmesi', 'Busoshoku Haki', 'Kenbunshoku Haki', 'Uçuş', 'Dövüş Sanatları'],
  },
  {
    name: 'Kozuki Oden',
    slug: 'oden',
    image: '/characters/oden.webp',
    crew: 'other',
    epithet: 'Yıkılmaz',
    bounty: 'Bilinmiyor',
    description: 'Wano\'nun efsanevi samuraiı, Kuri Daimyosu. Hem Roger hem Whitebeard mürettebatında yelken açmış tek kişi.',
    backstory: 'Kozuki Oden, Wano Ülkesi\'nin Şogunluğu\'nun varisi olarak doğdu ama kurallara uymayan asi bir ruhtu. 18 yaşında başkent Flower Capital\'den sürgün edildi. Kuri bölgesini tek başına ele geçirip Daimyo oldu. Whitebeard Korsanları\'na katılarak dünyayı keşfetti, ardından Roger\'ın son yolculuğuna katılarak Laugh Tale\'e ulaştı ve Void Century\'nin sırlarını öğrendi. Wano\'ya döndüğünde Kaido ve Orochi\'nin zulmüyle karşılaştı. 5 yıl boyunca Wano halkını korumak için kendini küçük düşürdü. Sonunda Kaido\'ya isyan etti ama ihanet sonucu yakalandı. Kaynar yağda haşlanarak idam edilirken 9 samurayını kurtardı ve "Wano\'nun sınırlarını açın!" diye haykırdı.',
    role: 'Wano\'nun efsanevi samuraiı ve Kozuki hanedanının son Daimyosu',
    age: '39 (ölüm anında)',
    height: '382 cm',
    origin: 'Flower Capital, Wano Ülkesi',
    firstArc: 'wano',
    appearances: ['wano'],
    abilities: ['İki Kılıç Stili (Oden Nitoryu)', 'Enma Kılıcı', 'Ame no Habakiri Kılıcı', 'Haoshoku Haki', 'Busoshoku Haki (İleri Seviye)', 'Kenbunshoku Haki', 'Oden İki Kılıç Stili: Togen Totsuka'],
  },
  {
    name: 'Sengoku',
    slug: 'sengoku',
    image: '/characters/sengoku.webp',
    crew: 'marine',
    epithet: 'Buda',
    devilFruit: 'Hito Hito no Mi, Model: Daibutsu',
    description: 'Deniz Kuvvetleri\'nin eski Büyük Amirali. Altın Buda formuna dönüşebilir.',
    backstory: 'Sengoku, Deniz Kuvvetleri\'nin Fleet Admiral\'ı olarak One Piece dünyasının en güçlü askeri figürlerinden biriydi. Garp ile birlikte Roger Çağı\'nın efsanevi Deniz Kuvvetleri savaşçılarındandır. Hito Hito no Mi Model: Daibutsu meyvesiyle dev bir altın Buda\'ya dönüşebilir ve şok dalgaları gönderebilir. Marineford Savaşı\'nı organize etti ve Ace\'in idamını yönetti. Savaş sonrası yaşanan kayıplar ve dünya dengesindeki değişiklikler nedeniyle görevinden istifa etti. Akainu\'yu halefi olarak bıraktı ve danışman rolüne geçti. Corazon\'un (Rosinante) yetiştiricisi olarak Law\'un hikayesinde de önemli bir yere sahiptir.',
    role: 'Eski Fleet Admiral — Deniz Kuvvetleri\'nin stratejik beyni',
    age: '79',
    height: '278 cm',
    origin: 'Bilinmiyor',
    firstArc: 'marineford',
    appearances: ['marineford', 'post-war', 'dressrosa', 'reverie'],
    abilities: ['Hito Hito no Mi Model: Daibutsu', 'Şok Dalgası Saldırıları', 'Haoshoku Haki', 'Busoshoku Haki', 'Kenbunshoku Haki', 'Askeri Strateji'],
  },
  {
    name: 'Arlong',
    slug: 'arlong',
    image: '/characters/arlong.webp',
    crew: 'other',
    epithet: 'Dişli Arlong',
    bounty: '20,000,000',
    description: 'Arlong Korsanları\'nın kaptanı ve East Blue\'nun en korkulan balıkadam korsanı. Nami\'nin çocukluğunu kâbusa çevirdi.',
    backstory: 'Arlong, Fish-Man Bölgesi\'nde büyümüş bir testere köpekbalığı balıkadamıdır. İnsanların balıkadamlara yaptığı ayrımcılık onu derinden etkilemiş ve insanlara karşı büyük bir nefret geliştirmiştir. Sun Pirates\'ın üyesi olarak Fisher Tiger\'ın yanında savaştı. Tiger\'ın ölümünden sonra East Blue\'ya geldi ve Cocoyashi Köyü\'nü ele geçirdi. Nami\'yi 8 yaşından itibaren kölesı gibi harita çizdirmeye zorladı ve köyünü 100 milyon Berry karşılığında serbest bırakacağına söz verdi ama Deniz Kuvvetleri ile anlaşarak parayı her seferinde çaldırdı. Luffy\'nin Arlong Park\'ı yıkmasıyla yenildi ve tutuklandı. East Blue Saga\'nın en etkili villainıdır.',
    role: 'Arlong Park villainı — Nami\'nin kâbusu',
    age: '41',
    height: '263 cm',
    origin: 'Fish-Man Bölgesi, Grand Line',
    firstArc: 'arlong-park',
    appearances: ['arlong-park', 'fish-man-island'],
    abilities: ['Köpekbalığı Dişleri (Yeniden Büyür)', 'Üstün Balıkadamı Gücü', 'Su Altı Savaşı', 'Kiribachi (Diş Kılıç)'],
  },
  {
    name: 'Gecko Moria',
    slug: 'gecko-moria',
    image: '/characters/gecko-moria.webp',
    crew: 'shichibukai',
    epithet: 'Gölgelerin Efendisi',
    bounty: '320,000,000',
    devilFruit: 'Kage Kage no Mi',
    description: 'Eski Yedi Savaş Lordu ve Thriller Bark\'ın efendisi. Gölgeleri çalarak zombi ordusu yaratır.',
    backstory: 'Gecko Moria, bir zamanlar New World\'de Kaido\'ya meydan okumuş ve tüm mürettebatını kaybetmiş bir korsandır. Bu yenilginin travmasıyla "bir daha kimseyi kaybetmeyeceğim, zombiler ölmez" felsefesini benimsedi. Kage Kage no Mi meyvesiyle insanların gölgelerini çalarak ölüleri canlandırma yeteneği kazandı. Thriller Bark adlı devasa gemiyi karargah yaparak yüzlerce zombi yarattı ve en güçlü savaşçı olan Oz\'u kontrol etti. Luffy tarafından yenildi ve Shichibukai statüsünü Marineford Savaşı sonrası kaybetti. Blackbeard tarafından mürettebata katılma teklifi aldı. Absalom\'un ölümü onu derinden etkiledi.',
    role: 'Eski Shichibukai — Gölge çalan zombi yaratıcısı',
    age: '50',
    height: '692 cm',
    origin: 'Bilinmiyor',
    firstArc: 'thriller-bark',
    appearances: ['thriller-bark', 'marineford', 'wano'],
    abilities: ['Kage Kage no Mi (Gölge Manipülasyonu)', 'Gölge Çalma', 'Zombi Yaratma', 'Doppelman', 'Brick Bat', 'Shadow Asgard'],
  },
  {
    name: 'Bon Clay (Mr. 2 Bon Kurei)',
    slug: 'bon-clay',
    image: '/characters/bon-clay.webp',
    crew: 'other',
    epithet: 'Mr. 2',
    bounty: '32,000,000',
    devilFruit: 'Mane Mane no Mi',
    description: 'Baroque Works\'ün eski ajanı. Luffy\'nin en sadık dostlarından biri ve kendini feda etmekten çekinmeyen kahraman.',
    backstory: 'Bon Clay, Baroque Works\'te Mr. 2 kod adıyla çalışan bir Okama savaşçısıdır. Mane Mane no Mi meyvesiyle dokunduğu kişinin yüzünü kopyalayabilir. Arabasta\'da düşman olarak karşılaştığı Luffy ve mürettebatıyla savaştıktan sonra dostluk kurdu. Deniz Kuvvetleri\'nden kaçışlarında kendini feda ederek onların kaçmasını sağladı. Impel Down\'da tekrar Luffy ile karşılaştı ve onu Ivankov\'a ulaştırarak hayatını kurtardı. Level 6\'dan kaçış sırasında Kapıları açmak için arkada kalarak ikinci kez kendini feda etti. Magellan\'a tek başına karşı koydu. Hayatta kaldı ve Impel Down\'un yeni Okama Kralı oldu. One Piece\'in en sevilen yan karakterlerinden biridir.',
    role: 'Okama Savaşçısı — Luffy\'nin en fedakar dostu',
    age: '32',
    height: '218 cm',
    origin: 'Bilinmiyor',
    firstArc: 'arabasta',
    appearances: ['arabasta', 'impel-down'],
    abilities: ['Mane Mane no Mi (Yüz Kopyalama)', 'Okama Kenpo', 'Ballet Dövüş Stili', 'Swan Arabesque'],
  },
  {
    name: 'Emporio Ivankov',
    slug: 'ivankov',
    image: '/characters/ivankov.webp',
    crew: 'revolutionary',
    epithet: 'Mucize İnsan',
    bounty: '100,000,000',
    devilFruit: 'Horu Horu no Mi',
    description: 'Devrimci Ordu komutanı ve Kamabakka Krallığı\'nın Okama Kralı. Hormonlarla mucizeler yaratır.',
    backstory: 'Emporio Ivankov, Devrimci Ordu\'nun Grand Line komutanı ve Kamabakka Krallığı\'nun kralıdır. Horu Horu no Mi meyvesiyle insan vücudundaki hormonları manipüle edebilir — cinsiyet değiştirmeden hastalık tedavisine kadar "mucizeler" yaratır. Dragon\'ın en güvendiği komutanlarından biridir. Bir noktada Impel Down\'a düşmüş ve Level 5.5 "Yeni Kama Land"i kurarak gizli bir topluluk oluşturmuştur. Luffy Impel Down\'a geldiğinde Luffy\'yi zehirden kurtardı ve kaçışa yardım etti. Marineford Savaşı\'nda Luffy\'nin yanında savaştı. Savaş sonrası Kamabakka\'ya döndü ve Sanji\'nin 2 yıllık eğitimine (istemeden) ev sahipliği yaptı.',
    role: 'Devrimci Ordu Komutanı — Mucize yaratan Okama Kralı',
    age: '53',
    height: '449 cm',
    origin: 'Kamabakka Krallığı, Grand Line',
    firstArc: 'impel-down',
    appearances: ['impel-down', 'marineford', 'post-war'],
    abilities: ['Horu Horu no Mi (Hormon Manipülasyonu)', 'Cinsiyet Değiştirme', 'Hormon Tedavisi', 'Death Wink', 'Hell Wink', 'Galaxy Wink', 'Newkama Kenpo'],
  },
  {
    name: 'Caesar Clown',
    slug: 'caesar-clown',
    image: '/characters/caesar-clown.webp',
    crew: 'other',
    epithet: 'Usta',
    bounty: '300,000,000',
    devilFruit: 'Gasu Gasu no Mi',
    description: 'Çılgın bilim insanı ve kitle imha silahları uzmanı. Punk Hazard\'ın ana villainı.',
    backstory: 'Caesar Clown, dünyanın en tehlikeli bilim insanlarından biridir. Vegapunk ile birlikte MADS bilim grubunda çalışmıştır ancak etik dışı deneyleri yüzünden atıldı. Punk Hazard\'da yasak kimyasal silah deneyleri yaparak adayı zehirledi ve çocuklar üzerinde gigantifikasyon deneyleri yürüttü. Gasu Gasu no Mi meyvesiyle gazı kontrol edebilir — oksijeni ortamdan çekebilir, zehirli gaz üretebilir. Doflamingo ve Kaido için yapay Şeytan Meyvesi olan SMILE üretiyordu. Luffy ve Law ittifakı tarafından Punk Hazard\'da yenildi. Dressrosa ve Whole Cake Island maceralarında zorla rehine olarak taşındı. Big Mom için gigantifikasyon araştırması yapmaya zorlandı.',
    role: 'Çılgın bilim insanı — kitle imha silahları uzmanı',
    age: '40',
    height: '309 cm',
    origin: 'Bilinmiyor',
    firstArc: 'punk-hazard',
    appearances: ['punk-hazard', 'dressrosa', 'whole-cake-island'],
    abilities: ['Gasu Gasu no Mi (Gaz Kontrolü)', 'Oksijen Çekme', 'Zehirli Gaz Üretimi', 'Shinokuni', 'Bilimsel Deha', 'Kimyasal Silah Üretimi'],
  },
  {
    name: 'Fujitora (Issho)',
    slug: 'fujitora',
    image: '/characters/fujitora.webp',
    crew: 'marine',
    epithet: 'Fujitora',
    devilFruit: 'Zushi Zushi no Mi',
    description: 'Deniz Kuvvetleri Amirali. Yerçekimini kontrol eden kör savaşçı. Adaletli ve vicdanlı bir asker.',
    backstory: 'Fujitora, asıl adı Issho olan bir Deniz Kuvvetleri Amirali\'dir. Dünyada gördüğü kötülüklere dayanamayarak kendi gözlerini kör etmiş, son derece nadir bir kararlılık gösteren adamdır. Akainu\'nun Fleet Admiral olmasından sonra Askere Alım yoluyla Amiral rütbesine yükseldi. Zushi Zushi no Mi meyvesiyle yerçekimini manipüle edebilir — meteorları yörüngeden çekebilir, nesneleri havaya kaldırabilir veya yere yapıştırabilir. Dressrosa\'da Luffy ile karşılaştı ve Doflamingo\'nun zulmünü gördükten sonra Shichibukai sisteminin kaldırılması için mücadele etti. Reverie\'de Shichibukai sisteminin resmen feshedilmesini sağladı. Kenbunshoku Haki\'si sayesinde çevresini kusursuz algılar.',
    role: 'Deniz Kuvvetleri Amirali — Adaletçi kör savaşçı',
    age: '54',
    height: '270 cm',
    origin: 'Bilinmiyor',
    firstArc: 'dressrosa',
    appearances: ['dressrosa', 'reverie'],
    abilities: ['Zushi Zushi no Mi (Yerçekimi Kontrolü)', 'Meteor Çağırma', 'Yerçekimi Bıçağı', 'Kenbunshoku Haki (İleri Seviye)', 'Busoshoku Haki', 'Kılıç Ustalığı'],
  },
  {
    name: 'Kozuki Momonosuke',
    slug: 'momonosuke',
    image: '/characters/momonosuke.webp',
    crew: 'ally',
    epithet: 'Wano\'nun Şogunu',
    devilFruit: 'Yapay Ejderha Zoan (Vegapunk)',
    description: 'Kozuki Oden\'in oğlu ve Wano Ülkesi\'nin yeni Şogunu. Yapay bir ejderha meyvesi yedi.',
    backstory: 'Kozuki Momonosuke, efsanevi samuray Oden\'in oğlu ve Wano\'nun meşru varisidir. Babası Kaido tarafından öldürüldüğünde annesi Toki, onu ve vasal samurailarını 20 yıl ileriye gönderdi. Punk Hazard\'da Vegapunk\'un Kaido\'nun kanından ürettiği yapay Şeytan Meyvesi\'ni yanlışlıkla yedi ve ejderhaya dönüşme yeteneği kazandı. Luffy ve mürettebatla tanışarak Dressrosa, Zou ve Wano maceralarına katıldı. Wano\'da Shinobu\'nun meyvesiyle 28 yaşına büyütüldü ve Kaido\'ya karşı savaşta dev ejderha formunda Onigashima\'yı taşıyarak ülkeyi kurtardı. Savaş sonrası Wano\'nun yeni Şogunu ilan edildi.',
    role: 'Wano Şogunu — Kozuki hanedanının varisi',
    age: '8 (fiziksel 28)',
    height: '180 cm (yetişkin)',
    origin: 'Kuri, Wano Ülkesi',
    firstArc: 'punk-hazard',
    appearances: ['punk-hazard', 'dressrosa', 'zou', 'wano'],
    abilities: ['Yapay Ejderha Zoan Dönüşümü', 'Bolo Breath', 'Tüm Sesleri Duyma Yeteneği', 'Zunisha ile İletişim', 'Kılıç Ustalığı (Ame no Habakiri)'],
  },
  {
    name: 'King (Alber)',
    slug: 'king',
    image: '/characters/king.webp',
    crew: 'beast-pirates',
    epithet: 'Ateş Felaketi',
    bounty: '1,390,000,000',
    devilFruit: 'Ryu Ryu no Mi, Model: Pteranodon',
    description: 'Hayvan Korsanları\'nın 1. Komutanı. Son Lunarian ırkından olan ateş savaşçısı.',
    backstory: 'King, asıl adı Alber olan ve neslinin tükendiği düşünülen Lunarian ırkının son üyesidir. Lunarianlar, Red Line\'ın tepesinde yaşayan ve ateş üreten bir ırktı — "Tanrılar" olarak anılırlardı. Dünya Hükümeti tarafından yakalanarak Punk Hazard\'da deney malzemesi olarak kullanıldı. Kaido tarafından kurtarıldı ve o günden sonra Kaido\'ya mutlak sadakatle bağlandı. Hayvan Korsanları\'nın All-Star\'ı ve en güçlü komutanı oldu. Wano\'da Zoro ile epik bir savaşa girdi. Zoro, King\'in Lunarian savunmasının sırrını çözerek — ateşi söndüğünde hızlı ama savunmasız olduğunu keşfederek — onu yendi.',
    role: 'All-Star (1. Komutan) — Hayvan Korsanları\'nın en güçlü üyesi',
    age: 'Bilinmiyor',
    height: '613 cm',
    origin: 'Red Line (Lunarian Yurdu)',
    firstArc: 'wano',
    appearances: ['wano'],
    abilities: ['Ryu Ryu no Mi Model: Pteranodon', 'Lunarian Ateş Üretimi', 'Lunarian Dayanıklılığı', 'Busoshoku Haki', 'Kenbunshoku Haki', 'Haoshoku Haki', 'Kılıç Ustalığı'],
  },
  {
    name: 'Queen',
    slug: 'queen',
    image: '/characters/queen.webp',
    crew: 'beast-pirates',
    epithet: 'Veba',
    bounty: '1,320,000,000',
    devilFruit: 'Ryu Ryu no Mi, Model: Brachiosaurus',
    description: 'Hayvan Korsanları\'nın 2. Komutanı. MADS eski üyesi, bilim insanı ve savaşçı.',
    backstory: 'Queen, Hayvan Korsanları\'nın All-Star\'larından biri ve aynı zamanda eski MADS bilim grubunun üyesidir. Vegapunk, Judge ve Caesar ile birlikte çalışmıştır. Bilimsel dehasını kendi vücuduna uyguladı — kollarını lazer silahlarıyla, vücudunu mekanik parçalarla güçlendirdi. Ryu Ryu no Mi Model: Brachiosaurus meyvesiyle dev bir dinozora dönüşebilir. Udon Hapishanesi\'nin yöneticisi olarak tutuklulara işkence etti. Virüs silahları Ice Oni gibi biyolojik silahlar geliştirdi. Wano savaşında Sanji ile karşı karşıya geldi. Sanji\'nin Germa genetik uyanışı ve Diable Jambe ile yenildi. Judge\'ın eski meslektaşı olarak Vinsmoke ailesiyle bağlantılıdır.',
    role: 'All-Star (2. Komutan) — Bilim insanı savaşçı',
    age: '56',
    height: '612 cm',
    origin: 'Bilinmiyor',
    firstArc: 'wano',
    appearances: ['wano'],
    abilities: ['Ryu Ryu no Mi Model: Brachiosaurus', 'Mekanik Vücut Modifikasyonları', 'Lazer Silahları', 'Ice Oni Virüsü', 'Brachio Launcher', 'Busoshoku Haki', 'Kenbunshoku Haki'],
  },
  {
    name: 'Donquixote Rosinante (Corazon)',
    slug: 'rosinante',
    image: '/characters/rosinante.webp',
    crew: 'marine',
    epithet: 'Corazon',
    devilFruit: 'Nagi Nagi no Mi',
    description: 'Doflamingo\'nun küçük kardeşi ve Deniz Kuvvetleri\'nin gizli ajanı. Law\'un hayatını kurtaran adam.',
    backstory: 'Donquixote Rosinante, Donquixote Doflamingo\'nun küçük kardeşidir. Celestial Dragon ailesinden gelen iki kardeş, dünyaya indikten sonra insanların zulmüne maruz kaldı. Anneleri öldü, babalarını Doflamingo öldürdü. Rosinante kaçarak Sengoku tarafından büyütüldü ve Deniz Kuvvetleri\'nin gizli ajanı oldu. Doflamingo\'nun Donquixote Ailesi\'ne sızdı ve "Corazon" kod adını aldı. Dilsiz ve beceriksiz numarası yaparak herkesin güvenini kazandı. Trafalgar Law ile tanıştığında, Amber Lead hastalığından ölmek üzere olan çocuğu kurtarmak için her şeyi riske attı. Ope Ope no Mi\'yi çalarak Law\'a yedirdi. Doflamingo tarafından vurularak öldürüldü — ama Nagi Nagi meyvesiyle Law\'un ağlama seslerini sonuna kadar gizledi.',
    role: 'Deniz Kuvvetleri gizli ajanı — Law\'un kurtarıcısı',
    age: '26 (ölüm anında)',
    height: '293 cm',
    origin: 'Mariejois (Celestial Dragon)',
    firstArc: 'dressrosa',
    appearances: ['dressrosa'],
    abilities: ['Nagi Nagi no Mi (Sessizlik)', 'Ses Engelleme Alanı', 'Silah Kullanımı', 'Gizli Ajan Becerileri'],
  },
  {
    name: 'Hody Jones',
    slug: 'hody-jones',
    image: '/characters/hody-jones.webp',
    crew: 'other',
    epithet: 'Yeni Balıkadamı Korsanları Kaptanı',
    bounty: 'Bilinmiyor',
    description: 'Fish-Man Island\'ın villainı. İnsanlara karşı körü körüne nefret besleyen fanatik balıkadamı.',
    backstory: 'Hody Jones, Fish-Man Bölgesi\'nde büyümüş beyaz köpekbalığı balıkadamıdır. Arlong\'un ideolojisinden derinden etkilenmiş ancak Arlong\'un aksine insanlar tarafından bizzat zulüm görmemiştir — nefreti tamamen öğretilmiş ve körü körüne benimsemiştir. Bu "hiçbir şey" yaşamamış olması onu serinin en anlamlı villainlarından biri yapar. Yeni Balıkadamı Korsanları\'nı kurarak Fish-Man Island\'ı ele geçirmeye çalıştı. Energy Steroid haplarıyla gücünü yapay olarak artırdı. Kraliçe Otohime\'i suikast ettirdi ve bunu insanların üstüne yıktı. Luffy tarafından ağır bir şekilde yenildi. Energy Steroid\'lerin yan etkisiyle hızla yaşlanarak cezasını çekti.',
    role: 'Fish-Man Island villainı — öğretilmiş nefretin sembolü',
    age: '30',
    height: '381 cm',
    origin: 'Fish-Man Bölgesi, Grand Line',
    firstArc: 'fish-man-island',
    appearances: ['fish-man-island'],
    abilities: ['Balıkadamı Karate', 'Su Altı Savaşı', 'Energy Steroid (Yapay Güç)', 'Köpekbalığı Dişleri', 'Su Atışı'],
  },
  {
    name: 'Magellan',
    slug: 'magellan',
    image: '/characters/magellan.webp',
    crew: 'marine',
    epithet: 'Zehir İblis',
    devilFruit: 'Doku Doku no Mi',
    description: 'Impel Down\'ın eski Baş Gardiyanı. Zehirden oluşan vücuduyla dünyanın en tehlikeli hapishanesini yönetir.',
    backstory: 'Magellan, dünyanın en güçlendirilmiş hapishanesi Impel Down\'ın Baş Gardiyanıdır. Doku Doku no Mi meyvesiyle her türlü zehri üretebilir ve kontrol edebilir — nörotoksinlerden asit zehirine kadar geniş bir yelpazeye sahiptir. Zehir yemeyi sevdiği için günün büyük bölümünü tuvalette geçirmesine rağmen, görev başındayken son derece korkutucudur. Luffy\'nin Ace\'i kurtarmak için Impel Down\'a sızma girişiminde Luffy\'yi tek bir saldırıyla ölümün eşiğine getirdi. Blackbeard ve mürettebatını da tek başına zehirledi. Impel Down tarihindeki en büyük toplu kaçışı engelleyemediği için Baş Gardiyanlıktan alınarak Yardımcı Gardiyan\'a düşürüldü.',
    role: 'Impel Down Baş Gardiyanı — Zehir canavarı',
    age: '47',
    height: '491 cm',
    origin: 'Bilinmiyor',
    firstArc: 'impel-down',
    appearances: ['impel-down'],
    abilities: ['Doku Doku no Mi (Zehir Üretimi)', 'Hydra', 'Venom Demon', 'Chloro Ball', 'Zehir Nefesi', 'Tüm Zehir Türleri Kontrolü'],
  },
  {
    name: 'Perona',
    slug: 'perona',
    image: '/characters/perona.webp',
    crew: 'other',
    epithet: 'Hayalet Prenses',
    bounty: 'Bilinmiyor',
    devilFruit: 'Horo Horo no Mi',
    description: 'Thriller Bark\'ın hayalet prensesi. Negatif hayaletleriyle rakiplerinin moralini yerle bir eder.',
    backstory: 'Perona, Gecko Moria\'nın mürettebatında yer alan ve Thriller Bark\'ta yaşayan gotik hayalet prensestir. Horo Horo no Mi meyvesiyle hayalet üretebilir — bu hayaletler dokundukları kişiyi aşırı depresyona sokar. Astral projeksiyon yapabilir ve ruhunu vücudundan ayırarak uzaktan keşif yapabilir. Thriller Bark\'ta Usopp tarafından yenildi — zaten negatif olan Usopp\'a hayaletleri etki etmedi. Kuma\'nın Nikyu Nikyu meyvesiyle Kuraigana Adası\'na fırlatıldı ve orada Mihawk ile birlikte yaşamaya başladı. 2 yıl boyunca Zoro\'nun da aynı adada eğitim gördüğü dönemde onlara ev sahipliği yaptı. Wano\'da Zoro\'nun haberlerini takip ederek endişe gösterdi.',
    role: 'Gotik hayalet prenses — beklenmedik müttefik',
    age: '25',
    height: '160 cm',
    origin: 'Bilinmiyor',
    firstArc: 'thriller-bark',
    appearances: ['thriller-bark', 'sabaody-archipelago', 'wano'],
    abilities: ['Horo Horo no Mi (Hayalet Üretimi)', 'Negatif Hayalet', 'Mini Hayalet Bombası', 'Astral Projeksiyon', 'Toku Hollow'],
  },
  {
    name: 'Bartolomeo',
    slug: 'bartolomeo',
    image: '/characters/bartolomeo.webp',
    crew: 'ally',
    epithet: 'Yamyam',
    bounty: '200,000,000',
    devilFruit: 'Bari Bari no Mi',
    description: 'Luffy\'nin bir numaralı fanı ve Barto Club kaptanı. Kırılmaz bariyer oluşturma yeteneğine sahip.',
    backstory: 'Bartolomeo, Luffy\'nin Loguetown\'daki idam sehpasında gülümsemesini gördükten sonra korsanlığa başlayan fanatik bir Luffy hayranıdır. Bari Bari no Mi meyvesiyle kırılmaz bariyerler oluşturabilir — bu bariyerler Amiral saldırılarını bile durdurabilecek güçtedir. Dressrosa\'daki Corrida Colosseum turnuvasına katıldı ve Mera Mera no Mi\'yi Luffy\'ye vermek için savaştı. Doflamingo\'nun düşüşünden sonra Hasır Şapka Büyük Filo\'nun bir parçası oldu. East Blue\'daki Shanks\'ın bayrağını yakarak Kızıl Saç Korsanları\'nın öfkesini üstüne çekti. Luffy\'ye olan bağlılığı sınır tanımaz; Luffy\'nin posterleriyle dolu bir odada yaşar ve her zaferini gözyaşlarıyla kutlar.',
    role: 'Hasır Şapka Büyük Filo\'nun 2. Gemisi — Luffy\'nin 1 numaralı fanı',
    age: '24',
    height: '220 cm',
    origin: 'East Blue',
    firstArc: 'dressrosa',
    appearances: ['dressrosa', 'zou'],
    abilities: ['Bari Bari no Mi (Bariyer Oluşturma)', 'Bariyer Crash', 'Bariyer Mızrak', 'Dövüş Sanatları'],
  },
  {
    name: 'Nico Olvia',
    slug: 'nico-olvia',
    image: '/characters/nico-olvia.webp',
    crew: 'other',
    epithet: 'Ohara\'nın Kızı',
    description: 'Nico Robin\'in annesi ve Ohara\'nın önde gelen arkeologlarından biri. Void Century\'nin sırlarını araştırdı.',
    backstory: 'Nico Olvia, Ohara Adası\'nın en yetenekli arkeologlarından biriydi ve Poneglyph\'leri okuyarak Void Century\'nin gerçeğini araştıran bilim insanıydı. Araştırma gezisi için küçük kızı Robin\'i geride bıraktı. Yıllarca denizlerde Poneglyph araştırması yaptıktan sonra Dünya Hükümeti tarafından yakalandı. Ohara\'ya dönmeyi başardığında, Buster Call emrinin verildiğini öğrendi. Son anlarında kızı Robin ile karşılaştı ve onu tanıdı. "Yaşamak iste!" mesajıyla Robin\'e hayatta kalması için ilham verdi. Ohara\'nın Buster Call ile yok edilmesi sırasında Bilgi Ağacı\'nı kurtarmaya çalışan diğer arkeologlarla birlikte hayatını kaybetti. Robin\'in hayat boyu taşıdığı acının ve kararlılığın kaynağıdır.',
    role: 'Ohara arkeoloğu — Robin\'in annesi',
    age: '33 (ölüm anında)',
    height: 'Bilinmiyor',
    origin: 'Ohara, West Blue',
    firstArc: 'enies-lobby',
    appearances: ['enies-lobby'],
    abilities: ['Poneglyph Okuma', 'Arkeoloji Bilgisi', 'Void Century Araştırması'],
  },
  {
    name: 'Nefertari Cobra',
    slug: 'cobra',
    image: '/characters/cobra.webp',
    crew: 'ally',
    epithet: 'Arabasta Kralı',
    description: 'Arabasta Krallığı\'nın kralı ve Nefertari Vivi\'nin babası. Halkını seven adil bir hükümdar.',
    backstory: 'Nefertari Cobra, 800 yıllık Nefertari hanedanının son kralıdır. Arabasta\'da Crocodile\'ın Baroque Works örgütüyle iç savaş çıkarmaya çalıştığı dönemde ülkesini korumak için mücadele etti. Luffy ve mürettebatın yardımıyla Crocodile yenildi ve krallık kurtarıldı. Nefertari ailesi, 800 yıl önce Dünya Hükümeti\'ni kuran 20 krallıktan biriydi ama Mariejois\'e çıkmayı reddeden tek aileydi — bu durum onları Celestial Dragon\'lardan ayıran özel bir konuma getirdi. Reverie\'de Gorosei\'ye Poneglyph\'ler ve Void Century hakkında sorular sordu. Bu sorular Im\'un dikkatini çekti ve Cobra, Reverie sırasında suikaste kurban gitti. Ölümü Sabo\'nun üstüne yıkıldı ama gerçek katil Im\'dur.',
    role: 'Arabasta Kralı — Void Century\'nin sırlarına yaklaşan hükümdar',
    age: '50 (ölüm anında)',
    height: 'Bilinmiyor',
    origin: 'Alubarna, Arabasta Krallığı, Grand Line',
    firstArc: 'arabasta',
    appearances: ['arabasta', 'reverie'],
    abilities: ['Siyasi Liderlik', 'Diplomasi', 'Nefertari Hanedanı Bilgisi', 'Poneglyph Farkındalığı'],
  },
  {
    name: 'Jewelry Bonney',
    slug: 'jewelry-bonney',
    image: '/characters/jewelry-bonney.webp',
    crew: 'supernova',
    epithet: 'Obur',
    bounty: '320,000,000',
    devilFruit: 'Toshi Toshi no Mi',
    description: 'En Kötü Nesil\'den bir süpernova ve Bartholomew Kuma\'nın kızı. Yaşı değiştirme gücüne sahip.',
    backstory: 'Jewelry Bonney, South Blue\'dan gelen ve En Kötü Nesil\'in 11 süpernovasından biri olan kadın korsandır. Toshi Toshi no Mi meyvesiyle kendisinin ve başkalarının yaşını değiştirebilir — genç ya da yaşlı yapabilir. Sabaody Takımadaları\'nda ilk kez göründü ve inanılmaz iştahıyla dikkat çekti. Aslında Bartholomew Kuma\'nın kızıdır ve babası Dünya Hükümeti tarafından Pacifista\'ya dönüştürüldükten sonra onu kurtarmak için mücadele etmektedir. Egghead Arc\'ta Luffy ve mürettebatla birlikte hareket etti. Kuma\'nın geçmişi ve Bonney\'nin çocukluğu Egghead\'de detaylı olarak anlatıldı. Nika\'nın gerçeğini öğrenen ve Kuma\'nın anılarını geri getirmeye çalışan duygusal bir karakterdir. Sapientifikasyon yeteneğiyle meyvesinin uyanışını gösterdi.',
    role: 'Süpernova — Kuma\'nın kızı ve özgürlük savaşçısı',
    age: '12 (gerçek yaş)',
    height: '174 cm',
    origin: 'Sorbet Krallığı, South Blue',
    firstArc: 'sabaody-archipelago',
    appearances: ['sabaody-archipelago', 'post-war', 'reverie', 'egghead'],
    abilities: ['Toshi Toshi no Mi (Yaş Manipülasyonu)', 'Yaş Değiştirme (Kendine ve Başkalarına)', 'Distortion Future', 'Sapientifikasyon (Uyanış)', 'Dövüş Sanatları'],
  },
]

export function getCharacterBySlug(slug: string): Character | undefined {
  return CHARACTERS.find((c) => c.slug === slug)
}

export function getCharactersByCrew(crew: string): Character[] {
  return CHARACTERS.filter((c) => c.crew === crew)
}

export const CREW_LABELS: Record<string, string> = {
  'straw-hat': 'Hasır Şapka',
  'marine': 'Deniz Kuvvetleri',
  'shichibukai': 'Yedi Savaş Lordu',
  'yonko': 'Dört İmparator',
  'revolutionary': 'Devrimci Ordu',
  'baroque-works': 'Baroque Works',
  'cp9': 'CP9',
  'supernova': 'En Kötü Nesil',
  'beast-pirates': 'Hayvan Korsanları',
  'big-mom-pirates': 'Big Mom Korsanları',
  'roger-pirates': 'Roger Korsanları',
  'whitebeard-pirates': 'Beyaz Sakal Korsanları',
  'red-hair-pirates': 'Kızıl Saç Korsanları',
  'ally': 'Müttefik',
  'other': 'Diğer',
}
