import type { Character } from '@/types'

export const CHARACTERS: Character[] = [
  {
    name: 'Monkey D. Luffy',
    slug: 'luffy',
    image: '/characters/luffy.jpg',
    crew: 'straw-hat',
    epithet: 'Hasır Şapka',
    bounty: '3,000,000,000',
    devilFruit: 'Hito Hito no Mi, Model: Nika',
    description: 'Hasır Şapka Korsanlarının kaptanı. Korsanlar Kralı olmak en büyük hayali. Neşeli, özgürlüğüne düşkün ve inanılmaz güçlü bir savaşçı.',
    backstory: 'Monkey D. Luffy, East Blue\'daki Foosha Köyü\'nde büyüdü. Küçük yaşta Kızıl Saçlı Shanks ile tanıştı ve ondan korsan olma hayalini aldı. Gomu Gomu no Mi\'yi (aslında Hito Hito no Mi, Model: Nika) yanlışlıkla yedi ve lastik insan oldu. Shanks, Luffy\'yi bir deniz canavarından kurtarırken sol kolunu kaybetti ve ayrılırken ona hasır şapkasını verdi: "Bunu bana geri ver, harika bir korsan olduğunda." Luffy, Ace ve Sabo ile kardeşler olarak büyüdü. 17 yaşında denize açıldı. Marineford Savaşı\'nda ağabeyi Ace\'i kaybetti — hayatının en büyük travması. 2 yıl Rayleigh\'den Haki eğitimi aldı. Wano\'da meyvesinin gerçek uyanışı olan Gear 5\'i açığa çıkardı ve Joy Boy\'un mirasçısı oldu.',
    role: 'Kaptan — mürettebatın kalbi, karar verici ve en güçlü savaşçısı',
    age: '19',
    height: '174 cm',
    origin: 'Foosha Köyü, Dawn Adası, East Blue',
    firstArc: 'romance-dawn',
    appearances: ['romance-dawn', 'orange-town', 'syrup-village', 'baratie', 'arlong-park', 'loguetown', 'reverse-mountain', 'whiskey-peak', 'little-garden', 'drum-island', 'arabasta', 'jaya', 'skypiea', 'long-ring-long-land', 'water-seven', 'enies-lobby', 'post-enies-lobby', 'thriller-bark', 'sabaody-archipelago', 'amazon-lily', 'impel-down', 'marineford', 'post-war', 'return-to-sabaody', 'fish-man-island', 'punk-hazard', 'dressrosa', 'zou', 'whole-cake-island', 'wano', 'egghead'],
    abilities: ['Gear 2', 'Gear 3', 'Gear 4 (Boundman, Snakeman, Tankman)', 'Gear 5 (Nika)', 'Haoshoku Haki', 'Busoshoku Haki', 'Kenbunshoku Haki (Gelecek Görüşü)'],
  },
  {
    name: 'Roronoa Zoro',
    slug: 'zoro',
    image: '/characters/zoro.jpg',
    crew: 'straw-hat',
    epithet: 'Korsan Avcısı',
    bounty: '1,111,000,000',
    description: 'Hasır Şapkaların savaşçısı ve kılıç ustası. Dünyanın en iyi kılıç ustası olmayı hedefliyor. Üç kılıç stili (Santoryu) kullanır.',
    backstory: 'Roronoa Zoro, küçük yaşta Shimotsuki Dojo\'da kılıç eğitimi aldı. Çocukluk arkadaşı ve rakibi Kuina ile "birimiz dünyanın en iyi kılıç ustası olacak" sözü verdi. Kuina\'nın ani ölümünden sonra onun kılıcı Wado Ichimonji\'yi aldı ve yemin etti: bir daha asla kaybetmeyecek. East Blue\'da korsan avcısı olarak ün kazandı. Baratie\'de Mihawk\'a meydan okudu ve ağır bir yenilgi aldı — ama bu yenilgi onu daha güçlü yaptı. Enies Lobby\'de hayatını mürettebatı için feda etmeye hazırdı. Thriller Bark\'ta Kuma\'dan Luffy\'nin tüm acısını üstüne aldı: "Hiçbir şey olmadı." 2 yıl Mihawk\'tan eğitim aldı. Wano\'da Enma kılıcını edindi ve Haoshoku Haki\'yi kılıcına akıtmayı öğrendi.',
    role: 'Savaşçı / Yan Kaptan — mürettebatın en güçlü ikinci üyesi',
    age: '21',
    height: '181 cm',
    origin: 'Shimotsuki Köyü, East Blue',
    firstArc: 'romance-dawn',
    appearances: ['romance-dawn', 'orange-town', 'syrup-village', 'baratie', 'arlong-park', 'loguetown', 'reverse-mountain', 'whiskey-peak', 'little-garden', 'drum-island', 'arabasta', 'jaya', 'skypiea', 'long-ring-long-land', 'water-seven', 'enies-lobby', 'post-enies-lobby', 'thriller-bark', 'sabaody-archipelago', 'return-to-sabaody', 'fish-man-island', 'punk-hazard', 'dressrosa', 'zou', 'wano', 'egghead'],
    abilities: ['Santoryu (Üç Kılıç)', 'Busoshoku Haki', 'Haoshoku Haki', 'Kenbunshoku Haki', 'Ashura', 'Enma Kılıcı'],
  },
  {
    name: 'Nami',
    slug: 'nami',
    image: '/characters/nami.jpg',
    crew: 'straw-hat',
    epithet: 'Hırsız Kedi',
    bounty: '366,000,000',
    description: 'Hasır Şapkaların navigatörü. Dünyanın haritasını çizmeyi hayal eder. Hava durumunu okuma ve manipüle etme konusunda dahi.',
    backstory: 'Nami, bebek olarak Bellemere tarafından savaş alanında bulundu ve Nojiko ile birlikte evlat edinildi. Cocoyashi Köyü\'nde mutlu bir çocukluk geçirdi ama Arlong geldiğinde her şey değişti. Bellemere, kızlarını korumak için hayatını feda etti. Arlong, 8 yaşındaki Nami\'ye bir anlaşma sundu: 100 milyon Berry kazanırsa köyünü satın alabilir. 8 yıl boyunca Arlong için harita çizerek para biriktirdi ama Arlong hileyle parayı çaldırdı. Luffy\'nin Arlong Park\'ı yıkmasıyla özgürleşti. Dünyanın haritasını çizmek — tüm denizleri kendi gözleriyle görüp çizmek — en büyük rüyası.',
    role: 'Navigatör — rotayı belirleyen, haritaları çizen ve hava durumunu okuyan',
    age: '20',
    height: '170 cm',
    origin: 'Cocoyashi Köyü, Conomi Adaları, East Blue',
    firstArc: 'orange-town',
    appearances: ['orange-town', 'syrup-village', 'baratie', 'arlong-park', 'loguetown', 'reverse-mountain', 'whiskey-peak', 'little-garden', 'drum-island', 'arabasta', 'jaya', 'skypiea', 'long-ring-long-land', 'water-seven', 'enies-lobby', 'post-enies-lobby', 'thriller-bark', 'sabaody-archipelago', 'return-to-sabaody', 'fish-man-island', 'punk-hazard', 'dressrosa', 'zou', 'whole-cake-island', 'wano', 'egghead'],
    abilities: ['Clima-Tact', 'Zeus', 'Hava Manipülasyonu', 'Navigasyon Dehası'],
  },
  {
    name: 'Usopp',
    slug: 'usopp',
    image: '/characters/usopp.jpg',
    crew: 'straw-hat',
    epithet: 'Tanrı / Sogeking',
    bounty: '500,000,000',
    description: 'Hasır Şapkaların nişancısı. Yalancı hikayeleri meşhurdur ama aslında çok yetenekli bir nişancıdır. Cesur bir savaşçı olmayı hayal eder.',
    backstory: 'Usopp, Syrup Köyü\'nde annesiyle büyüdü. Babası Yasopp, Shanks\'ın mürettebatına katılarak aileyi terk etti. Annesi hasta olup öldüğünde Usopp yalnız kaldı. Her gün köyde "korsanlar geliyor!" diye bağırarak yalan söylemeye başladı — aslında babasının geri döneceğini umuyordu. Kaptan Kuro olayından sonra Luffy\'nin mürettebatına katıldı. Water Seven\'da Going Merry\'yi bırakma kararıyla sarsıldı ve Luffy\'ye düello etti. "Sogeking" maskesiyle Enies Lobby\'de savaştı. Dressrosa\'da Kenbunshoku Haki\'yi uyandırdı ve "Tanrı Usopp" olarak 200 milyon ödüle ulaştı. En büyük hayali: cesur bir deniz savaşçısı olmak.',
    role: 'Nişancı — uzun menzil savaşçısı, taktikçi ve icatçı',
    age: '19',
    height: '176 cm',
    origin: 'Syrup Köyü, East Blue',
    firstArc: 'syrup-village',
    appearances: ['syrup-village', 'baratie', 'arlong-park', 'loguetown', 'reverse-mountain', 'whiskey-peak', 'little-garden', 'drum-island', 'arabasta', 'jaya', 'skypiea', 'long-ring-long-land', 'water-seven', 'enies-lobby', 'post-enies-lobby', 'thriller-bark', 'sabaody-archipelago', 'return-to-sabaody', 'fish-man-island', 'punk-hazard', 'dressrosa', 'zou', 'whole-cake-island', 'wano', 'egghead'],
    abilities: ['Nişancılık', 'Kenbunshoku Haki', 'Pop Green', 'Kabuto', 'Yaratıcı Taktikler'],
  },
  {
    name: 'Sanji',
    slug: 'sanji',
    image: '/characters/sanji.jpg',
    crew: 'straw-hat',
    epithet: 'Kara Bacak',
    bounty: '1,032,000,000',
    devilFruit: undefined,
    description: 'Hasır Şapkaların aşçısı. All Blue\'yu bulmayı hayal eder. Sadece ayaklarıyla savaşır, ellerini asla dövüş için kullanmaz.',
    backstory: 'Sanji, Germa 66 krallık ailesi Vinsmoke\'ların üçüncü oğlu olarak doğdu. Babası Judge, çocuklarını genetik olarak modifiye ederek duygusuz silahlar yapmak istedi. Annesi Sora, bunu engellemek için ilaç aldı ve hayatını kaybetti. Sanji, kardeşleri gibi olmadığı için "başarısız" sayıldı ve hapsedildi. Kardeşleri tarafından dövüldü, sadece ablası Reiju ona yardım etti. Kaçarak Baratie\'ye sığındı. Baş aşçı Zeff ile birlikte küçük bir adada mahsur kaldı. Zeff, Sanji\'yi kurtarmak için kendi bacağını yedi. "Bir beyefendi asla bir kadına vurmaz ve asla aç birini geri çevirmez" — Zeff\'in öğretisi Sanji\'nin yaşam felsefesi oldu. All Blue — tüm denizlerin balıklarının bulunduğu efsanevi deniz — rüyası.',
    role: 'Aşçı — mürettebatın beslenme uzmanı ve en güçlü savaşçılardan biri',
    age: '21',
    height: '180 cm',
    origin: 'Germa Krallığı / Baratie, North Blue',
    firstArc: 'baratie',
    appearances: ['baratie', 'arlong-park', 'loguetown', 'reverse-mountain', 'whiskey-peak', 'little-garden', 'drum-island', 'arabasta', 'jaya', 'skypiea', 'long-ring-long-land', 'water-seven', 'enies-lobby', 'post-enies-lobby', 'thriller-bark', 'sabaody-archipelago', 'return-to-sabaody', 'fish-man-island', 'punk-hazard', 'dressrosa', 'zou', 'whole-cake-island', 'wano', 'egghead'],
    abilities: ['Diable Jambe', 'Ifrit Jambe', 'Germa Dış İskeleti', 'Kenbunshoku Haki', 'Busoshoku Haki', 'Skywalk'],
  },
  {
    name: 'Tony Tony Chopper',
    slug: 'chopper',
    image: '/characters/chopper.jpg',
    crew: 'straw-hat',
    epithet: 'Pamuk Şeker Sever',
    bounty: '1,000',
    devilFruit: 'Hito Hito no Mi',
    description: 'Hasır Şapkaların doktoru. İnsan formuna dönüşebilen bir ren geyiği. Tüm hastalıkları tedavi edecek bir ilaç bulmayı hayal eder.',
    backstory: 'Tony Tony Chopper, Drum Adası\'nda doğmuş bir ren geyiğidir. Mavi burnu yüzünden sürüsü tarafından dışlandı. Hito Hito no Mi\'yi yiyerek insan zekası kazandı ama hem hayvanlar hem insanlar onu "canavar" olarak gördü. Doktor Hiluluk onu buldu ve sevdi. Hiluluk, "tüm hastalıkları iyileştiren kiraz çiçekleri" rüyasıyla yaşayan çılgın bir doktordur. Chopper, Hiluluk\'u kurtarmak için zehirli bir mantar buldu — zehirli olduğunu bilmeden. Hiluluk, Chopper\'ın sevgisini bildiği için mantarı içti ve sonra kendini feda etti: "İnsanlar ne zaman ölür? Unutulduklarında!" Dr. Kureha\'dan tıp eğitimi alan Chopper, Luffy\'nin daveti ile mürettebata katıldı.',
    role: 'Doktor — mürettebatın sağlık uzmanı, 7 farklı forma dönüşebilir',
    age: '17',
    height: '90 cm (insan formu)',
    origin: 'Drum Adası, Grand Line',
    firstArc: 'drum-island',
    appearances: ['drum-island', 'arabasta', 'jaya', 'skypiea', 'long-ring-long-land', 'water-seven', 'enies-lobby', 'post-enies-lobby', 'thriller-bark', 'sabaody-archipelago', 'return-to-sabaody', 'fish-man-island', 'punk-hazard', 'dressrosa', 'zou', 'whole-cake-island', 'wano', 'egghead'],
    abilities: ['7 Form Dönüşümü', 'Monster Point', 'Rumble Ball', 'Tıp Bilgisi'],
  },
  {
    name: 'Nico Robin',
    slug: 'robin',
    image: '/characters/robin.jpg',
    crew: 'straw-hat',
    epithet: 'Şeytan Çocuğu',
    bounty: '930,000,000',
    devilFruit: 'Hana Hana no Mi',
    description: 'Hasır Şapkaların arkeologu. Poneglyph\'leri okuyabilen son kişi. Rio Poneglyph\'i bulmak ve gerçek tarihi öğrenmek en büyük hayali.',
    backstory: 'Nico Robin, Ohara adasında büyüdü. 8 yaşında arkeolog oldu ve Poneglyph\'leri okumayı öğrendi. Annesi Olvia, araştırma için denize çıktı ve yakalandı. Dünya Hükümeti, Ohara\'nın Void Century araştırmalarını tehdit olarak gördü ve Buster Call ile tüm adayı yok etti. Robin, Aokiji\'nin "izin vermesiyle" kaçan tek kurtulandır. 20 yıl boyunca kaçak olarak yaşadı — güvendiği herkes onu sattı. 8 yaşında 79 milyon Berry ödül konulmuştu. Crocodile\'a katıldı ama ihanet etti. Arabasta sonrası Hasır Şapkalara sığındı. Enies Lobby\'deki "Yaşamak istiyorum!" çığlığı, 20 yıl sonra ilk kez hayata tutunmasıdır.',
    role: 'Arkeolog — Poneglyph okuyucu, tarihin anahtarı',
    age: '30',
    height: '188 cm',
    origin: 'Ohara, West Blue',
    firstArc: 'arabasta',
    appearances: ['arabasta', 'jaya', 'skypiea', 'long-ring-long-land', 'water-seven', 'enies-lobby', 'post-enies-lobby', 'thriller-bark', 'sabaody-archipelago', 'return-to-sabaody', 'fish-man-island', 'punk-hazard', 'dressrosa', 'zou', 'wano', 'egghead'],
    abilities: ['Hana Hana no Mi', 'Gigante Fleur', 'Demonio Fleur', 'Arkeoloji ve Tarih Bilgisi'],
  },
  {
    name: 'Franky',
    slug: 'franky',
    image: '/characters/franky.jpg',
    crew: 'straw-hat',
    epithet: 'Cyborg',
    bounty: '394,000,000',
    description: 'Hasır Şapkaların gemi ustası. Cyborg bir usta. Thousand Sunny\'nin yapımcısı. Rüyası, kendi yaptığı gemiyle dünyanın sonuna ulaşmak.',
    backstory: 'Franky (gerçek adı Cutty Flam), South Blue\'dan terk edilmiş bir çocuk olarak Water Seven\'a geldi. Usta gemi yapımcısı Tom onu ve Iceburg\'u öğrenci olarak aldı. Tom, Roger\'ın gemisi Oro Jackson\'ı yapmış ve Sea Train\'i icat etmiştir. Franky, savaş gemileri yapardı ama bunlar Spandam tarafından kullanılarak Tom\'a iftira atıldı. Franky, Tom\'u kurtarmak için Sea Train\'in önüne atladı ve ezildi. Hurda metallerle kendini cyborg olarak yeniden inşa etti. Tom, Pluton planlarını Franky\'ye emanet etti. Enies Lobby\'den sonra, Tom\'un mirası olan Adam Ağacı\'ndan Thousand Sunny\'yi yaptı ve mürettebata katıldı.',
    role: 'Gemi Ustası — Thousand Sunny\'nin yapımcısı ve bakımcısı',
    age: '36',
    height: '240 cm',
    origin: 'South Blue / Water Seven',
    firstArc: 'water-seven',
    appearances: ['water-seven', 'enies-lobby', 'post-enies-lobby', 'thriller-bark', 'sabaody-archipelago', 'return-to-sabaody', 'fish-man-island', 'punk-hazard', 'dressrosa', 'zou', 'wano', 'egghead'],
    abilities: ['Cyborg Gövde', 'Radical Beam', 'General Franky', 'Coup de Vent', 'Mühendislik Dehası'],
  },
  {
    name: 'Brook',
    slug: 'brook',
    image: '/characters/brook.jpg',
    crew: 'straw-hat',
    epithet: 'Soul King',
    bounty: '383,000,000',
    devilFruit: 'Yomi Yomi no Mi',
    description: 'Hasır Şapkaların müzisyeni. Ölüp dirilen iskelet müzisyen. Laboon ile tekrar buluşmayı hayal eder.',
    backstory: 'Brook, Batı Deniz\'deki Rumbar Korsanlarının müzisyeniydi. 50 yıl önce mürettebatıyla birlikte Grand Line\'a girdi. Twin Cape\'de dev balina Laboon\'u bıraktılar: "Geri döneceğiz!" Ancak zehirli bir düşmanla karşılaştılar ve tüm mürettebat öldü. Brook, Yomi Yomi meyvesi sayesinde dirildi ama ruhunun geri dönmesi 1 yıl sürdü — bu sürede bedeni iskelet olmuştu. 50 yıl boyunca Florian Üçgeni\'nde tek başına dolaştı. Gölgesi Moria tarafından çalındı. Hasır Şapkalar tarafından kurtarıldıktan sonra mürettebata katıldı. Laboon\'a verdiği sözü tutmak — Binks\'in Sake\'sini çalarak geri dönmek — en büyük hayali.',
    role: 'Müzisyen — mürettebatın moral kaynağı ve ruh savaşçısı',
    age: '90',
    height: '277 cm',
    origin: 'Batı Deniz',
    firstArc: 'thriller-bark',
    appearances: ['thriller-bark', 'sabaody-archipelago', 'return-to-sabaody', 'fish-man-island', 'punk-hazard', 'dressrosa', 'zou', 'whole-cake-island', 'wano', 'egghead'],
    abilities: ['Yomi Yomi no Mi', 'Ruh Gücü', 'Soul Solid (Buz Kılıcı)', 'Müzik'],
  },
  {
    name: 'Jinbe',
    slug: 'jinbe',
    image: '/characters/jinbe.jpg',
    crew: 'straw-hat',
    epithet: 'Denizin Şövalyesi',
    bounty: '1,100,000,000',
    description: 'Hasır Şapkaların dümencisi. Balık-Adam Karate ustası ve eski Shichibukai. İnsanlar ve Balık-Adamlar arasında barış istiyor.',
    backstory: 'Jinbe, Fish-Man Island\'da doğmuş bir balina köpekbalığı Balık-Adamıdır. Fisher Tiger\'ın Güneş Korsanlarına katıldı ve Tiger\'ın ölümünden sonra kaptan oldu. Shichibukai olarak Fish-Man Island\'ı korudu. Marineford Savaşı\'nda Ace\'in idamına karşı çıkarak Shichibukai\'lik\'ten istifa etti ve Impel Down\'a hapsedildi. Luffy ile birlikte kaçtı ve Marineford\'da savaştı. Ace\'in ölümünden sonra çöken Luffy\'ye hayatta kalanlarını hatırlattı. Big Mom\'un mürettebatındaydı ama Luffy için ayrıldı. Whole Cake Island\'da resmi olarak Hasır Şapkalara katıldı. İnsanlar ve Balık-Adamlar arasında barış — Fisher Tiger ve Otohime\'nin rüyası — en büyük hedefi.',
    role: 'Dümenci — denizcilik uzmanı ve deneyimli savaşçı',
    age: '46',
    height: '301 cm',
    origin: 'Fish-Man Island, Grand Line',
    firstArc: 'impel-down',
    appearances: ['impel-down', 'marineford', 'post-war', 'fish-man-island', 'whole-cake-island', 'wano', 'egghead'],
    abilities: ['Balık-Adam Karate', 'Busoshoku Haki', 'Kenbunshoku Haki', 'Su Manipülasyonu'],
  },
  // ─── Yonko ──────────────────────────────────────────────────────────────
  {
    name: 'Shanks',
    slug: 'shanks',
    image: '/characters/shanks.jpg',
    crew: 'yonko',
    epithet: 'Kızıl Saçlı',
    bounty: '4,048,900,000',
    description: 'Kızıl Saçlı Korsanların kaptanı ve Dört İmparator\'dan biri. Luffy\'ye hasır şapkayı veren ve ona ilham kaynağı olan efsanevi korsan.',
    backstory: 'Shanks, Roger Korsanlarında çıraklık yaptı. Roger\'ın idamından sonra kendi korsanlarını kurdu ve Yonko\'lar arasına girdi. Foosha Köyü\'nde küçük Luffy ile tanıştı ve onu korumak için sol kolunu kaybetti. Hasır şapkayı Luffy\'ye emanet etti. Marineford Savaşı\'nı tek başına durdurdu. Gizemli geçmişi — Celestial Dragon kökenli olabileceği ve God Valley olayındaki rolü — hâlâ tam olarak bilinmemektedir. Haki\'nin en güçlü kullanıcılarından biridir.',
    role: 'Luffy\'nin ilham kaynağı ve koruyucu figürü',
    age: '39',
    height: '199 cm',
    origin: 'Batı Deniz',
    firstArc: 'romance-dawn',
    appearances: ['romance-dawn', 'marineford', 'post-war', 'reverie', 'wano'],
    abilities: ['Haoshoku Haki (En Güçlü)', 'Busoshoku Haki', 'Kenbunshoku Haki', 'Kılıç Ustalığı'],
  },
  {
    name: 'Kaido',
    slug: 'kaido',
    image: '/characters/kaido.jpg',
    crew: 'yonko',
    epithet: 'Yüz Hayvanın Kaido\'su',
    bounty: '4,611,100,000',
    devilFruit: 'Uo Uo no Mi, Model: Seiryu',
    description: 'Eski Dört İmparator ve Hayvan Korsanlarının kaptanı. Dünyanın en güçlü canlısı olarak bilinir. Wano\'yu 20 yıl boyunca tiranlıkla yönetti.',
    backstory: 'Kaido, Vodka Krallığı\'nda doğdu. Küçük yaşta savaşçı olarak kullanıldı ve ülkesi tarafından Deniz Kuvvetleri\'ne satıldı. Rocks Korsanlarında büyüdü ve Big Mom\'dan Uo Uo no Mi meyvesini aldı. God Valley olayından sonra kendi korsanlarını kurdu. Wano\'yu 20 yıl önce işgal etti ve Kozuki Oden\'i idam etti. Ölmek isteyip de ölemeyen "dünyanın en güçlü canlısı" olarak bilinir. Joy Boy\'u bekliyordu — ve Luffy\'nin Gear 5\'iyle karşılaştığında gülümsedi.',
    role: 'Wano sagasının ana antagonisti — tarihin en güçlü korsanlarından biri',
    age: '59',
    height: '710 cm',
    origin: 'Vodka Krallığı',
    firstArc: 'punk-hazard',
    appearances: ['punk-hazard', 'dressrosa', 'zou', 'wano'],
    abilities: ['Uo Uo no Mi (Ejderha Formu)', 'Haoshoku Haki', 'Busoshoku Haki', 'Kenbunshoku Haki', 'Thunder Bagua', 'Blazing Bagua'],
  },
  {
    name: 'Edward Newgate (Whitebeard)',
    slug: 'whitebeard',
    image: '/characters/whitebeard.jpg',
    crew: 'yonko',
    epithet: 'Beyaz Sakal',
    bounty: '5,046,000,000',
    devilFruit: 'Gura Gura no Mi',
    description: 'Eski Dört İmparator ve "Dünyanın En Güçlü Adamı". Deprem yaratabilir. Mürettebatını ailesi olarak görür.',
    backstory: 'Edward Newgate, fakir bir ülkede doğdu ve tek istediği aile oldu. Rocks Korsanlarında savaştı ama ayrılarak kendi mürettebatını kurdu. "Çocuklarım" dediği mürettebatını her şeyden çok severdi. Roger ile çağdaş ve rakipti. Ace\'i evlat edindi ve korudu. Marineford\'da Ace\'i kurtarmak için Marine HQ\'ya saldırdı. Yüzlerce yara almış, göğsü delinmiş olmasına rağmen tek bir adım bile geri atmadan ayakta öldü. Son sözleri: "ONE PIECE GERÇEK!"',
    role: 'Eski çağın en güçlü korsanı — aile değerleri ve yıkılmaz irade sembolü',
    age: '72 (ölümünde)',
    height: '666 cm',
    origin: 'Sphinx, Yeni Dünya',
    firstArc: 'marineford',
    appearances: ['marineford'],
    abilities: ['Gura Gura no Mi (Deprem)', 'Haoshoku Haki', 'Busoshoku Haki', 'Kenbunshoku Haki'],
  },
  {
    name: 'Marshall D. Teach (Blackbeard)',
    slug: 'blackbeard',
    image: '/characters/blackbeard.jpg',
    crew: 'yonko',
    epithet: 'Kara Sakal',
    bounty: '3,996,000,000',
    devilFruit: 'Yami Yami no Mi + Gura Gura no Mi',
    description: 'Kara Sakal Korsanlarının kaptanı. Tarihte iki Şeytan Meyvesi gücüne sahip tek kişi.',
    backstory: 'Marshall D. Teach, Beyaz Sakal Korsanlarında uzun yıllar gizlenerek yaşadı. Yami Yami meyvesini ele geçirmek için yoldaşı Thatch\'i öldürdü. Ace\'i yakalayarak Deniz Kuvvetleri\'ne teslim etti — bu, Marineford Savaşı\'nı tetikledi. Impel Down\'dan en tehlikeli suçluları topladı. Marineford\'da Beyaz Sakal\'ın cesedinden Gura Gura meyvesini çaldı. İki Şeytan Meyvesine sahip tarihteki tek kişi. D. soyadının taşıyıcısı olarak One Piece\'in en büyük gizemlerinden birini temsil eder.',
    role: 'Serinin en büyük antagonistlerinden biri — Luffy\'nin karanlık aynası',
    age: '40',
    height: '344 cm',
    origin: 'Bilinmiyor',
    firstArc: 'jaya',
    appearances: ['jaya', 'impel-down', 'marineford', 'post-war', 'wano'],
    abilities: ['Yami Yami no Mi (Karanlık)', 'Gura Gura no Mi (Deprem)', 'Busoshoku Haki', 'Kenbunshoku Haki'],
  },
  {
    name: 'Charlotte Linlin (Big Mom)',
    slug: 'bigmom',
    image: '/characters/bigmom.jpg',
    crew: 'yonko',
    epithet: 'Big Mom',
    bounty: '4,388,000,000',
    devilFruit: 'Soru Soru no Mi',
    description: 'Eski Dört İmparator ve Big Mom Korsanlarının kaptanı. Ruhları manipüle edebilir. 85 çocuk annesi.',
    backstory: 'Charlotte Linlin, çocukken devasa gücü yüzünden ailesi tarafından terk edildi. Yetimhanede Mother Carmel tarafından büyütüldü. 6 yaşında Elbaf devlerini bile korkutan bir canavar olmuştu. Carmel\'in gizemli kayboluşundan sonra Soru Soru meyvesini "devraldı". Rocks Korsanlarında savaştı. Totto Land\'ı kurarak 85 çocukla devasa bir aile imparatorluğu oluşturdu. Whole Cake Island\'da Luffy ile savaştı. Wano\'da Kid ve Law tarafından yenildi.',
    role: 'Whole Cake Island ve Wano sagalarının ana antagonistlerinden biri',
    age: '68',
    height: '880 cm',
    origin: 'Elbaf yakınları',
    firstArc: 'fish-man-island',
    appearances: ['fish-man-island', 'whole-cake-island', 'wano'],
    abilities: ['Soru Soru no Mi (Ruh)', 'Napoleon (Kılıç Homie)', 'Prometheus (Ateş)', 'Hera (Yıldırım)', 'Haoshoku Haki'],
  },
  {
    name: 'Buggy',
    slug: 'buggy',
    image: '/characters/buggy.jpg',
    crew: 'yonko',
    epithet: 'Şanslı Palyaço / Yıldız Palyaço',
    bounty: '3,189,000,000',
    devilFruit: 'Bara Bara no Mi',
    description: 'Eski Roger Korsanı. Şans eseri Dört İmparator arasına girmeyi başardı. Cross Guild\'in "lideri".',
    backstory: 'Buggy, Shanks ile birlikte Roger Korsanlarında çıraklık yaptı. Bara Bara meyvesini yanlışlıkla yedi. Roger\'ın idamından sonra East Blue\'da küçük çaplı korsanlık yaptı. Impel Down\'dan kaçtığında tesadüfen bir kahraman oldu. Marineford\'da Roger mürettebatı geçmişi ortaya çıkınca ünü arttı. Shichibukai sistemi kaldırıldığında Mihawk ve Crocodile ile Cross Guild\'i kurdu — ama kontrol tamamen onlardadır. Buggy "yüz" olarak kullanılmaktadır. Şans eseri Yonko ilan edildi.',
    role: 'Komedik antagonist ve şanslı anti-kahraman',
    age: '39',
    height: '192 cm',
    origin: 'Grand Line (Roger Korsanları gemisinde doğdu)',
    firstArc: 'orange-town',
    appearances: ['orange-town', 'loguetown', 'impel-down', 'marineford'],
    abilities: ['Bara Bara no Mi (Parçalanma)', 'Muggy Ball', 'Şans Faktörü', 'Karizmatik Liderlik'],
  },
  // ─── Supernova ──────────────────────────────────────────────────────────
  {
    name: 'Portgas D. Ace',
    slug: 'ace',
    image: '/characters/ace.jpg',
    crew: 'other',
    epithet: 'Ateş Yumruk',
    bounty: '550,000,000',
    devilFruit: 'Mera Mera no Mi',
    description: 'Luffy\'nin üvey ağabeyi ve Beyaz Sakal Korsanlarının 2. Bölük Komutanı. Korsanlar Kralı Gold Roger\'ın oğlu.',
    backstory: 'Portgas D. Ace, Korsanlar Kralı Gol D. Roger\'ın oğludur. Annesi Portgas D. Rouge, Ace\'i korumak için hamileliğini 20 ay uzattı ve doğumdan sonra öldü. Garp tarafından Dadan\'a bırakılarak Luffy ve Sabo ile kardeşler olarak büyüdü. "Roger\'ın oğlu olarak yaşamayı hak ediyor muyum?" sorusu onu ömür boyu takip etti. 17 yaşında denize açıldı ve Beyaz Sakal\'ın "oğlu" oldu. Blackbeard\'ı takip ederken yakalandı ve Marineford\'da idam edilmek üzere tutuldu. Kurtarıldı ama Akainu\'nun Luffy\'ye yönelik saldırısını vücuduyla engelledi ve öldü.',
    role: 'Luffy\'nin ağabeyi — motivasyonu ve en büyük kaybı',
    age: '20 (ölümünde)',
    height: '185 cm',
    origin: 'Baterilla, South Blue',
    firstArc: 'arabasta',
    appearances: ['arabasta', 'impel-down', 'marineford'],
    abilities: ['Mera Mera no Mi (Ateş)', 'Busoshoku Haki', 'Haoshoku Haki'],
  },
  {
    name: 'Trafalgar D. Law',
    slug: 'law',
    image: '/characters/law.jpg',
    crew: 'supernova',
    epithet: 'Ölüm Cerrahı',
    bounty: '3,000,000,000',
    devilFruit: 'Ope Ope no Mi',
    description: 'Heart Korsanlarının kaptanı. Luffy ile ittifak kurarak Doflamingo ve Kaido\'ya karşı savaştı.',
    backstory: 'Trafalgar D. Water Law, Flevance\'da doğdu. Flevance, Amber Lead zehirlenmesiyle yok edilen bir ülkedir. Ailesi ve tüm tanıdıkları öldürüldü. 10 yaşında Doflamingo\'ya sığındı — ölmek istiyordu. Doflamingo\'nun kardeşi Corazon (Rosinante), Law\'ı kurtardı. Ope Ope meyvesini bularak Law\'ın Amber Lead hastalığını iyileştirdi ve Doflamingo\'ya karşı hayatını feda etti. Law, Corazon\'un intikamı ve D. soyadının gizemini çözmek için Luffy ile ittifak kurdu.',
    role: 'Luffy\'nin en önemli müttefiki — stratejik deha',
    age: '26',
    height: '191 cm',
    origin: 'Flevance, North Blue',
    firstArc: 'sabaody-archipelago',
    appearances: ['sabaody-archipelago', 'marineford', 'punk-hazard', 'dressrosa', 'zou', 'wano'],
    abilities: ['Ope Ope no Mi', 'Room / Shambles', 'K-Room', 'Puncture Wille', 'Busoshoku Haki', 'Kenbunshoku Haki'],
  },
  {
    name: 'Eustass Kid',
    slug: 'kid',
    image: '/characters/kid.jpg',
    crew: 'supernova',
    epithet: 'Kaptan',
    bounty: '3,000,000,000',
    devilFruit: 'Jiki Jiki no Mi',
    description: 'Kid Korsanlarının kaptanı. Manyetizma gücüyle metali kontrol eder. Big Mom\'u Law ile birlikte yendi.',
    backstory: 'Eustass Kid, South Blue\'dan gelen agresif ve hırslı bir korsan. Sabaody\'de Luffy ile aynı dönemde ortaya çıkan Supernova\'lardan biri. Yeni Dünya\'da Kaido\'ya meydan okudu ve yakalandı, sol kolunu kaybetti. Udon hapishanesinde Luffy ile birlikte çalıştı. Wano\'da Killer ile birlikte Kaido\'nun ordusuna karşı savaştı. Law ile birlikte Big Mom\'u yendi.',
    role: 'Luffy\'nin rakibi ve paralel yolculuğun korsanı',
    age: '23',
    height: '205 cm',
    origin: 'South Blue',
    firstArc: 'sabaody-archipelago',
    appearances: ['sabaody-archipelago', 'wano'],
    abilities: ['Jiki Jiki no Mi (Manyetizma)', 'Assign', 'Damned Punk', 'Busoshoku Haki', 'Haoshoku Haki'],
  },
  {
    name: 'Boa Hancock',
    slug: 'hancock',
    image: '/characters/hancock.jpg',
    crew: 'shichibukai',
    epithet: 'Yılan Prensesi',
    bounty: '1,659,000,000',
    devilFruit: 'Mero Mero no Mi',
    description: 'Kuja Korsanlarının kaptanı ve Amazon Lily\'nin imparatoriçesi. Eski Shichibukai. Luffy\'ye aşık.',
    backstory: 'Hancock, çocukken kız kardeşleri Sandersonia ve Marigold ile birlikte Celestial Dragonlar tarafından köle yapıldı. Sırtına köle damgası vuruldu. Fisher Tiger\'ın Mariejois saldırısıyla kurtulduktan sonra Amazon Lily\'ye döndü. Güzelliğini ve gücünü kullanarak Kuja kabilesinin lideri ve Shichibukai oldu. Luffy\'nin köle damgasına gösterdiği öfke ve duyarlılık Hancock\'u etkiledi — ilk kez birine güvendi ve aşık oldu.',
    role: 'Luffy\'nin müttefiki ve aşığı',
    age: '31',
    height: '191 cm',
    origin: 'Amazon Lily, Calm Belt',
    firstArc: 'amazon-lily',
    appearances: ['amazon-lily', 'impel-down', 'marineford'],
    abilities: ['Mero Mero no Mi (Taşa Çevirme)', 'Haoshoku Haki', 'Busoshoku Haki', 'Kenbunshoku Haki'],
  },
  {
    name: 'Dracule Mihawk',
    slug: 'mihawk',
    image: '/characters/mihawk.jpg',
    crew: 'shichibukai',
    epithet: 'Şahin Gözlü',
    bounty: '3,590,000,000',
    description: 'Dünyanın en güçlü kılıç ustası. Eski Shichibukai. Zoro\'nun hedefi.',
    backstory: 'Dracule Mihawk, dünyanın en güçlü kılıç ustasıdır. Siyah kılıç Yoru ile tek başına Don Krieg\'in tüm filosunu yok etmiştir. Shanks ile eski rakiptir — Shanks kolunu kaybetmeden önce düzenli düello yaparlardı. Shichibukai sisteminin kaldırılmasından sonra Crocodile ve Buggy ile Cross Guild\'i kurdu. 2 yıl boyunca Zoro\'yu eğitmiştir — düşmanını eğitmesi, Zoro\'ya olan saygısını gösterir.',
    role: 'Zoro\'nun nihai hedefi ve geçici akıl hocası',
    age: '43',
    height: '198 cm',
    origin: 'Bilinmiyor',
    firstArc: 'baratie',
    appearances: ['baratie', 'marineford'],
    abilities: ['Dünyanın En Güçlü Kılıç Ustalığı', 'Yoru (Siyah Kılıç)', 'Busoshoku Haki', 'Kenbunshoku Haki'],
  },
  {
    name: 'Crocodile',
    slug: 'crocodile',
    image: '/characters/crocodile.jpg',
    crew: 'shichibukai',
    epithet: 'Çöl Kralı',
    bounty: '1,965,000,000',
    devilFruit: 'Suna Suna no Mi',
    description: 'Eski Shichibukai ve Baroque Works\'un lideri. Cross Guild kurucularından.',
    backstory: 'Crocodile, bir zamanlar Yeni Dünya\'da Beyaz Sakal\'a meydan okuyup yenilmiş bir korsandır. Bu yenilgi onu kırdı. East Blue\'ya dönerek Baroque Works gizli örgütünü kurdu ve Arabasta Krallığı\'nı ele geçirmeye çalıştı. Luffy tarafından 3 kez yenildi. Impel Down\'da Luffy ile geçici ittifak kurarak kaçtı ve Marineford\'da savaştı. Savaş sonrası Yeni Dünya\'ya döndü ve Mihawk ve Buggy ile Cross Guild\'i kurdu.',
    role: 'İlk büyük antagonistten müttefike dönüşen karmaşık karakter',
    age: '46',
    height: '253 cm',
    origin: 'Bilinmiyor',
    firstArc: 'arabasta',
    appearances: ['arabasta', 'impel-down', 'marineford'],
    abilities: ['Suna Suna no Mi (Kum)', 'Kum Fırtınası', 'Kanca Silahı', 'Stratejik Zeka'],
  },
  {
    name: 'Donquixote Doflamingo',
    slug: 'doflamingo',
    image: '/characters/doflamingo.jpg',
    crew: 'shichibukai',
    epithet: 'Göklerin Şeytanı / Joker',
    bounty: '340,000,000',
    devilFruit: 'Ito Ito no Mi',
    description: 'Eski Shichibukai ve Dressrosa\'nın zorba kralı. Celestial Dragon kökenli.',
    backstory: 'Donquixote Doflamingo, Celestial Dragon ailesinden doğdu. Babası Homing, insanlar arasında yaşamaya karar verince aile ayrıcalıklarını kaybetti. İnsanlar tarafından linç edildiler. Doflamingo, 10 yaşında babasını öldürdü ve başını Mariejois\'a göndererek geri kabul edilmeyi umdu ama reddedildi. Trebol\'un rehberliğinde kendi korsanlarını kurdu. Dressrosa\'yı ele geçirdi ve 10 yıl tiranlıkla yönetti. Kaido\'nun SMILE tedarikçisi olarak yeraltı dünyasının "Joker"ıydı. Luffy tarafından Gear 4 ile yenilerek Impel Down\'a gönderildi.',
    role: 'Dressrosa sagasının ana antagonisti — karizmatik ve acımasız tiran',
    age: '41',
    height: '305 cm',
    origin: 'Mariejois (Celestial Dragon)',
    firstArc: 'jaya',
    appearances: ['jaya', 'punk-hazard', 'dressrosa'],
    abilities: ['Ito Ito no Mi (İp)', 'Haoshoku Haki', 'Busoshoku Haki', 'Birdcage', 'Awakening'],
  },
  {
    name: 'Bartholomew Kuma',
    slug: 'kuma',
    image: '/characters/kuma.jpg',
    crew: 'revolutionary',
    epithet: 'Tiran',
    bounty: '296,000,000',
    devilFruit: 'Nikyu Nikyu no Mi',
    description: 'Eski Shichibukai ve Devrimci Ordunun eski komutanı. Bonney\'nin babası. Kendini feda etti.',
    backstory: 'Bartholomew Kuma, Buccaneer soyundan gelen bir adamdır. Çocukken Celestial Dragonlar tarafından köle yapıldı. Nika efsanesine — insanları kurtaran güneş tanrısı — inandı. Devrimci Orduna katıldı ve Dragon\'ın sağ kolu oldu. Kızı Bonney\'i korumak için Vegapunk ile anlaştı: bilincini tamamen feda ederek Pacifista\'ya dönüştürüldü. Thriller Bark\'ta ve Sabaody\'de Hasır Şapkaları korudu — son bilinçli eylemleri onları kurtarmak oldu.',
    role: 'Trajik kahraman — sevgi ve fedakarlığın sembolü',
    age: '47',
    height: '689 cm',
    origin: 'Sorbet Krallığı, South Blue',
    firstArc: 'thriller-bark',
    appearances: ['thriller-bark', 'sabaody-archipelago', 'egghead'],
    abilities: ['Nikyu Nikyu no Mi (Pençe)', 'Pençe Dalgası', 'Işınlanma', 'Pacifista Gövdesi'],
  },
  {
    name: 'Sabo',
    slug: 'sabo',
    image: '/characters/sabo.jpg',
    crew: 'revolutionary',
    epithet: 'Ateş İmparatoru',
    bounty: '602,000,000',
    devilFruit: 'Mera Mera no Mi',
    description: 'Devrimci Ordunun Genelkurmay Başkanı ve Luffy ile Ace\'in kardeşi.',
    backstory: 'Sabo, soylu bir aile çocuğuydu ama ailesinin baskısından kaçarak Ace ve Luffy ile kardeşler oldu. 10 yaşında tek başına denize açıldı ama Celestial Dragon\'ın gemisi tarafından vuruldu. Dragon tarafından kurtarıldı ve Devrimci Orduda büyüdü. Hafızasını kaybetmişti — Marineford\'da Ace\'in ölüm haberini duyunca her şeyi hatırladı. Dressrosa\'da Mera Mera meyvesini yiyerek Ace\'in mirasını devraldı. Reverie\'de Celestial Dragonlara karşı savaştı.',
    role: 'Luffy\'nin kardeşi ve Devrimci Ordunun askeri lideri',
    age: '22',
    height: '187 cm',
    origin: 'Goa Krallığı, East Blue',
    firstArc: 'post-war',
    appearances: ['post-war', 'dressrosa', 'reverie'],
    abilities: ['Mera Mera no Mi (Ateş)', 'Ryusoken (Ejderha Pençesi)', 'Busoshoku Haki', 'Kenbunshoku Haki'],
  },
  {
    name: 'Nefertari Vivi',
    slug: 'vivi',
    image: '/characters/vivi.jpg',
    crew: 'other',
    epithet: 'Arabasta Prensesi',
    description: 'Arabasta Krallığının prensesi. Ruhsal olarak mürettebatın bir parçası.',
    backstory: 'Nefertari Vivi, Arabasta Krallığının prensesidir. Ülkesini kurtarmak için Baroque Works\'e sızdı ve Crocodile\'ın planını keşfetti. Hasır Şapkalarla birlikte yolculuk ederek dost oldu ve birlikte Crocodile\'ı yendiler. Mürettebatla kalmak ile prenses sorumluluğu arasında kalarak ülkesinde kaldı. "X işareti" vedası serinin en duygusal sahnelerinden biridir. Reverie\'ye katıldı ama sonrasında kayboldu.',
    role: 'Luffy\'nin ilk gerçek müttefiki ve onursal mürettebat üyesi',
    age: '18',
    height: '169 cm',
    origin: 'Alubarna, Arabasta Krallığı',
    firstArc: 'whiskey-peak',
    appearances: ['whiskey-peak', 'little-garden', 'drum-island', 'arabasta', 'reverie'],
    abilities: ['Diplomasi', 'Peacock Slasher', 'Liderlik', 'Casusluk'],
  },
  {
    name: 'Enel',
    slug: 'enel',
    image: '/characters/enel.jpg',
    crew: 'other',
    epithet: 'Tanrı',
    bounty: undefined,
    devilFruit: 'Goro Goro no Mi',
    description: 'Skypiea\'nın eski tanrısı. Yıldırım gücüne sahip. Şu anda Ay\'da yaşıyor.',
    backstory: 'Enel, Birka gökyüzü adasında doğdu. Goro Goro meyvesini yiyerek yıldırım gücünü kazandı ve Birka\'yı yok etti. Skypiea\'yı ele geçirerek kendini "Tanrı" ilan etti. Mantra (Kenbunshoku Haki) ile adada olan her şeyi duyabiliyordu. Planı Skypiea\'yı yok edip Ay\'a gitmekti. Luffy, lastik vücudu sayesinde yıldırıma karşı bağışık olan tek kişi olarak onu yendi. Enel, Maxim gemisiyle Ay\'a ulaştı ve orada eski bir medeniyetin kalıntılarını keşfetti.',
    role: 'Skypiea arcının ana antagonisti — kibir ve güç sembolü',
    age: 'Bilinmiyor',
    height: '266 cm',
    origin: 'Birka (Gökyüzü Adası)',
    firstArc: 'skypiea',
    appearances: ['skypiea'],
    abilities: ['Goro Goro no Mi (Yıldırım)', 'Mantra (Kenbunshoku Haki)', 'El Thor', '200 Milyon Volt', 'Maxim Gemisi'],
  },
  // ─── Marines ──────────────────────────────────────────────────────────
  {
    name: 'Smoker',
    slug: 'smoker',
    image: '/characters/smoker.jpg',
    crew: 'marine',
    epithet: 'Beyaz Avcı',
    bounty: undefined,
    devilFruit: 'Moku Moku no Mi',
    description: 'Deniz Kuvvetleri Tümamirali. Luffy\'yi Loguetown\'dan beri takip eden adaletli denizci.',
    backstory: 'Smoker, Loguetown\'da görev yapan ilkeli bir Deniz Kuvvetleri subayıdır. Luffy\'nin idam platformundan kurtulduğuna tanık oldu ve onu takibe başladı. Arabasta\'da Hasır Şapkaların suçsuz olduğunu gördü ama resmi çizgiyi takip etmek zorunda kaldı. Punk Hazard\'da Law ve Luffy ile geçici ittifak kurdu. Vergo\'nun ihanetini keşfetti. Dressrosa sonrası Fujitora ile birlikte Shichibukai sistemini sorguladı. Kendi adaletini arayan bağımsız bir asker.',
    role: 'Luffy\'nin "değişen düşmanı" — adaleti sorgulayan denizci',
    age: '36',
    height: '209 cm',
    origin: 'Bilinmiyor',
    firstArc: 'loguetown',
    appearances: ['loguetown', 'arabasta', 'punk-hazard'],
    abilities: ['Moku Moku no Mi (Duman)', 'Busoshoku Haki', 'Nanashaku Jitte', 'Kenbunshoku Haki'],
  },
  {
    name: 'Koby',
    slug: 'koby',
    image: '/characters/koby.jpg',
    crew: 'marine',
    epithet: 'SWORD Üyesi',
    description: 'Deniz Kuvvetleri yükselen yıldızı. Luffy ile tanışarak hayatı değişen eski kaçak.',
    backstory: 'Koby, Alvida\'nın gemisinde kaçak olarak çalışan korkak bir çocuktu. Luffy ile tanışması hayatını değiştirdi. "Amiral olmak istiyorum!" — Luffy sayesinde rüyasını keşfetti. Garp\'ın eğitimi altında büyüdü. Marineford\'da savaşı durdurmak için Akainu\'nun karşısına çıktı. Water Seven\'da SWORD gizli birliğine katıldı. Amazon Lily\'de Blackbeard\'a karşı savaştı. Kenbunshoku Haki\'de üstün yetenek gösterdi.',
    role: 'Luffy\'nin Deniz Kuvvetleri\'ndeki paraleli — yeni neslin amiralı',
    age: '18',
    height: '167 cm',
    origin: 'Bilinmiyor, East Blue',
    firstArc: 'romance-dawn',
    appearances: ['romance-dawn', 'water-seven', 'marineford'],
    abilities: ['Rokushiki', 'Busoshoku Haki', 'Kenbunshoku Haki', 'Honesty Impact'],
  },
  {
    name: 'Monkey D. Garp',
    slug: 'garp',
    image: '/characters/garp.jpg',
    crew: 'marine',
    epithet: 'Deniz Kahramanı',
    description: 'Efsanevi Tümamiralı. Luffy\'nin dedesi. Gold Roger\'ı köşeye sıkıştıran adam.',
    backstory: 'Monkey D. Garp, Deniz Kuvvetleri tarihinin en güçlü savaşçılarından biridir. Roger ile defalarca savaşmış ve onu köşeye sıkıştırmıştır. Roger, ölmeden önce oğlu Ace\'i Garp\'a emanet etti. Garp, Ace\'i Dadan\'a bırakarak büyüttü — Luffy ve Sabo ile birlikte. Marineford\'da torunları Ace ve Luffy\'nin karşı tarafında savaşmak zorunda kaldı — bu onu yıktı. Ace\'in ölümü Garp\'ın en büyük pişmanlığıdır. SWORD\'un gizli destekçisi olduğu ortaya çıktı.',
    role: 'Aile ve görev arasında kalan efsanevi savaşçı',
    age: '78',
    height: '287 cm',
    origin: 'Goa Krallığı, East Blue',
    firstArc: 'water-seven',
    appearances: ['water-seven', 'post-enies-lobby', 'marineford', 'post-war'],
    abilities: ['Busoshoku Haki', 'Haoshoku Haki', 'Galaxy Impact', 'İnanılmaz Fiziksel Güç'],
  },
  {
    name: 'Sakazuki (Akainu)',
    slug: 'akainu',
    image: '/characters/akainu.jpg',
    crew: 'marine',
    epithet: 'Kırmızı Köpek',
    bounty: undefined,
    devilFruit: 'Magu Magu no Mi',
    description: 'Deniz Kuvvetleri Büyükamirali. "Mutlak Adalet" felsefesini benimser. Ace\'i öldüren kişi.',
    backstory: 'Sakazuki, "Mutlak Adalet" — suçlulara hiçbir merhamet göstermeme — felsefesiyle bilinen acımasız bir askerdir. Ohara\'nın Buster Call\'ında sivil gemisini vurdu. Marineford\'da Ace\'i öldürdü ve Luffy\'yi neredeyse öldürüyordu. Savaş sonrası Aokiji ile Büyükamiral koltuğu için 10 gün savaştı ve kazandı. Şimdi Deniz Kuvvetleri\'nin başındadır. Korsanlara ve suçlulara karşı sıfır tolerans politikası uygulamaktadır.',
    role: 'Serinin en acımasız antagonistlerinden biri — adalet ve tiranlık sınırı',
    age: '55',
    height: '306 cm',
    origin: 'North Blue',
    firstArc: 'marineford',
    appearances: ['marineford'],
    abilities: ['Magu Magu no Mi (Magma)', 'Busoshoku Haki', 'Kenbunshoku Haki', 'Magma Yumruk'],
  },
  {
    name: 'Kuzan (Aokiji)',
    slug: 'aokiji',
    image: '/characters/aokiji.jpg',
    crew: 'other',
    epithet: 'Mavi Sülün',
    bounty: undefined,
    devilFruit: 'Hie Hie no Mi',
    description: 'Eski Deniz Kuvvetleri Amirali. Akainu ile savaşıp kaybettikten sonra ayrıldı.',
    backstory: 'Kuzan, "Tembel Adalet" felsefesiyle tanınan bir Amiraldir. Ohara\'da küçük Robin\'in kaçmasına izin verdi. Long Ring Long Land\'da Hasır Şapkalarla karşılaştı ve gücünü gösterdi. Sengoku\'nun emriyle Büyükamiral adayıydı ama Akainu ile 10 günlük savaşta kaybetti. Deniz Kuvvetleri\'nden ayrıldı. Blackbeard ile birlikte çalıştığı görüldü ama asıl amacı belirsizdir. SWORD ile bağlantılı olabilir.',
    role: 'Gri alan karakter — ne tam dost ne tam düşman',
    age: '49',
    height: '298 cm',
    origin: 'Bilinmiyor',
    firstArc: 'long-ring-long-land',
    appearances: ['long-ring-long-land', 'marineford'],
    abilities: ['Hie Hie no Mi (Buz)', 'Busoshoku Haki', 'Kenbunshoku Haki', 'Ice Age'],
  },
  {
    name: 'Borsalino (Kizaru)',
    slug: 'kizaru',
    image: '/characters/kizaru.jpg',
    crew: 'marine',
    epithet: 'Sarı Maymun',
    bounty: undefined,
    devilFruit: 'Pika Pika no Mi',
    description: 'Deniz Kuvvetleri Amirali. Işık hızında hareket edebilen en hızlı savaşçılardan biri.',
    backstory: 'Borsalino, rahat ve alaycı tavırlarıyla bilinen güçlü bir Amiraldir. Sabaody\'de Supernova\'ları tek başına yendi. Marineford\'da savaştı. Egghead\'de eski arkadaşı Vegapunk\'ı öldürmek zorunda kaldı — bu görev onu derinden etkiledi. Luffy\'nin Gear 5\'i ile savaştığında, 2 yıl önceki güç farkının kapandığını gördü.',
    role: 'Güçlü ama duygusal çatışma yaşayan Amiral',
    age: '58',
    height: '302 cm',
    origin: 'Bilinmiyor',
    firstArc: 'sabaody-archipelago',
    appearances: ['sabaody-archipelago', 'marineford', 'egghead'],
    abilities: ['Pika Pika no Mi (Işık)', 'Busoshoku Haki', 'Kenbunshoku Haki', 'Işık Hızı Tekmeleri'],
  },
  // ─── Others ──────────────────────────────────────────────────────────
  {
    name: 'Yamato',
    slug: 'yamato',
    image: '/characters/yamato.jpg',
    crew: 'other',
    epithet: 'Wano\'nun Koruyucusu',
    bounty: undefined,
    devilFruit: 'Inu Inu no Mi, Model: Okuchi no Makami',
    description: 'Kaido\'nun kızı. Kozuki Oden\'e hayranlık duyar. Wano\'yu korumayı seçti.',
    backstory: 'Yamato, Kaido\'nun kızıdır ama babasından nefret eder. 8 yaşında Oden\'in idam günlüğünü buldu ve onun ruhunu benimsedi. Kendini "Kozuki Oden" olarak tanıtır. Kaido tarafından zincirlenip Onigashima\'da hapsedildi. Ace ile arkadaş olmuş ve Luffy\'nin maceralarını öğrenmiştir. Wano savaşında Kaido\'ya karşı savaştı. Mürettebata katılmak istedi ama sonunda Wano\'yu korumak için geride kaldı.',
    role: 'Wano\'nun koruyucusu — Oden\'in ruhsal mirasçısı',
    age: '28',
    height: '263 cm',
    origin: 'Onigashima, Wano',
    firstArc: 'wano',
    appearances: ['wano'],
    abilities: ['Inu Inu no Mi (Makami Formu)', 'Haoshoku Haki', 'Busoshoku Haki', 'Narikabura'],
  },
  {
    name: 'Carrot',
    slug: 'carrot',
    image: '/characters/carrot.jpg',
    crew: 'other',
    epithet: 'Garchu!',
    description: 'Zou\'dan gelen Mink kabilesi savaşçısı. Sulong formuna dönüşebilir.',
    backstory: 'Carrot, Zou\'da yaşayan tavşan Mink\'tir. Pedro\'nun öğrencisi olarak savaşçılık eğitimi almıştır. Zou\'dan gizlice Thousand Sunny\'ye binerek mürettebatla Whole Cake Island macerasına katıldı. Pedro\'nun fedakarlığı onu derinden etkiledi. Dolunayda Sulong formuna girerek Big Mom\'un filosunu tek başına dağıttı. Wano savaşına da katıldı. Savaş sonrası Pedro\'nun mirası olarak Zou\'nun yeni lideri oldu.',
    role: 'Mink savaşçısı ve geçici mürettebat yoldaşı',
    age: '15',
    height: '161 cm',
    origin: 'Zou',
    firstArc: 'zou',
    appearances: ['zou', 'whole-cake-island', 'wano'],
    abilities: ['Electro', 'Sulong Formu', 'Çeviklik', 'Mink Savaş Sanatları'],
  },
  {
    name: 'Vegapunk',
    slug: 'vegapunk',
    image: '/characters/vegapunk.jpg',
    crew: 'other',
    epithet: 'Dünyanın En Zeki İnsanı',
    bounty: undefined,
    description: 'Dünyanın en zeki bilim insanı. 6 uyduya ayrılmış deha.',
    backstory: 'Vegapunk, Karakuri Adası\'nda doğmuş bir dehadır. Nomi Nomi meyvesiyle sınırsız bilgi depolama yeteneği kazanmıştır. Judge, Caesar ve Queen ile birlikte MADS bilim grubunu kurdu. Dünya Hükümeti tarafından yakalanarak bilim danışmanı yapıldı. Pacifista\'ları, Seraphim\'leri, Sea Prism Stone silahlarını ve daha fazlasını icat etti. 6 uyduya bölünerek verimlilik artırdı. Void Century araştırmaları yüzünden Dünya Hükümeti tarafından ölüm emri verildi. Son mesajıyla dünyaya gerçeği anlatmaya çalıştı.',
    role: 'Egghead arcının merkez figürü — bilim ve gerçek arayışı',
    age: 'Bilinmiyor',
    height: 'Bilinmiyor',
    origin: 'Karakuri Adası, Grand Line',
    firstArc: 'egghead',
    appearances: ['egghead'],
    abilities: ['Nomi Nomi no Mi (Bilgi Depolama)', 'Üstün Zeka', 'Teknoloji İcatları', 'Uydu Sistemi'],
  },
]

export function getCharacterBySlug(slug: string): Character | undefined {
  return CHARACTERS.find((c) => c.slug === slug)
}

export function getCharactersByCrew(crew: string): Character[] {
  return CHARACTERS.filter((c) => c.crew === crew)
}

export const CREW_LABELS: Record<string, string> = {
  'straw-hat': 'Hasır Şapka',
  'marine': 'Deniz Kuvvetleri',
  'shichibukai': 'Yedi Savaş Lordu',
  'yonko': 'Dört İmparator',
  'revolutionary': 'Devrimci Ordu',
  'baroque-works': 'Baroque Works',
  'cp9': 'CP9',
  'supernova': 'En Kötü Nesil',
  'beast-pirates': 'Hayvan Korsanları',
  'big-mom-pirates': 'Big Mom Korsanları',
  'other': 'Diğer',
}
