import type { Crew } from '@/types'

export const CREW_TYPE_LABELS: Record<string, string> = {
  pirate: 'Korsan',
  marine: 'Deniz Kuvvetleri',
  government: 'Dünya Hükümeti',
  revolutionary: 'Devrimci',
  other: 'Diğer',
}

export const CREWS: Crew[] = [
  {
    name: 'Hasır Şapka Korsanları',
    slug: 'straw-hat-pirates',
    japaneseName: '麦わらの一味',
    type: 'pirate',
    captain: 'Monkey D. Luffy',
    captainSlug: 'luffy',
    status: 'active',
    description: 'Monkey D. Luffy tarafından kurulan ve Grand Line\'da efsaneleşen korsan mürettebatı. 10 üyeden oluşur ve her biri kendi alanında olağanüstü yeteneklidir.',
    history: 'East Blue\'da Romance Dawn ile başlayan macera, Grand Line\'ın her iki yarısını da kasıp kavurmuştur. Mürettebat, Dünya Hükümeti\'ne savaş ilan etmiş, iki Yonko\'yu devirmiş ve Luffy "Beşinci İmparator" ilan edilmiştir. Her üye bir rüyanın peşindedir ve Korsanlar Kralı\'nın mürettebatı olmayı hedefler.',
    totalBounty: '8,816,001,000',
    notableMembers: [
      { name: 'Monkey D. Luffy', slug: 'luffy', role: 'Kaptan' },
      { name: 'Roronoa Zoro', slug: 'zoro', role: 'Savaşçı / Yan Kaptan' },
      { name: 'Nami', slug: 'nami', role: 'Navigatör' },
      { name: 'Usopp', slug: 'usopp', role: 'Nişancı' },
      { name: 'Sanji', slug: 'sanji', role: 'Aşçı' },
      { name: 'Tony Tony Chopper', slug: 'chopper', role: 'Doktor' },
      { name: 'Nico Robin', slug: 'robin', role: 'Arkeolog' },
      { name: 'Franky', slug: 'franky', role: 'Gemi Ustası' },
      { name: 'Brook', slug: 'brook', role: 'Müzisyen' },
      { name: 'Jinbe', slug: 'jinbe', role: 'Dümenci' },
    ],
    achievements: [
      'East Blue\'nun en güçlü korsanlarını yenme',
      'Crocodile ve Baroque Works\'ü devirme',
      'Enies Lobby\'de Dünya Hükümeti bayrağını yakma',
      'Doflamingo\'yu Dressrosa\'da devirme',
      'Big Mom ve Kaido\'yu yenme (Wano)',
      'Hasır Şapka Büyük Filosu\'nun kurulması (5.640+ üye)',
    ],
    jollyRoger: 'Hasır şapka takan kafatası',
    color: 'text-gold',
    bg: 'bg-gold/10',
  },
  {
    name: 'Kızıl Saçlı Korsanları',
    slug: 'red-hair-pirates',
    japaneseName: '赤髪海賊団',
    type: 'pirate',
    captain: 'Shanks',
    captainSlug: 'shanks',
    status: 'active',
    description: 'Dört İmparator\'dan biri olan Shanks\'ın mürettebatı. Şeytan Meyvesi kullanmayan, tamamen Haki ve fiziksel güce dayanan nadir bir Yonko mürettebatı.',
    history: 'Shanks, Gol D. Roger\'ın mürettebatında kabin çocuğu olarak başladı. Roger\'ın idamından sonra kendi mürettebatını kurdu ve Dört İmparator\'lardan biri haline geldi. Luffy\'ye hasır şapkasını vererek büyük korsan çağının yeni neslini ilham etti.',
    notableMembers: [
      { name: 'Shanks', slug: 'shanks', role: 'Kaptan' },
      { name: 'Benn Beckman', role: 'Yan Kaptan' },
      { name: 'Lucky Roux', role: 'Savaşçı' },
      { name: 'Yasopp', role: 'Nişancı (Usopp\'un babası)' },
    ],
    achievements: [
      'Marineford Savaşı\'nı tek başına durdurma',
      'Kaido\'nun Marineford\'a gelmesini engelleme',
      'En dengeli Yonko mürettebatı olma',
    ],
    jollyRoger: 'İki kılıçlı kafatası',
    color: 'text-luffy',
    bg: 'bg-luffy/10',
  },
  {
    name: 'Beyaz Sakal Korsanları',
    slug: 'whitebeard-pirates',
    japaneseName: '白ひげ海賊団',
    type: 'pirate',
    captain: 'Edward Newgate / Whitebeard',
    captainSlug: 'whitebeard',
    status: 'disbanded',
    description: '"Dünyanın En Güçlü Adamı" Edward Newgate\'in mürettebatı. 16 komutan ve 43 müttefik mürettebattan oluşan devasa bir güçtü.',
    history: 'Whitebeard, Rocks Korsanları\'nın dağılmasından sonra kendi mürettebatını kurdu. Mürettebatını "ailesi" olarak gördü — Korsanlar Kralı olmak yerine aile istedi. Marineford Savaşı\'nda Ace\'i kurtarmaya çalışırken hayatını kaybetti. Son sözleri: "One Piece... gerçek!"',
    totalBounty: '~20,000,000,000+ (tahmini)',
    territory: ['Sphinx', 'Fish-Man Island (eski)'],
    notableMembers: [
      { name: 'Edward Newgate', slug: 'whitebeard', role: '1. Komutan (Kaptan)' },
      { name: 'Marco', role: '1. Bölük Komutanı (Anka Kuşu)' },
      { name: 'Portgas D. Ace', slug: 'ace', role: '2. Bölük Komutanı' },
      { name: 'Jozu', role: '3. Bölük Komutanı (Elmas Adam)' },
      { name: 'Thatch', role: '4. Bölük Komutanı (Teach tarafından öldürüldü)' },
      { name: 'Vista', role: '5. Bölük Komutanı (Çiçek Kılıcı)' },
    ],
    achievements: [
      'Dünyanın en güçlü korsan mürettebatı unvanı',
      'Fish-Man Island\'ı koruma altına alma',
      'Roger\'ın en büyük rakibi olma',
      'Marineford\'u yerle bir etme (son savaş)',
    ],
    jollyRoger: 'Hilal bıyıklı kafatası üzerinde haç işareti',
    color: 'text-pirate-text',
    bg: 'bg-pirate-text/10',
  },
  {
    name: 'Blackbeard Korsanları',
    slug: 'blackbeard-pirates',
    japaneseName: '黒ひげ海賊団',
    type: 'pirate',
    captain: 'Marshall D. Teach / Blackbeard',
    captainSlug: 'blackbeard',
    status: 'active',
    description: 'Tarihte iki Şeytan Meyvesi gücünü aynı anda taşıyan tek kişi olan Blackbeard\'ın mürettebatı. Fırsatçı ve acımasız bir yapıya sahip.',
    history: 'Teach, Whitebeard Korsanları\'nda gizlice Yami Yami meyvesini bekledi. Thatch\'i öldürüp meyveyi çaldıktan sonra kendi mürettebatını kurdu. Ace\'i yakalayarak Marineford Savaşı\'nı tetikledi. Whitebeard\'ın ölümünden sonra Gura Gura meyvesini de çaldı — iki meyve gücüne sahip tek kişi oldu.',
    territory: ['Hachinosu (Korsan Adası)', 'Eski Whitebeard toprakları'],
    notableMembers: [
      { name: 'Marshall D. Teach', slug: 'blackbeard', role: 'Kaptan / Amiral' },
      { name: 'Shiryu', role: 'Kılıç Ustası (eski Impel Down müdür yardımcısı)' },
      { name: 'Kuzan / Aokiji', slug: 'aokiji', role: '10. Kaptan (eski Amiral)' },
      { name: 'Jesus Burgess', role: 'Güreş Şampiyonu' },
      { name: 'Van Augur', role: 'Nişancı' },
      { name: 'Doc Q', role: 'Doktor' },
    ],
    achievements: [
      'İki Şeytan Meyvesi gücüne sahip olma (benzersiz)',
      'Whitebeard\'ı öldürme',
      'Yonko statüsüne yükselme',
      'Impel Down Level 6 mahkumlarını serbest bırakma',
    ],
    jollyRoger: 'Üç kafataslı korsan bayrağı',
    color: 'text-purple-400',
    bg: 'bg-purple-500/10',
  },
  {
    name: 'Big Mom Korsanları',
    slug: 'big-mom-pirates',
    japaneseName: 'ビッグ・マム海賊団',
    type: 'pirate',
    captain: 'Charlotte Linlin / Big Mom',
    captainSlug: 'bigmom',
    status: 'defeated',
    description: 'Charlotte Linlin (Big Mom) tarafından yönetilen ve Totto Land\'ı kontrol eden devasa mürettebat. Big Mom\'un 85 çocuğu mürettebatın çekirdeğini oluşturur.',
    history: 'Big Mom, 5 yaşında Elbaf\'ta Haoshoku Haki\'yi kullanarak kaos yarattı. Mother Carmel\'in gizemli kayboluşundan sonra kendi mürettebatını kurdu ve Totto Land\'ı inşa etti — tüm ırkların bir arada yaşadığı bir ütopya (aslında distopya). Wano\'da Law ve Kid tarafından yenildi.',
    territory: ['Totto Land (35 ada)'],
    notableMembers: [
      { name: 'Charlotte Linlin', slug: 'bigmom', role: 'Kaptan' },
      { name: 'Charlotte Katakuri', role: 'Tatlı Komutan (En güçlü oğul)' },
      { name: 'Charlotte Smoothie', role: 'Tatlı Komutan' },
      { name: 'Charlotte Cracker', role: 'Tatlı Komutan' },
      { name: 'Charlotte Perospero', role: 'Büyük Oğul' },
      { name: 'Charlotte Pudding', role: 'Üç Gözlü (Sanji\'nin nişanlısı)' },
    ],
    achievements: [
      'Totto Land\'ı inşa etme (35 adalık ülke)',
      'Tüm ırkları bir araya getirme girişimi',
      'Road Poneglyph\'lerden birine sahip olma',
    ],
    jollyRoger: 'Şapkalı kafatası, çapraz kemikler yerine lolipop',
    color: 'text-pink-400',
    bg: 'bg-pink-500/10',
  },
  {
    name: 'Beast Korsanları',
    slug: 'beast-pirates',
    japaneseName: '百獣海賊団',
    type: 'pirate',
    captain: 'Kaido',
    captainSlug: 'kaido',
    status: 'defeated',
    description: '"Canlılar Arasında En Güçlü Yaratık" Kaido\'nun mürettebatı. Zoan tipi Şeytan Meyvesi kullanıcılarından oluşan devasa bir ordu. Yapay SMILE meyveleri ile güçlendirilmiş askerler.',
    history: 'Kaido, Rocks Korsanları\'nın dağılmasından sonra kendi mürettebatını kurdu. 20 yıl önce Wano\'yu işgal etti ve Kozuki Oden\'i idam etti. SMILE fabrikası ile yapay Zoan ordusu oluşturdu. Onigashima Savaşı\'nda Luffy\'nin Gear 5\'i tarafından yenildi.',
    territory: ['Wano Kuni (eski)', 'Onigashima'],
    notableMembers: [
      { name: 'Kaido', slug: 'kaido', role: 'Kaptan (En Güçlü Yaratık)' },
      { name: 'King', role: 'All-Star (Lunarian)' },
      { name: 'Queen', role: 'All-Star (Bilim Adamı)' },
      { name: 'Jack', role: 'All-Star (Mamut)' },
      { name: 'Tobi Roppo (6 kişi)', role: 'Seçkin Savaşçılar' },
    ],
    achievements: [
      'Wano\'yu 20 yıl boyunca kontrol etme',
      'SMILE üretimi ile yapay Zoan ordusu',
      'Dünyanın en büyük savaş gücünü oluşturma',
    ],
    jollyRoger: 'Boynuzlu kafatası, çapraz kemikler',
    color: 'text-emerald-400',
    bg: 'bg-emerald-500/10',
  },
  {
    name: 'Roger Korsanları',
    slug: 'roger-pirates',
    japaneseName: 'ロジャー海賊団',
    type: 'pirate',
    captain: 'Gol D. Roger',
    status: 'disbanded',
    description: 'Grand Line\'ı fetheden ve Laugh Tale\'e ulaşan tek mürettebat. Korsanlar Kralı Gol D. Roger\'ın efsanevi mürettebatı.',
    history: 'Roger, ölümcül bir hastalığa yakalanmadan önce Grand Line\'ın sonuna ulaşmayı başardı. Dört Road Poneglyph\'i takip ederek Laugh Tale\'e vardı ve One Piece\'i buldu — ki bu onu o kadar güldürdü ki adaya "Laugh Tale" adını verdi. Roger, kendini Deniz Kuvvetleri\'ne teslim etti ve idam edildi. Son sözleri Büyük Korsan Çağı\'nı başlattı.',
    notableMembers: [
      { name: 'Gol D. Roger', role: 'Kaptan (Korsanlar Kralı)' },
      { name: 'Silvers Rayleigh', role: 'Yan Kaptan (Karanlık Kral)' },
      { name: 'Scopper Gaban', role: 'Savaşçı' },
      { name: 'Shanks', slug: 'shanks', role: 'Kabin Çocuğu' },
      { name: 'Buggy', slug: 'buggy', role: 'Kabin Çocuğu' },
      { name: 'Kozuki Oden', role: 'Geçici Üye (Wano\'dan)' },
      { name: 'Crocus', role: 'Doktor' },
    ],
    achievements: [
      'Grand Line\'ı fetheden ve Laugh Tale\'e ulaşan tek mürettebat',
      'One Piece\'i bulan tek mürettebat',
      'Void Century\'nin sırlarını öğrenen tek mürettebat',
      'Büyük Korsan Çağı\'nı başlatma (Roger\'ın idamı)',
    ],
    jollyRoger: 'Bıyıklı kafatası',
    color: 'text-gold-bright',
    bg: 'bg-gold-bright/10',
  },
  {
    name: 'Deniz Kuvvetleri',
    slug: 'marines',
    japaneseName: '海軍',
    type: 'marine',
    status: 'active',
    description: 'Dünya Hükümeti\'nin deniz askeri gücü. Adaleti ve düzeni sağlamakla görevli dünyanın en büyük askeri organizasyonu. Üç Amiral, bir Büyük Amiral ve binlerce asker.',
    history: 'Deniz Kuvvetleri, Dünya Hükümeti\'nin kurulmasıyla birlikte oluşturuldu. Korsanlara, devrimcilere ve diğer tehditlere karşı savaşır. Ancak "adalet" anlayışı tartışmalıdır — Absolute Justice (Mutlak Adalet) taraftarları sivilleri bile feda edebilir.',
    notableMembers: [
      { name: 'Sakazuki / Akainu', slug: 'akainu', role: 'Büyük Amiral (Fleet Admiral)' },
      { name: 'Borsalino / Kizaru', slug: 'kizaru', role: 'Amiral' },
      { name: 'Fujitora / Issho', role: 'Amiral' },
      { name: 'Ryokugyu / Aramaki', role: 'Amiral' },
      { name: 'Monkey D. Garp', slug: 'garp', role: 'Tümamiral (Kahraman)' },
      { name: 'Smoker', slug: 'smoker', role: 'Tümamiral' },
      { name: 'Koby', slug: 'koby', role: 'Albay' },
      { name: 'Sengoku', role: 'Eski Büyük Amiral (Müfettiş Genel)' },
    ],
    achievements: [
      'Marineford Savaşı (Whitebeard\'a karşı)',
      'Büyük Korsan Çağı boyunca düzeni koruma girişimi',
      'SSG (Özel Bilim Grubu) ile Shichibukai\'yi değiştirme',
    ],
    color: 'text-sea',
    bg: 'bg-sea/10',
  },
  {
    name: 'Devrimci Ordu',
    slug: 'revolutionary-army',
    japaneseName: '革命軍',
    type: 'revolutionary',
    captain: 'Monkey D. Dragon',
    status: 'active',
    description: 'Dünya Hükümeti\'ni devirmek için savaşan gizli ordu. Monkey D. Dragon (Luffy\'nin babası) tarafından yönetilir. Dünyanın en aranan adamı.',
    history: 'Dragon, Dünya Hükümeti\'nin zulmüne karşı Devrimci Ordu\'yu kurdu. Dünya genelinde hücreleri ve ajanları var. Sabo, Portgas D. Ace\'in ölümünden sonra 2. Komutan olarak yükseldi. Reverie\'de Celestial Dragon\'lara karşı operasyon düzenledi.',
    notableMembers: [
      { name: 'Monkey D. Dragon', role: 'Lider (Dünyanın En Aranan Adamı)' },
      { name: 'Sabo', slug: 'sabo', role: 'Genelkurmay Başkanı / 2. Komutan' },
      { name: 'Emporio Ivankov', role: 'Grand Line Ordu Komutanı' },
      { name: 'Bartholomew Kuma', slug: 'kuma', role: 'Eski Şichibukai, Devrimci casusu' },
      { name: 'Koala', role: 'Balık-Adam Karatesi uzmanı' },
    ],
    achievements: [
      'Dünya genelinde 8+ ülkede devrim gerçekleştirme',
      'Reverie\'de Celestial Dragon\'lara operasyon',
      'Kuma\'nın kurtarılması',
    ],
    color: 'text-green-400',
    bg: 'bg-green-500/10',
  },
  {
    name: 'Shichibukai (Yedi Savaş Lordu)',
    slug: 'shichibukai',
    japaneseName: '王下七武海',
    type: 'government',
    status: 'disbanded',
    description: 'Dünya Hükümeti tarafından tanınan yedi güçlü korsan. Deniz Kuvvetleri ile işbirliği karşılığında serbestçe korsanlık yapabilirler. Reverie kararıyla sistem kaldırıldı.',
    history: 'Shichibukai sistemi, korsanlar arasında denge sağlamak için kuruldu. Yonko, Deniz Kuvvetleri ve Shichibukai — bu üç güç dünya dengesini koruyordu. Ancak üyelerin çoğu güvenilmez çıkınca ve Fujitora\'nın girişimleriyle Reverie\'de sistem kaldırıldı.',
    notableMembers: [
      { name: 'Dracule Mihawk', slug: 'mihawk', role: 'Dünyanın En İyi Kılıç Ustası' },
      { name: 'Boa Hancock', slug: 'hancock', role: 'Korsan İmparatoriçesi' },
      { name: 'Donquixote Doflamingo', slug: 'doflamingo', role: 'Joker (eski)' },
      { name: 'Bartholomew Kuma', slug: 'kuma', role: 'Tiranı (Devrimci casusu)' },
      { name: 'Sir Crocodile', slug: 'crocodile', role: 'Mr. 0 (eski)' },
      { name: 'Gecko Moria', role: 'Gölge Lordu (eski)' },
      { name: 'Jinbe', slug: 'jinbe', role: 'İlk Son (eski)' },
      { name: 'Trafalgar Law', slug: 'law', role: 'Ölümün Cerrahı' },
      { name: 'Buggy', slug: 'buggy', role: 'Palyaço (şans eseri)' },
      { name: 'Edward Weevil', role: 'Whitebeard Jr. (iddia)' },
    ],
    achievements: [
      'Dünya dengesinin üç sütunundan biri olma',
      'Marineford Savaşı\'nda kritik rol',
    ],
    color: 'text-amber-400',
    bg: 'bg-amber-500/10',
  },
  {
    name: 'Cross Guild',
    slug: 'cross-guild',
    japaneseName: 'クロスギルド',
    type: 'pirate',
    captain: 'Buggy (görünürde)',
    captainSlug: 'buggy',
    status: 'active',
    description: 'Mihawk ve Crocodile tarafından kurulan, ancak Buggy\'nin şans eseri lider olarak görüldüğü organizasyon. Deniz Kuvvetleri\'ne ödül koyan ilk organizasyon!',
    history: 'Shichibukai sistemi kaldırıldıktan sonra Mihawk ve Crocodile güçlerini birleştirdi. Buggy\'nin ünü ve şanssızlığı sayesinde dünya, Buggy\'yi lider olarak gördü. Cross Guild, Deniz Kuvvetleri üyelerine ödül koyarak dünyayı şok etti.',
    notableMembers: [
      { name: 'Buggy', slug: 'buggy', role: 'Başkan (görünürde)' },
      { name: 'Dracule Mihawk', slug: 'mihawk', role: 'Gerçek güç (kılıç)' },
      { name: 'Sir Crocodile', slug: 'crocodile', role: 'Gerçek güç (strateji)' },
    ],
    achievements: [
      'Deniz Kuvvetleri\'ne ödül koyan ilk organizasyon',
      'Buggy\'nin Yonko ilan edilmesine yol açma',
    ],
    color: 'text-gold',
    bg: 'bg-gold/10',
  },
  {
    name: 'CP0 / CP9',
    slug: 'cipher-pol',
    japaneseName: 'サイファーポール',
    type: 'government',
    status: 'active',
    description: 'Dünya Hükümeti\'nin gizli istihbarat ve suikast birimleri. CP1-CP8 normal istihbarat, CP9 gizli suikast birimi, CP0 ise doğrudan Celestial Dragon\'lara bağlı en güçlü birim.',
    history: 'CP9, Enies Lobby olayında Hasır Şapkalar tarafından yenildi. CP0 ise daha sonra ortaya çıktı ve doğrudan Gorosei\'nin emirlerini yerine getirir. Egghead olayında kritik rol oynadılar.',
    notableMembers: [
      { name: 'Rob Lucci', role: 'CP0 Ajanı (eski CP9 en güçlü üyesi)' },
      { name: 'Kaku', role: 'CP0 Ajanı (eski CP9)' },
      { name: 'Spandam', role: 'CP0 Ajanı (eski CP9 şefi)' },
      { name: 'Stussy', role: 'CP0 Ajanı (MADS klonu)' },
    ],
    achievements: [
      'Enies Lobby\'de Robin\'i yakalama (başarısız)',
      'Rokushiki savaş tekniklerinin ustası',
      'Dünya Hükümeti\'nin en gizli operasyonları',
    ],
    color: 'text-slate-400',
    bg: 'bg-slate-500/10',
  },
]

export function getCrewBySlug(slug: string): Crew | undefined {
  return CREWS.find((c) => c.slug === slug)
}

export function getCrewsByType(type: string): Crew[] {
  return CREWS.filter((c) => c.type === type)
}
