export type DevilFruitEntry = {
  name: string
  slug: string
  japaneseName: string
  type: 'Paramecia' | 'Zoan' | 'Logia' | 'Mythical Zoan' | 'Ancient Zoan' | 'Special Paramecia'
  meaning: string
  description: string
  abilities: string[]
  weakness?: string
  awakening?: string
  user: string
  userSlug?: string // links to character page
  status: 'active' | 'deceased' | 'unknown'
  firstAppearance: string
  image?: string
}

export const DEVIL_FRUIT_TYPE_INFO: Record<string, { label: string; description: string; color: string; bg: string }> = {
  'Paramecia': {
    label: 'Paramecia',
    description: 'Kullanıcıya vücut yapısını değiştirme, madde üretme veya çevreyi manipüle etme gibi çeşitli süper güçler veren meyveler. En yaygın Şeytan Meyvesi türüdür.',
    color: 'text-purple-400',
    bg: 'bg-purple-500/15',
  },
  'Zoan': {
    label: 'Zoan',
    description: 'Kullanıcının bir hayvana dönüşmesini sağlayan meyveler. Üç form sunar: insan formu, hayvan formu ve hibrit form. Fiziksel güç ve dayanıklılığı artırır.',
    color: 'text-green-400',
    bg: 'bg-green-500/15',
  },
  'Logia': {
    label: 'Logia',
    description: 'Kullanıcının vücudunu bir doğa elementine dönüştürmesini sağlayan en nadir ve güçlü Şeytan Meyvesi türü. Fiziksel saldırılar vücuttan geçer.',
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/15',
  },
  'Mythical Zoan': {
    label: 'Efsanevi Zoan',
    description: 'Efsanevi yaratıklara dönüşüm sağlayan ultra nadir Zoan alt türü. Logia\'dan bile nadir olan bu meyveler, dönüşümün yanı sıra özel güçler de verir.',
    color: 'text-amber-300',
    bg: 'bg-amber-500/15',
  },
  'Ancient Zoan': {
    label: 'Kadim Zoan',
    description: 'Nesli tükenmiş hayvanatlara dönüşüm sağlayan nadir Zoan alt türü. Olağanüstü dayanıklılık ve fiziksel güç sunar.',
    color: 'text-emerald-400',
    bg: 'bg-emerald-500/15',
  },
  'Special Paramecia': {
    label: 'Özel Paramecia',
    description: 'Logia benzeri özellikler gösteren nadir Paramecia alt türü. Vücut elementel bir maddeye dönüşebilir.',
    color: 'text-pink-400',
    bg: 'bg-pink-500/15',
  },
}

export const DEVIL_FRUITS: DevilFruitEntry[] = [
  // ─── PARAMECIA ────────────────────────────────────────────────────────
  {
    name: 'Gomu Gomu no Mi / Hito Hito no Mi, Model: Nika',
    slug: 'gomu-gomu',
    japaneseName: 'ゴムゴムの実 / ヒトヒトの実 モデル:ニカ',
    type: 'Mythical Zoan',
    meaning: 'Lastik / İnsan-İnsan Meyvesi, Model: Nika',
    description: 'Dünya Hükümeti tarafından "Gomu Gomu no Mi" olarak gizlenen bu meyve aslında Hito Hito no Mi, Model: Nika — Güneş Tanrısı Nika\'nın gücünü veren efsanevi Zoan meyvesidir. Kullanıcının vücuduna lastik özellikleri kazandırır ve uyanış formu olan Gear 5\'te hayal gücüyle sınırsız dönüşüm sağlar.',
    abilities: [
      'Vücudu lastik gibi uzar, esneklik ve şok emilimi sağlar',
      'Elektrik saldırılarına karşı bağışıklık',
      'Gear 2: Kan dolaşımını hızlandırarak süper hız',
      'Gear 3: Kemiklere hava pompalayarak dev uzuvlar',
      'Gear 4: Kasları Haki ile güçlendirme (Boundman, Snakeman, Tankman)',
      'Gear 5 (Uyanış): Çevreyi ve vücudu hayal gücüyle şekillendirme, çizgi film fiziği',
    ],
    weakness: 'Kesici saldırılara karşı lastik koruması yoktur',
    awakening: 'Gear 5 — Güneş Tanrısı Nika formu. Çevresindeki nesneleri de lastik yapabilir, fizik kurallarını büker.',
    user: 'Monkey D. Luffy',
    userSlug: 'luffy',
    status: 'active',
    firstAppearance: 'Romance Dawn',
  },
  {
    name: 'Bara Bara no Mi',
    slug: 'bara-bara',
    japaneseName: 'バラバラの実',
    type: 'Paramecia',
    meaning: 'Parçala-Parçala Meyvesi',
    description: 'Kullanıcının vücudunu parçalara ayırmasını ve bu parçaları havada kontrol etmesini sağlar. Kesici saldırılara karşı tam bağışıklık verir.',
    abilities: [
      'Vücudu parçalara ayırma ve uzaktan kontrol',
      'Kesici saldırılara tam bağışıklık',
      'Parçalar havada serbestçe uçabilir',
      'Ayaklar yere bağlı kalmalıdır (uyanış öncesi)',
    ],
    user: 'Buggy',
    userSlug: 'buggy',
    status: 'active',
    firstAppearance: 'Orange Town',
  },
  {
    name: 'Suna Suna no Mi',
    slug: 'suna-suna',
    japaneseName: 'スナスナの実',
    type: 'Logia',
    meaning: 'Kum-Kum Meyvesi',
    description: 'Kullanıcının vücudunu kuma dönüştürmesini, kum üretmesini ve kontrol etmesini sağlayan Logia tipi meyve. Dokunduğu her şeyin nemini emebilir.',
    abilities: [
      'Vücudu kuma dönüştürme ve fiziksel saldırılara bağışıklık',
      'Kum fırtınaları ve kum bıçaklar üretme',
      'Dokunduğu canlıların ve nesnelerin nemini emme',
      'Ground Death: Çevresindeki her şeyi kurutma',
      'Sables: Devasa kum hortumları yaratma',
    ],
    weakness: 'Su temasında katılaşır ve vurulamaz hale gelir',
    user: 'Sir Crocodile',
    userSlug: 'crocodile',
    status: 'active',
    firstAppearance: 'Alabasta',
  },
  {
    name: 'Mera Mera no Mi',
    slug: 'mera-mera',
    japaneseName: 'メラメラの実',
    type: 'Logia',
    meaning: 'Alev-Alev Meyvesi',
    description: 'Kullanıcının vücudunu ateşe dönüştürmesini ve ateş üretip kontrol etmesini sağlayan Logia tipi meyve. Portgas D. Ace\'in ölümünden sonra Sabo tarafından yenildi.',
    abilities: [
      'Vücudu ateşe dönüştürme',
      'Devasa ateş topları ve ateş duvarları oluşturma',
      'Hiken (Ateş Yumruğu): İmza saldırısı',
      'Entei: Devasa ateş sütunu',
      'Fiziksel saldırılara bağışıklık',
    ],
    weakness: 'Magu Magu no Mi (magma) karşısında güçsüz — magma ateşi yakar',
    user: 'Sabo (eski: Portgas D. Ace)',
    userSlug: 'sabo',
    status: 'active',
    firstAppearance: 'Arabasta',
  },
  {
    name: 'Goro Goro no Mi',
    slug: 'goro-goro',
    japaneseName: 'ゴロゴロの実',
    type: 'Logia',
    meaning: 'Gürültü-Gürültü Meyvesi (Yıldırım)',
    description: 'En güçlü Logia meyvelerinden biri. Kullanıcının vücudunu yıldırıma dönüştürmesini sağlar. 200 milyon volt elektrik üretebilir. Luffy\'nin lastik vücudu nedeniyle etkisizdi.',
    abilities: [
      'Vücudu yıldırıma dönüştürme',
      '200 milyon volt elektrik üretme',
      'Işık hızına yakın hareket',
      'El Tor: Yıldırım sütunu saldırısı',
      'Raigo: Devasa elektrik küre (ada yıkıcı güç)',
      'Kenbunshoku Haki\'yi güçlendirerek geniş alan taraması',
    ],
    weakness: 'Lastik (yalıtkan) maddelere karşı etkisiz',
    user: 'Enel',
    userSlug: 'enel',
    status: 'active',
    firstAppearance: 'Skypiea',
  },
  {
    name: 'Hana Hana no Mi',
    slug: 'hana-hana',
    japaneseName: 'ハナハナの実',
    type: 'Paramecia',
    meaning: 'Çiçek-Çiçek Meyvesi',
    description: 'Kullanıcının vücudunun herhangi bir parçasını (kol, bacak, göz, kulak) herhangi bir yüzeyde çoğaltmasını sağlar. Casusluk ve savaşta son derece çok yönlü.',
    abilities: [
      'Vücut parçalarını herhangi bir yüzeyde çoğaltma',
      'Clutch: Düşmanın kemiklerini kırma tekniği',
      'Gigantesco Mano: Dev boyutlu uzuvlar oluşturma',
      'Casusluk için göz ve kulak çoğaltma',
      'Demonio Fleur: Dev şeytan formu (uyanış)',
    ],
    awakening: 'Demonio Fleur — Dev şeytan formu oluşturarak muazzam fiziksel güç kazanır.',
    user: 'Nico Robin',
    userSlug: 'robin',
    status: 'active',
    firstAppearance: 'Arabasta',
  },
  {
    name: 'Ope Ope no Mi',
    slug: 'ope-ope',
    japaneseName: 'オペオペの実',
    type: 'Paramecia',
    meaning: 'Operasyon-Operasyon Meyvesi',
    description: 'En değerli Şeytan Meyvesi olarak bilinen "Nihai Meyve". Kullanıcı bir ameliyat odası (ROOM) oluşturarak içindeki her şeyi kontrol edebilir. Ölümsüzlük operasyonu yapabilir.',
    abilities: [
      'ROOM: Kontrol alanı oluşturma',
      'Shambles: Alandaki nesnelerin ve kişilerin yerini değiştirme',
      'Mes: Kalpleri vücuttan çıkarma',
      'Takt: Nesneleri telekinetik kontrol',
      'Gamma Knife: İç organları tahrip eden enerji bıçağı',
      'Kroom: Haki ile güçlendirilmiş dev kılıç (uyanış)',
      'Ölümsüzlük Operasyonu: Kullanıcının hayatı pahasına hedefi ölümsüz yapma',
    ],
    awakening: 'KROOM — Silahına ROOM kaplama yaparak iç hasarı artırır. Shock Wille ile şok dalgası.',
    user: 'Trafalgar D. Water Law',
    userSlug: 'law',
    status: 'active',
    firstAppearance: 'Sabaody Archipelago',
  },
  {
    name: 'Mochi Mochi no Mi',
    slug: 'mochi-mochi',
    japaneseName: 'モチモチの実',
    type: 'Special Paramecia',
    meaning: 'Mochi-Mochi Meyvesi',
    description: 'Özel Paramecia türü — Logia benzeri özelliklerle vücudu mochiye dönüştürme yeteneği verir. Kullanıcı mochi üretebilir, kontrol edebilir ve vücudunu mochiye çevirebilir.',
    abilities: [
      'Vücudu mochiye dönüştürme (Logia benzeri)',
      'Mochi üretme ve şekillendirme',
      'Buzz Cut Mochi: Mochi donut saldırısı',
      'Mochi kollarla çoklu yumruk (Power Mochi)',
      'Unstoppable Donuts: Uçan mochi donutlar',
    ],
    awakening: 'Çevresini mochiye dönüştürebilir ve mochi miktarını artırır.',
    user: 'Charlotte Katakuri',
    status: 'active',
    firstAppearance: 'Whole Cake Island',
  },
  {
    name: 'Gura Gura no Mi',
    slug: 'gura-gura',
    japaneseName: 'グラグラの実',
    type: 'Paramecia',
    meaning: 'Deprem-Deprem Meyvesi',
    description: 'Dünyanın en güçlü Paramecia meyvesi. Depremler yaratma, deniz tsunamileri oluşturma ve havayı kırma yeteneği verir. Whitebeard\'ın ölümünden sonra Blackbeard tarafından çalındı.',
    abilities: [
      'Depremler ve sismik dalgalar oluşturma',
      'Tsunamiler yaratma',
      'Havayı "kırma" — titreşim darbesiyle uzak mesafeli saldırı',
      'Dünyayı yıkma potansiyeli olan güç',
      'Kaiserhou: Deprem yumruğu',
    ],
    user: 'Marshall D. Teach / Blackbeard (eski: Edward Newgate / Whitebeard)',
    userSlug: 'blackbeard',
    status: 'active',
    firstAppearance: 'Marineford',
  },
  {
    name: 'Yami Yami no Mi',
    slug: 'yami-yami',
    japaneseName: 'ヤミヤミの実',
    type: 'Logia',
    meaning: 'Karanlık-Karanlık Meyvesi',
    description: 'En benzersiz Logia meyvesi. Karanlık ve yerçekimi kontrolü sağlar. Diğer Şeytan Meyvesi güçlerini geçici olarak devre dışı bırakabilir. Ancak Logia olmasına rağmen saldırılardan kaçınamaz — aksine acıyı çeker.',
    abilities: [
      'Karanlık ve yerçekimi kontrolü',
      'Black Hole: Her şeyi yutan karanlık vorteks',
      'Liberation: Yutulan şeyleri geri fırlatma',
      'Diğer Şeytan Meyvesi güçlerini dokunarak devre dışı bırakma',
      'Diğer ölü kullanıcıların meyvelerini çalabilme (benzersiz)',
      'Acıyı çekmesi — Logia bağışıklığı yok',
    ],
    weakness: 'Diğer Logiaların aksine fiziksel saldırılardan kaçınamaz, acıyı emip artırır',
    user: 'Marshall D. Teach / Blackbeard',
    userSlug: 'blackbeard',
    status: 'active',
    firstAppearance: 'Jaya',
  },
  {
    name: 'Nikyu Nikyu no Mi',
    slug: 'nikyu-nikyu',
    japaneseName: 'ニキュニキュの実',
    type: 'Paramecia',
    meaning: 'Pati-Pati Meyvesi',
    description: 'Kullanıcının avuç içlerine pençe yastıkları oluşturarak her şeyi "itme" yeteneği verir. Havayı, acıyı, yorgunluğu bile itebilir. İnsanları dünyanın bir ucundan diğerine gönderebilir.',
    abilities: [
      'Her şeyi (nesne, hava, acı, yorgunluk) itebilme',
      'Pad Ho: Hava basıncı saldırısı',
      'Ursus Shock: Sıkıştırılmış hava bombası',
      'İnsanları uzak mesafelere fırlatma (3 gün 3 gece uçuş)',
      'Acı ve yorgunluğu vücuttan çıkarma',
    ],
    user: 'Bartholomew Kuma',
    userSlug: 'kuma',
    status: 'active',
    firstAppearance: 'Thriller Bark',
  },
  {
    name: 'Doku Doku no Mi',
    slug: 'doku-doku',
    japaneseName: 'ドクドクの実',
    type: 'Paramecia',
    meaning: 'Zehir-Zehir Meyvesi',
    description: 'Kullanıcının her türlü zehir üretmesini ve kontrol etmesini sağlar. Impel Down müdürü Magellan\'ın meyvesi.',
    abilities: [
      'Her türlü zehir üretme ve kontrol etme',
      'Hydra: Üç başlı zehir ejderhası',
      'Venom Demon: En güçlü zehir formu, dokunduğu her şeyi eritir',
      'Zehre karşı bağışıklık',
    ],
    user: 'Magellan',
    status: 'active',
    firstAppearance: 'Impel Down',
  },
  {
    name: 'Magu Magu no Mi',
    slug: 'magu-magu',
    japaneseName: 'マグマグの実',
    type: 'Logia',
    meaning: 'Magma-Magma Meyvesi',
    description: 'En yüksek saldırı gücüne sahip Logia meyvesi. Kullanıcının vücudunu magmaya dönüştürmesini sağlar. Ateş Logia\'sından üstündür — magma ateşi yakar.',
    abilities: [
      'Vücudu magmaya dönüştürme',
      'Dai Funka: Devasa magma yumruğu',
      'Ryusei Kazan: Magma meteorları yağdırma',
      'Meigo: Magma yumruk — Ace\'i öldüren saldırı',
      'Ateş Logia\'sından üstün güç hiyerarşisi',
    ],
    user: 'Sakazuki / Akainu',
    userSlug: 'akainu',
    status: 'active',
    firstAppearance: 'Marineford',
  },
  {
    name: 'Hie Hie no Mi',
    slug: 'hie-hie',
    japaneseName: 'ヒエヒエの実',
    type: 'Logia',
    meaning: 'Buz-Buz Meyvesi',
    description: 'Kullanıcının vücudunu buza dönüştürmesini ve çevresini dondurmasını sağlayan Logia tipi meyve. Devasa buz kıtaları oluşturabilir.',
    abilities: [
      'Vücudu buza dönüştürme',
      'Okyanusları dondurma (Ice Age)',
      'Ice Saber: Buz kılıçlar oluşturma',
      'Ice Time Capsule: Düşmanı buzda hapsetme',
      'Pheasant Beak: Buz kuş saldırısı',
    ],
    user: 'Kuzan / Aokiji',
    userSlug: 'aokiji',
    status: 'active',
    firstAppearance: 'Long Ring Long Land',
  },
  {
    name: 'Pika Pika no Mi',
    slug: 'pika-pika',
    japaneseName: 'ピカピカの実',
    type: 'Logia',
    meaning: 'Işık-Işık Meyvesi',
    description: 'Kullanıcının vücudunu ışığa dönüştürmesini sağlayan Logia tipi meyve. Işık hızında hareket ve lazer ışınları saldırısı yapabilir.',
    abilities: [
      'Vücudu ışığa dönüştürme',
      'Işık hızında hareket (Yata no Kagami)',
      'Lazer ışını saldırıları',
      'Ama no Murakumo: Işık kılıcı oluşturma',
      'Yasakani no Magatama: Çoklu lazer yağmuru',
    ],
    user: 'Borsalino / Kizaru',
    userSlug: 'kizaru',
    status: 'active',
    firstAppearance: 'Sabaody Archipelago',
  },
  {
    name: 'Moku Moku no Mi',
    slug: 'moku-moku',
    japaneseName: 'モクモクの実',
    type: 'Logia',
    meaning: 'Duman-Duman Meyvesi',
    description: 'Kullanıcının vücudunu dumana dönüştürmesini sağlayan Logia tipi meyve. Smoker\'ın imza meyvesi.',
    abilities: [
      'Vücudu dumana dönüştürme',
      'Duman üretme ve kontrol etme',
      'White Blow: Duman yumruğu',
      'White Launcher: Yoğun duman saldırısı',
    ],
    user: 'Smoker',
    userSlug: 'smoker',
    status: 'active',
    firstAppearance: 'Loguetown',
  },
  {
    name: 'Ito Ito no Mi',
    slug: 'ito-ito',
    japaneseName: 'イトイトの実',
    type: 'Paramecia',
    meaning: 'İplik-İplik Meyvesi',
    description: 'Kullanıcının iplikler üretmesini ve kontrol etmesini sağlar. İplikleri kesme, kontrol etme, klonlama ve bulutlara tutunarak uçma gibi çok yönlü kullanım sunar.',
    abilities: [
      'Keskin iplikler üretme (çeliği bile keser)',
      'Parasite: İnsanları kukla gibi kontrol etme',
      'Black Knight: İplikten klon oluşturma',
      'Birdcage: Dev ip kafesi — ada çapında tuzak',
      'Bulutlara tutunarak uçma',
      'İç organları iplikle tamir etme',
    ],
    awakening: 'Çevresindeki nesneleri (binalar, zemin) ipliklere dönüştürebilir.',
    user: 'Donquixote Doflamingo',
    userSlug: 'doflamingo',
    status: 'active',
    firstAppearance: 'Jaya',
  },
  {
    name: 'Noro Noro no Mi',
    slug: 'noro-noro',
    japaneseName: 'ノロノロの実',
    type: 'Paramecia',
    meaning: 'Yavaşlat-Yavaşlat Meyvesi',
    description: 'Noro Noro Beam adlı foton ışınları atarak hedefi 30 saniye boyunca yavaşlatır.',
    abilities: [
      'Noro Noro Beam: Hedefi 30 saniye yavaşlatma',
      'Yavaşlama sırasında vurulan darbeler birikir ve süre bitince hepsi birden etki eder',
    ],
    user: 'Foxy',
    status: 'active',
    firstAppearance: 'Long Ring Long Land',
  },
  {
    name: 'Kage Kage no Mi',
    slug: 'kage-kage',
    japaneseName: 'カゲカゲの実',
    type: 'Paramecia',
    meaning: 'Gölge-Gölge Meyvesi',
    description: 'Kullanıcının gölgeleri kontrol etmesini, çalmasını ve başka bedenlere yerleştirmesini sağlar. Çalınan gölgenin sahibi güneş ışığında yok olur.',
    abilities: [
      'Gölgeleri kesme ve çalma',
      'Çalınan gölgeleri cesetlere yerleştirerek zombi yaratma',
      'Doppelman: Kendi gölgesiyle yer değiştirme',
      'Brick Bat: Gölgeden yarasalar oluşturma',
      'Shadows Asgard: Binlerce gölgeyi emerek dev form',
    ],
    user: 'Gecko Moria',
    status: 'active',
    firstAppearance: 'Thriller Bark',
  },
  {
    name: 'Suke Suke no Mi',
    slug: 'suke-suke',
    japaneseName: 'スケスケの実',
    type: 'Paramecia',
    meaning: 'Şeffaf-Şeffaf Meyvesi',
    description: 'Kullanıcının kendisini ve dokunduğu şeyleri görünmez yapmasını sağlar.',
    abilities: [
      'Kendini görünmez yapma',
      'Dokunduğu nesneleri ve kişileri görünmez yapma',
      'Görünmez saldırılar yapma',
    ],
    user: 'Shiryu (eski: Absalom)',
    status: 'active',
    firstAppearance: 'Thriller Bark',
  },
  {
    name: 'Horo Horo no Mi',
    slug: 'horo-horo',
    japaneseName: 'ホロホロの実',
    type: 'Paramecia',
    meaning: 'Hayalet-Hayalet Meyvesi',
    description: 'Kullanıcının hayaletler oluşturmasını sağlar. Negatif hayaletler hedefin moralini tamamen çökertir, mini hayaletler patlayıcı saldırı yapar.',
    abilities: [
      'Negative Hollow: Dokunduğu kişinin moralini sıfıra düşüren hayaletler',
      'Mini Hollow: Patlayıcı mini hayaletler',
      'Astral Projection: Ruhunu vücudundan ayırarak uzaktan gözlem',
      'Special Hollow: Dev boyutlu patlayıcı hayalet',
    ],
    user: 'Perona',
    status: 'active',
    firstAppearance: 'Thriller Bark',
  },
  {
    name: 'Yomi Yomi no Mi',
    slug: 'yomi-yomi',
    japaneseName: 'ヨミヨミの実',
    type: 'Paramecia',
    meaning: 'Diriliş-Diriliş Meyvesi',
    description: 'Kullanıcıya ölümden sonra bir kez geri dönme hakkı verir. Brook bu sayede iskelet olarak hayata döndü. Ruhun gücünü kullanarak buz ve müzik saldırıları yapabilir.',
    abilities: [
      'Ölümden sonra bir kez dirilme',
      'Ruhunu vücuttan ayırma (Soul Solid)',
      'Ruh soğuğuyla buz kılıç saldırıları',
      'Müzikle ruhları etkileme',
      'Ruhunu kullanarak astral yürüyüş',
    ],
    user: 'Brook',
    userSlug: 'brook',
    status: 'active',
    firstAppearance: 'Thriller Bark',
  },
  {
    name: 'Soru Soru no Mi',
    slug: 'soru-soru',
    japaneseName: 'ソルソルの実',
    type: 'Paramecia',
    meaning: 'Ruh-Ruh Meyvesi',
    description: 'Kullanıcının canlıların ruhlarını (yaşam enerjisini) çalmasını ve nesnelere yerleştirmesini sağlar. Ruh verilen nesneler "Homie" olarak canlanır.',
    abilities: [
      'Ruh çalma (korkmuş insanlardan yaşam süresini alma)',
      'Homie yaratma: Nesnelere ve hayvanlara ruh yerleştirme',
      'Prometheus (güneş), Zeus (bulut), Hera (bulut), Napoleon (kılıç) — güçlü Homie\'ler',
      'Kendi ruhundan güç vererek dev form alma',
    ],
    user: 'Charlotte Linlin / Big Mom',
    userSlug: 'bigmom',
    status: 'active',
    firstAppearance: 'Fish-Man Island (isim olarak), Whole Cake Island',
  },
  {
    name: 'Bane Bane no Mi',
    slug: 'bane-bane',
    japaneseName: 'バネバネの実',
    type: 'Paramecia',
    meaning: 'Yay-Yay Meyvesi',
    description: 'Kullanıcının vücudunun herhangi bir yerinde yaylar oluşturmasını sağlar. Yaylarla süper sıçrama ve güçlü yumruklar atabilir.',
    abilities: [
      'Vücutta yay oluşturma',
      'Spring Hopper: Yaylarla süper hızlı sıçrama',
      'Spring Death Knock: Yay destekli güçlü yumruk',
    ],
    user: 'Bellamy',
    status: 'active',
    firstAppearance: 'Jaya',
  },
  {
    name: 'Bomu Bomu no Mi',
    slug: 'bomu-bomu',
    japaneseName: 'ボムボムの実',
    type: 'Paramecia',
    meaning: 'Bomba-Bomba Meyvesi',
    description: 'Kullanıcının vücudunun herhangi bir parçasını (nefes, salyalar dahil) patlayıcıya dönüştürmesini sağlar.',
    abilities: [
      'Vücut parçalarını patlayıcıya dönüştürme',
      'Breeze Breath Bomb: Patlayıcı nefes',
      'Nose Fancy Cannon: Patlar müküs',
    ],
    user: 'Mr. 5 / Gem',
    status: 'active',
    firstAppearance: 'Whiskey Peak',
  },
  {
    name: 'Doru Doru no Mi',
    slug: 'doru-doru',
    japaneseName: 'ドルドルの実',
    type: 'Paramecia',
    meaning: 'Mum-Mum Meyvesi',
    description: 'Kullanıcının vücudundan mum üretmesini sağlar. Mum, sertleşince çelik kadar dayanıklı olur.',
    abilities: [
      'Mum üretme ve şekillendirme',
      'Candle Wall: Çelik kadar sert mum duvarlar',
      'Candle Lock: Düşmanı mum içinde hapsetme',
      'Candle Champion: Mum zırhla dev form',
    ],
    user: 'Mr. 3 / Galdino',
    status: 'active',
    firstAppearance: 'Little Garden',
  },
  // ─── ZOAN ─────────────────────────────────────────────────────────────
  {
    name: 'Hito Hito no Mi',
    slug: 'hito-hito',
    japaneseName: 'ヒトヒトの実',
    type: 'Zoan',
    meaning: 'İnsan-İnsan Meyvesi',
    description: 'Kullanıcıya insan zekası ve insan formu verir. Tony Tony Chopper tarafından yenildi ve bir ren geyiğine insan özellikleri kazandırdı.',
    abilities: [
      'İnsan zekası ve konuşma yeteneği',
      'İnsan ve hibrit form',
      'Rumble Ball ile 7 farklı dönüşüm noktası',
      'Monster Point: Dev canavar formu',
      'Kung Fu Point: Savaş formu',
    ],
    user: 'Tony Tony Chopper',
    userSlug: 'chopper',
    status: 'active',
    firstAppearance: 'Drum Island',
  },
  {
    name: 'Tori Tori no Mi, Model: Phoenix',
    slug: 'tori-tori-phoenix',
    japaneseName: 'トリトリの実 モデル:不死鳥',
    type: 'Mythical Zoan',
    meaning: 'Kuş-Kuş Meyvesi, Model: Anka Kuşu',
    description: 'Efsanevi Zoan meyvesi. Kullanıcıya anka kuşuna dönüşme ve yenilenmeve mavi alevlerle iyileşme yeteneği verir.',
    abilities: [
      'Anka kuşu formu — uçma yeteneği',
      'Mavi alevlerle kendini iyileştirme (regenerasyon)',
      'Mavi alevlerle başkalarını iyileştirme',
      'Fiziksel saldırıları absorbe etme ve iyileşme',
      'Hibrit formda savaş yeteneği',
    ],
    user: 'Marco',
    status: 'active',
    firstAppearance: 'Marineford',
  },
  {
    name: 'Uo Uo no Mi, Model: Seiryu',
    slug: 'uo-uo-seiryu',
    japaneseName: 'ウオウオの実 モデル:青龍',
    type: 'Mythical Zoan',
    meaning: 'Balık-Balık Meyvesi, Model: Mavi Ejderha',
    description: 'En güçlü Zoan meyvelerinden biri. Kullanıcıya Mavi Ejderhaya dönüşme yeteneği verir. Kaido\'nun ada boyutunda ejderha formuna dönüşmesini sağlar.',
    abilities: [
      'Dev ejderha formuna dönüşme',
      'Boro Breath: Ateş nefesi',
      'Kaifu: Rüzgar bıçakları',
      'Yıldırım üretme',
      'Bulutlar oluşturarak uçma (Flame Clouds)',
      'Alev Bulutlarla adaları taşıma',
    ],
    user: 'Kaido',
    userSlug: 'kaido',
    status: 'active',
    firstAppearance: 'Punk Hazard (ejderha formu), Wano',
  },
  {
    name: 'Inu Inu no Mi, Model: Okuchi no Makami',
    slug: 'inu-inu-okuchi',
    japaneseName: 'イヌイヌの実 モデル:大口真神',
    type: 'Mythical Zoan',
    meaning: 'Köpek-Köpek Meyvesi, Model: Kutsal Kurt',
    description: 'Efsanevi Zoan meyvesi. Wano\'nun koruyucu tanrısı Okuchi no Makami\'ye (kutsal kurt) dönüşüm sağlar. Buz üretme yeteneği de verir.',
    abilities: [
      'Dev kurt formuna dönüşme',
      'Buz ve soğuk üretme yeteneği',
      'Namuji Hyoga: Buz nefesi',
      'Olağanüstü fiziksel güç ve hız',
    ],
    user: 'Yamato',
    userSlug: 'yamato',
    status: 'active',
    firstAppearance: 'Wano',
  },
  {
    name: 'Hebi Hebi no Mi, Model: Yamata no Orochi',
    slug: 'hebi-hebi-orochi',
    japaneseName: 'ヘビヘビの実 モデル:八岐大蛇',
    type: 'Mythical Zoan',
    meaning: 'Yılan-Yılan Meyvesi, Model: Yamata no Orochi',
    description: 'Sekiz başlı dev yılana dönüşüm sağlayan Efsanevi Zoan. Her baş kesildiğinde hayatta kalmayı sağlar — 8 cana sahip olduğu söylenir.',
    abilities: [
      'Sekiz başlı dev yılan formu',
      'Her baş kesildiğinde hayatta kalma (toplam 8 can)',
      'Büyük fiziksel güç',
    ],
    user: 'Kurozumi Orochi',
    status: 'deceased',
    firstAppearance: 'Wano',
  },
  {
    name: 'Zou Zou no Mi, Model: Mammoth',
    slug: 'zou-zou-mammoth',
    japaneseName: 'ゾウゾウの実 モデル:マンモス',
    type: 'Ancient Zoan',
    meaning: 'Fil-Fil Meyvesi, Model: Mamut',
    description: 'Kadim Zoan meyvesi. Dev bir mamuta dönüşüm sağlar. Olağanüstü fiziksel güç ve dayanıklılık verir.',
    abilities: [
      'Dev mamut formuna dönüşme',
      'Muazzam fiziksel güç',
      'Olağanüstü dayanıklılık ve toparlanma',
    ],
    user: 'Jack',
    status: 'active',
    firstAppearance: 'Zou',
  },
  {
    name: 'Ryu Ryu no Mi, Model: Allosaurus',
    slug: 'ryu-ryu-allosaurus',
    japaneseName: 'リュウリュウの実 モデル:アロサウルス',
    type: 'Ancient Zoan',
    meaning: 'Ejderha-Ejderha Meyvesi, Model: Allosaurus',
    description: 'Kadim Zoan meyvesi. Allosaurus dinozorununa dönüşüm sağlar.',
    abilities: [
      'Allosaurus formuna dönüşme',
      'Güçlü çene ve pençe saldırıları',
      'X Drake: Hibrit formda kılıç kullanımı',
    ],
    user: 'X Drake',
    status: 'active',
    firstAppearance: 'Sabaody Archipelago',
  },
  {
    name: 'Ryu Ryu no Mi, Model: Brachiosaurus',
    slug: 'ryu-ryu-brachiosaurus',
    japaneseName: 'リュウリュウの実 モデル:ブラキオサウルス',
    type: 'Ancient Zoan',
    meaning: 'Ejderha-Ejderha Meyvesi, Model: Brachiosaurus',
    description: 'Kadim Zoan meyvesi. Dev Brachiosaurus dinozoruna dönüşüm sağlar.',
    abilities: [
      'Dev Brachiosaurus formuna dönüşme',
      'Muazzam fiziksel güç ve boyut',
      'Brachiojaurus: Dev boyun saldırısı',
    ],
    user: 'Queen',
    status: 'active',
    firstAppearance: 'Wano',
  },
  {
    name: 'Ryu Ryu no Mi, Model: Pteranodon',
    slug: 'ryu-ryu-pteranodon',
    japaneseName: 'リュウリュウの実 モデル:プテラノドン',
    type: 'Ancient Zoan',
    meaning: 'Ejderha-Ejderha Meyvesi, Model: Pteranodon',
    description: 'Kadim Zoan meyvesi. Uçan dinozor Pteranodon\'a dönüşüm sağlar.',
    abilities: [
      'Pteranodon formuna dönüşme — uçma yeteneği',
      'Tempura Udon: Süper hızlı dalış saldırısı',
      'Süper hız ve sert kafa saldırıları',
    ],
    user: 'King',
    status: 'active',
    firstAppearance: 'Wano',
  },
  {
    name: 'Neko Neko no Mi, Model: Leopard',
    slug: 'neko-neko-leopard',
    japaneseName: 'ネコネコの実 モデル:レオパルド',
    type: 'Zoan',
    meaning: 'Kedi-Kedi Meyvesi, Model: Leopar',
    description: 'CP9\'un en güçlü üyesi Rob Lucci\'nin meyvesi. Leopar formuna dönüşüm sağlayarak çeviklik ve saldırı gücünü artırır.',
    abilities: [
      'Leopar formuna dönüşme',
      'Hibrit formda Rokushiki teknikleriyle kombine savaş',
      'Olağanüstü hız ve çeviklik',
      'Güçlü pençe saldırıları',
    ],
    awakening: 'Uyanış formu — daha büyük ve güçlü leopar formu, siyah alev benzeri aura.',
    user: 'Rob Lucci',
    status: 'active',
    firstAppearance: 'Water Seven',
  },
  {
    name: 'Ushi Ushi no Mi, Model: Giraffe',
    slug: 'ushi-ushi-giraffe',
    japaneseName: 'ウシウシの実 モデル:ジラフ',
    type: 'Zoan',
    meaning: 'İnek-İnek Meyvesi, Model: Zürafa',
    description: 'Zürafaya dönüşüm sağlayan Zoan meyvesi. Uzun boyun ile menzilli kılıç saldırıları yapılabilir.',
    abilities: [
      'Zürafa formuna dönüşme',
      'Uzun boyunla artırılmış menzil',
      'Pasta Machine: Boynu döndürerek çoklu saldırı',
      'Kılıç teknikleriyle kombine uzun menzil',
    ],
    user: 'Kaku',
    status: 'active',
    firstAppearance: 'Enies Lobby',
  },
  // ─── DAHA FAZLA PARAMECIA ────────────────────────────────────────────
  {
    name: 'Fuwa Fuwa no Mi',
    slug: 'fuwa-fuwa',
    japaneseName: 'フワフワの実',
    type: 'Paramecia',
    meaning: 'Süzülme-Süzülme Meyvesi',
    description: 'Kullanıcının dokunduğu cansız nesneleri havada süzündürmesini sağlar. Adaları bile havada tutabilir.',
    abilities: [
      'Cansız nesneleri havada süzündürme',
      'Adaları havada tutma',
      'Kaya ve bina parçalarını silah olarak fırlatma',
    ],
    user: 'Shiki (Altın Aslan)',
    status: 'active',
    firstAppearance: 'Strong World / Chapter 0',
  },
  {
    name: 'Hobi Hobi no Mi',
    slug: 'hobi-hobi',
    japaneseName: 'ホビホビの実',
    type: 'Paramecia',
    meaning: 'Hobi-Hobi Meyvesi',
    description: 'En korkunç Paramecia meyvelerinden biri. Dokunduğu kişiyi oyuncağa çevirir ve herkesin hafızasından siler. Kullanıcı yaşlanmaz.',
    abilities: [
      'İnsanları oyuncağa çevirme',
      'Oyuncağa çevrilen kişinin varlığı herkesin hafızasından siliniyor',
      'Oyuncaklara köle sözleşmesi dayatma',
      'Kullanıcı yaşlanmaz (Sugar hep çocuk görünümünde)',
    ],
    weakness: 'Kullanıcı bayılırsa tüm oyuncaklar geri döner ve hafızalar geri gelir',
    user: 'Sugar',
    status: 'active',
    firstAppearance: 'Dressrosa',
  },
  {
    name: 'Zushi Zushi no Mi',
    slug: 'zushi-zushi',
    japaneseName: 'ズシズシの実',
    type: 'Paramecia',
    meaning: 'Yerçekimi-Yerçekimi Meyvesi',
    description: 'Kullanıcının yerçekimini kontrol etmesini sağlar. Göklere kaldırma, yere çakma veya yerçekimini tersine çevirme gibi güçler sunar.',
    abilities: [
      'Yerçekimini kontrol etme',
      'Düşmanları yere çakma (Moko)',
      'Nesneleri ve insanları havaya kaldırma',
      'Horizontaal yerçekimi uygulama',
      'Göktaşları çekme (uyanış)',
    ],
    user: 'Fujitora / Issho',
    status: 'active',
    firstAppearance: 'Dressrosa',
  },
  {
    name: 'Tama Tama no Mi',
    slug: 'kibi-kibi',
    japaneseName: 'キビキビの実',
    type: 'Paramecia',
    meaning: 'Kibi-Kibi Meyvesi',
    description: 'Kullanıcının yanağından kibi dango (küçük yiyecek topları) üretmesini sağlar. Hayvanlar ve SMILE kullanıcıları bu dango\'yu yiyince kullanıcıya itaat eder.',
    abilities: [
      'Kibi dango üretme',
      'Hayvanları evcilleştirme',
      'SMILE kullanıcılarını kontrol etme',
      'Wano savaşında düşman kuvvetlerini döndürme',
    ],
    user: 'Tama',
    status: 'active',
    firstAppearance: 'Wano',
  },
  {
    name: 'Jiki Jiki no Mi',
    slug: 'jiki-jiki',
    japaneseName: 'ジキジキの実',
    type: 'Paramecia',
    meaning: 'Mıknatıs-Mıknatıs Meyvesi',
    description: 'Kullanıcının manyetik güçleri kontrol etmesini sağlar. Metal nesneleri çekme, itme ve silah olarak kullanma yeteneği verir.',
    abilities: [
      'Manyetik alan oluşturma',
      'Metal nesneleri çekme ve fırlatma',
      'Assign: Hedeflere mıknatıs atama (çekme/itme)',
      'Punk Corna Dio: Metal nesnelerden dev yapılar oluşturma',
      'Damned Punk: Dev elektromanyetik top',
    ],
    user: 'Eustass Kid',
    userSlug: 'kid',
    status: 'active',
    firstAppearance: 'Sabaody Archipelago',
  },
  {
    name: 'Wara Wara no Mi',
    slug: 'wara-wara',
    japaneseName: 'ワラワラの実',
    type: 'Paramecia',
    meaning: 'Saman-Saman Meyvesi',
    description: 'Kullanıcının vücudunu samana dönüştürmesini ve voodoo benzeri güçler kullanmasını sağlar. Başkalarının acısını yansıtabilir.',
    abilities: [
      'Vücudu samana dönüştürme',
      'Straw Man: Voodoo bebek yaparak hasarı başkasına aktarma',
      'Saman zırhla savunma',
    ],
    user: 'Basil Hawkins',
    status: 'active',
    firstAppearance: 'Sabaody Archipelago',
  },
]

// Helper functions
export function getDevilFruitBySlug(slug: string): DevilFruitEntry | undefined {
  return DEVIL_FRUITS.find((df) => df.slug === slug)
}

export function getDevilFruitsByType(type: string): DevilFruitEntry[] {
  return DEVIL_FRUITS.filter((df) => df.type === type)
}

export function getAllDevilFruitTypes(): string[] {
  return [...new Set(DEVIL_FRUITS.map((df) => df.type))]
}
