export type Sea = {
  name: string
  slug: string
  description: string
  color: string
}

export type Location = {
  name: string
  slug: string
  sea: string
  type: 'island' | 'sea' | 'city' | 'fortress' | 'ship' | 'other'
  description: string
  significance: string[]
  relatedArcs: string[]
  relatedCharacters: string[]
  dangerLevel: 1 | 2 | 3 | 4 | 5
  image?: string
}

export const SEAS: Sea[] = [
  {
    name: 'East Blue',
    slug: 'east-blue',
    description: 'Dört denizin en zayıfı olarak bilinir ancak Korsanlar Kralı Gol D. Roger, Monkey D. Luffy ve Roronoa Zoro gibi efsanelerin doğduğu denizdir. "Rüyaların denizi" olarak da anılır.',
    color: 'text-blue-400',
  },
  {
    name: 'West Blue',
    slug: 'west-blue',
    description: 'Nico Robin ve Brook\'un memleketi. Ohara Adası\'nın (Void Century araştırma merkezi) ve Shanks\'ın doğduğu deniz.',
    color: 'text-orange-400',
  },
  {
    name: 'North Blue',
    slug: 'north-blue',
    description: 'Trafalgar Law, Sanji ve Doflamingo\'nun doğduğu deniz. Germa Krallığı ve Flevance (Beyaz Şehir) buradadır.',
    color: 'text-cyan-400',
  },
  {
    name: 'South Blue',
    slug: 'south-blue',
    description: 'Franky ve Eustass Kid\'in doğduğu deniz. Briss Krallığı ve Torino Krallığı buradadır.',
    color: 'text-green-400',
  },
  {
    name: 'Grand Line',
    slug: 'grand-line',
    description: 'Dünyayı Red Line ile birlikte ikiye bölen efsanevi deniz yolu. "Korsan Mezarlığı" olarak bilinir. Dünyanın en tehlikeli ve en gizemli denizi. İki yarıya ayrılır: Paradise (cennet) ve New World.',
    color: 'text-gold',
  },
  {
    name: 'New World',
    slug: 'new-world',
    description: 'Grand Line\'ın ikinci yarısı. Dört İmparator\'un hüküm sürdüğü, dünyanın en tehlikeli bölgesi. Haki kullanmadan hayatta kalmak neredeyse imkansızdır.',
    color: 'text-luffy',
  },
  {
    name: 'Calm Belt',
    slug: 'calm-belt',
    description: 'Grand Line\'ın iki yanındaki rüzgarsız kuşak. Dev Deniz Kralları\'nın yaşadığı alan. Normal gemiler geçemez, sadece Deniz Taşı kaplı gemiler veya Kuja Korsanları (yılanlarla çekme) geçebilir.',
    color: 'text-pirate-muted',
  },
  {
    name: 'Red Line',
    slug: 'red-line',
    description: 'Dünyayı dikey olarak ikiye bölen devasa kırmızı kıta. Mary Geoise (Dünya Hükümeti merkezi) üzerindedir. Tek geçiş noktaları: Reverse Mountain ve Fish-Man Island (deniz altı).',
    color: 'text-luffy',
  },
]

export const LOCATIONS: Location[] = [
  // ─── EAST BLUE ─────────────────────────────────────────────────────
  {
    name: 'Foosha Köyü',
    slug: 'foosha',
    sea: 'east-blue',
    type: 'island',
    description: 'Dawn Adası\'ndaki küçük balıkçı köyü. Monkey D. Luffy\'nin büyüdüğü ve Shanks ile tanıştığı yer. Makino\'nun barı burada.',
    significance: [
      'Luffy\'nin memleketi',
      'Shanks\'ın sık uğradığı liman',
      'Luffy\'nin Gomu Gomu meyvesini yediği yer',
    ],
    relatedArcs: ['romance-dawn'],
    relatedCharacters: ['luffy', 'shanks', 'garp'],
    dangerLevel: 1,
  },
  {
    name: 'Shells Town',
    slug: 'shells-town',
    sea: 'east-blue',
    type: 'city',
    description: 'Deniz Kuvvetleri üssünün bulunduğu kasaba. Albay Morgan\'ın zulmü altındaydı. Zoro\'nun hapsedildiği yer.',
    significance: [
      'Zoro\'nun mürettebata katıldığı yer',
      'Albay Morgan\'ın yenildiği yer',
    ],
    relatedArcs: ['romance-dawn'],
    relatedCharacters: ['zoro', 'luffy', 'koby'],
    dangerLevel: 1,
  },
  {
    name: 'Baratie',
    slug: 'baratie',
    sea: 'east-blue',
    type: 'ship',
    description: 'Denizde yüzen efsanevi restoran. Baş aşçı Zeff tarafından kuruldu. Sanji burada büyüdü ve aşçılık öğrendi.',
    significance: [
      'Sanji\'nin mürettebata katıldığı yer',
      'Zoro vs Mihawk dövüşü',
      'Don Krieg saldırısı',
    ],
    relatedArcs: ['baratie'],
    relatedCharacters: ['sanji'],
    dangerLevel: 2,
  },
  {
    name: 'Arlong Park',
    slug: 'arlong-park',
    sea: 'east-blue',
    type: 'fortress',
    description: 'Arlong\'un Conomi Adaları\'nda kurduğu kale. Nami\'nin 8 yıl boyunca köyünü kurtarmak için çalıştığı yer.',
    significance: [
      'Nami\'nin geçmişinin aydınlandığı yer',
      'Luffy Arlong\'u yenip Nami\'yi özgürleştirdi',
      'One Piece\'in en duygusal anlarından biri: "Bana yardım et"',
    ],
    relatedArcs: ['arlong-park'],
    relatedCharacters: ['nami', 'luffy'],
    dangerLevel: 2,
  },
  {
    name: 'Loguetown',
    slug: 'loguetown',
    sea: 'east-blue',
    type: 'city',
    description: '"Başlangıç ve Son Şehri". Gol D. Roger\'ın hem doğduğu hem idam edildiği şehir. Grand Line\'a girmeden önceki son durak.',
    significance: [
      'Roger\'ın doğduğu ve öldüğü yer',
      'Büyük Korsan Çağı\'nın başladığı yer',
      'Luffy\'nin idam sehpasında Dragon tarafından kurtarıldığı yer',
      'Smoker ile ilk karşılaşma',
    ],
    relatedArcs: ['loguetown'],
    relatedCharacters: ['luffy', 'smoker'],
    dangerLevel: 2,
  },
  // ─── GRAND LINE (PARADISE) ────────────────────────────────────────
  {
    name: 'Reverse Mountain',
    slug: 'reverse-mountain',
    sea: 'grand-line',
    type: 'other',
    description: 'Grand Line\'a giriş noktası. Dört denizden gelen akıntılar dağın tepesine çıkar ve Grand Line tarafına dökülerek girer. Laboon (dev balina) burada bekler.',
    significance: [
      'Grand Line\'a tek yasal giriş noktası',
      'Laboon ile karşılaşma',
      'Brook\'un geçmişiyle bağlantı',
    ],
    relatedArcs: ['reverse-mountain'],
    relatedCharacters: ['brook'],
    dangerLevel: 3,
  },
  {
    name: 'Alabasta Krallığı',
    slug: 'alabasta',
    sea: 'grand-line',
    type: 'island',
    description: 'Çöl krallığı. Nefertari ailesinin yönettiği antik krallık. Crocodile\'ın iç savaş çıkararak ele geçirmeye çalıştığı yer.',
    significance: [
      'Crocodile/Baroque Works ile final savaş',
      'Vivi\'nin ülkesi',
      'Poneglyph\'lerden birinin bulunduğu yer',
      'Robin\'in mürettebata katılması',
    ],
    relatedArcs: ['arabasta'],
    relatedCharacters: ['luffy', 'vivi', 'crocodile', 'robin'],
    dangerLevel: 3,
  },
  {
    name: 'Skypiea',
    slug: 'skypiea',
    sea: 'grand-line',
    type: 'island',
    description: 'Beyaz-Beyaz Denizi\'nde (10.000 metre yükseklikte) bulunan gökyüzü adası. Kami (Tanrı) Enel tarafından yönetiliyordu. Shandora antik şehrinin kalıntıları burada.',
    significance: [
      'Gökyüzü adalarının varlığının kanıtı',
      'Enel\'in yenildiği yer (Luffy\'nin lastik vücudu vs yıldırım)',
      'Roger\'ın Poneglyph\'e mesaj bıraktığı yer',
      'Altın Çan\'ın bulunduğu yer',
    ],
    relatedArcs: ['skypiea'],
    relatedCharacters: ['luffy', 'enel'],
    dangerLevel: 4,
  },
  {
    name: 'Water 7',
    slug: 'water-7',
    sea: 'grand-line',
    type: 'city',
    description: 'Su üzerine kurulmuş gemi yapım şehri. Galley-La Company\'nin merkezi. Dünyanın en iyi gemi ustaları burada çalışır.',
    significance: [
      'Going Merry\'nin kaybedilmesi',
      'Franky\'nin mürettebata katılması',
      'CP9 olayı ve Robin\'in kaçırılması',
      'Thousand Sunny\'nin yapıldığı yer',
    ],
    relatedArcs: ['water-seven', 'enies-lobby'],
    relatedCharacters: ['franky', 'robin', 'luffy'],
    dangerLevel: 3,
  },
  {
    name: 'Enies Lobby',
    slug: 'enies-lobby',
    sea: 'grand-line',
    type: 'fortress',
    description: 'Adalet Adası — Dünya Hükümeti\'nin yargı merkezi. Güneş hiç batmaz. Hasır Şapkalar, Robin\'i kurtarmak için buraya saldırdı ve Dünya Hükümeti bayrağını yaktı.',
    significance: [
      'Robin\'in kurtarılması — "Yaşamak istiyorum!"',
      'Dünya Hükümeti bayrağının yakılması',
      'Luffy Gear 2 ve Gear 3\'ü ilk kez kullandı',
      'CP9 ile savaşlar',
      'Going Merry\'nin son yolculuğu ve vedası',
    ],
    relatedArcs: ['enies-lobby'],
    relatedCharacters: ['robin', 'luffy'],
    dangerLevel: 5,
  },
  {
    name: 'Thriller Bark',
    slug: 'thriller-bark',
    sea: 'grand-line',
    type: 'ship',
    description: 'Dünyanın en büyük gemisi — ada boyutunda bir korsan gemisi. Gecko Moria\'nın hükmettiği ve gölgeleri çalarak zombi ordusu oluşturduğu yer.',
    significance: [
      'Brook\'un mürettebata katılması',
      'Zoro\'nun Kuma\'dan Luffy\'nin acısını üstlenmesi — "Hiçbir şey olmadı"',
      'Oars vs Hasır Şapkalar',
      'Bartholomew Kuma ile ilk karşılaşma',
    ],
    relatedArcs: ['thriller-bark'],
    relatedCharacters: ['brook', 'kuma'],
    dangerLevel: 4,
  },
  {
    name: 'Sabaody Archipelago',
    slug: 'sabaody',
    sea: 'grand-line',
    type: 'island',
    description: 'Red Line\'ın önündeki son ada. Mangrove ağaçlarından oluşan takımadalar. Köle ticaretinin yapıldığı ve Celestial Dragon\'ların gezdiği yer.',
    significance: [
      'Luffy\'nin Celestial Dragon\'ı yumrukladığı yer',
      '11 Supernova\'nın bir araya geldiği yer',
      'Kuma\'nın mürettebatı dünyanın dört bir yanına gönderdiği yer',
      'Rayleigh ile tanışma',
      'Haki kavramının tanıtıldığı yer',
    ],
    relatedArcs: ['sabaody-archipelago'],
    relatedCharacters: ['luffy', 'kuma', 'law', 'kid'],
    dangerLevel: 5,
  },
  {
    name: 'Amazon Lily',
    slug: 'amazon-lily',
    sea: 'calm-belt',
    type: 'island',
    description: 'Sadece kadınların yaşadığı ada. Kuja Korsanları\'nın ve İmparatoriçe Boa Hancock\'un memleketi. Calm Belt\'te, dev Deniz Kralları arasında korunur.',
    significance: [
      'Luffy\'nin Hancock ile tanışması',
      'Luffy\'nin Haki\'yi ilk bilinçli kullandığı yer',
      'Hancock\'un Luffy\'ye aşık olması',
    ],
    relatedArcs: ['amazon-lily'],
    relatedCharacters: ['hancock', 'luffy'],
    dangerLevel: 4,
  },
  {
    name: 'Impel Down',
    slug: 'impel-down',
    sea: 'calm-belt',
    type: 'fortress',
    description: 'Dünyanın en güvenli denizaltı hapishanesi. 6 seviyeden oluşur, her seviye daha vahşi işkencelere sahiptir. Level 6 dünyanın en tehlikeli suçlularını barındırır.',
    significance: [
      'Luffy\'nin Ace\'i kurtarmak için girdiği yer',
      'Buggy, Mr. 3, Bon Clay, Ivankov ve Jinbe ile ittifak',
      'Magellan ile savaş',
      'Blackbeard\'ın Level 6 mahkumları serbest bırakması',
    ],
    relatedArcs: ['impel-down'],
    relatedCharacters: ['luffy', 'jinbe', 'buggy'],
    dangerLevel: 5,
  },
  {
    name: 'Marineford',
    slug: 'marineford',
    sea: 'grand-line',
    type: 'fortress',
    description: 'Deniz Kuvvetleri Karargahı. Dünyanın en büyük savaşının yaşandığı yer. Whitebeard Korsanları vs Deniz Kuvvetleri + Shichibukai.',
    significance: [
      'Portgas D. Ace\'in ölümü',
      'Whitebeard\'ın ölümü ve son sözleri: "One Piece gerçek!"',
      'Shanks\'ın savaşı durdurması',
      'Luffy\'nin Haoshoku Haki\'yi uyandırması',
      'Blackbeard\'ın Gura Gura meyvesini çalması',
    ],
    relatedArcs: ['marineford'],
    relatedCharacters: ['luffy', 'ace', 'whitebeard', 'shanks', 'blackbeard', 'akainu'],
    dangerLevel: 5,
  },
  // ─── NEW WORLD ────────────────────────────────────────────────────
  {
    name: 'Fish-Man Island',
    slug: 'fish-man-island',
    sea: 'new-world',
    type: 'island',
    description: 'Red Line\'ın altındaki denizaltı adası. Balık-Adamlar ve Denizkızlarının memleketi. Grand Line\'ın iki yarısını birbirine bağlayan geçiş noktası.',
    significance: [
      'Luffy\'nin 50.000 düşmanı tek seferde bayıltması (Haoshoku)',
      'Jinbe\'nin mürettebata davet edilmesi',
      'Joy Boy ve Poseidon efsanesi',
      'Big Mom\'un tehdidi',
    ],
    relatedArcs: ['fish-man-island'],
    relatedCharacters: ['luffy', 'jinbe'],
    dangerLevel: 3,
  },
  {
    name: 'Punk Hazard',
    slug: 'punk-hazard',
    sea: 'new-world',
    type: 'island',
    description: 'Yarısı buz, yarısı ateş olan ada. Akainu ve Aokiji\'nin 10 günlük düellosunun sonucu. Caesar Clown\'ın yasadışı silah laboratuvarı.',
    significance: [
      'Law ile ittifak',
      'Doflamingo\'yu devirme planının başlangıcı',
      'Akainu vs Aokiji düellosunun sonuçları',
      'SMILE (yapay Zoan) üretimi',
    ],
    relatedArcs: ['punk-hazard'],
    relatedCharacters: ['law', 'luffy'],
    dangerLevel: 4,
  },
  {
    name: 'Dressrosa',
    slug: 'dressrosa',
    sea: 'new-world',
    type: 'island',
    description: 'Tutkuların ülkesi. Donquixote Doflamingo tarafından yönetilen krallık. İspanya/Akdeniz estetiğine sahip, gladyatör turnuvalarıyla ünlü.',
    significance: [
      'Doflamingo\'nun yenilgisi',
      'Sabo\'nun geri dönüşü ve Mera Mera meyvesini yemesi',
      'Hasır Şapka Büyük Filosu\'nun kurulması',
      'Usopp\'un Kenbunshoku Haki\'yi uyandırması',
      'Gear 4 ilk kullanım',
    ],
    relatedArcs: ['dressrosa'],
    relatedCharacters: ['luffy', 'doflamingo', 'sabo', 'law'],
    dangerLevel: 5,
  },
  {
    name: 'Zou',
    slug: 'zou',
    sea: 'new-world',
    type: 'other',
    description: 'Devasa bir filin (Zunesha) sırtında 1000 yıldır var olan ada/ülke. Mink kabilesinin memleketi. Yalnızca Zunesha\'nın yürüdüğü yerde bulunabilir.',
    significance: [
      'Road Poneglyph\'lerden birinin bulunduğu yer',
      'Mink kabilesi ile ittifak',
      'Ninja-Korsan-Mink-Samuray ittifakı',
      'Sanji\'nin Whole Cake Island\'a gidişi',
    ],
    relatedArcs: ['zou'],
    relatedCharacters: ['luffy'],
    dangerLevel: 3,
  },
  {
    name: 'Whole Cake Island',
    slug: 'whole-cake-island',
    sea: 'new-world',
    type: 'island',
    description: 'Big Mom\'un Totto Land\'ının merkez adası. Her şey yiyeceklerden yapılmış — evler, ağaçlar, yollar. Charlotte ailesinin 85 çocuğu burada yaşar.',
    significance: [
      'Sanji\'nin kurtarılması',
      'Luffy vs Katakuri — Gelecek Görüşü Haki',
      'Big Mom ile ilk büyük çatışma',
      'Brook\'un Road Poneglyph kopyasını alması',
      'Jinbe\'nin resmi katılımı',
      'Germa 66 ile karşılaşma',
    ],
    relatedArcs: ['whole-cake-island'],
    relatedCharacters: ['sanji', 'luffy', 'bigmom', 'brook', 'jinbe'],
    dangerLevel: 5,
  },
  {
    name: 'Wano Kuni',
    slug: 'wano',
    sea: 'new-world',
    type: 'island',
    description: 'Kaido tarafından işgal edilmiş, izole Japon tarzı ülke. Samurai ve ninja geleneğine sahip. 20 yıl önce Kozuki Oden idam edildi, ülke karanlığa gömüldü.',
    significance: [
      'Kaido\'nun yenilgisi',
      'Luffy Gear 5\'i uyandırdı — Joy Boy\'un dönüşü',
      'Büyük Onigashima Savaşı',
      'Zoro\'nun Enma kılıcını edinmesi',
      'Kozuki Oden\'in hikayesi',
      'Road Poneglyph',
      'Haoshoku İnfüzyonu\'nun öğrenilmesi',
    ],
    relatedArcs: ['wano'],
    relatedCharacters: ['luffy', 'kaido', 'zoro', 'yamato'],
    dangerLevel: 5,
  },
  {
    name: 'Egghead',
    slug: 'egghead',
    sea: 'new-world',
    type: 'island',
    description: 'Dr. Vegapunk\'ın "Gelecek Adası". 500 yıl sonrasının teknolojisine sahip. Dünya Hükümeti\'nin en büyük sırlarının ortaya çıktığı yer.',
    significance: [
      'Vegapunk\'ın dünyaya mesajı',
      'Void Century hakkında bilgiler',
      'Dünya Hükümeti\'nin karanlık yüzü',
      'Kuma\'nın geçmişi ve fedakarlığı',
      'Gorosei ile savaş',
    ],
    relatedArcs: ['egghead'],
    relatedCharacters: ['luffy', 'vegapunk', 'kuma'],
    dangerLevel: 5,
  },
  {
    name: 'Mary Geoise (Marijoa)',
    slug: 'mary-geoise',
    sea: 'red-line',
    type: 'fortress',
    description: 'Red Line\'ın tepesindeki Dünya Hükümeti\'nin merkezi. Celestial Dragon\'ların (Tenryuubito) yaşadığı kutsal şehir. Dünyanın en güçlü otoritesinin merkezi.',
    significance: [
      'Dünya Hükümeti ve Gorosei\'nin merkezi',
      'Im-sama\'nın tahtı (Boş Taht)',
      'Reverie toplantılarının yapıldığı yer',
      'Devasa hazine "National Treasure"',
      'Fisher Tiger\'ın köle ayaklanması',
    ],
    relatedArcs: ['reverie'],
    relatedCharacters: [],
    dangerLevel: 5,
  },
  {
    name: 'Laugh Tale (Raftel)',
    slug: 'laugh-tale',
    sea: 'new-world',
    type: 'island',
    description: 'Grand Line\'ın sonundaki efsanevi ada. One Piece hazinesinin bulunduğu yer. Sadece Gol D. Roger\'ın mürettebatı ulaşabildi. Dört Road Poneglyph\'in işaret ettiği koordinatların kesişim noktası.',
    significance: [
      'One Piece hazinesinin bulunduğu yer',
      'Sadece Roger Korsanları ulaştı',
      'Void Century\'nin tüm gerçeğinin ortaya çıktığı yer',
      'Roger\'ın "Laugh Tale" adını verdiği yer — çünkü güldü',
    ],
    relatedArcs: [],
    relatedCharacters: [],
    dangerLevel: 5,
  },
]

export function getLocationsBySea(seaSlug: string): Location[] {
  return LOCATIONS.filter((l) => l.sea === seaSlug)
}

export function getLocationBySlug(slug: string): Location | undefined {
  return LOCATIONS.find((l) => l.slug === slug)
}
